// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package server

import (
	"context"

	"wklive/proto/system"
	"wklive/services/system/internal/logic/systeminternal"
	"wklive/services/system/internal/svc"
)

type SystemInternalServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedSystemInternalServer
}

func NewSystemInternalServer(svcCtx *svc.ServiceContext) *SystemInternalServer {
	return &SystemInternalServer{
		svcCtx: svcCtx,
	}
}

func (s *SystemInternalServer) SysConfigDetail(ctx context.Context, in *system.SysConfigDetailReq) (*system.SysConfigDetailResp, error) {
	l := systeminternallogic.NewSysConfigDetailLogic(ctx, s.svcCtx)
	return l.SysConfigDetail(in)
}

func (s *SystemInternalServer) SysConfigByKeys(ctx context.Context, in *system.SysConfigByKeysReq) (*system.SysConfigByKeysResp, error) {
	l := systeminternallogic.NewSysConfigByKeysLogic(ctx, s.svcCtx)
	return l.SysConfigByKeys(in)
}

func (s *SystemInternalServer) SysTenantList(ctx context.Context, in *system.SysTenantListReq) (*system.SysTenantListResp, error) {
	l := systeminternallogic.NewSysTenantListLogic(ctx, s.svcCtx)
	return l.SysTenantList(in)
}

func (s *SystemInternalServer) SysTenantDetail(ctx context.Context, in *system.SysTenantDetailReq) (*system.SysTenantDetailResp, error) {
	l := systeminternallogic.NewSysTenantDetailLogic(ctx, s.svcCtx)
	return l.SysTenantDetail(in)
}

func (s *SystemInternalServer) ResolveTenantDomain(ctx context.Context, in *system.ResolveTenantDomainReq) (*system.ResolveTenantDomainResp, error) {
	l := systeminternallogic.NewResolveTenantDomainLogic(ctx, s.svcCtx)
	return l.ResolveTenantDomain(in)
}
