DROP TABLE IF EXISTS `t_trade_symbol`;
CREATE TABLE `t_trade_symbol` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol` VARCHAR(64) NOT NULL COMMENT '统一交易标的代码，如BTCUSDT、ETHUSD-PERP',
  `display_symbol` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '前端展示名称',
  `product_type` TINYINT NOT NULL COMMENT '产品大类：1现货 2衍生品 3秒合约',
  `base_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '基础资产，例如BTC',
  `quote_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '计价资产，例如USDT',
  `settle_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '结算资产，现货一般等于quote_asset',
  `margin_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '保证金资产；现货为空，U本位为稳定币，币本位为基础币',
  `contract_type` TINYINT NOT NULL DEFAULT 0 COMMENT '合约期限类型：0不适用 1永续 2交割',
  `contract_value_type` TINYINT NOT NULL DEFAULT 0 COMMENT '合约价值类型：0不适用 1线性 2反向',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '交易状态：1启用 2禁用 3仅平仓',
  `price_scale` INT NOT NULL DEFAULT 8 COMMENT '价格精度，小数位数',
  `qty_scale` INT NOT NULL DEFAULT 8 COMMENT '数量精度，小数位数',
  `min_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最小下单价格',
  `max_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大下单价格',
  `price_tick` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '价格步长',
  `min_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最小下单数量',
  `max_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大下单数量',
  `qty_step` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '数量步长',
  `min_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最小名义价值',
  `max_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大名义价值，0表示不限',
  `listing_time` BIGINT NOT NULL DEFAULT 0 COMMENT '产品上线时间，毫秒时间戳，0表示不限',
  `trading_start_time` BIGINT NOT NULL DEFAULT 0 COMMENT '开始交易时间，毫秒时间戳，0表示不限',
  `trading_end_time` BIGINT NOT NULL DEFAULT 0 COMMENT '停止交易时间，毫秒时间戳，0表示不限',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_product` (`tenant_id`, `symbol`, `product_type`, `contract_type`, `contract_value_type`),
  KEY `idx_tenant_product_status` (`tenant_id`, `product_type`, `status`),
  CONSTRAINT `chk_symbol_product_contract` CHECK (
    (`product_type` IN (1, 3) AND `contract_type` = 0 AND `contract_value_type` = 0)
    OR (`product_type` = 2 AND `contract_type` IN (1, 2) AND `contract_value_type` IN (1, 2))
  ),
  CONSTRAINT `chk_symbol_status_scale` CHECK (`status` IN (1, 2, 3) AND `price_scale` BETWEEN 0 AND 18 AND `qty_scale` BETWEEN 0 AND 18),
  CONSTRAINT `chk_symbol_price_qty` CHECK (`min_price` >= 0 AND `max_price` >= 0 AND (`max_price` = 0 OR `max_price` >= `min_price`) AND `price_tick` > 0 AND `min_qty` >= 0 AND (`max_qty` = 0 OR `max_qty` >= `min_qty`) AND `qty_step` > 0),
  CONSTRAINT `chk_symbol_notional_time` CHECK (`min_notional` >= 0 AND (`max_notional` = 0 OR `max_notional` >= `min_notional`) AND (`trading_end_time` = 0 OR `trading_start_time` = 0 OR `trading_end_time` > `trading_start_time`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易标的主表';

DROP TABLE IF EXISTS `t_trade_symbol_spot`;
CREATE TABLE `t_trade_symbol_spot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID，对应t_trade_symbol.id',
  `maker_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT 'Maker手续费率',
  `taker_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT 'Taker手续费率',
  `buy_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '买入开关：1启用 2禁用',
  `sell_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '卖出开关：1启用 2禁用',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_id` (`tenant_id`, `symbol_id`),
  CONSTRAINT `chk_spot_fee_rate` CHECK (`maker_fee_rate` >= 0 AND `taker_fee_rate` >= 0),
  CONSTRAINT `chk_spot_switches` CHECK (`buy_enabled` IN (1, 2) AND `sell_enabled` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='现货交易对扩展表';

DROP TABLE IF EXISTS `t_trade_symbol_contract`;
CREATE TABLE `t_trade_symbol_contract` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID，对应t_trade_symbol.id',
  `contract_size` DECIMAL(36,18) NOT NULL DEFAULT 1 COMMENT '每张合约面值',
  `multiplier` DECIMAL(36,18) NOT NULL DEFAULT 1 COMMENT '合约乘数',
  `maintenance_margin_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '维持保证金率',
  `initial_margin_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '初始保证金率',
  `maker_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT 'Maker手续费率',
  `taker_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT 'Taker手续费率',
  `funding_interval_minutes` INT NOT NULL DEFAULT 0 COMMENT '资金费结算周期，单位分钟',
  `funding_rate_cap` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '资金费率上限，0表示不限制',
  `funding_rate_floor` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '资金费率下限，0表示不限制',
  `funding_rate_source` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '资金费率算法或数据源标识',
  `index_symbol` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '指数价格标识',
  `mark_price_source` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '标记价格来源',
  `settlement_price_source` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '交割结算价格来源',
  `delivery_time` BIGINT NOT NULL DEFAULT 0 COMMENT '交割时间或到期时间，永续合约为0',
  `open_cutoff_time` BIGINT NOT NULL DEFAULT 0 COMMENT '交割合约停止开仓时间，永续合约为0',
  `matching_stop_time` BIGINT NOT NULL DEFAULT 0 COMMENT '交割合约停止撮合时间，永续合约为0',
  `settlement_window_seconds` INT NOT NULL DEFAULT 0 COMMENT '交割价采样窗口秒数',
  `settlement_price_algorithm` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '交割价算法及版本标识',
  `delivery_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '交割手续费率',
  `liquidation_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '强平手续费率',
  `support_cross` TINYINT NOT NULL DEFAULT 1 COMMENT '是否支持全仓：1支持 0不支持',
  `support_isolated` TINYINT NOT NULL DEFAULT 1 COMMENT '是否支持逐仓：1支持 0不支持',
  `open_long_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '开多开关：1启用 2禁用',
  `open_short_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '开空开关：1启用 2禁用',
  `close_long_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '平多开关：1启用 2禁用',
  `close_short_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '平空开关：1启用 2禁用',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_id` (`tenant_id`, `symbol_id`),
  CONSTRAINT `chk_contract_parameters` CHECK (`contract_size` > 0 AND `multiplier` > 0 AND `maintenance_margin_rate` >= 0 AND `initial_margin_rate` >= `maintenance_margin_rate` AND `delivery_fee_rate` >= 0 AND `liquidation_fee_rate` >= 0 AND `settlement_window_seconds` >= 0),
  CONSTRAINT `chk_contract_delivery_time` CHECK (`delivery_time` = 0 OR ((`open_cutoff_time` = 0 OR `open_cutoff_time` < `delivery_time`) AND (`matching_stop_time` = 0 OR `matching_stop_time` <= `delivery_time`) AND (`open_cutoff_time` = 0 OR `matching_stop_time` = 0 OR `open_cutoff_time` <= `matching_stop_time`))),
  CONSTRAINT `chk_contract_margin_modes` CHECK (`support_cross` IN (0, 1) AND `support_isolated` IN (0, 1) AND (`support_cross` = 1 OR `support_isolated` = 1)),
  CONSTRAINT `chk_contract_switches` CHECK (`open_long_enabled` IN (1, 2) AND `open_short_enabled` IN (1, 2) AND `close_long_enabled` IN (1, 2) AND `close_short_enabled` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约交易对扩展表';

DROP TABLE IF EXISTS `t_trade_symbol_seconds`;
CREATE TABLE `t_trade_symbol_seconds` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `duration_seconds` INT NOT NULL COMMENT '到期周期，秒',
  `payout_rate` DECIMAL(20,10) NOT NULL COMMENT '胜出收益率',
  `fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '秒合约手续费率',
  `draw_rule` TINYINT NOT NULL DEFAULT 1 COMMENT '平局规则：1退本金 2判输',
  `start_price_source` VARCHAR(64) NOT NULL COMMENT '起始价格来源',
  `settlement_price_source` VARCHAR(64) NOT NULL COMMENT '结算价格来源',
  `quote_validity_ms` INT NOT NULL DEFAULT 3000 COMMENT '价格快照最大延迟毫秒',
  `settlement_window_ms` INT NOT NULL DEFAULT 0 COMMENT '到期价采样窗口毫秒数',
  `settlement_price_algorithm` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '结算价格算法及版本标识',
  `draw_tolerance` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '平局价格容差',
  `max_exposure_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '产品总敞口上限，0表示不限',
  `min_stake` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最小本金',
  `max_stake` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大本金，0表示不限',
  `up_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '看涨开关：1启用 2禁用',
  `down_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '看跌开关：1启用 2禁用',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_duration` (`tenant_id`, `symbol_id`, `duration_seconds`),
  CONSTRAINT `chk_seconds_parameters` CHECK (`duration_seconds` > 0 AND `payout_rate` >= 0 AND `fee_rate` >= 0 AND `draw_rule` IN (1, 2) AND `quote_validity_ms` > 0 AND `settlement_window_ms` >= 0 AND `draw_tolerance` >= 0 AND `max_exposure_amount` >= 0 AND `min_stake` >= 0 AND (`max_stake` = 0 OR `max_stake` >= `min_stake`)),
  CONSTRAINT `chk_seconds_switches` CHECK (`up_enabled` IN (1, 2) AND `down_enabled` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='秒合约产品配置';

DROP TABLE IF EXISTS `t_trade_symbol_session`;
CREATE TABLE `t_trade_symbol_session` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `day_of_week` TINYINT NOT NULL COMMENT '星期：1周一至7周日',
  `start_second` INT NOT NULL COMMENT '当天开始秒数',
  `end_second` INT NOT NULL COMMENT '当天结束秒数',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'UTC' COMMENT 'IANA时区',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 2禁用',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_symbol_week_session` (`tenant_id`, `symbol_id`, `day_of_week`, `start_second`, `end_second`),
  CONSTRAINT `chk_symbol_session_time` CHECK (`day_of_week` BETWEEN 1 AND 7 AND `start_second` >= 0 AND `start_second` < `end_second` AND `end_second` <= 86400 AND `enabled` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易标的周期交易时段';

DROP TABLE IF EXISTS `t_trade_user_config`;
CREATE TABLE `t_trade_user_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `product_type` TINYINT NOT NULL COMMENT '产品大类：1现货 2衍生品 3秒合约',
  `symbol_id` BIGINT NOT NULL DEFAULT 0 COMMENT '交易标的ID，0表示该市场下的全局配置',
  `trade_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '交易开关：1启用 2禁用',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_product_symbol` (`tenant_id`, `user_id`, `product_type`, `symbol_id`),
  CONSTRAINT `chk_trade_user_config` CHECK (`product_type` IN (1, 2, 3) AND `trade_enabled` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户交易配置表';

DROP TABLE IF EXISTS `t_contract_user_config`;
CREATE TABLE `t_contract_user_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL DEFAULT 0 COMMENT '交易标的ID，0表示合约全局配置',
  `position_mode` TINYINT NOT NULL DEFAULT 1 COMMENT '持仓模式：1单向持仓 2双向持仓',
  `margin_mode` TINYINT NOT NULL DEFAULT 1 COMMENT '保证金模式：1全仓 2逐仓',
  `default_leverage` INT NOT NULL DEFAULT 1 COMMENT '默认杠杆倍数',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_symbol` (`tenant_id`, `user_id`, `symbol_id`),
  CONSTRAINT `chk_contract_user_config` CHECK (`position_mode` IN (1, 2) AND `margin_mode` IN (1, 2) AND `default_leverage` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户合约交易偏好配置';

DROP TABLE IF EXISTS `t_trade_order`;
CREATE TABLE `t_trade_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '平台订单号，全租户内唯一',
  `client_order_id` VARCHAR(64) DEFAULT NULL COMMENT '客户端订单号，可空；非空时用于幂等控制',
  `request_hash` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '规范化下单参数摘要，用于识别幂等键参数冲突',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `product_type` TINYINT NOT NULL COMMENT '产品大类快照：1现货 2衍生品 3秒合约',
  `contract_type` TINYINT NOT NULL DEFAULT 0 COMMENT '合约期限类型快照：0不适用 1永续 2交割',
  `contract_value_type` TINYINT NOT NULL DEFAULT 0 COMMENT '合约价值类型快照：0不适用 1线性 2反向',
  `side` TINYINT NOT NULL DEFAULT 0 COMMENT '买卖方向：0不适用 1买 2卖；秒合约为0',
  `position_side` TINYINT NOT NULL DEFAULT 0 COMMENT '持仓方向：0未知/无 1净持仓 2多 3空，现货一般为0',
  `order_type` TINYINT NOT NULL DEFAULT 0 COMMENT '成交方式：0不适用 1限价 2市价；秒合约为0',
  `time_in_force` TINYINT NOT NULL DEFAULT 0 COMMENT '订单有效方式：0默认 1GTC 2IOC 3FOK 4PostOnly',
  `status` TINYINT NOT NULL COMMENT '订单状态：1待成交 2部分成交 3已成交 4已撤单 5已拒单 6已过期 7冻结中 8等待触发 9撤单中 10过期处理中 11结算中',
  `price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '委托价格',
  `qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '委托数量',
  `amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '委托总额或名义价值',
  `filled_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '累计成交数量',
  `filled_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '累计成交金额',
  `canceled_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT 'Matcher最终确认的撤销或过期数量',
  `avg_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '平均成交价格',
  `fee` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '累计手续费',
  `fee_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手续费币种',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '订单来源：1App 2Web 3API 4System',
  `is_reduce_only` TINYINT NOT NULL DEFAULT 2 COMMENT '是否只减仓：1是 2否',
  `is_close_position` TINYINT NOT NULL DEFAULT 2 COMMENT '是否在触发/执行时关闭全部可平仓位：1是 2否',
  `trigger_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '触发价格，非条件单则为0',
  `trigger_type` TINYINT NOT NULL DEFAULT 0 COMMENT '触发价格类型：0无 1最新价 2标记价 3指数价',
  `trigger_kind` TINYINT NOT NULL DEFAULT 0 COMMENT '触发用途：0无 1条件单 2止盈 3止损',
  `oco_group_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'OCO关联组号，空表示无关联',
  `expire_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'GTD到期时间，0表示不适用',
  `triggered_at` BIGINT NOT NULL DEFAULT 0 COMMENT '条件单实际触发时间',
  `completion_reason` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '终止原因，如FILLED、DUST、NO_LIQUIDITY、PRICE_PROTECTION',
  `cancel_reason` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '撤单原因或拒单原因',
  `biz_ext` JSON DEFAULT NULL COMMENT '业务扩展字段，JSON格式',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '订单并发状态转移版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_no` (`tenant_id`, `order_no`),
  UNIQUE KEY `uk_tenant_user_product_client_order_id` (`tenant_id`, `user_id`, `product_type`, `client_order_id`),
  KEY `idx_tenant_user_status_created` (`tenant_id`, `user_id`, `status`, `create_times`),
  KEY `idx_tenant_symbol_status_created` (`tenant_id`, `symbol_id`, `status`, `create_times`),
  KEY `idx_tenant_user_product_created` (`tenant_id`, `user_id`, `product_type`, `create_times`),
  KEY `idx_trigger_waiting` (`tenant_id`, `status`, `trigger_type`, `symbol_id`),
  KEY `idx_expire_at` (`tenant_id`, `status`, `expire_at`),
  KEY `idx_oco_group` (`tenant_id`, `user_id`, `oco_group_no`),
  CONSTRAINT `chk_order_product_contract` CHECK (
    (`product_type` IN (1, 3) AND `contract_type` = 0 AND `contract_value_type` = 0)
    OR (`product_type` = 2 AND `contract_type` IN (1, 2) AND `contract_value_type` IN (1, 2))
  ),
  CONSTRAINT `chk_order_execution_fields` CHECK (
    (`product_type` IN (1, 2) AND `side` IN (1, 2) AND `order_type` IN (1, 2))
    OR (`product_type` = 3 AND `side` = 0 AND `order_type` = 0)
  ),
  CONSTRAINT `chk_order_status` CHECK (`status` IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)),
  CONSTRAINT `chk_order_amounts` CHECK (`price` >= 0 AND `qty` >= 0 AND `amount` >= 0 AND `filled_qty` >= 0 AND `canceled_qty` >= 0 AND (`qty` = 0 OR `filled_qty` + `canceled_qty` <= `qty`) AND `filled_amount` >= 0 AND `fee` >= 0),
  CONSTRAINT `chk_order_flags` CHECK (`is_reduce_only` IN (1, 2) AND `is_close_position` IN (1, 2) AND `version` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易订单主表';

DROP TABLE IF EXISTS `t_trade_order_spot`;
CREATE TABLE `t_trade_order_spot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_id` BIGINT NOT NULL COMMENT '订单ID，对应t_trade_order.id',
  `frozen_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '下单冻结的资产币种',
  `frozen_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '下单冻结的资产数量',
  `settle_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '结算币种',
  `settle_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '结算金额',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_id` (`tenant_id`, `order_id`),
  CONSTRAINT `chk_order_spot_amounts` CHECK (`frozen_amount` >= 0 AND `settle_amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='现货订单明细表';

DROP TABLE IF EXISTS `t_trade_order_contract`;
CREATE TABLE `t_trade_order_contract` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_id` BIGINT NOT NULL COMMENT '订单ID，对应t_trade_order.id',
  `margin_mode` TINYINT NOT NULL COMMENT '保证金模式：1全仓 2逐仓',
  `leverage` INT NOT NULL DEFAULT 1 COMMENT '下单时杠杆倍数',
  `margin_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '保证金币种',
  `margin_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '本次订单占用保证金',
  `reserved_close_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT 'Position预占的可平数量',
  `risk_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '下单保证金与风控计算使用的价格快照',
  `risk_tier_id` BIGINT NOT NULL DEFAULT 0 COMMENT '下单时命中的风险限额档位ID',
  `close_position_type` TINYINT NOT NULL DEFAULT 0 COMMENT '平仓类型：0普通 1平多 2平空',
  `liquidation_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '下单时预估强平价格',
  `take_profit_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '止盈价格',
  `stop_loss_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '止损价格',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_id` (`tenant_id`, `order_id`),
  CONSTRAINT `chk_order_contract` CHECK (`margin_mode` IN (1, 2) AND `leverage` > 0 AND `margin_amount` >= 0 AND `reserved_close_qty` >= 0 AND `risk_price` >= 0 AND `close_position_type` IN (0, 1, 2) AND `liquidation_price` >= 0 AND `take_profit_price` >= 0 AND `stop_loss_price` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约订单明细表';

DROP TABLE IF EXISTS `t_trade_order_seconds`;
CREATE TABLE `t_trade_order_seconds` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `direction` TINYINT NOT NULL COMMENT '方向：1看涨 2看跌',
  `duration_seconds` INT NOT NULL COMMENT '到期周期秒数',
  `stake_asset` VARCHAR(32) NOT NULL COMMENT '本金资产',
  `stake_amount` DECIMAL(36,18) NOT NULL COMMENT '本金金额',
  `payout_rate` DECIMAL(20,10) NOT NULL COMMENT '下单时锁定的收益率',
  `fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '下单时锁定的手续费率',
  `frozen_at` BIGINT NOT NULL DEFAULT 0 COMMENT '本金冻结成功时间',
  `activated_at` BIGINT NOT NULL DEFAULT 0 COMMENT '起始价锁定并激活时间',
  `start_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '起始价格',
  `start_price_time` BIGINT NOT NULL DEFAULT 0 COMMENT '起始价格时间',
  `start_price_source` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '起始价格来源快照',
  `expire_time` BIGINT NOT NULL COMMENT '到期时间',
  `settlement_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '结算价格',
  `settlement_price_time` BIGINT NOT NULL DEFAULT 0 COMMENT '结算价格时间',
  `settlement_price_source` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '结算价格来源快照',
  `price_algorithm` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '结算采样算法及版本快照',
  `result` TINYINT NOT NULL DEFAULT 0 COMMENT '结果：0待定 1胜 2负 3平 4作废',
  `profit_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '盈利金额，不含返还本金',
  `fee_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '手续费金额',
  `return_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最终返还本金及收益总额',
  `settlement_status` TINYINT NOT NULL DEFAULT 0 COMMENT '流程状态：0待冻结 1激活中 2进行中 3结算中 4已结算 5退款中 6已退款 7人工处理',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '当前流程累计失败次数',
  `next_retry_at` BIGINT NOT NULL DEFAULT 0 COMMENT '下次允许处理时间',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后处理错误',
  `reservation_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Asset资金预占号',
  `settlement_reason` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '结算、作废、退款或人工处理原因',
  `settled_at` BIGINT NOT NULL DEFAULT 0 COMMENT '结算或退款完成时间',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '并发状态转移版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_id` (`tenant_id`, `order_id`),
  KEY `idx_settlement_due` (`tenant_id`, `settlement_status`, `expire_time`),
  KEY `idx_seconds_retry_due` (`tenant_id`, `settlement_status`, `next_retry_at`, `id`),
  CONSTRAINT `chk_seconds_order` CHECK (`direction` IN (1, 2) AND `duration_seconds` > 0 AND `stake_amount` > 0 AND `payout_rate` >= 0 AND `fee_rate` >= 0 AND `result` IN (0, 1, 2, 3, 4) AND `settlement_status` BETWEEN 0 AND 7 AND `retry_count` >= 0 AND `profit_amount` >= 0 AND `fee_amount` >= 0 AND `return_amount` >= 0 AND `version` >= 0 AND ((`settlement_status` IN (0, 1) AND `start_price` = 0 AND `start_price_time` = 0 AND `expire_time` = 0) OR (`settlement_status` IN (2, 3, 4) AND `start_price` > 0 AND `start_price_time` > 0 AND `activated_at` > 0 AND `expire_time` > `activated_at`) OR `settlement_status` IN (5, 6, 7)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='秒合约订单及到期结算快照';

DROP TABLE IF EXISTS `t_trade_market_snapshot`;
CREATE TABLE `t_trade_market_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID，0为公共行情',
  `snapshot_id` VARCHAR(64) NOT NULL COMMENT '快照内容哈希',
  `snapshot_kind` VARCHAR(32) NOT NULL COMMENT 'PRICE/FUNDING/MARK/INDEX/DELIVERY',
  `symbol_id` BIGINT NOT NULL DEFAULT 0,
  `source` VARCHAR(255) NOT NULL DEFAULT '',
  `price` DECIMAL(36,18) NOT NULL DEFAULT 0,
  `mark_price` DECIMAL(36,18) NOT NULL DEFAULT 0,
  `index_price` DECIMAL(36,18) NOT NULL DEFAULT 0,
  `funding_rate` DECIMAL(20,10) NOT NULL DEFAULT 0,
  `source_timestamp` BIGINT NOT NULL,
  `snapshot_timestamp` BIGINT NOT NULL,
  `revision` BIGINT NOT NULL,
  `formula_version` VARCHAR(64) NOT NULL DEFAULT '',
  `confirmed` TINYINT NOT NULL DEFAULT 1,
  `raw_payload` JSON NOT NULL,
  `create_times` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_snapshot` (`tenant_id`,`symbol_id`,`snapshot_id`),
  KEY `idx_symbol_kind_time` (`tenant_id`,`symbol_id`,`snapshot_kind`,`source_timestamp`),
  CONSTRAINT `chk_trade_market_snapshot` CHECK (`source_timestamp` > 0 AND `revision` > 0 AND `confirmed` IN (1,2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='结算使用的不可变行情及资金费快照';

DROP TABLE IF EXISTS `t_trade_seconds_price_snapshot`;
CREATE TABLE `t_trade_seconds_price_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_id` BIGINT NOT NULL COMMENT '秒合约订单ID',
  `snapshot_type` TINYINT NOT NULL COMMENT '快照类型：1起始价 2结算候选价 3最终结算价',
  `source` VARCHAR(64) NOT NULL COMMENT '行情来源',
  `price` DECIMAL(36,18) NOT NULL COMMENT '归一化价格',
  `quote_time` BIGINT NOT NULL COMMENT '行情业务时间',
  `received_at` BIGINT NOT NULL COMMENT 'Trade接收时间',
  `algorithm` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '采样算法及版本',
  `is_selected` TINYINT NOT NULL DEFAULT 2 COMMENT '是否被选为最终价格：1是 2否',
  `raw_payload` JSON DEFAULT NULL COMMENT '可审计的原始行情摘要',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_type_source_quote` (`tenant_id`, `order_id`, `snapshot_type`, `source`, `quote_time`),
  KEY `idx_order_snapshot_type` (`tenant_id`, `order_id`, `snapshot_type`, `quote_time`),
  CONSTRAINT `chk_seconds_price_snapshot` CHECK (`snapshot_type` IN (1, 2, 3) AND `price` > 0 AND `quote_time` > 0 AND `received_at` > 0 AND `is_selected` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='秒合约可审计价格快照';

DROP TABLE IF EXISTS `t_trade_fill`;
CREATE TABLE `t_trade_fill` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `fill_no` VARCHAR(64) NOT NULL COMMENT '成交号',
  `match_no` VARCHAR(64) NOT NULL COMMENT '撮合编号，同一买卖成交共享',
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '平台订单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `product_type` TINYINT NOT NULL COMMENT '产品大类快照：1现货 2衍生品',
  `contract_type` TINYINT NOT NULL DEFAULT 0 COMMENT '合约期限类型快照',
  `contract_value_type` TINYINT NOT NULL DEFAULT 0 COMMENT '合约价值类型快照',
  `side` TINYINT NOT NULL COMMENT '买卖方向：1买 2卖',
  `position_side` TINYINT NOT NULL DEFAULT 0 COMMENT '持仓方向：0未知/无 1净持仓 2多 3空',
  `price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '成交价格',
  `qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '成交数量',
  `amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '成交金额',
  `fee` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '手续费',
  `fee_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手续费币种',
  `liquidity_type` TINYINT NOT NULL DEFAULT 0 COMMENT '流动性类型：1Maker 2Taker',
  `realized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '已实现盈亏，现货一般为0',
  `settlement_status` TINYINT NOT NULL DEFAULT 1 COMMENT '结算状态：1待结算 2结算中 3已结算 4失败 5人工处理',
  `settlement_retry_count` INT NOT NULL DEFAULT 0 COMMENT '结算重试次数',
  `settled_at` BIGINT NOT NULL DEFAULT 0 COMMENT '结算完成时间',
  `match_time` BIGINT NOT NULL DEFAULT 0 COMMENT '成交时间，毫秒时间戳',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_fill_no` (`tenant_id`, `fill_no`),
  UNIQUE KEY `uk_tenant_match_order` (`tenant_id`, `match_no`, `order_id`),
  KEY `idx_tenant_order_id` (`tenant_id`, `order_id`),
  KEY `idx_tenant_match_no` (`tenant_id`, `match_no`),
  KEY `idx_settlement_retry` (`tenant_id`, `settlement_status`, `create_times`),
  KEY `idx_tenant_user_symbol_match_time` (`tenant_id`, `user_id`, `symbol_id`, `match_time`),
  CONSTRAINT `chk_fill_product_contract` CHECK (
    (`product_type` = 1 AND `contract_type` = 0 AND `contract_value_type` = 0)
    OR (`product_type` = 2 AND `contract_type` IN (1, 2) AND `contract_value_type` IN (1, 2))
  ),
  CONSTRAINT `chk_fill_values` CHECK (`side` IN (1, 2) AND `price` > 0 AND `qty` > 0 AND `amount` > 0 AND `fee` >= 0 AND `liquidity_type` IN (1, 2) AND `settlement_status` IN (1, 2, 3, 4, 5))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='成交明细表';

DROP TABLE IF EXISTS `t_trade_cancel_log`;
CREATE TABLE `t_trade_cancel_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '平台订单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `cancel_source` TINYINT NOT NULL COMMENT '撤单来源：1用户主动 2系统撤单 3风控撤单 4超时撤单',
  `cancel_reason` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '撤单原因',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_order_id` (`tenant_id`, `order_id`),
  KEY `idx_tenant_user_created` (`tenant_id`, `user_id`, `create_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='撤单日志表';

DROP TABLE IF EXISTS `t_contract_position`;
CREATE TABLE `t_contract_position` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `contract_type` TINYINT NOT NULL COMMENT '合约期限类型：1永续 2交割',
  `contract_value_type` TINYINT NOT NULL COMMENT '合约价值类型：1线性 2反向',
  `position_side` TINYINT NOT NULL COMMENT '持仓方向：1净持仓 2多 3空',
  `margin_mode` TINYINT NOT NULL COMMENT '保证金模式：1全仓 2逐仓',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '持仓状态：1正常 2待强平 3强平中 4交割中 5已关闭 6人工处理',
  `leverage` INT NOT NULL DEFAULT 1 COMMENT '当前杠杆倍数',
  `qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '当前持仓数量',
  `avail_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '可平仓数量',
  `frozen_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '挂单冻结数量',
  `open_avg_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '开仓均价',
  `mark_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '标记价格快照',
  `mark_snapshot_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '不可变标记价格快照ID',
  `margin_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '保证金币种',
  `position_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '仓位保证金',
  `maintenance_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '当前维持保证金要求',
  `isolated_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '逐仓追加保证金',
  `unrealized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '未实现盈亏',
  `realized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '已实现盈亏',
  `liquidation_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '强平价格',
  `bankruptcy_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '破产价格',
  `risk_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '最近一次风险率快照',
  `adl_rank` INT NOT NULL DEFAULT 0 COMMENT '自动减仓优先级',
  `last_funding_time` BIGINT NOT NULL DEFAULT 0 COMMENT '最近资金费结算时间',
  `closed_at` BIGINT NOT NULL DEFAULT 0 COMMENT '仓位关闭时间',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_symbol_side_mode` (`tenant_id`, `user_id`, `symbol_id`, `position_side`, `margin_mode`),
  KEY `idx_tenant_symbol_contract` (`tenant_id`, `symbol_id`, `contract_type`),
  KEY `idx_tenant_status_symbol` (`tenant_id`, `status`, `symbol_id`),
  KEY `idx_tenant_user_contract_value` (`tenant_id`, `user_id`, `contract_value_type`),
  CONSTRAINT `chk_position_dimensions` CHECK (`contract_type` IN (1, 2) AND `contract_value_type` IN (1, 2) AND `position_side` IN (1, 2, 3) AND `margin_mode` IN (1, 2) AND `status` BETWEEN 1 AND 6 AND `leverage` > 0),
  CONSTRAINT `chk_position_quantities` CHECK (`qty` >= 0 AND `avail_qty` >= 0 AND `frozen_qty` >= 0 AND `avail_qty` + `frozen_qty` <= `qty` AND `position_margin` >= 0 AND `maintenance_margin` >= 0 AND `isolated_margin` >= 0 AND `risk_rate` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约当前持仓表';

DROP TABLE IF EXISTS `t_contract_margin_snapshot`;
CREATE TABLE `t_contract_margin_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `margin_asset` VARCHAR(32) NOT NULL COMMENT '保证金币种',
  `wallet_balance` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT 'Asset账户余额快照，不作为资金账本',
  `available_balance` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT 'Asset可用余额快照',
  `frozen_balance` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT 'Asset冻结余额快照',
  `position_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '仓位占用保证金',
  `order_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '挂单占用保证金',
  `unrealized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '未实现盈亏',
  `realized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '已实现盈亏',
  `source_event_no` VARCHAR(64) DEFAULT NULL COMMENT '最新Asset事件号，用于投影幂等',
  `snapshot_time` BIGINT NOT NULL DEFAULT 0 COMMENT '快照业务时间',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_margin_asset` (`tenant_id`, `user_id`, `margin_asset`),
  UNIQUE KEY `uk_tenant_source_event` (`tenant_id`, `source_event_no`),
  CONSTRAINT `chk_margin_snapshot_balances` CHECK (`wallet_balance` >= 0 AND `available_balance` >= 0 AND `frozen_balance` >= 0 AND `position_margin` >= 0 AND `order_margin` >= 0 AND `version` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约风控保证金投影；Asset为资金账本唯一事实源';

DROP TABLE IF EXISTS `t_contract_position_history`;
CREATE TABLE `t_contract_position_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `position_id` BIGINT NOT NULL COMMENT '持仓ID，对应t_contract_position.id',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `contract_type` TINYINT NOT NULL COMMENT '合约期限类型快照：1永续 2交割',
  `contract_value_type` TINYINT NOT NULL COMMENT '合约价值类型快照：1线性 2反向',
  `position_side` TINYINT NOT NULL COMMENT '持仓方向：1净持仓 2多 3空',
  `action_type` TINYINT NOT NULL COMMENT '变更动作类型：1开仓 2加仓 3减仓 4平仓 5强平 6结算 7资金费结转 8手动调整',
  `action_key` VARCHAR(128) NOT NULL COMMENT '持仓变更幂等键，如fill_id+position_id+action',
  `before_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前持仓数量',
  `after_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后持仓数量',
  `before_avail_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前可平数量',
  `after_avail_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后可平数量',
  `before_frozen_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前冻结数量',
  `after_frozen_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后冻结数量',
  `before_open_avg_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前开仓均价',
  `after_open_avg_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后开仓均价',
  `before_position_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前仓位保证金',
  `after_position_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后仓位保证金',
  `before_isolated_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前逐仓附加保证金',
  `after_isolated_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后逐仓附加保证金',
  `before_unrealized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前未实现盈亏',
  `after_unrealized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后未实现盈亏',
  `realized_pnl_delta` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '本次变更产生的已实现盈亏增量',
  `fee_delta` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '本次变更产生的手续费增量',
  `fee_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手续费币种',
  `mark_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '本次记录时的标记价格',
  `ref_order_id` BIGINT NOT NULL DEFAULT 0 COMMENT '关联订单ID，没有则为0',
  `ref_fill_id` BIGINT NOT NULL DEFAULT 0 COMMENT '关联成交ID，没有则为0',
  `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_action_key` (`tenant_id`, `action_key`),
  KEY `idx_tenant_position_id_created` (`tenant_id`, `position_id`, `create_times`),
  KEY `idx_tenant_user_symbol_created` (`tenant_id`, `user_id`, `symbol_id`, `create_times`),
  KEY `idx_tenant_ref_order_id` (`tenant_id`, `ref_order_id`),
  KEY `idx_tenant_ref_fill_id` (`tenant_id`, `ref_fill_id`),
  CONSTRAINT `chk_position_history_dimensions` CHECK (`contract_type` IN (1, 2) AND `contract_value_type` IN (1, 2) AND `position_side` IN (1, 2, 3) AND `action_type` IN (1, 2, 3, 4, 5, 6, 7, 8))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约持仓历史表';

DROP TABLE IF EXISTS `t_contract_leverage_config`;
CREATE TABLE `t_contract_leverage_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `margin_mode` TINYINT NOT NULL COMMENT '保证金模式：1全仓 2逐仓',
  `long_leverage` INT NOT NULL DEFAULT 1 COMMENT '做多杠杆倍数',
  `short_leverage` INT NOT NULL DEFAULT 1 COMMENT '做空杠杆倍数',
  `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '启用开关：1启用 2禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_symbol_margin_mode` (`tenant_id`, `user_id`, `symbol_id`, `margin_mode`),
  KEY `idx_tenant_user_symbol` (`tenant_id`, `user_id`, `symbol_id`),
  CONSTRAINT `chk_user_leverage` CHECK (`margin_mode` IN (1, 2) AND `long_leverage` > 0 AND `short_leverage` > 0 AND `enabled` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户合约杠杆配置表';

DROP TABLE IF EXISTS `t_trade_symbol_leverage_config`;
CREATE TABLE `t_trade_symbol_leverage_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID，对应t_trade_symbol.id',
  `margin_mode` TINYINT NOT NULL COMMENT '保证金模式：1全仓 2逐仓',
  `leverage_values` JSON NOT NULL COMMENT '可选杠杆倍数列表，如[1,2,5,10]',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '启用开关：1启用 2禁用',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_margin_mode` (`tenant_id`, `symbol_id`, `margin_mode`),
  KEY `idx_tenant_symbol_margin_enabled` (`tenant_id`, `symbol_id`, `margin_mode`, `enabled`),
  CONSTRAINT `chk_symbol_leverage` CHECK (`margin_mode` IN (1, 2) AND JSON_LENGTH(`leverage_values`) > 0 AND `enabled` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易对杠杆档位配置表';

DROP TABLE IF EXISTS `t_trade_symbol_leverage_default`;
CREATE TABLE `t_trade_symbol_leverage_default` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `margin_mode` TINYINT NOT NULL COMMENT '保证金模式：1全仓 2逐仓',
  `leverage` INT NOT NULL COMMENT '默认杠杆倍数，必须来自已启用档位',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_margin` (`tenant_id`, `symbol_id`, `margin_mode`),
  CONSTRAINT `chk_symbol_default_leverage` CHECK (`margin_mode` IN (1, 2) AND `leverage` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易对默认杠杆配置；每个保证金模式唯一';

DROP TABLE IF EXISTS `t_contract_risk_limit_tier`;
CREATE TABLE `t_contract_risk_limit_tier` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `tier_no` INT NOT NULL COMMENT '风险档位，从1递增',
  `notional_floor` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '名义价值下界，含',
  `notional_cap` DECIMAL(36,18) NOT NULL COMMENT '名义价值上界，0表示不限',
  `max_leverage` INT NOT NULL COMMENT '该档最大杠杆',
  `initial_margin_rate` DECIMAL(20,10) NOT NULL COMMENT '该档初始保证金率',
  `maintenance_margin_rate` DECIMAL(20,10) NOT NULL COMMENT '该档维持保证金率',
  `maintenance_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '维持保证金速算扣除额',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 2禁用',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_tier` (`tenant_id`, `symbol_id`, `tier_no`),
  KEY `idx_symbol_notional` (`tenant_id`, `symbol_id`, `enabled`, `notional_floor`),
  CONSTRAINT `chk_contract_risk_tier` CHECK (`tier_no` > 0 AND `notional_floor` >= 0 AND (`notional_cap` = 0 OR `notional_cap` > `notional_floor`) AND `max_leverage` > 0 AND `initial_margin_rate` >= `maintenance_margin_rate` AND `maintenance_margin_rate` >= 0 AND `maintenance_amount` >= 0 AND `enabled` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约名义价值风险限额档位';

DROP TABLE IF EXISTS `t_risk_user_trade_limit`;
CREATE TABLE `t_risk_user_trade_limit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `product_type` TINYINT NOT NULL COMMENT '产品大类：1现货 2衍生品 3秒合约',
  `can_open` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许开仓/开单：1允许 0禁止',
  `can_close` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许平仓/卖出：1允许 0禁止',
  `can_cancel` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许撤单：1允许 0禁止',
  `can_trigger_order` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许条件单：1允许 0禁止',
  `can_api_trade` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许API交易：1允许 0禁止',
  `trade_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '交易开关：1启用 2禁用',
  `only_reduce_only` TINYINT NOT NULL DEFAULT 2 COMMENT '仅减仓开关：1启用 2禁用',
  `max_open_order_count` INT NOT NULL DEFAULT 0 COMMENT '最大挂单数，0表示不限',
  `max_order_count_per_day` INT NOT NULL DEFAULT 0 COMMENT '单日最大下单次数，0表示不限',
  `max_cancel_count_per_day` INT NOT NULL DEFAULT 0 COMMENT '单日最大撤单次数，0表示不限',
  `max_open_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大可开仓名义价值，0表示不限',
  `max_position_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大持仓名义价值，0表示不限',
  `risk_level` TINYINT NOT NULL DEFAULT 0 COMMENT '风险等级：0默认 1低风险限制 2中风险限制 3高风险限制',
  `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '启用开关：1启用 2禁用',
  `effective_start_time` BIGINT NOT NULL DEFAULT 0 COMMENT '限制生效开始时间，毫秒时间戳，0表示立即生效',
  `effective_end_time` BIGINT NOT NULL DEFAULT 0 COMMENT '限制生效结束时间，毫秒时间戳，0表示长期有效',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_product_type` (`tenant_id`, `user_id`, `product_type`),
  KEY `idx_tenant_trade_enabled` (`tenant_id`, `trade_enabled`),
  KEY `idx_tenant_enabled` (`tenant_id`, `enabled`),
  CONSTRAINT `chk_user_trade_limit_flags` CHECK (`product_type` IN (1, 2, 3) AND `can_open` IN (0, 1) AND `can_close` IN (0, 1) AND `can_cancel` IN (0, 1) AND `can_trigger_order` IN (0, 1) AND `can_api_trade` IN (0, 1) AND `trade_enabled` IN (1, 2) AND `only_reduce_only` IN (1, 2) AND `enabled` IN (1, 2)),
  CONSTRAINT `chk_user_trade_limit_values` CHECK (`max_open_order_count` >= 0 AND `max_order_count_per_day` >= 0 AND `max_cancel_count_per_day` >= 0 AND `max_open_notional` >= 0 AND `max_position_notional` >= 0 AND (`effective_end_time` = 0 OR `effective_start_time` = 0 OR `effective_end_time` > `effective_start_time`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户交易限制表';

DROP TABLE IF EXISTS `t_risk_user_symbol_limit`;
CREATE TABLE `t_risk_user_symbol_limit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `max_position_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大持仓数量，0表示不限',
  `max_position_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大持仓名义价值，0表示不限',
  `max_open_orders` INT NOT NULL DEFAULT 0 COMMENT '最大挂单数，0表示不限',
  `max_order_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '单笔最大下单数量，0表示不限',
  `max_order_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '单笔最大下单名义价值，0表示不限',
  `min_order_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '单笔最小下单数量，0表示不限制',
  `min_order_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '单笔最小下单名义价值，0表示不限制',
  `max_long_position_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大多头持仓数量，0表示不限',
  `max_short_position_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大空头持仓数量，0表示不限',
  `price_deviation_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '允许价格偏离率，0表示不限制',
  `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '启用开关：1启用 2禁用',
  `effective_start_time` BIGINT NOT NULL DEFAULT 0 COMMENT '限制生效开始时间，毫秒时间戳',
  `effective_end_time` BIGINT NOT NULL DEFAULT 0 COMMENT '限制生效结束时间，毫秒时间戳',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_symbol` (`tenant_id`, `user_id`, `symbol_id`),
  KEY `idx_tenant_symbol` (`tenant_id`, `symbol_id`),
  CONSTRAINT `chk_user_symbol_limit_values` CHECK (`max_position_qty` >= 0 AND `max_position_notional` >= 0 AND `max_open_orders` >= 0 AND `max_order_qty` >= 0 AND `max_order_notional` >= 0 AND `min_order_qty` >= 0 AND `min_order_notional` >= 0 AND `max_long_position_qty` >= 0 AND `max_short_position_qty` >= 0 AND `price_deviation_rate` >= 0 AND `enabled` IN (1, 2)),
  CONSTRAINT `chk_user_symbol_limit_time` CHECK (`effective_end_time` = 0 OR `effective_start_time` = 0 OR `effective_end_time` > `effective_start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户单标的限制表';

DROP TABLE IF EXISTS `t_risk_order_check_log`;
CREATE TABLE `t_risk_order_check_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '平台订单号',
  `client_order_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户端订单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `product_type` TINYINT NOT NULL COMMENT '产品大类快照',
  `check_type` TINYINT NOT NULL COMMENT '检查类型：1余额检查 2保证金检查 3仓位检查 4交易权限检查 5价格保护检查 6数量限制检查 7名义价值限制检查 8频率限制检查',
  `check_result` TINYINT NOT NULL COMMENT '检查结果：1通过 2拒绝 3告警放行',
  `reject_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '拒绝码',
  `reject_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '拒绝原因描述',
  `request_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '请求价格',
  `request_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '请求数量',
  `request_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '请求名义价值或金额',
  `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `check_snapshot` JSON DEFAULT NULL COMMENT '检查时的上下文快照，JSON格式',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_order_no` (`tenant_id`, `order_no`),
  KEY `idx_tenant_user_symbol_created` (`tenant_id`, `user_id`, `symbol_id`, `create_times`),
  KEY `idx_tenant_product_check_created` (`tenant_id`, `product_type`, `check_type`, `create_times`),
  CONSTRAINT `chk_risk_check_log` CHECK (`product_type` IN (1, 2, 3) AND `check_type` BETWEEN 1 AND 8 AND `check_result` IN (1, 2, 3) AND `request_price` >= 0 AND `request_qty` >= 0 AND `request_amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单风控检查日志表';

DROP TABLE IF EXISTS `t_biz_trade_event`;
CREATE TABLE `t_biz_trade_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `event_no` VARCHAR(64) NOT NULL COMMENT '事件号',
  `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型，如ORDER_CREATED、ORDER_FILLED、ORDER_CANCELED、POSITION_CHANGED、MARGIN_CHANGED',
  `biz_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务主键，如订单号、成交号、持仓ID等',
  `biz_type` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务类型，如order、fill、position、margin',
  `user_id` BIGINT NOT NULL DEFAULT 0 COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL DEFAULT 0 COMMENT '交易标的ID，没有则为0',
  `product_type` TINYINT NOT NULL DEFAULT 0 COMMENT '产品大类：0无 1现货 2衍生品 3秒合约',
  `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `consumer` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '目标消费者标识；内部实时事件为trade-realtime',
  `event_status` TINYINT NOT NULL DEFAULT 1 COMMENT '事件状态：1待投递 2投递成功 3投递失败 4已取消 5投递中 6死信',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `max_retry_count` INT NOT NULL DEFAULT 20 COMMENT '最大重试次数',
  `next_retry_at` BIGINT NOT NULL DEFAULT 0 COMMENT '下次重试时间，毫秒时间戳',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后一次投递错误信息',
  `claimed_by` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '当前领取实例',
  `claimed_at` BIGINT NOT NULL DEFAULT 0 COMMENT '领取时间，毫秒时间戳',
  `delivered_at` BIGINT NOT NULL DEFAULT 0 COMMENT '消费成功时间，毫秒时间戳',
  `payload_version` INT NOT NULL DEFAULT 1 COMMENT '事件Payload结构版本',
  `payload` JSON NOT NULL COMMENT '事件内容，JSON格式',
  `ext_data` JSON DEFAULT NULL COMMENT '扩展字段，JSON格式',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_event_no` (`tenant_id`, `event_no`),
  KEY `idx_tenant_event_status_next_retry_at` (`tenant_id`, `event_status`, `next_retry_at`),
  KEY `idx_tenant_event_status_claimed_at` (`tenant_id`, `event_status`, `claimed_at`),
  KEY `idx_tenant_event_type_created` (`tenant_id`, `event_type`, `create_times`),
  KEY `idx_tenant_biz_type_biz_id` (`tenant_id`, `biz_type`, `biz_id`),
  KEY `idx_tenant_user_created` (`tenant_id`, `user_id`, `create_times`),
  CONSTRAINT `chk_trade_event` CHECK (`product_type` IN (0, 1, 2, 3) AND `event_status` IN (1, 2, 3, 4, 5, 6) AND `retry_count` >= 0 AND `max_retry_count` >= 0 AND `payload_version` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易业务事件表';

DROP TABLE IF EXISTS `t_trade_event_inbox`;
CREATE TABLE `t_trade_event_inbox` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '上游事件所属租户ID',
  `consumer` VARCHAR(64) NOT NULL COMMENT '消费者名称',
  `event_no` VARCHAR(64) NOT NULL COMMENT '上游事件号',
  `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1处理中 2成功 3失败',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后错误',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_consumer_tenant_event` (`consumer`, `tenant_id`, `event_no`),
  KEY `idx_tenant_status_update` (`tenant_id`, `status`, `update_times`),
  CONSTRAINT `chk_inbox_status` CHECK (`status` IN (1, 2, 3) AND `retry_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易事件消费幂等表';

DROP TABLE IF EXISTS `t_trade_asset_reservation`;
CREATE TABLE `t_trade_asset_reservation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `reservation_no` VARCHAR(64) NOT NULL COMMENT 'Asset预占号',
  `asset` VARCHAR(32) NOT NULL COMMENT '预占资产',
  `reserved_amount` DECIMAL(36,18) NOT NULL COMMENT '预占金额',
  `consumed_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '已结算消耗金额',
  `released_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '已释放金额',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1冻结中 2已冻结 3部分消耗 4已消耗 5释放中 6已释放 7失败',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '查询、消费或释放重试次数',
  `next_retry_at` BIGINT NOT NULL DEFAULT 0 COMMENT '下次重试时间',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后错误',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_reservation_no` (`tenant_id`, `reservation_no`),
  KEY `idx_tenant_order_status` (`tenant_id`, `order_id`, `status`),
  CONSTRAINT `chk_asset_reservation_amounts` CHECK (`reserved_amount` > 0 AND `consumed_amount` >= 0 AND `released_amount` >= 0 AND `consumed_amount` + `released_amount` <= `reserved_amount`),
  CONSTRAINT `chk_asset_reservation_status` CHECK (`status` IN (1, 2, 3, 4, 5, 6, 7) AND `retry_count` >= 0 AND `version` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单资金预占状态镜像';

DROP TABLE IF EXISTS `t_trade_settlement_instruction`;
CREATE TABLE `t_trade_settlement_instruction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `instruction_no` VARCHAR(64) NOT NULL COMMENT '结算指令号/幂等键',
  `biz_type` VARCHAR(32) NOT NULL DEFAULT 'fill' COMMENT '业务类型：fill/order/funding/delivery/liquidation/seconds',
  `biz_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务幂等主键',
  `batch_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '资金费、交割或强平批次号',
  `fill_id` BIGINT NOT NULL DEFAULT 0 COMMENT '成交ID，非成交结算可为0',
  `order_id` BIGINT NOT NULL DEFAULT 0 COMMENT '订单ID',
  `position_id` BIGINT NOT NULL DEFAULT 0 COMMENT '持仓ID，非持仓结算可为0',
  `reservation_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '关联Asset预占号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `action` TINYINT NOT NULL COMMENT '动作：1扣冻结 2释放冻结 3可用入账 4扣手续费 5盈亏入账 6保证金调整',
  `asset` VARCHAR(32) NOT NULL COMMENT '资产',
  `amount` DECIMAL(36,18) NOT NULL COMMENT '金额，正数',
  `step_no` INT NOT NULL DEFAULT 1 COMMENT '同一业务Saga内的执行顺序',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1待执行 2执行中 3成功 4失败 5人工处理',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `next_retry_at` BIGINT NOT NULL DEFAULT 0 COMMENT '下次重试时间',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后错误',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_instruction_no` (`tenant_id`, `instruction_no`),
  KEY `idx_pending_retry` (`tenant_id`, `status`, `next_retry_at`),
  KEY `idx_tenant_fill` (`tenant_id`, `fill_id`),
  KEY `idx_tenant_order` (`tenant_id`, `order_id`),
  KEY `idx_tenant_biz` (`tenant_id`, `biz_type`, `biz_id`, `step_no`),
  CONSTRAINT `chk_settlement_instruction` CHECK (`action` IN (1, 2, 3, 4, 5, 6, 7, 8) AND `amount` > 0 AND `step_no` > 0 AND `status` IN (1, 2, 3, 4, 5) AND `retry_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发送给Asset的幂等结算指令';

DROP TABLE IF EXISTS `t_contract_liquidation`;
CREATE TABLE `t_contract_liquidation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `liquidation_no` VARCHAR(64) NOT NULL COMMENT '强平批次号',
  `position_id` BIGINT NOT NULL COMMENT '被接管持仓ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `position_side` TINYINT NOT NULL COMMENT '仓位方向：1净持仓 2多 3空',
  `margin_mode` TINYINT NOT NULL COMMENT '保证金模式：1全仓 2逐仓',
  `trigger_mark_price` DECIMAL(36,18) NOT NULL COMMENT '触发强平的标记价格',
  `trigger_snapshot_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '强平触发价格快照ID',
  `trigger_index_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '触发时指数价格',
  `trigger_qty` DECIMAL(36,18) NOT NULL COMMENT '接管时仓位数量',
  `liquidated_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '已强平数量',
  `maintenance_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '触发时维持保证金',
  `account_equity` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '触发时风险单元权益，可为负',
  `bankruptcy_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '破产价格',
  `liquidation_fee` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '强平手续费',
  `insurance_fund_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '保险基金承接金额',
  `adl_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT 'ADL处理数量',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1待接管 2强平中 3部分强平恢复 4已强平 5保险基金处理 6ADL处理 7人工处理',
  `reason` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '触发及结束原因',
  `started_at` BIGINT NOT NULL DEFAULT 0 COMMENT '开始时间',
  `completed_at` BIGINT NOT NULL DEFAULT 0 COMMENT '完成时间',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_liquidation_no` (`tenant_id`, `liquidation_no`),
  KEY `idx_position_status` (`tenant_id`, `position_id`, `status`),
  KEY `idx_symbol_status_created` (`tenant_id`, `symbol_id`, `status`, `create_times`),
  CONSTRAINT `chk_contract_liquidation` CHECK (`position_side` IN (1, 2, 3) AND `margin_mode` IN (1, 2) AND `trigger_mark_price` > 0 AND `trigger_index_price` >= 0 AND `trigger_qty` > 0 AND `liquidated_qty` >= 0 AND `liquidated_qty` <= `trigger_qty` AND `maintenance_margin` >= 0 AND `bankruptcy_price` >= 0 AND `liquidation_fee` >= 0 AND `insurance_fund_amount` >= 0 AND `adl_qty` >= 0 AND `status` BETWEEN 1 AND 7 AND `version` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约强平、保险基金与ADL处理记录';

DROP TABLE IF EXISTS `t_contract_insurance_fund_account`;
CREATE TABLE `t_contract_insurance_fund_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
  `symbol_id` BIGINT NOT NULL DEFAULT 0 COMMENT '交易标的ID，0表示该资产默认账户',
  `settle_asset` VARCHAR(32) NOT NULL COMMENT '结算资产',
  `adl_enabled` TINYINT NOT NULL DEFAULT 2 COMMENT '余额不足是否启用ADL：1是 2否',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 2禁用',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_asset` (`tenant_id`, `symbol_id`, `settle_asset`),
  KEY `idx_tenant_asset_status` (`tenant_id`, `settle_asset`, `status`),
  CONSTRAINT `chk_insurance_fund_account` CHECK (`adl_enabled` IN (1,2) AND `status` IN (1,2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租户级合约保险基金账户配置';

DROP TABLE IF EXISTS `t_contract_funding_batch`;
CREATE TABLE `t_contract_funding_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `batch_no` VARCHAR(64) NOT NULL COMMENT '资金费批次号',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `funding_rate` DECIMAL(20,10) NOT NULL COMMENT '锁定资金费率',
  `mark_price` DECIMAL(36,18) NOT NULL COMMENT '锁定标记价格',
  `index_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '锁定指数价格',
  `price_source` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '统一资金费快照ID',
  `formula_version` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '费率与金额公式版本',
  `settlement_time` BIGINT NOT NULL COMMENT '资金费结算时刻',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1价格已锁定 2结算中 3已完成 4失败 5人工处理',
  `total_positions` INT NOT NULL DEFAULT 0 COMMENT '批次仓位总数',
  `settled_positions` INT NOT NULL DEFAULT 0 COMMENT '已结算仓位数',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后错误',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_batch_no` (`tenant_id`, `batch_no`),
  UNIQUE KEY `uk_symbol_settlement_time` (`tenant_id`, `symbol_id`, `settlement_time`),
  KEY `idx_funding_batch_status` (`tenant_id`, `status`, `settlement_time`),
  CONSTRAINT `chk_funding_batch` CHECK (`mark_price` > 0 AND `index_price` >= 0 AND `settlement_time` > 0 AND `status` BETWEEN 1 AND 5 AND `total_positions` >= 0 AND `settled_positions` >= 0 AND `settled_positions` <= `total_positions` AND `version` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='永续合约资金费锁定与执行批次';

DROP TABLE IF EXISTS `t_contract_funding_difference_account`;
CREATE TABLE `t_contract_funding_difference_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `settle_asset` VARCHAR(32) NOT NULL,
  `fund_user_id` BIGINT NOT NULL COMMENT 'Asset平台资金费差额账户用户ID',
  `wallet_type` TINYINT NOT NULL COMMENT 'Asset钱包类型',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 2禁用',
  `version` BIGINT NOT NULL DEFAULT 0,
  `create_times` BIGINT NOT NULL DEFAULT 0,
  `update_times` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_asset` (`tenant_id`,`settle_asset`),
  CONSTRAINT `chk_funding_difference_account` CHECK (`tenant_id` > 0 AND `fund_user_id` > 0 AND `wallet_type` > 0 AND `status` IN (1,2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资金费舍入及非零差额平台账户';

DROP TABLE IF EXISTS `t_contract_funding_settlement`;
CREATE TABLE `t_contract_funding_settlement` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `settlement_no` VARCHAR(64) NOT NULL COMMENT '资金费结算号',
  `batch_id` BIGINT NOT NULL COMMENT '资金费批次ID',
  `batch_no` VARCHAR(64) NOT NULL COMMENT '资金费批次号快照',
  `symbol_id` BIGINT NOT NULL COMMENT '交易标的ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `position_id` BIGINT NOT NULL COMMENT '持仓ID',
  `position_side` TINYINT NOT NULL COMMENT '仓位方向快照：1净持仓 2多 3空',
  `funding_rate` DECIMAL(20,10) NOT NULL COMMENT '资金费率',
  `mark_price` DECIMAL(36,18) NOT NULL COMMENT '结算标记价',
  `position_qty` DECIMAL(36,18) NOT NULL COMMENT '结算持仓量',
  `position_version` BIGINT NOT NULL COMMENT '批次锁定时持仓版本',
  `fee_asset` VARCHAR(32) NOT NULL COMMENT '资金费资产',
  `fee_amount` DECIMAL(36,18) NOT NULL COMMENT '资金费，正收负付',
  `settlement_time` BIGINT NOT NULL COMMENT '结算时间',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1待结算 2已结算 3失败 4人工处理',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `next_retry_at` BIGINT NOT NULL DEFAULT 0 COMMENT '下次重试时间',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后错误',
  `settled_at` BIGINT NOT NULL DEFAULT 0 COMMENT '结算完成时间',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_settlement_no` (`tenant_id`, `settlement_no`),
  UNIQUE KEY `uk_batch_position` (`tenant_id`, `batch_id`, `position_id`),
  KEY `idx_funding_settlement_retry` (`tenant_id`, `status`, `next_retry_at`),
  CONSTRAINT `chk_funding_settlement` CHECK (`position_side` IN (1, 2, 3) AND `mark_price` > 0 AND `position_qty` > 0 AND `position_version` >= 0 AND `settlement_time` > 0 AND `status` IN (1, 2, 3, 4) AND `retry_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='永续合约资金费结算记录';

DROP TABLE IF EXISTS `t_contract_adl_execution`;
CREATE TABLE `t_contract_adl_execution` (
  `id` BIGINT NOT NULL AUTO_INCREMENT, `tenant_id` BIGINT NOT NULL,
  `execution_no` VARCHAR(96) NOT NULL, `liquidation_id` BIGINT NOT NULL, `liquidation_no` VARCHAR(64) NOT NULL,
  `position_id` BIGINT NOT NULL, `user_id` BIGINT NOT NULL, `position_version` BIGINT NOT NULL,
  `qty` DECIMAL(36,18) NOT NULL, `position_margin_release` DECIMAL(36,18) NOT NULL,
  `isolated_margin_release` DECIMAL(36,18) NOT NULL, `realized_pnl` DECIMAL(36,18) NOT NULL,
  `asset_credit` DECIMAL(36,18) NOT NULL, `asset` VARCHAR(32) NOT NULL,
  `bankruptcy_price` DECIMAL(36,18) NOT NULL, `relief_amount` DECIMAL(36,18) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1, `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '',
  `create_times` BIGINT NOT NULL DEFAULT 0, `update_times` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_tenant_execution` (`tenant_id`,`execution_no`),
  UNIQUE KEY `uk_liquidation_position` (`tenant_id`,`liquidation_id`,`position_id`),
  KEY `idx_adl_recovery` (`tenant_id`,`status`,`update_times`),
  CONSTRAINT `chk_adl_execution` CHECK (`qty` > 0 AND `position_margin_release` >= 0 AND `isolated_margin_release` >= 0 AND `asset_credit` >= 0 AND `relief_amount` > 0 AND `status` IN (1,2,3,4,5))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ADL资产与仓位持久化执行步骤';

DROP TABLE IF EXISTS `t_contract_delivery_batch`;
CREATE TABLE `t_contract_delivery_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `batch_no` VARCHAR(64) NOT NULL COMMENT '交割批次号',
  `symbol_id` BIGINT NOT NULL COMMENT '交割合约标的ID',
  `settlement_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '锁定交割价格',
  `price_source` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '统一交割价格快照ID',
  `price_algorithm` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '采样算法及版本',
  `sample_snapshot` JSON DEFAULT NULL COMMENT '原始样本与剔除信息摘要',
  `open_cutoff_time` BIGINT NOT NULL DEFAULT 0 COMMENT '停止开仓时间快照',
  `matching_stop_time` BIGINT NOT NULL DEFAULT 0 COMMENT '停止撮合时间快照',
  `delivery_time` BIGINT NOT NULL COMMENT '计划交割时间',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1仅平仓 2停止撮合 3锁价中 4结算中 5已完成 6失败 7人工处理 8归档',
  `total_positions` INT NOT NULL DEFAULT 0 COMMENT '待交割仓位总数',
  `settled_positions` INT NOT NULL DEFAULT 0 COMMENT '已交割仓位数',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后错误',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '并发版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_batch_no` (`tenant_id`, `batch_no`),
  UNIQUE KEY `uk_symbol_delivery_time` (`tenant_id`, `symbol_id`, `delivery_time`),
  KEY `idx_delivery_batch_status` (`tenant_id`, `status`, `delivery_time`),
  CONSTRAINT `chk_delivery_batch` CHECK (`settlement_price` >= 0 AND `delivery_time` > 0 AND `status` BETWEEN 1 AND 8 AND `total_positions` >= 0 AND `settled_positions` >= 0 AND `settled_positions` <= `total_positions` AND `version` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交割合约价格锁定与执行批次';

DROP TABLE IF EXISTS `t_contract_delivery_settlement`;
CREATE TABLE `t_contract_delivery_settlement` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  `settlement_no` VARCHAR(64) NOT NULL COMMENT '交割结算号',
  `batch_id` BIGINT NOT NULL COMMENT '交割批次ID',
  `batch_no` VARCHAR(64) NOT NULL COMMENT '交割批次号快照',
  `symbol_id` BIGINT NOT NULL COMMENT '交割合约标的ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `position_id` BIGINT NOT NULL COMMENT '持仓ID',
  `position_side` TINYINT NOT NULL COMMENT '仓位方向快照：1净持仓 2多 3空',
  `settlement_price` DECIMAL(36,18) NOT NULL COMMENT '交割价格',
  `position_qty` DECIMAL(36,18) NOT NULL COMMENT '交割持仓量',
  `realized_pnl` DECIMAL(36,18) NOT NULL COMMENT '交割已实现盈亏',
  `delivery_fee` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '交割手续费',
  `settle_asset` VARCHAR(32) NOT NULL COMMENT '结算资产',
  `delivery_time` BIGINT NOT NULL COMMENT '交割时间',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1待结算 2已结算 3失败 4人工处理',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `next_retry_at` BIGINT NOT NULL DEFAULT 0 COMMENT '下次重试时间',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后错误',
  `settled_at` BIGINT NOT NULL DEFAULT 0 COMMENT '结算完成时间',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_settlement_no` (`tenant_id`, `settlement_no`),
  UNIQUE KEY `uk_batch_position` (`tenant_id`, `batch_id`, `position_id`),
  KEY `idx_delivery_settlement_retry` (`tenant_id`, `status`, `next_retry_at`),
  CONSTRAINT `chk_delivery_settlement` CHECK (`position_side` IN (1, 2, 3) AND `settlement_price` > 0 AND `position_qty` > 0 AND `delivery_fee` >= 0 AND `delivery_time` > 0 AND `status` IN (1, 2, 3, 4) AND `retry_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交割合约到期结算记录';
