CREATE TABLE `t_trade_symbol` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol` VARCHAR(64) NOT NULL COMMENT '统一交易标的代码，如BTCUSDT、ETHUSD-PERP',
  `display_symbol` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '前端展示名称',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：1现货 2秒合约 3U本位 4币本位',
  `base_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '基础资产，例如BTC',
  `quote_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '计价资产，例如USDT',
  `settle_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '结算资产，现货一般等于quote_asset',
  `contract_type` TINYINT NOT NULL DEFAULT 0 COMMENT '合约类型：0非合约 1永续 2交割 3秒合约',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '交易状态：1启用 2停用 3仅平仓',
  `price_scale` INT NOT NULL DEFAULT 8 COMMENT '价格精度，小数位数',
  `qty_scale` INT NOT NULL DEFAULT 8 COMMENT '数量精度，小数位数',
  `min_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最小下单价格',
  `max_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大下单价格',
  `price_tick` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '价格步长',
  `min_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最小下单数量',
  `max_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大下单数量',
  `qty_step` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '数量步长',
  `min_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最小名义价值',
  `max_leverage` INT NOT NULL DEFAULT 1 COMMENT '最大杠杆倍数，现货固定为1',
  `open_time` BIGINT NOT NULL DEFAULT 0 COMMENT '开盘时间，毫秒时间戳，0表示不限',
  `close_time` BIGINT NOT NULL DEFAULT 0 COMMENT '收盘时间，毫秒时间戳，0表示不限',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_market_type` (`tenant_id`, `symbol`, `market_type`),
  KEY `idx_tenant_status_market_type` (`tenant_id`, `status`, `market_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易标的主表';

CREATE TABLE `t_trade_symbol_spot` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL COMMENT '交易标的ID，对应t_trade_symbol.id',
  `maker_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT 'Maker手续费率',
  `taker_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT 'Taker手续费率',
  `buy_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许买入：1允许 0禁止',
  `sell_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许卖出：1允许 0禁止',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_id` (`tenant_id`, `symbol_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='现货交易对扩展表';

CREATE TABLE `t_trade_symbol_contract` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL COMMENT '交易标的ID，对应t_trade_symbol.id',
  `contract_size` DECIMAL(36,18) NOT NULL DEFAULT 1 COMMENT '每张合约面值',
  `multiplier` DECIMAL(36,18) NOT NULL DEFAULT 1 COMMENT '合约乘数',
  `maintenance_margin_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '维持保证金率',
  `initial_margin_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '初始保证金率',
  `maker_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT 'Maker手续费率',
  `taker_fee_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT 'Taker手续费率',
  `funding_interval_minutes` INT NOT NULL DEFAULT 0 COMMENT '资金费结算周期，单位分钟',
  `delivery_time` BIGINT NOT NULL DEFAULT 0 COMMENT '交割时间或到期时间，永续合约为0',
  `support_cross` TINYINT NOT NULL DEFAULT 1 COMMENT '是否支持全仓：1支持 0不支持',
  `support_isolated` TINYINT NOT NULL DEFAULT 1 COMMENT '是否支持逐仓：1支持 0不支持',
  `buy_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许开多/买入：1允许 0禁止',
  `sell_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许开空/卖出：1允许 0禁止',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_symbol_id` (`tenant_id`, `symbol_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约交易对扩展表';

CREATE TABLE `t_trade_user_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：1现货 2秒合约 3U本位 4币本位',
  `symbol_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易标的ID，0表示该市场下的全局配置',
  `position_mode` TINYINT NOT NULL DEFAULT 1 COMMENT '持仓模式：1单向持仓 2双向持仓',
  `margin_mode` TINYINT NOT NULL DEFAULT 1 COMMENT '保证金模式：1全仓 2逐仓',
  `default_leverage` INT NOT NULL DEFAULT 1 COMMENT '默认杠杆倍数',
  `trade_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许交易：1允许 0禁止',
  `reduce_only_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否仅允许减仓：1是 0否',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_market_symbol` (`tenant_id`, `user_id`, `market_type`, `symbol_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户交易配置表';

CREATE TABLE `t_trade_order` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '平台订单号，全租户内唯一',
  `client_order_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户端订单号，用于幂等控制',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL COMMENT '交易标的ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：1现货 2秒合约 3U本位 4币本位',
  `side` TINYINT NOT NULL COMMENT '买卖方向：1买 2卖',
  `position_side` TINYINT NOT NULL DEFAULT 0 COMMENT '持仓方向：0无 1多 2空，现货一般为0',
  `order_type` TINYINT NOT NULL COMMENT '订单类型：1限价 2市价 3条件单 4止盈 5止损',
  `time_in_force` TINYINT NOT NULL DEFAULT 0 COMMENT '订单有效方式：0默认 1GTC 2IOC 3FOK 4PostOnly',
  `status` TINYINT NOT NULL COMMENT '订单状态：1待成交 2部分成交 3已成交 4已撤单 5已拒单 6已过期',
  `price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '委托价格',
  `qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '委托数量',
  `amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '委托总额或名义价值',
  `filled_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '累计成交数量',
  `filled_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '累计成交金额',
  `avg_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '平均成交价格',
  `fee` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '累计手续费',
  `fee_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手续费币种',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '订单来源：1App 2Web 3API 4System',
  `is_reduce_only` TINYINT NOT NULL DEFAULT 0 COMMENT '是否只减仓：1是 0否',
  `is_close_only` TINYINT NOT NULL DEFAULT 0 COMMENT '是否只允许平仓：1是 0否',
  `trigger_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '触发价格，非条件单则为0',
  `trigger_type` TINYINT NOT NULL DEFAULT 0 COMMENT '触发价格类型：0无 1最新价 2标记价 3指数价',
  `cancel_reason` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '撤单原因或拒单原因',
  `biz_ext` JSON DEFAULT NULL COMMENT '业务扩展字段，JSON格式',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_no` (`tenant_id`, `order_no`),
  UNIQUE KEY `uk_tenant_user_client_order_id` (`tenant_id`, `user_id`, `client_order_id`),
  KEY `idx_tenant_user_status_created` (`tenant_id`, `user_id`, `status`, `create_times`),
  KEY `idx_tenant_symbol_status_created` (`tenant_id`, `symbol_id`, `status`, `create_times`),
  KEY `idx_tenant_user_market_created` (`tenant_id`, `user_id`, `market_type`, `create_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易订单主表';

CREATE TABLE `t_trade_order_spot` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单ID，对应t_trade_order.id',
  `frozen_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '下单冻结的资产币种',
  `frozen_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '下单冻结的资产数量',
  `settle_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '结算币种',
  `settle_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '结算金额',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_id` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='现货订单明细表';

CREATE TABLE `t_trade_order_contract` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单ID，对应t_trade_order.id',
  `margin_mode` TINYINT NOT NULL COMMENT '保证金模式：1全仓 2逐仓',
  `leverage` INT NOT NULL DEFAULT 1 COMMENT '下单时杠杆倍数',
  `margin_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '保证金币种',
  `margin_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '本次订单占用保证金',
  `close_position_type` TINYINT NOT NULL DEFAULT 0 COMMENT '平仓类型：0普通 1平多 2平空',
  `liquidation_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '下单时预估强平价格',
  `take_profit_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '止盈价格',
  `stop_loss_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '止损价格',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_id` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约订单明细表';

CREATE TABLE `t_trade_fill` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `fill_no` VARCHAR(64) NOT NULL COMMENT '成交号',
  `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '平台订单号',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL COMMENT '交易标的ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：1现货 2秒合约 3U本位 4币本位',
  `side` TINYINT NOT NULL COMMENT '买卖方向：1买 2卖',
  `position_side` TINYINT NOT NULL DEFAULT 0 COMMENT '持仓方向：0无 1多 2空',
  `price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '成交价格',
  `qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '成交数量',
  `amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '成交金额',
  `fee` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '手续费',
  `fee_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手续费币种',
  `liquidity_type` TINYINT NOT NULL DEFAULT 0 COMMENT '流动性类型：1Maker 2Taker',
  `realized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '已实现盈亏，现货一般为0',
  `match_time` BIGINT NOT NULL DEFAULT 0 COMMENT '成交时间，毫秒时间戳',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_fill_no` (`tenant_id`, `fill_no`),
  KEY `idx_tenant_order_id` (`tenant_id`, `order_id`),
  KEY `idx_tenant_user_symbol_match_time` (`tenant_id`, `user_id`, `symbol_id`, `match_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='成交明细表';

CREATE TABLE `t_trade_cancel_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '平台订单号',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `cancel_source` TINYINT NOT NULL COMMENT '撤单来源：1用户主动 2系统撤单 3风控撤单 4超时撤单',
  `cancel_reason` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '撤单原因',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_order_id` (`tenant_id`, `order_id`),
  KEY `idx_tenant_user_created` (`tenant_id`, `user_id`, `create_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='撤单日志表';

CREATE TABLE `t_contract_position` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL COMMENT '交易标的ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：2秒合约 3U本位 4币本位',
  `position_side` TINYINT NOT NULL COMMENT '持仓方向：1多 2空',
  `margin_mode` TINYINT NOT NULL COMMENT '保证金模式：1全仓 2逐仓',
  `leverage` INT NOT NULL DEFAULT 1 COMMENT '当前杠杆倍数',
  `qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '当前持仓数量',
  `avail_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '可平仓数量',
  `frozen_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '挂单冻结数量',
  `open_avg_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '开仓均价',
  `mark_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '标记价格快照',
  `margin_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '保证金币种',
  `position_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '仓位保证金',
  `isolated_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '逐仓追加保证金',
  `unrealized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '未实现盈亏',
  `realized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '已实现盈亏',
  `liquidation_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '强平价格',
  `adl_rank` INT NOT NULL DEFAULT 0 COMMENT '自动减仓优先级',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_symbol_side_mode` (`tenant_id`, `user_id`, `symbol_id`, `position_side`, `margin_mode`),
  KEY `idx_tenant_symbol_market` (`tenant_id`, `symbol_id`, `market_type`),
  KEY `idx_tenant_user_market` (`tenant_id`, `user_id`, `market_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约当前持仓表';

CREATE TABLE `t_contract_margin_account` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：2秒合约 3U本位 4币本位',
  `margin_asset` VARCHAR(32) NOT NULL COMMENT '保证金币种',
  `balance` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '账户权益余额',
  `available_balance` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '可用余额',
  `frozen_balance` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '冻结余额',
  `position_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '仓位占用保证金',
  `order_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '挂单占用保证金',
  `unrealized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '未实现盈亏',
  `realized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '已实现盈亏',
  `version` BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_market_asset` (`tenant_id`, `user_id`, `market_type`, `margin_asset`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约保证金账户表';

CREATE TABLE `t_contract_position_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `position_id` BIGINT UNSIGNED NOT NULL COMMENT '持仓ID，对应t_contract_position.id',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL COMMENT '交易标的ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：2秒合约 3U本位 4币本位',
  `position_side` TINYINT NOT NULL COMMENT '持仓方向：1多 2空',
  `action_type` TINYINT NOT NULL COMMENT '变更动作类型：1开仓 2加仓 3减仓 4平仓 5强平 6结算 7资金费结转 8手动调整',
  `before_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前持仓数量',
  `after_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后持仓数量',
  `before_avail_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前可平数量',
  `after_avail_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后可平数量',
  `before_frozen_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前冻结数量',
  `after_frozen_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后冻结数量',
  `before_open_avg_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前开仓均价',
  `after_open_avg_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后开仓均价',
  `before_position_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前仓位保证金',
  `after_position_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后仓位保证金',
  `before_isolated_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前逐仓附加保证金',
  `after_isolated_margin` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后逐仓附加保证金',
  `before_unrealized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更前未实现盈亏',
  `after_unrealized_pnl` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '变更后未实现盈亏',
  `realized_pnl_delta` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '本次变更产生的已实现盈亏增量',
  `fee_delta` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '本次变更产生的手续费增量',
  `fee_asset` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手续费币种',
  `mark_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '本次记录时的标记价格',
  `ref_order_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联订单ID，没有则为0',
  `ref_fill_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联成交ID，没有则为0',
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_position_id_created` (`tenant_id`, `position_id`, `create_times`),
  KEY `idx_tenant_user_symbol_created` (`tenant_id`, `user_id`, `symbol_id`, `create_times`),
  KEY `idx_tenant_ref_order_id` (`tenant_id`, `ref_order_id`),
  KEY `idx_tenant_ref_fill_id` (`tenant_id`, `ref_fill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合约持仓历史表';

CREATE TABLE `t_contract_leverage_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL COMMENT '交易标的ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：2秒合约 3U本位 4币本位',
  `margin_mode` TINYINT NOT NULL COMMENT '保证金模式：1全仓 2逐仓',
  `position_mode` TINYINT NOT NULL DEFAULT 1 COMMENT '持仓模式：1单向持仓 2双向持仓',
  `long_leverage` INT NOT NULL DEFAULT 1 COMMENT '做多杠杆倍数',
  `short_leverage` INT NOT NULL DEFAULT 1 COMMENT '做空杠杆倍数',
  `max_leverage` INT NOT NULL DEFAULT 1 COMMENT '当前允许的最大杠杆倍数',
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_symbol_market_margin_mode` (`tenant_id`, `user_id`, `symbol_id`, `market_type`, `margin_mode`),
  KEY `idx_tenant_user_market` (`tenant_id`, `user_id`, `market_type`),
  KEY `idx_tenant_symbol_market` (`tenant_id`, `symbol_id`, `market_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户合约杠杆配置表';

CREATE TABLE `t_risk_user_trade_limit` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：1现货 2秒合约 3U本位 4币本位',
  `can_open` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许开仓/开单：1允许 0禁止',
  `can_close` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许平仓/卖出：1允许 0禁止',
  `can_cancel` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许撤单：1允许 0禁止',
  `can_trigger_order` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许条件单：1允许 0禁止',
  `can_api_trade` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许API交易：1允许 0禁止',
  `trade_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许交易：1允许 0禁止',
  `only_reduce_only` TINYINT NOT NULL DEFAULT 0 COMMENT '是否仅允许减仓：1是 0否',
  `max_open_order_count` INT NOT NULL DEFAULT 0 COMMENT '最大挂单数，0表示不限',
  `max_order_count_per_day` INT NOT NULL DEFAULT 0 COMMENT '单日最大下单次数，0表示不限',
  `max_cancel_count_per_day` INT NOT NULL DEFAULT 0 COMMENT '单日最大撤单次数，0表示不限',
  `max_open_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大可开仓名义价值，0表示不限',
  `max_position_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大持仓名义价值，0表示不限',
  `risk_level` TINYINT NOT NULL DEFAULT 0 COMMENT '风险等级：0默认 1低风险限制 2中风险限制 3高风险限制',
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `effective_start_time` BIGINT NOT NULL DEFAULT 0 COMMENT '限制生效开始时间，毫秒时间戳，0表示立即生效',
  `effective_end_time` BIGINT NOT NULL DEFAULT 0 COMMENT '限制生效结束时间，毫秒时间戳，0表示长期有效',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_market_type` (`tenant_id`, `user_id`, `market_type`),
  KEY `idx_tenant_trade_enabled` (`tenant_id`, `trade_enabled`),
  KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户交易限制表';

CREATE TABLE `t_risk_user_symbol_limit` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL COMMENT '交易标的ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：1现货 2秒合约 3U本位 4币本位',
  `max_position_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大持仓数量，0表示不限',
  `max_position_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大持仓名义价值，0表示不限',
  `max_open_orders` INT NOT NULL DEFAULT 0 COMMENT '最大挂单数，0表示不限',
  `max_order_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '单笔最大下单数量，0表示不限',
  `max_order_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '单笔最大下单名义价值，0表示不限',
  `min_order_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '单笔最小下单数量，0表示不限制',
  `min_order_notional` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '单笔最小下单名义价值，0表示不限制',
  `max_long_position_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大多头持仓数量，0表示不限',
  `max_short_position_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '最大空头持仓数量，0表示不限',
  `price_deviation_rate` DECIMAL(20,10) NOT NULL DEFAULT 0 COMMENT '允许价格偏离率，0表示不限制',
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `effective_start_time` BIGINT NOT NULL DEFAULT 0 COMMENT '限制生效开始时间，毫秒时间戳',
  `effective_end_time` BIGINT NOT NULL DEFAULT 0 COMMENT '限制生效结束时间，毫秒时间戳',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_symbol_market` (`tenant_id`, `user_id`, `symbol_id`, `market_type`),
  KEY `idx_tenant_user_market` (`tenant_id`, `user_id`, `market_type`),
  KEY `idx_tenant_symbol_market` (`tenant_id`, `symbol_id`, `market_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户单标的限制表';

CREATE TABLE `t_risk_order_check_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '平台订单号',
  `client_order_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户端订单号',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL COMMENT '交易标的ID',
  `market_type` TINYINT NOT NULL COMMENT '市场类型：1现货 2秒合约 3U本位 4币本位',
  `check_type` TINYINT NOT NULL COMMENT '检查类型：1余额检查 2保证金检查 3仓位检查 4交易权限检查 5价格保护检查 6数量限制检查 7名义价值限制检查 8频率限制检查',
  `check_result` TINYINT NOT NULL COMMENT '检查结果：1通过 2拒绝 3告警放行',
  `reject_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '拒绝码',
  `reject_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '拒绝原因描述',
  `request_price` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '请求价格',
  `request_qty` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '请求数量',
  `request_amount` DECIMAL(36,18) NOT NULL DEFAULT 0 COMMENT '请求名义价值或金额',
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `check_snapshot` JSON DEFAULT NULL COMMENT '检查时的上下文快照，JSON格式',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_order_no` (`tenant_id`, `order_no`),
  KEY `idx_tenant_user_symbol_created` (`tenant_id`, `user_id`, `symbol_id`, `create_times`),
  KEY `idx_tenant_market_check_type_created` (`tenant_id`, `market_type`, `check_type`, `create_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单风控检查日志表';

CREATE TABLE `t_biz_trade_event` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `event_no` VARCHAR(64) NOT NULL COMMENT '事件号',
  `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型，如ORDER_CREATED、ORDER_FILLED、ORDER_CANCELED、POSITION_CHANGED、MARGIN_CHANGED',
  `biz_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务主键，如订单号、成交号、持仓ID等',
  `biz_type` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务类型，如order、fill、position、margin',
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  `symbol_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '交易标的ID，没有则为0',
  `market_type` TINYINT NOT NULL DEFAULT 0 COMMENT '市场类型：0无 1现货 2秒合约 3U本位 4币本位',
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '操作人ID，系统操作时可为0',
  `source` TINYINT NOT NULL DEFAULT 1 COMMENT '来源：1系统 2用户 3后台管理 4任务',
  `event_status` TINYINT NOT NULL DEFAULT 1 COMMENT '事件状态：1待投递 2投递成功 3投递失败 4已取消',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `max_retry_count` INT NOT NULL DEFAULT 20 COMMENT '最大重试次数',
  `next_retry_at` BIGINT NOT NULL DEFAULT 0 COMMENT '下次重试时间，毫秒时间戳',
  `last_error_msg` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '最后一次投递错误信息',
  `payload` JSON NOT NULL COMMENT '事件内容，JSON格式',
  `ext_data` JSON DEFAULT NULL COMMENT '扩展字段，JSON格式',
  `create_times` BIGINT NOT NULL DEFAULT 0 COMMENT '创建时间，毫秒时间戳',
  `update_times` BIGINT NOT NULL DEFAULT 0 COMMENT '更新时间，毫秒时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_event_no` (`tenant_id`, `event_no`),
  KEY `idx_tenant_event_status_next_retry_at` (`tenant_id`, `event_status`, `next_retry_at`),
  KEY `idx_tenant_event_type_created` (`tenant_id`, `event_type`, `create_times`),
  KEY `idx_tenant_biz_type_biz_id` (`tenant_id`, `biz_type`, `biz_id`),
  KEY `idx_tenant_user_created` (`tenant_id`, `user_id`, `create_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易业务事件表';