// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tMarketMarketSessionFieldNames          = builder.RawFieldNames(&TMarketMarketSession{})
	tMarketMarketSessionRows                = strings.Join(tMarketMarketSessionFieldNames, ",")
	tMarketMarketSessionRowsExpectAutoSet   = strings.Join(stringx.Remove(tMarketMarketSessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tMarketMarketSessionRowsWithPlaceHolder = strings.Join(stringx.Remove(tMarketMarketSessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTMarketMarketSessionIdPrefix = "cache:tMarketMarketSession:id:"
)

type (
	tMarketMarketSessionModel interface {
		Insert(ctx context.Context, data *TMarketMarketSession) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TMarketMarketSession, error)
		Update(ctx context.Context, data *TMarketMarketSession) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTMarketMarketSessionModel struct {
		sqlc.CachedConn
		table string
	}

	TMarketMarketSession struct {
		Id          int64  `db:"id"`
		CalendarId  int64  `db:"calendar_id"`
		SessionType string `db:"session_type"`
		StartTime   string `db:"start_time"`
		EndTime     string `db:"end_time"`
		CrossDay    int64  `db:"cross_day"`
		Sort        int64  `db:"sort"`
	}
)

func newTMarketMarketSessionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTMarketMarketSessionModel {
	return &defaultTMarketMarketSessionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_itick_market_session`",
	}
}

func (m *defaultTMarketMarketSessionModel) Delete(ctx context.Context, id int64) error {
	tMarketMarketSessionIdKey := fmt.Sprintf("%s%v", cacheTMarketMarketSessionIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tMarketMarketSessionIdKey)
	return err
}

func (m *defaultTMarketMarketSessionModel) FindOne(ctx context.Context, id int64) (*TMarketMarketSession, error) {
	tMarketMarketSessionIdKey := fmt.Sprintf("%s%v", cacheTMarketMarketSessionIdPrefix, id)
	var resp TMarketMarketSession
	err := m.QueryRowCtx(ctx, &resp, tMarketMarketSessionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tMarketMarketSessionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTMarketMarketSessionModel) Insert(ctx context.Context, data *TMarketMarketSession) (sql.Result, error) {
	tMarketMarketSessionIdKey := fmt.Sprintf("%s%v", cacheTMarketMarketSessionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, tMarketMarketSessionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CalendarId, data.SessionType, data.StartTime, data.EndTime, data.CrossDay, data.Sort)
	}, tMarketMarketSessionIdKey)
	return ret, err
}

func (m *defaultTMarketMarketSessionModel) Update(ctx context.Context, data *TMarketMarketSession) error {
	tMarketMarketSessionIdKey := fmt.Sprintf("%s%v", cacheTMarketMarketSessionIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tMarketMarketSessionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CalendarId, data.SessionType, data.StartTime, data.EndTime, data.CrossDay, data.Sort, data.Id)
	}, tMarketMarketSessionIdKey)
	return err
}

func (m *defaultTMarketMarketSessionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTMarketMarketSessionIdPrefix, primary)
}

func (m *defaultTMarketMarketSessionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tMarketMarketSessionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTMarketMarketSessionModel) tableName() string {
	return m.table
}
