// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: payment.proto

package server

import (
	"context"

	"wklive/proto/payment"
	"wklive/services/payment/internal/logic/callback"
	"wklive/services/payment/internal/svc"
)

type CallbackServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedCallbackServer
}

func NewCallbackServer(svcCtx *svc.ServiceContext) *CallbackServer {
	return &CallbackServer{
		svcCtx: svcCtx,
	}
}

func (s *CallbackServer) PaymentNotify(ctx context.Context, in *payment.ThirdPartyNotifyReq) (*payment.ThirdPartyNotifyResp, error) {
	l := callbacklogic.NewPaymentNotifyLogic(ctx, s.svcCtx)
	return l.PaymentNotify(in)
}

func (s *CallbackServer) PayoutNotify(ctx context.Context, in *payment.ThirdPartyNotifyReq) (*payment.ThirdPartyNotifyResp, error) {
	l := callbacklogic.NewPayoutNotifyLogic(ctx, s.svcCtx)
	return l.PayoutNotify(in)
}
