// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package system

import (
	"context"

	"wklive/rpc/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminLoginReq          = system.AdminLoginReq
	AdminLoginResp         = system.AdminLoginResp
	AssignUserRolesReq     = system.AssignUserRolesReq
	ChangeUserStatusReq    = system.ChangeUserStatusReq
	Empty                  = system.Empty
	Google2FADisableReq    = system.Google2FADisableReq
	Google2FAEnableReq     = system.Google2FAEnableReq
	Google2FAInitReq       = system.Google2FAInitReq
	Google2FAInitResp      = system.Google2FAInitResp
	Google2FAResetReq      = system.Google2FAResetReq
	LoginLogItem           = system.LoginLogItem
	LoginLogListReq        = system.LoginLogListReq
	LoginLogListResp       = system.LoginLogListResp
	OpLogItem              = system.OpLogItem
	OpLogListReq           = system.OpLogListReq
	OpLogListResp          = system.OpLogListResp
	PageReq                = system.PageReq
	ProfileReq             = system.ProfileReq
	ProfileResp            = system.ProfileResp
	ProfileUser            = system.ProfileUser
	ResetUserPwdReq        = system.ResetUserPwdReq
	RespBase             = system.RespBase
	SysMenuCreateReq       = system.SysMenuCreateReq
	SysMenuDeleteReq       = system.SysMenuDeleteReq
	SysMenuItem            = system.SysMenuItem
	SysMenuNode            = system.SysMenuNode
	SysMenuTreeResp        = system.SysMenuTreeResp
	SysMenuUpdateReq       = system.SysMenuUpdateReq
	SysPermItem            = system.SysPermItem
	SysPermListResp        = system.SysPermListResp
	SysRoleCreateReq       = system.SysRoleCreateReq
	SysRoleDeleteReq       = system.SysRoleDeleteReq
	SysRoleGrantDetailReq  = system.SysRoleGrantDetailReq
	SysRoleGrantDetailResp = system.SysRoleGrantDetailResp
	SysRoleGrantReq        = system.SysRoleGrantReq
	SysRoleItem            = system.SysRoleItem
	SysRoleListReq         = system.SysRoleListReq
	SysRoleListResp        = system.SysRoleListResp
	SysRoleUpdateReq       = system.SysRoleUpdateReq
	SysUserCreateReq       = system.SysUserCreateReq
	SysUserDeleteReq       = system.SysUserDeleteReq
	SysUserDetailReq       = system.SysUserDetailReq
	SysUserDetailResp      = system.SysUserDetailResp
	SysUserItem            = system.SysUserItem
	SysUserListReq         = system.SysUserListReq
	SysUserListResp        = system.SysUserListResp
	SysUserUpdateReq       = system.SysUserUpdateReq

	System interface {
		// P0
		AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error)
		// 获取当前用户信息
		GetProfile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error)
		// 2FA
		Google2FAInit(ctx context.Context, in *Google2FAInitReq, opts ...grpc.CallOption) (*Google2FAInitResp, error)
		// 启用Google 2FA
		Google2FAEnable(ctx context.Context, in *Google2FAEnableReq, opts ...grpc.CallOption) (*RespBase, error)
		// 禁用Google 2FA
		Google2FADisable(ctx context.Context, in *Google2FADisableReq, opts ...grpc.CallOption) (*RespBase, error)
		// 重置Google 2FA
		Google2FAReset(ctx context.Context, in *Google2FAResetReq, opts ...grpc.CallOption) (*RespBase, error)
		// 用户
		SysUserList(ctx context.Context, in *SysUserListReq, opts ...grpc.CallOption) (*SysUserListResp, error)
		// 获取用户详情
		SysUserDetail(ctx context.Context, in *SysUserDetailReq, opts ...grpc.CallOption) (*SysUserDetailResp, error)
		// 创建系统用户
		SysUserCreate(ctx context.Context, in *SysUserCreateReq, opts ...grpc.CallOption) (*RespBase, error)
		// 更新系统用户
		SysUserUpdate(ctx context.Context, in *SysUserUpdateReq, opts ...grpc.CallOption) (*RespBase, error)
		// 删除系统用户
		SysUserDelete(ctx context.Context, in *SysUserDeleteReq, opts ...grpc.CallOption) (*RespBase, error)
		// 修改用户状态
		ChangeUserStatus(ctx context.Context, in *ChangeUserStatusReq, opts ...grpc.CallOption) (*RespBase, error)
		// 重置用户密码
		ResetUserPwd(ctx context.Context, in *ResetUserPwdReq, opts ...grpc.CallOption) (*RespBase, error)
		// 分配用户角色
		AssignUserRoles(ctx context.Context, in *AssignUserRolesReq, opts ...grpc.CallOption) (*RespBase, error)
		// 角色
		SysRoleList(ctx context.Context, in *SysRoleListReq, opts ...grpc.CallOption) (*SysRoleListResp, error)
		// 创建角色
		SysRoleCreate(ctx context.Context, in *SysRoleCreateReq, opts ...grpc.CallOption) (*RespBase, error)
		// 更新角色
		SysRoleUpdate(ctx context.Context, in *SysRoleUpdateReq, opts ...grpc.CallOption) (*RespBase, error)
		// 删除角色
		SysRoleDelete(ctx context.Context, in *SysRoleDeleteReq, opts ...grpc.CallOption) (*RespBase, error)
		// 角色授权
		SysRoleGrant(ctx context.Context, in *SysRoleGrantReq, opts ...grpc.CallOption) (*RespBase, error)
		// 获取角色授权详情
		SysRoleGrantDetail(ctx context.Context, in *SysRoleGrantDetailReq, opts ...grpc.CallOption) (*SysRoleGrantDetailResp, error)
		// 获取权限列表
		SysPermList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SysPermListResp, error)
		// 获取菜单树
		GetMenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SysMenuTreeResp, error)
		// 菜单
		SysMenuCreate(ctx context.Context, in *SysMenuCreateReq, opts ...grpc.CallOption) (*RespBase, error)
		// 更新菜单
		SysMenuUpdate(ctx context.Context, in *SysMenuUpdateReq, opts ...grpc.CallOption) (*RespBase, error)
		// 删除菜单
		SysMenuDelete(ctx context.Context, in *SysMenuDeleteReq, opts ...grpc.CallOption) (*RespBase, error)
		// 日志
		LoginLogList(ctx context.Context, in *LoginLogListReq, opts ...grpc.CallOption) (*LoginLogListResp, error)
		// 操作日志
		OpLogList(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error)
	}

	defaultSystem struct {
		cli zrpc.Client
	}
)

func NewSystem(cli zrpc.Client) System {
	return &defaultSystem{
		cli: cli,
	}
}

// P0
func (m *defaultSystem) AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.AdminLogin(ctx, in, opts...)
}

// 获取当前用户信息
func (m *defaultSystem) GetProfile(ctx context.Context, in *ProfileReq, opts ...grpc.CallOption) (*ProfileResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetProfile(ctx, in, opts...)
}

// 2FA
func (m *defaultSystem) Google2FAInit(ctx context.Context, in *Google2FAInitReq, opts ...grpc.CallOption) (*Google2FAInitResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.Google2FAInit(ctx, in, opts...)
}

// 启用Google 2FA
func (m *defaultSystem) Google2FAEnable(ctx context.Context, in *Google2FAEnableReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.Google2FAEnable(ctx, in, opts...)
}

// 禁用Google 2FA
func (m *defaultSystem) Google2FADisable(ctx context.Context, in *Google2FADisableReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.Google2FADisable(ctx, in, opts...)
}

// 重置Google 2FA
func (m *defaultSystem) Google2FAReset(ctx context.Context, in *Google2FAResetReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.Google2FAReset(ctx, in, opts...)
}

// 用户
func (m *defaultSystem) SysUserList(ctx context.Context, in *SysUserListReq, opts ...grpc.CallOption) (*SysUserListResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysUserList(ctx, in, opts...)
}

// 获取用户详情
func (m *defaultSystem) SysUserDetail(ctx context.Context, in *SysUserDetailReq, opts ...grpc.CallOption) (*SysUserDetailResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysUserDetail(ctx, in, opts...)
}

// 创建系统用户
func (m *defaultSystem) SysUserCreate(ctx context.Context, in *SysUserCreateReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysUserCreate(ctx, in, opts...)
}

// 更新系统用户
func (m *defaultSystem) SysUserUpdate(ctx context.Context, in *SysUserUpdateReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysUserUpdate(ctx, in, opts...)
}

// 删除系统用户
func (m *defaultSystem) SysUserDelete(ctx context.Context, in *SysUserDeleteReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysUserDelete(ctx, in, opts...)
}

// 修改用户状态
func (m *defaultSystem) ChangeUserStatus(ctx context.Context, in *ChangeUserStatusReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ChangeUserStatus(ctx, in, opts...)
}

// 重置用户密码
func (m *defaultSystem) ResetUserPwd(ctx context.Context, in *ResetUserPwdReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.ResetUserPwd(ctx, in, opts...)
}

// 分配用户角色
func (m *defaultSystem) AssignUserRoles(ctx context.Context, in *AssignUserRolesReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.AssignUserRoles(ctx, in, opts...)
}

// 角色
func (m *defaultSystem) SysRoleList(ctx context.Context, in *SysRoleListReq, opts ...grpc.CallOption) (*SysRoleListResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysRoleList(ctx, in, opts...)
}

// 创建角色
func (m *defaultSystem) SysRoleCreate(ctx context.Context, in *SysRoleCreateReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysRoleCreate(ctx, in, opts...)
}

// 更新角色
func (m *defaultSystem) SysRoleUpdate(ctx context.Context, in *SysRoleUpdateReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysRoleUpdate(ctx, in, opts...)
}

// 删除角色
func (m *defaultSystem) SysRoleDelete(ctx context.Context, in *SysRoleDeleteReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysRoleDelete(ctx, in, opts...)
}

// 角色授权
func (m *defaultSystem) SysRoleGrant(ctx context.Context, in *SysRoleGrantReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysRoleGrant(ctx, in, opts...)
}

// 获取角色授权详情
func (m *defaultSystem) SysRoleGrantDetail(ctx context.Context, in *SysRoleGrantDetailReq, opts ...grpc.CallOption) (*SysRoleGrantDetailResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysRoleGrantDetail(ctx, in, opts...)
}

// 获取权限列表
func (m *defaultSystem) SysPermList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SysPermListResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysPermList(ctx, in, opts...)
}

// 获取菜单树
func (m *defaultSystem) GetMenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SysMenuTreeResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetMenuTree(ctx, in, opts...)
}

// 菜单
func (m *defaultSystem) SysMenuCreate(ctx context.Context, in *SysMenuCreateReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysMenuCreate(ctx, in, opts...)
}

// 更新菜单
func (m *defaultSystem) SysMenuUpdate(ctx context.Context, in *SysMenuUpdateReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysMenuUpdate(ctx, in, opts...)
}

// 删除菜单
func (m *defaultSystem) SysMenuDelete(ctx context.Context, in *SysMenuDeleteReq, opts ...grpc.CallOption) (*RespBase, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.SysMenuDelete(ctx, in, opts...)
}

// 日志
func (m *defaultSystem) LoginLogList(ctx context.Context, in *LoginLogListReq, opts ...grpc.CallOption) (*LoginLogListResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.LoginLogList(ctx, in, opts...)
}

// 操作日志
func (m *defaultSystem) OpLogList(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.OpLogList(ctx, in, opts...)
}
