// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/itick/itick_app.proto

package itick

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItickApp_ListVisibleProductCategories_FullMethodName = "/itick.ItickApp/ListVisibleProductCategories"
	ItickApp_ListVisibleProducts_FullMethodName          = "/itick.ItickApp/ListVisibleProducts"
	ItickApp_GetKline_FullMethodName                     = "/itick.ItickApp/GetKline"
	ItickApp_GetQuote_FullMethodName                     = "/itick.ItickApp/GetQuote"
	ItickApp_BatchGetQuote_FullMethodName                = "/itick.ItickApp/BatchGetQuote"
	ItickApp_GetDepth_FullMethodName                     = "/itick.ItickApp/GetDepth"
	ItickApp_SubscribeQuote_FullMethodName               = "/itick.ItickApp/SubscribeQuote"
	ItickApp_SubscribeDepth_FullMethodName               = "/itick.ItickApp/SubscribeDepth"
)

// ItickAppClient is the client API for ItickApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ====================
// app service
// ====================
type ItickAppClient interface {
	// 获取允许显示的产品类型
	ListVisibleProductCategories(ctx context.Context, in *ListVisibleProductCategoriesReq, opts ...grpc.CallOption) (*ListVisibleProductCategoriesResp, error)
	// 获取允许显示的产品
	ListVisibleProducts(ctx context.Context, in *ListVisibleProductsReq, opts ...grpc.CallOption) (*ListVisibleProductsResp, error)
	// 获取K线
	GetKline(ctx context.Context, in *GetKlineReq, opts ...grpc.CallOption) (*GetKlineResp, error)
	// 获取最新报价
	GetQuote(ctx context.Context, in *GetQuoteReq, opts ...grpc.CallOption) (*GetQuoteResp, error)
	// 批量获取最新报价
	BatchGetQuote(ctx context.Context, in *BatchGetQuoteReq, opts ...grpc.CallOption) (*BatchGetQuoteResp, error)
	// 获取深度
	GetDepth(ctx context.Context, in *GetDepthReq, opts ...grpc.CallOption) (*GetDepthResp, error)
	// 订阅报价
	SubscribeQuote(ctx context.Context, in *SubscribeQuoteReq, opts ...grpc.CallOption) (*SubscribeQuoteResp, error)
	// 订阅深度
	SubscribeDepth(ctx context.Context, in *SubscribeDepthReq, opts ...grpc.CallOption) (*SubscribeDepthResp, error)
}

type itickAppClient struct {
	cc grpc.ClientConnInterface
}

func NewItickAppClient(cc grpc.ClientConnInterface) ItickAppClient {
	return &itickAppClient{cc}
}

func (c *itickAppClient) ListVisibleProductCategories(ctx context.Context, in *ListVisibleProductCategoriesReq, opts ...grpc.CallOption) (*ListVisibleProductCategoriesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVisibleProductCategoriesResp)
	err := c.cc.Invoke(ctx, ItickApp_ListVisibleProductCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itickAppClient) ListVisibleProducts(ctx context.Context, in *ListVisibleProductsReq, opts ...grpc.CallOption) (*ListVisibleProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVisibleProductsResp)
	err := c.cc.Invoke(ctx, ItickApp_ListVisibleProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itickAppClient) GetKline(ctx context.Context, in *GetKlineReq, opts ...grpc.CallOption) (*GetKlineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKlineResp)
	err := c.cc.Invoke(ctx, ItickApp_GetKline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itickAppClient) GetQuote(ctx context.Context, in *GetQuoteReq, opts ...grpc.CallOption) (*GetQuoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuoteResp)
	err := c.cc.Invoke(ctx, ItickApp_GetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itickAppClient) BatchGetQuote(ctx context.Context, in *BatchGetQuoteReq, opts ...grpc.CallOption) (*BatchGetQuoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetQuoteResp)
	err := c.cc.Invoke(ctx, ItickApp_BatchGetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itickAppClient) GetDepth(ctx context.Context, in *GetDepthReq, opts ...grpc.CallOption) (*GetDepthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepthResp)
	err := c.cc.Invoke(ctx, ItickApp_GetDepth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itickAppClient) SubscribeQuote(ctx context.Context, in *SubscribeQuoteReq, opts ...grpc.CallOption) (*SubscribeQuoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeQuoteResp)
	err := c.cc.Invoke(ctx, ItickApp_SubscribeQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itickAppClient) SubscribeDepth(ctx context.Context, in *SubscribeDepthReq, opts ...grpc.CallOption) (*SubscribeDepthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeDepthResp)
	err := c.cc.Invoke(ctx, ItickApp_SubscribeDepth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItickAppServer is the server API for ItickApp service.
// All implementations must embed UnimplementedItickAppServer
// for forward compatibility.
//
// ====================
// app service
// ====================
type ItickAppServer interface {
	// 获取允许显示的产品类型
	ListVisibleProductCategories(context.Context, *ListVisibleProductCategoriesReq) (*ListVisibleProductCategoriesResp, error)
	// 获取允许显示的产品
	ListVisibleProducts(context.Context, *ListVisibleProductsReq) (*ListVisibleProductsResp, error)
	// 获取K线
	GetKline(context.Context, *GetKlineReq) (*GetKlineResp, error)
	// 获取最新报价
	GetQuote(context.Context, *GetQuoteReq) (*GetQuoteResp, error)
	// 批量获取最新报价
	BatchGetQuote(context.Context, *BatchGetQuoteReq) (*BatchGetQuoteResp, error)
	// 获取深度
	GetDepth(context.Context, *GetDepthReq) (*GetDepthResp, error)
	// 订阅报价
	SubscribeQuote(context.Context, *SubscribeQuoteReq) (*SubscribeQuoteResp, error)
	// 订阅深度
	SubscribeDepth(context.Context, *SubscribeDepthReq) (*SubscribeDepthResp, error)
	mustEmbedUnimplementedItickAppServer()
}

// UnimplementedItickAppServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItickAppServer struct{}

func (UnimplementedItickAppServer) ListVisibleProductCategories(context.Context, *ListVisibleProductCategoriesReq) (*ListVisibleProductCategoriesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVisibleProductCategories not implemented")
}
func (UnimplementedItickAppServer) ListVisibleProducts(context.Context, *ListVisibleProductsReq) (*ListVisibleProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVisibleProducts not implemented")
}
func (UnimplementedItickAppServer) GetKline(context.Context, *GetKlineReq) (*GetKlineResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKline not implemented")
}
func (UnimplementedItickAppServer) GetQuote(context.Context, *GetQuoteReq) (*GetQuoteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedItickAppServer) BatchGetQuote(context.Context, *BatchGetQuoteReq) (*BatchGetQuoteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetQuote not implemented")
}
func (UnimplementedItickAppServer) GetDepth(context.Context, *GetDepthReq) (*GetDepthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepth not implemented")
}
func (UnimplementedItickAppServer) SubscribeQuote(context.Context, *SubscribeQuoteReq) (*SubscribeQuoteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeQuote not implemented")
}
func (UnimplementedItickAppServer) SubscribeDepth(context.Context, *SubscribeDepthReq) (*SubscribeDepthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeDepth not implemented")
}
func (UnimplementedItickAppServer) mustEmbedUnimplementedItickAppServer() {}
func (UnimplementedItickAppServer) testEmbeddedByValue()                  {}

// UnsafeItickAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItickAppServer will
// result in compilation errors.
type UnsafeItickAppServer interface {
	mustEmbedUnimplementedItickAppServer()
}

func RegisterItickAppServer(s grpc.ServiceRegistrar, srv ItickAppServer) {
	// If the following call pancis, it indicates UnimplementedItickAppServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItickApp_ServiceDesc, srv)
}

func _ItickApp_ListVisibleProductCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVisibleProductCategoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItickAppServer).ListVisibleProductCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItickApp_ListVisibleProductCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItickAppServer).ListVisibleProductCategories(ctx, req.(*ListVisibleProductCategoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItickApp_ListVisibleProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVisibleProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItickAppServer).ListVisibleProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItickApp_ListVisibleProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItickAppServer).ListVisibleProducts(ctx, req.(*ListVisibleProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItickApp_GetKline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItickAppServer).GetKline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItickApp_GetKline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItickAppServer).GetKline(ctx, req.(*GetKlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItickApp_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItickAppServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItickApp_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItickAppServer).GetQuote(ctx, req.(*GetQuoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItickApp_BatchGetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetQuoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItickAppServer).BatchGetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItickApp_BatchGetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItickAppServer).BatchGetQuote(ctx, req.(*BatchGetQuoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItickApp_GetDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItickAppServer).GetDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItickApp_GetDepth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItickAppServer).GetDepth(ctx, req.(*GetDepthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItickApp_SubscribeQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeQuoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItickAppServer).SubscribeQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItickApp_SubscribeQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItickAppServer).SubscribeQuote(ctx, req.(*SubscribeQuoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItickApp_SubscribeDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeDepthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItickAppServer).SubscribeDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItickApp_SubscribeDepth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItickAppServer).SubscribeDepth(ctx, req.(*SubscribeDepthReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ItickApp_ServiceDesc is the grpc.ServiceDesc for ItickApp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItickApp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "itick.ItickApp",
	HandlerType: (*ItickAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVisibleProductCategories",
			Handler:    _ItickApp_ListVisibleProductCategories_Handler,
		},
		{
			MethodName: "ListVisibleProducts",
			Handler:    _ItickApp_ListVisibleProducts_Handler,
		},
		{
			MethodName: "GetKline",
			Handler:    _ItickApp_GetKline_Handler,
		},
		{
			MethodName: "GetQuote",
			Handler:    _ItickApp_GetQuote_Handler,
		},
		{
			MethodName: "BatchGetQuote",
			Handler:    _ItickApp_BatchGetQuote_Handler,
		},
		{
			MethodName: "GetDepth",
			Handler:    _ItickApp_GetDepth_Handler,
		},
		{
			MethodName: "SubscribeQuote",
			Handler:    _ItickApp_SubscribeQuote_Handler,
		},
		{
			MethodName: "SubscribeDepth",
			Handler:    _ItickApp_SubscribeDepth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/itick/itick_app.proto",
}
