// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/itick/itick_internal.proto

package itick

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItickInternal_GetAuthoritativeSnapshot_FullMethodName = "/itick.ItickInternal/GetAuthoritativeSnapshot"
)

// ItickInternalClient is the client API for ItickInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItickInternal exposes service-to-service market-data capabilities. Public
// API gateways should continue to use ItickApp.
type ItickInternalClient interface {
	// Reads an authoritative snapshot from the permanent archive at or before
	// the requested business timestamp.
	GetAuthoritativeSnapshot(ctx context.Context, in *GetAuthoritativeSnapshotReq, opts ...grpc.CallOption) (*GetAuthoritativeSnapshotResp, error)
}

type itickInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewItickInternalClient(cc grpc.ClientConnInterface) ItickInternalClient {
	return &itickInternalClient{cc}
}

func (c *itickInternalClient) GetAuthoritativeSnapshot(ctx context.Context, in *GetAuthoritativeSnapshotReq, opts ...grpc.CallOption) (*GetAuthoritativeSnapshotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthoritativeSnapshotResp)
	err := c.cc.Invoke(ctx, ItickInternal_GetAuthoritativeSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItickInternalServer is the server API for ItickInternal service.
// All implementations must embed UnimplementedItickInternalServer
// for forward compatibility.
//
// ItickInternal exposes service-to-service market-data capabilities. Public
// API gateways should continue to use ItickApp.
type ItickInternalServer interface {
	// Reads an authoritative snapshot from the permanent archive at or before
	// the requested business timestamp.
	GetAuthoritativeSnapshot(context.Context, *GetAuthoritativeSnapshotReq) (*GetAuthoritativeSnapshotResp, error)
	mustEmbedUnimplementedItickInternalServer()
}

// UnimplementedItickInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItickInternalServer struct{}

func (UnimplementedItickInternalServer) GetAuthoritativeSnapshot(context.Context, *GetAuthoritativeSnapshotReq) (*GetAuthoritativeSnapshotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthoritativeSnapshot not implemented")
}
func (UnimplementedItickInternalServer) mustEmbedUnimplementedItickInternalServer() {}
func (UnimplementedItickInternalServer) testEmbeddedByValue()                       {}

// UnsafeItickInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItickInternalServer will
// result in compilation errors.
type UnsafeItickInternalServer interface {
	mustEmbedUnimplementedItickInternalServer()
}

func RegisterItickInternalServer(s grpc.ServiceRegistrar, srv ItickInternalServer) {
	// If the following call panics, it indicates UnimplementedItickInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItickInternal_ServiceDesc, srv)
}

func _ItickInternal_GetAuthoritativeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthoritativeSnapshotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItickInternalServer).GetAuthoritativeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItickInternal_GetAuthoritativeSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItickInternalServer).GetAuthoritativeSnapshot(ctx, req.(*GetAuthoritativeSnapshotReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ItickInternal_ServiceDesc is the grpc.ServiceDesc for ItickInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItickInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "itick.ItickInternal",
	HandlerType: (*ItickInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthoritativeSnapshot",
			Handler:    _ItickInternal_GetAuthoritativeSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/itick/itick_internal.proto",
}
