// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package admin

import (
	"context"

	"wklive/proto/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddBankReq                    = user.AddBankReq
	AddBankResp                   = user.AddBankResp
	AddUserBankReq                = user.AddUserBankReq
	AddUserBankResp               = user.AddUserBankResp
	ChangeLoginPasswordReq        = user.ChangeLoginPasswordReq
	ChangePayPasswordReq          = user.ChangePayPasswordReq
	CommonResp                    = user.CommonResp
	CreateGuestTransferData       = user.CreateGuestTransferData
	CreateGuestTransferReq        = user.CreateGuestTransferReq
	CreateGuestTransferResp       = user.CreateGuestTransferResp
	CreateUserReq                 = user.CreateUserReq
	CreateUserResp                = user.CreateUserResp
	DeleteBankReq                 = user.DeleteBankReq
	DeleteUserBankReq             = user.DeleteUserBankReq
	DeleteUserReq                 = user.DeleteUserReq
	DisableGoogle2FAReq           = user.DisableGoogle2FAReq
	EnableGoogle2FAReq            = user.EnableGoogle2FAReq
	ExchangeGuestTransferData     = user.ExchangeGuestTransferData
	ExchangeGuestTransferReq      = user.ExchangeGuestTransferReq
	ExchangeGuestTransferResp     = user.ExchangeGuestTransferResp
	GetIdentityReq                = user.GetIdentityReq
	GetIdentityResp               = user.GetIdentityResp
	GetProfileReq                 = user.GetProfileReq
	GetProfileResp                = user.GetProfileResp
	GetSecurityReq                = user.GetSecurityReq
	GetSecurityResp               = user.GetSecurityResp
	GetUserBankReq                = user.GetUserBankReq
	GetUserBankResp               = user.GetUserBankResp
	GetUserDetailReq              = user.GetUserDetailReq
	GetUserDetailResp             = user.GetUserDetailResp
	GetUserSecurityReq            = user.GetUserSecurityReq
	GetUserSecurityResp           = user.GetUserSecurityResp
	GuestDomainMigrationStatsData = user.GuestDomainMigrationStatsData
	GuestDomainMigrationStatsReq  = user.GuestDomainMigrationStatsReq
	GuestDomainMigrationStatsResp = user.GuestDomainMigrationStatsResp
	GuestLogin                    = user.GuestLogin
	GuestLoginReq                 = user.GuestLoginReq
	GuestLoginResp                = user.GuestLoginResp
	InitGoogle2FAData             = user.InitGoogle2FAData
	InitGoogle2FAReq              = user.InitGoogle2FAReq
	InitGoogle2FAResp             = user.InitGoogle2FAResp
	ListBanksReq                  = user.ListBanksReq
	ListBanksResp                 = user.ListBanksResp
	ListUserBanksReq              = user.ListUserBanksReq
	ListUserBanksResp             = user.ListUserBanksResp
	ListUserIdentitiesReq         = user.ListUserIdentitiesReq
	ListUserIdentitiesResp        = user.ListUserIdentitiesResp
	ListUsersReq                  = user.ListUsersReq
	ListUsersResp                 = user.ListUsersResp
	LoginData                     = user.LoginData
	LoginReq                      = user.LoginReq
	LoginResp                     = user.LoginResp
	LogoutReq                     = user.LogoutReq
	RefreshTokenReq               = user.RefreshTokenReq
	RefreshTokenResp              = user.RefreshTokenResp
	RegisterData                  = user.RegisterData
	RegisterReq                   = user.RegisterReq
	RegisterResp                  = user.RegisterResp
	ResetLoginPasswordReq         = user.ResetLoginPasswordReq
	ResetPayPasswordReq           = user.ResetPayPasswordReq
	ResetUserGoogle2FAReq         = user.ResetUserGoogle2FAReq
	ReviewUserIdentityReq         = user.ReviewUserIdentityReq
	ReviewUserIdentityResp        = user.ReviewUserIdentityResp
	SetDefaultBankReq             = user.SetDefaultBankReq
	SetDefaultUserBankReq         = user.SetDefaultUserBankReq
	SetPayPasswordReq             = user.SetPayPasswordReq
	SubmitIdentityReq             = user.SubmitIdentityReq
	SubmitIdentityResp            = user.SubmitIdentityResp
	UnlockUserReq                 = user.UnlockUserReq
	UpdateBankReq                 = user.UpdateBankReq
	UpdateBankResp                = user.UpdateBankResp
	UpdateIdentityReq             = user.UpdateIdentityReq
	UpdateIdentityResp            = user.UpdateIdentityResp
	UpdateProfileReq              = user.UpdateProfileReq
	UpdateProfileResp             = user.UpdateProfileResp
	UpdateRiskLevelReq            = user.UpdateRiskLevelReq
	UpdateUserBankReq             = user.UpdateUserBankReq
	UpdateUserBankResp            = user.UpdateUserBankResp
	UpdateUserBankStatusReq       = user.UpdateUserBankStatusReq
	UpdateUserBaseReq             = user.UpdateUserBaseReq
	UpdateUserBaseResp            = user.UpdateUserBaseResp
	UpdateUserLevelReq            = user.UpdateUserLevelReq
	UpdateUserStatusReq           = user.UpdateUserStatusReq
	UserCommonResp                = user.UserCommonResp

	Admin interface {
		// 退役域名未迁移游客及活跃分布统计
		GuestDomainMigrationStats(ctx context.Context, in *GuestDomainMigrationStatsReq, opts ...grpc.CallOption) (*GuestDomainMigrationStatsResp, error)
		// 创建用户
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		// 获取用户详情
		GetUserDetail(ctx context.Context, in *GetUserDetailReq, opts ...grpc.CallOption) (*GetUserDetailResp, error)
		// 用户列表
		ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error)
		// 更新用户基本信息
		UpdateUserBase(ctx context.Context, in *UpdateUserBaseReq, opts ...grpc.CallOption) (*UpdateUserBaseResp, error)
		// 更新用户状态
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 更新用户会员等级
		UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 重置登录密码
		ResetLoginPassword(ctx context.Context, in *ResetLoginPasswordReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 重置支付密码
		ResetPayPassword(ctx context.Context, in *ResetPayPasswordReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 解锁用户（解除登录锁定）
		UnlockUser(ctx context.Context, in *UnlockUserReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 更新用户风险等级
		UpdateRiskLevel(ctx context.Context, in *UpdateRiskLevelReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 删除用户
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 获取用户安全设置
		GetUserSecurity(ctx context.Context, in *GetUserSecurityReq, opts ...grpc.CallOption) (*GetUserSecurityResp, error)
		// 重置用户谷歌2FA
		ResetUserGoogle2FA(ctx context.Context, in *ResetUserGoogle2FAReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 实名认证信息列表
		ListUserIdentities(ctx context.Context, in *ListUserIdentitiesReq, opts ...grpc.CallOption) (*ListUserIdentitiesResp, error)
		// 审核实名认证信息
		ReviewUserIdentity(ctx context.Context, in *ReviewUserIdentityReq, opts ...grpc.CallOption) (*ReviewUserIdentityResp, error)
		// 用户银行卡列表
		ListUserBanks(ctx context.Context, in *ListUserBanksReq, opts ...grpc.CallOption) (*ListUserBanksResp, error)
		// 获取用户银行卡详情
		GetUserBank(ctx context.Context, in *GetUserBankReq, opts ...grpc.CallOption) (*GetUserBankResp, error)
		// 添加用户银行卡
		AddUserBank(ctx context.Context, in *AddUserBankReq, opts ...grpc.CallOption) (*AddUserBankResp, error)
		// 更新用户银行卡
		UpdateUserBank(ctx context.Context, in *UpdateUserBankReq, opts ...grpc.CallOption) (*UpdateUserBankResp, error)
		// 删除用户银行卡
		DeleteUserBank(ctx context.Context, in *DeleteUserBankReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 更新用户银行卡状态
		UpdateUserBankStatus(ctx context.Context, in *UpdateUserBankStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 设置默认用户银行卡
		SetDefaultUserBank(ctx context.Context, in *SetDefaultUserBankReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

// 退役域名未迁移游客及活跃分布统计
func (m *defaultAdmin) GuestDomainMigrationStats(ctx context.Context, in *GuestDomainMigrationStatsReq, opts ...grpc.CallOption) (*GuestDomainMigrationStatsResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.GuestDomainMigrationStats(ctx, in, opts...)
}

// 创建用户
func (m *defaultAdmin) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

// 获取用户详情
func (m *defaultAdmin) GetUserDetail(ctx context.Context, in *GetUserDetailReq, opts ...grpc.CallOption) (*GetUserDetailResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.GetUserDetail(ctx, in, opts...)
}

// 用户列表
func (m *defaultAdmin) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.ListUsers(ctx, in, opts...)
}

// 更新用户基本信息
func (m *defaultAdmin) UpdateUserBase(ctx context.Context, in *UpdateUserBaseReq, opts ...grpc.CallOption) (*UpdateUserBaseResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.UpdateUserBase(ctx, in, opts...)
}

// 更新用户状态
func (m *defaultAdmin) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

// 更新用户会员等级
func (m *defaultAdmin) UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.UpdateUserLevel(ctx, in, opts...)
}

// 重置登录密码
func (m *defaultAdmin) ResetLoginPassword(ctx context.Context, in *ResetLoginPasswordReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.ResetLoginPassword(ctx, in, opts...)
}

// 重置支付密码
func (m *defaultAdmin) ResetPayPassword(ctx context.Context, in *ResetPayPasswordReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.ResetPayPassword(ctx, in, opts...)
}

// 解锁用户（解除登录锁定）
func (m *defaultAdmin) UnlockUser(ctx context.Context, in *UnlockUserReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.UnlockUser(ctx, in, opts...)
}

// 更新用户风险等级
func (m *defaultAdmin) UpdateRiskLevel(ctx context.Context, in *UpdateRiskLevelReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.UpdateRiskLevel(ctx, in, opts...)
}

// 删除用户
func (m *defaultAdmin) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

// 获取用户安全设置
func (m *defaultAdmin) GetUserSecurity(ctx context.Context, in *GetUserSecurityReq, opts ...grpc.CallOption) (*GetUserSecurityResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.GetUserSecurity(ctx, in, opts...)
}

// 重置用户谷歌2FA
func (m *defaultAdmin) ResetUserGoogle2FA(ctx context.Context, in *ResetUserGoogle2FAReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.ResetUserGoogle2FA(ctx, in, opts...)
}

// 实名认证信息列表
func (m *defaultAdmin) ListUserIdentities(ctx context.Context, in *ListUserIdentitiesReq, opts ...grpc.CallOption) (*ListUserIdentitiesResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.ListUserIdentities(ctx, in, opts...)
}

// 审核实名认证信息
func (m *defaultAdmin) ReviewUserIdentity(ctx context.Context, in *ReviewUserIdentityReq, opts ...grpc.CallOption) (*ReviewUserIdentityResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.ReviewUserIdentity(ctx, in, opts...)
}

// 用户银行卡列表
func (m *defaultAdmin) ListUserBanks(ctx context.Context, in *ListUserBanksReq, opts ...grpc.CallOption) (*ListUserBanksResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.ListUserBanks(ctx, in, opts...)
}

// 获取用户银行卡详情
func (m *defaultAdmin) GetUserBank(ctx context.Context, in *GetUserBankReq, opts ...grpc.CallOption) (*GetUserBankResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.GetUserBank(ctx, in, opts...)
}

// 添加用户银行卡
func (m *defaultAdmin) AddUserBank(ctx context.Context, in *AddUserBankReq, opts ...grpc.CallOption) (*AddUserBankResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.AddUserBank(ctx, in, opts...)
}

// 更新用户银行卡
func (m *defaultAdmin) UpdateUserBank(ctx context.Context, in *UpdateUserBankReq, opts ...grpc.CallOption) (*UpdateUserBankResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.UpdateUserBank(ctx, in, opts...)
}

// 删除用户银行卡
func (m *defaultAdmin) DeleteUserBank(ctx context.Context, in *DeleteUserBankReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.DeleteUserBank(ctx, in, opts...)
}

// 更新用户银行卡状态
func (m *defaultAdmin) UpdateUserBankStatus(ctx context.Context, in *UpdateUserBankStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.UpdateUserBankStatus(ctx, in, opts...)
}

// 设置默认用户银行卡
func (m *defaultAdmin) SetDefaultUserBank(ctx context.Context, in *SetDefaultUserBankReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.SetDefaultUserBank(ctx, in, opts...)
}
