// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: staking.proto

package server

import (
	"context"

	"wklive/proto/staking"
	"wklive/services/staking/internal/logic/stakingtask"
	"wklive/services/staking/internal/svc"
)

type StakingTaskServer struct {
	svcCtx *svc.ServiceContext
	staking.UnimplementedStakingTaskServer
}

func NewStakingTaskServer(svcCtx *svc.ServiceContext) *StakingTaskServer {
	return &StakingTaskServer{
		svcCtx: svcCtx,
	}
}

// 质押收益发放/到期结算
func (s *StakingTaskServer) ProcessRewardsAndSettleOrders(ctx context.Context, in *staking.StakingTaskReq) (*staking.StakingTaskResp, error) {
	l := stakingtasklogic.NewProcessRewardsAndSettleOrdersLogic(ctx, s.svcCtx)
	return l.ProcessRewardsAndSettleOrders(in)
}
