// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: staking.proto

package stakingtask

import (
	"context"

	"wklive/proto/staking"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ManualRedeemReq         = staking.ManualRedeemReq
	ManualRedeemResp        = staking.ManualRedeemResp
	ManualRewardReq         = staking.ManualRewardReq
	ManualRewardResp        = staking.ManualRewardResp
	OrderDetailReq          = staking.OrderDetailReq
	OrderDetailResp         = staking.OrderDetailResp
	OrderListReq            = staking.OrderListReq
	OrderListResp           = staking.OrderListResp
	ProductChangeStatusReq  = staking.ProductChangeStatusReq
	ProductChangeStatusResp = staking.ProductChangeStatusResp
	ProductCreateReq        = staking.ProductCreateReq
	ProductCreateResp       = staking.ProductCreateResp
	ProductDetailReq        = staking.ProductDetailReq
	ProductDetailResp       = staking.ProductDetailResp
	ProductListReq          = staking.ProductListReq
	ProductListResp         = staking.ProductListResp
	ProductUpdateReq        = staking.ProductUpdateReq
	ProductUpdateResp       = staking.ProductUpdateResp
	RedeemLogListReq        = staking.RedeemLogListReq
	RedeemLogListResp       = staking.RedeemLogListResp
	RewardLogListReq        = staking.RewardLogListReq
	RewardLogListResp       = staking.RewardLogListResp
	CreateOrderData         = staking.CreateOrderData
	CreateOrderReq          = staking.CreateOrderReq
	CreateOrderResp         = staking.CreateOrderResp
	MyOrderDetailReq        = staking.MyOrderDetailReq
	MyOrderDetailResp       = staking.MyOrderDetailResp
	MyOrderListReq          = staking.MyOrderListReq
	MyOrderListResp         = staking.MyOrderListResp
	MyRedeemLogListReq      = staking.MyRedeemLogListReq
	MyRedeemLogListResp     = staking.MyRedeemLogListResp
	MyRewardLogListReq      = staking.MyRewardLogListReq
	MyRewardLogListResp     = staking.MyRewardLogListResp
	UserProductDetailReq    = staking.UserProductDetailReq
	UserProductDetailResp   = staking.UserProductDetailResp
	UserProductListReq      = staking.UserProductListReq
	UserProductListResp     = staking.UserProductListResp
	RedeemData              = staking.RedeemData
	RedeemReq               = staking.RedeemReq
	RedeemResp              = staking.RedeemResp
	StakingTaskReq          = staking.StakingTaskReq
	StakingTaskResp         = staking.StakingTaskResp

	StakingTask interface {
		// 质押收益发放/到期结算
		ProcessRewardsAndSettleOrders(ctx context.Context, in *StakingTaskReq, opts ...grpc.CallOption) (*StakingTaskResp, error)
	}

	defaultStakingTask struct {
		cli zrpc.Client
	}
)

func NewStakingTask(cli zrpc.Client) StakingTask {
	return &defaultStakingTask{
		cli: cli,
	}
}

// 质押收益发放/到期结算
func (m *defaultStakingTask) ProcessRewardsAndSettleOrders(ctx context.Context, in *StakingTaskReq, opts ...grpc.CallOption) (*StakingTaskResp, error) {
	client := staking.NewStakingTaskClient(m.cli.Conn())
	return client.ProcessRewardsAndSettleOrders(ctx, in, opts...)
}
