// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tOptionClientOrderKeyFieldNames          = builder.RawFieldNames(&TOptionClientOrderKey{})
	tOptionClientOrderKeyRows                = strings.Join(tOptionClientOrderKeyFieldNames, ",")
	tOptionClientOrderKeyRowsExpectAutoSet   = strings.Join(stringx.Remove(tOptionClientOrderKeyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tOptionClientOrderKeyRowsWithPlaceHolder = strings.Join(stringx.Remove(tOptionClientOrderKeyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTOptionClientOrderKeyIdPrefix                          = "cache:tOptionClientOrderKey:id:"
	cacheTOptionClientOrderKeyTenantIdUserIdClientOrderIdPrefix = "cache:tOptionClientOrderKey:tenantId:userId:clientOrderId:"
)

type (
	tOptionClientOrderKeyModel interface {
		Insert(ctx context.Context, data *TOptionClientOrderKey) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TOptionClientOrderKey, error)
		FindOneByTenantIdUserIdClientOrderId(ctx context.Context, tenantId int64, userId int64, clientOrderId string) (*TOptionClientOrderKey, error)
		Update(ctx context.Context, data *TOptionClientOrderKey) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTOptionClientOrderKeyModel struct {
		sqlc.CachedConn
		table string
	}

	TOptionClientOrderKey struct {
		Id            int64  `db:"id"`              // 主键ID
		TenantId      int64  `db:"tenant_id"`       // 租户ID
		UserId        int64  `db:"user_id"`         // 用户ID
		ClientOrderId string `db:"client_order_id"` // 客户端幂等订单号，禁止为空
		OrderId       int64  `db:"order_id"`        // Option订单ID
		OrderNo       string `db:"order_no"`        // Option订单号
		CreateTimes   int64  `db:"create_times"`    // 创建时间
	}
)

func newTOptionClientOrderKeyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTOptionClientOrderKeyModel {
	return &defaultTOptionClientOrderKeyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_option_client_order_key`",
	}
}

func (m *defaultTOptionClientOrderKeyModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tOptionClientOrderKeyIdKey := fmt.Sprintf("%s%v", cacheTOptionClientOrderKeyIdPrefix, id)
	tOptionClientOrderKeyTenantIdUserIdClientOrderIdKey := fmt.Sprintf("%s%v:%v:%v", cacheTOptionClientOrderKeyTenantIdUserIdClientOrderIdPrefix, data.TenantId, data.UserId, data.ClientOrderId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tOptionClientOrderKeyIdKey, tOptionClientOrderKeyTenantIdUserIdClientOrderIdKey)
	return err
}

func (m *defaultTOptionClientOrderKeyModel) FindOne(ctx context.Context, id int64) (*TOptionClientOrderKey, error) {
	tOptionClientOrderKeyIdKey := fmt.Sprintf("%s%v", cacheTOptionClientOrderKeyIdPrefix, id)
	var resp TOptionClientOrderKey
	err := m.QueryRowCtx(ctx, &resp, tOptionClientOrderKeyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tOptionClientOrderKeyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTOptionClientOrderKeyModel) FindOneByTenantIdUserIdClientOrderId(ctx context.Context, tenantId int64, userId int64, clientOrderId string) (*TOptionClientOrderKey, error) {
	tOptionClientOrderKeyTenantIdUserIdClientOrderIdKey := fmt.Sprintf("%s%v:%v:%v", cacheTOptionClientOrderKeyTenantIdUserIdClientOrderIdPrefix, tenantId, userId, clientOrderId)
	var resp TOptionClientOrderKey
	err := m.QueryRowIndexCtx(ctx, &resp, tOptionClientOrderKeyTenantIdUserIdClientOrderIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `user_id` = ? and `client_order_id` = ? limit 1", tOptionClientOrderKeyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, userId, clientOrderId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTOptionClientOrderKeyModel) Insert(ctx context.Context, data *TOptionClientOrderKey) (sql.Result, error) {
	tOptionClientOrderKeyIdKey := fmt.Sprintf("%s%v", cacheTOptionClientOrderKeyIdPrefix, data.Id)
	tOptionClientOrderKeyTenantIdUserIdClientOrderIdKey := fmt.Sprintf("%s%v:%v:%v", cacheTOptionClientOrderKeyTenantIdUserIdClientOrderIdPrefix, data.TenantId, data.UserId, data.ClientOrderId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, tOptionClientOrderKeyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.UserId, data.ClientOrderId, data.OrderId, data.OrderNo, data.CreateTimes)
	}, tOptionClientOrderKeyIdKey, tOptionClientOrderKeyTenantIdUserIdClientOrderIdKey)
	return ret, err
}

func (m *defaultTOptionClientOrderKeyModel) Update(ctx context.Context, newData *TOptionClientOrderKey) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tOptionClientOrderKeyIdKey := fmt.Sprintf("%s%v", cacheTOptionClientOrderKeyIdPrefix, data.Id)
	tOptionClientOrderKeyTenantIdUserIdClientOrderIdKey := fmt.Sprintf("%s%v:%v:%v", cacheTOptionClientOrderKeyTenantIdUserIdClientOrderIdPrefix, data.TenantId, data.UserId, data.ClientOrderId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tOptionClientOrderKeyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.UserId, newData.ClientOrderId, newData.OrderId, newData.OrderNo, newData.CreateTimes, newData.Id)
	}, tOptionClientOrderKeyIdKey, tOptionClientOrderKeyTenantIdUserIdClientOrderIdKey)
	return err
}

func (m *defaultTOptionClientOrderKeyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTOptionClientOrderKeyIdPrefix, primary)
}

func (m *defaultTOptionClientOrderKeyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tOptionClientOrderKeyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTOptionClientOrderKeyModel) tableName() string {
	return m.table
}
