// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/shopspring/decimal"
)

var (
	tOptionPhysicalDeliveryUnitFieldNames          = builder.RawFieldNames(&TOptionPhysicalDeliveryUnit{})
	tOptionPhysicalDeliveryUnitRows                = strings.Join(tOptionPhysicalDeliveryUnitFieldNames, ",")
	tOptionPhysicalDeliveryUnitRowsExpectAutoSet   = strings.Join(stringx.Remove(tOptionPhysicalDeliveryUnitFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tOptionPhysicalDeliveryUnitRowsWithPlaceHolder = strings.Join(stringx.Remove(tOptionPhysicalDeliveryUnitFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTOptionPhysicalDeliveryUnitIdPrefix                     = "cache:tOptionPhysicalDeliveryUnit:id:"
	cacheTOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoPrefix = "cache:tOptionPhysicalDeliveryUnit:tenantId:deliveryUnitNo:"
)

type (
	tOptionPhysicalDeliveryUnitModel interface {
		Insert(ctx context.Context, data *TOptionPhysicalDeliveryUnit) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TOptionPhysicalDeliveryUnit, error)
		FindOneByTenantIdDeliveryUnitNo(ctx context.Context, tenantId int64, deliveryUnitNo string) (*TOptionPhysicalDeliveryUnit, error)
		Update(ctx context.Context, data *TOptionPhysicalDeliveryUnit) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTOptionPhysicalDeliveryUnitModel struct {
		sqlc.CachedConn
		table string
	}

	TOptionPhysicalDeliveryUnit struct {
		Id                  int64           `db:"id"`                    // 主键ID
		TenantId            int64           `db:"tenant_id"`             // 租户ID
		DeliveryUnitNo      string          `db:"delivery_unit_no"`      // 稳定交割单元号
		BatchId             int64           `db:"batch_id"`              // 结算批次ID
		BatchNo             string          `db:"batch_no"`              // 结算批次号
		ContractId          int64           `db:"contract_id"`           // 期权合约ID
		LongPositionId      int64           `db:"long_position_id"`      // 多头持仓ID
		LongUserId          int64           `db:"long_user_id"`          // 多头用户ID
		LongAccountId       int64           `db:"long_account_id"`       // 多头Option账户ID
		ShortPositionId     int64           `db:"short_position_id"`     // 空头持仓ID
		ShortUserId         int64           `db:"short_user_id"`         // 空头用户ID
		ShortAccountId      int64           `db:"short_account_id"`      // 空头Option账户ID
		Quantity            decimal.Decimal `db:"quantity"`              // 配对合约数量
		DeliveryCoin        string          `db:"delivery_coin"`         // 标的交割币
		DeliveryQuantity    decimal.Decimal `db:"delivery_quantity"`     // 标的交割数量
		PaymentCoin         string          `db:"payment_coin"`          // 行权款币
		PaymentAmount       decimal.Decimal `db:"payment_amount"`        // 行权款金额
		Status              int64           `db:"status"`                // 1已创建 2资产处理中 3补资 4人工 5完成 6违约
		CureDeadline        int64           `db:"cure_deadline"`         // 补资截止时间
		FailedInstructionId int64           `db:"failed_instruction_id"` // 最近失败资产指令ID
		LastErrorMsg        string          `db:"last_error_msg"`        // 最近失败原因
		CompletedAt         int64           `db:"completed_at"`          // 完成时间
		ManualRetryCount    int64           `db:"manual_retry_count"`    // 逾期后人工重试代次
		CreateTimes         int64           `db:"create_times"`          // 创建时间
		UpdateTimes         int64           `db:"update_times"`          // 更新时间
	}
)

func newTOptionPhysicalDeliveryUnitModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTOptionPhysicalDeliveryUnitModel {
	return &defaultTOptionPhysicalDeliveryUnitModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_option_physical_delivery_unit`",
	}
}

func (m *defaultTOptionPhysicalDeliveryUnitModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tOptionPhysicalDeliveryUnitIdKey := fmt.Sprintf("%s%v", cacheTOptionPhysicalDeliveryUnitIdPrefix, id)
	tOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoKey := fmt.Sprintf("%s%v:%v", cacheTOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoPrefix, data.TenantId, data.DeliveryUnitNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tOptionPhysicalDeliveryUnitIdKey, tOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoKey)
	return err
}

func (m *defaultTOptionPhysicalDeliveryUnitModel) FindOne(ctx context.Context, id int64) (*TOptionPhysicalDeliveryUnit, error) {
	tOptionPhysicalDeliveryUnitIdKey := fmt.Sprintf("%s%v", cacheTOptionPhysicalDeliveryUnitIdPrefix, id)
	var resp TOptionPhysicalDeliveryUnit
	err := m.QueryRowCtx(ctx, &resp, tOptionPhysicalDeliveryUnitIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tOptionPhysicalDeliveryUnitRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTOptionPhysicalDeliveryUnitModel) FindOneByTenantIdDeliveryUnitNo(ctx context.Context, tenantId int64, deliveryUnitNo string) (*TOptionPhysicalDeliveryUnit, error) {
	tOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoKey := fmt.Sprintf("%s%v:%v", cacheTOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoPrefix, tenantId, deliveryUnitNo)
	var resp TOptionPhysicalDeliveryUnit
	err := m.QueryRowIndexCtx(ctx, &resp, tOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `delivery_unit_no` = ? limit 1", tOptionPhysicalDeliveryUnitRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, deliveryUnitNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTOptionPhysicalDeliveryUnitModel) Insert(ctx context.Context, data *TOptionPhysicalDeliveryUnit) (sql.Result, error) {
	tOptionPhysicalDeliveryUnitIdKey := fmt.Sprintf("%s%v", cacheTOptionPhysicalDeliveryUnitIdPrefix, data.Id)
	tOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoKey := fmt.Sprintf("%s%v:%v", cacheTOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoPrefix, data.TenantId, data.DeliveryUnitNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tOptionPhysicalDeliveryUnitRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.DeliveryUnitNo, data.BatchId, data.BatchNo, data.ContractId, data.LongPositionId, data.LongUserId, data.LongAccountId, data.ShortPositionId, data.ShortUserId, data.ShortAccountId, data.Quantity, data.DeliveryCoin, data.DeliveryQuantity, data.PaymentCoin, data.PaymentAmount, data.Status, data.CureDeadline, data.FailedInstructionId, data.LastErrorMsg, data.CompletedAt, data.ManualRetryCount, data.CreateTimes, data.UpdateTimes)
	}, tOptionPhysicalDeliveryUnitIdKey, tOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoKey)
	return ret, err
}

func (m *defaultTOptionPhysicalDeliveryUnitModel) Update(ctx context.Context, newData *TOptionPhysicalDeliveryUnit) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tOptionPhysicalDeliveryUnitIdKey := fmt.Sprintf("%s%v", cacheTOptionPhysicalDeliveryUnitIdPrefix, data.Id)
	tOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoKey := fmt.Sprintf("%s%v:%v", cacheTOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoPrefix, data.TenantId, data.DeliveryUnitNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tOptionPhysicalDeliveryUnitRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.DeliveryUnitNo, newData.BatchId, newData.BatchNo, newData.ContractId, newData.LongPositionId, newData.LongUserId, newData.LongAccountId, newData.ShortPositionId, newData.ShortUserId, newData.ShortAccountId, newData.Quantity, newData.DeliveryCoin, newData.DeliveryQuantity, newData.PaymentCoin, newData.PaymentAmount, newData.Status, newData.CureDeadline, newData.FailedInstructionId, newData.LastErrorMsg, newData.CompletedAt, newData.ManualRetryCount, newData.CreateTimes, newData.UpdateTimes, newData.Id)
	}, tOptionPhysicalDeliveryUnitIdKey, tOptionPhysicalDeliveryUnitTenantIdDeliveryUnitNoKey)
	return err
}

func (m *defaultTOptionPhysicalDeliveryUnitModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTOptionPhysicalDeliveryUnitIdPrefix, primary)
}

func (m *defaultTOptionPhysicalDeliveryUnitModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tOptionPhysicalDeliveryUnitRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTOptionPhysicalDeliveryUnitModel) tableName() string {
	return m.table
}
