CREATE TABLE `t_user_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` bigint NOT NULL DEFAULT 0 COMMENT '用户ID',
  `wallet_type` tinyint NOT NULL DEFAULT 1 COMMENT '钱包类型:1现货 2资金 3合约 4理财 5期权',
  `coin` varchar(20) NOT NULL DEFAULT '' COMMENT '币种代码,如 USDT/BTC/ETH',
  `total_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '总资产',
  `available_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '可用资产',
  `frozen_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '冻结资产',
  `locked_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '锁定资产/锁仓资产',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态:1正常 0禁用',
  `version` int NOT NULL DEFAULT 0 COMMENT '版本号,用于乐观锁',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` bigint NOT NULL DEFAULT 0 COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT 0 COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_wallet_coin` (`tenant_id`,`user_id`,`wallet_type`,`coin`),
  KEY `idx_tenant_user_id` (`tenant_id`,`user_id`),
  KEY `idx_tenant_coin` (`tenant_id`,`coin`),
  KEY `idx_tenant_wallet_type` (`tenant_id`,`wallet_type`),
  KEY `idx_update_time` (`update_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户资产汇总表';

CREATE TABLE `t_asset_flow` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `flow_no` varchar(64) NOT NULL DEFAULT '' COMMENT '资产流水单号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` bigint NOT NULL DEFAULT 0 COMMENT '用户ID',
  `wallet_type` tinyint NOT NULL DEFAULT 1 COMMENT '钱包类型:1现货 2资金 3合约 4理财 5期权',
  `coin` varchar(20) NOT NULL DEFAULT '' COMMENT '币种代码,如 USDT/BTC/ETH',
  `change_type` varchar(32) NOT NULL DEFAULT '' COMMENT '变动类型',
  `biz_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务类型:payment/trade/staking/option/system/transfer',
  `scene_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务场景:recharge/withdraw/place_order/cancel_order/trade_match/staking_lock/staking_unlock/manual_adjust',
  `biz_id` bigint NOT NULL DEFAULT 0 COMMENT '业务ID',
  `biz_no` varchar(64) NOT NULL DEFAULT '' COMMENT '业务单号',
  `op_type` tinyint NOT NULL DEFAULT 1 COMMENT '操作方向:1增加 2减少 3冻结 4解冻 5锁定 6解锁 7扣减冻结 8扣减锁定',
  `change_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '本次变动金额',
  `before_total_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '变动前总资产',
  `after_total_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '变动后总资产',
  `before_available_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '变动前可用资产',
  `after_available_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '变动后可用资产',
  `before_frozen_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '变动前冻结资产',
  `after_frozen_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '变动后冻结资产',
  `before_locked_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '变动前锁定资产',
  `after_locked_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '变动后锁定资产',
  `balance_snapshot_version` int NOT NULL DEFAULT 0 COMMENT '资产快照版本号',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `ext_json` json DEFAULT NULL COMMENT '扩展信息JSON',
  `create_times` bigint NOT NULL DEFAULT 0 COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT 0 COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_flow_no` (`flow_no`),
  KEY `idx_tenant_user_id` (`tenant_id`,`user_id`),
  KEY `idx_tenant_biz_type_biz_id` (`tenant_id`,`biz_type`,`biz_id`),
  KEY `idx_tenant_biz_no` (`tenant_id`,`biz_no`),
  KEY `idx_tenant_coin_wallet` (`tenant_id`,`coin`,`wallet_type`),
  KEY `idx_tenant_change_type` (`tenant_id`,`change_type`),
  KEY `idx_create_time` (`create_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产流水表';

CREATE TABLE `t_asset_freeze` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `freeze_no` varchar(64) NOT NULL DEFAULT '' COMMENT '冻结单号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` bigint NOT NULL DEFAULT 0 COMMENT '用户ID',
  `wallet_type` tinyint NOT NULL DEFAULT 1 COMMENT '钱包类型:1现货 2资金 3合约 4理财 5期权',
  `coin` varchar(20) NOT NULL DEFAULT '' COMMENT '币种代码',
  `biz_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务类型:trade/withdraw/option/system',
  `scene_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务场景:place_order/withdraw_apply/option_open/manual_freeze',
  `biz_id` bigint NOT NULL DEFAULT 0 COMMENT '业务ID',
  `biz_no` varchar(64) NOT NULL DEFAULT '' COMMENT '业务单号',
  `amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '冻结总金额',
  `used_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '已使用金额',
  `unfreeze_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '已解冻金额',
  `remain_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '剩余冻结金额',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态:1冻结中 2部分释放 3已解冻 4已扣完 5已关闭',
  `expire_time` bigint NOT NULL DEFAULT 0 COMMENT '过期时间戳(毫秒),0表示不过期',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `ext_json` json DEFAULT NULL COMMENT '扩展信息JSON',
  `create_times` bigint NOT NULL DEFAULT 0 COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT 0 COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_freeze_no` (`freeze_no`),
  KEY `idx_tenant_user_id` (`tenant_id`,`user_id`),
  KEY `idx_tenant_biz_type_biz_id` (`tenant_id`,`biz_type`,`biz_id`),
  KEY `idx_tenant_biz_no` (`tenant_id`,`biz_no`),
  KEY `idx_tenant_coin_wallet` (`tenant_id`,`coin`,`wallet_type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产冻结明细表';

CREATE TABLE `t_asset_lock` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `lock_no` varchar(64) NOT NULL DEFAULT '' COMMENT '锁仓单号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` bigint NOT NULL DEFAULT 0 COMMENT '用户ID',
  `wallet_type` tinyint NOT NULL DEFAULT 1 COMMENT '钱包类型:1现货 2资金 3合约 4理财 5期权',
  `coin` varchar(20) NOT NULL DEFAULT '' COMMENT '币种代码',
  `biz_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务类型:staking/earn/activity/system',
  `scene_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务场景:staking_join/fixed_earn_join/activity_lock/manual_lock',
  `biz_id` bigint NOT NULL DEFAULT 0 COMMENT '业务ID',
  `biz_no` varchar(64) NOT NULL DEFAULT '' COMMENT '业务单号',
  `amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '锁仓总金额',
  `unlock_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '已解锁金额',
  `remain_amount` decimal(36,18) NOT NULL DEFAULT 0.000000000000000000 COMMENT '剩余锁仓金额',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态:1锁仓中 2部分解锁 3已解锁 4已关闭',
  `start_time` bigint NOT NULL DEFAULT 0 COMMENT '开始时间戳(毫秒)',
  `end_time` bigint NOT NULL DEFAULT 0 COMMENT '结束时间戳(毫秒)',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `ext_json` json DEFAULT NULL COMMENT '扩展信息JSON',
  `create_times` bigint NOT NULL DEFAULT 0 COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT 0 COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_lock_no` (`lock_no`),
  KEY `idx_tenant_user_id` (`tenant_id`,`user_id`),
  KEY `idx_tenant_biz_type_biz_id` (`tenant_id`,`biz_type`,`biz_id`),
  KEY `idx_tenant_biz_no` (`tenant_id`,`biz_no`),
  KEY `idx_tenant_coin_wallet` (`tenant_id`,`coin`,`wallet_type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产锁仓明细表';

CREATE TABLE `t_asset_idempotent` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户ID',
  `biz_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务类型',
  `biz_no` varchar(64) NOT NULL DEFAULT '' COMMENT '业务单号',
  `scene_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务场景',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态:1处理中 2成功 3失败',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` bigint NOT NULL DEFAULT 0 COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT 0 COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_biz_scene_no` (`tenant_id`,`biz_type`,`scene_type`,`biz_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产幂等控制表';