// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: staking_admin.proto

package stakingadmin

import (
	"context"

	"wklive/proto/staking"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminManualRedeemReq         = staking.AdminManualRedeemReq
	AdminManualRedeemResp        = staking.AdminManualRedeemResp
	AdminManualRewardReq         = staking.AdminManualRewardReq
	AdminManualRewardResp        = staking.AdminManualRewardResp
	AdminOrderDetailReq          = staking.AdminOrderDetailReq
	AdminOrderDetailResp         = staking.AdminOrderDetailResp
	AdminOrderListReq            = staking.AdminOrderListReq
	AdminOrderListResp           = staking.AdminOrderListResp
	AdminProductChangeStatusReq  = staking.AdminProductChangeStatusReq
	AdminProductChangeStatusResp = staking.AdminProductChangeStatusResp
	AdminProductCreateReq        = staking.AdminProductCreateReq
	AdminProductCreateResp       = staking.AdminProductCreateResp
	AdminProductDetailReq        = staking.AdminProductDetailReq
	AdminProductDetailResp       = staking.AdminProductDetailResp
	AdminProductListReq          = staking.AdminProductListReq
	AdminProductListResp         = staking.AdminProductListResp
	AdminProductUpdateReq        = staking.AdminProductUpdateReq
	AdminProductUpdateResp       = staking.AdminProductUpdateResp
	AdminRedeemLogListReq        = staking.AdminRedeemLogListReq
	AdminRedeemLogListResp       = staking.AdminRedeemLogListResp
	AdminRewardLogListReq        = staking.AdminRewardLogListReq
	AdminRewardLogListResp       = staking.AdminRewardLogListResp

	StakingAdmin interface {
		// 获取质押产品列表
		AdminProductList(ctx context.Context, in *AdminProductListReq, opts ...grpc.CallOption) (*AdminProductListResp, error)
		// 获取质押产品详情
		AdminProductDetail(ctx context.Context, in *AdminProductDetailReq, opts ...grpc.CallOption) (*AdminProductDetailResp, error)
		// 创建质押产品
		ProductCreate(ctx context.Context, in *AdminProductCreateReq, opts ...grpc.CallOption) (*AdminProductCreateResp, error)
		// 更新质押产品
		ProductUpdate(ctx context.Context, in *AdminProductUpdateReq, opts ...grpc.CallOption) (*AdminProductUpdateResp, error)
		// 修改质押产品状态
		ProductChangeStatus(ctx context.Context, in *AdminProductChangeStatusReq, opts ...grpc.CallOption) (*AdminProductChangeStatusResp, error)
		// 获取质押订单列表
		OrderList(ctx context.Context, in *AdminOrderListReq, opts ...grpc.CallOption) (*AdminOrderListResp, error)
		// 获取质押订单详情
		OrderDetail(ctx context.Context, in *AdminOrderDetailReq, opts ...grpc.CallOption) (*AdminOrderDetailResp, error)
		// 获取收益记录列表
		RewardLogList(ctx context.Context, in *AdminRewardLogListReq, opts ...grpc.CallOption) (*AdminRewardLogListResp, error)
		// 获取赎回记录列表
		RedeemLogList(ctx context.Context, in *AdminRedeemLogListReq, opts ...grpc.CallOption) (*AdminRedeemLogListResp, error)
		// 手动发放收益
		ManualReward(ctx context.Context, in *AdminManualRewardReq, opts ...grpc.CallOption) (*AdminManualRewardResp, error)
		// 手动赎回
		ManualRedeem(ctx context.Context, in *AdminManualRedeemReq, opts ...grpc.CallOption) (*AdminManualRedeemResp, error)
	}

	defaultStakingAdmin struct {
		cli zrpc.Client
	}
)

func NewStakingAdmin(cli zrpc.Client) StakingAdmin {
	return &defaultStakingAdmin{
		cli: cli,
	}
}

// 获取质押产品列表
func (m *defaultStakingAdmin) AdminProductList(ctx context.Context, in *AdminProductListReq, opts ...grpc.CallOption) (*AdminProductListResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.AdminProductList(ctx, in, opts...)
}

// 获取质押产品详情
func (m *defaultStakingAdmin) AdminProductDetail(ctx context.Context, in *AdminProductDetailReq, opts ...grpc.CallOption) (*AdminProductDetailResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.AdminProductDetail(ctx, in, opts...)
}

// 创建质押产品
func (m *defaultStakingAdmin) ProductCreate(ctx context.Context, in *AdminProductCreateReq, opts ...grpc.CallOption) (*AdminProductCreateResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.ProductCreate(ctx, in, opts...)
}

// 更新质押产品
func (m *defaultStakingAdmin) ProductUpdate(ctx context.Context, in *AdminProductUpdateReq, opts ...grpc.CallOption) (*AdminProductUpdateResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.ProductUpdate(ctx, in, opts...)
}

// 修改质押产品状态
func (m *defaultStakingAdmin) ProductChangeStatus(ctx context.Context, in *AdminProductChangeStatusReq, opts ...grpc.CallOption) (*AdminProductChangeStatusResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.ProductChangeStatus(ctx, in, opts...)
}

// 获取质押订单列表
func (m *defaultStakingAdmin) OrderList(ctx context.Context, in *AdminOrderListReq, opts ...grpc.CallOption) (*AdminOrderListResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.OrderList(ctx, in, opts...)
}

// 获取质押订单详情
func (m *defaultStakingAdmin) OrderDetail(ctx context.Context, in *AdminOrderDetailReq, opts ...grpc.CallOption) (*AdminOrderDetailResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.OrderDetail(ctx, in, opts...)
}

// 获取收益记录列表
func (m *defaultStakingAdmin) RewardLogList(ctx context.Context, in *AdminRewardLogListReq, opts ...grpc.CallOption) (*AdminRewardLogListResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.RewardLogList(ctx, in, opts...)
}

// 获取赎回记录列表
func (m *defaultStakingAdmin) RedeemLogList(ctx context.Context, in *AdminRedeemLogListReq, opts ...grpc.CallOption) (*AdminRedeemLogListResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.RedeemLogList(ctx, in, opts...)
}

// 手动发放收益
func (m *defaultStakingAdmin) ManualReward(ctx context.Context, in *AdminManualRewardReq, opts ...grpc.CallOption) (*AdminManualRewardResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.ManualReward(ctx, in, opts...)
}

// 手动赎回
func (m *defaultStakingAdmin) ManualRedeem(ctx context.Context, in *AdminManualRedeemReq, opts ...grpc.CallOption) (*AdminManualRedeemResp, error) {
	client := staking.NewStakingAdminClient(m.cli.Conn())
	return client.ManualRedeem(ctx, in, opts...)
}
