// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddBankReq struct {
	BankName    string `json:"bankName"`
	BankCode    string `json:"bankCode,optional"`
	AccountName string `json:"accountName"`
	AccountNo   string `json:"accountNo"`
	BranchName  string `json:"branchName,optional"`
	CountryCode string `json:"countryCode,optional"`
	IsDefault   bool   `json:"isDefault,optional"`
}

type AddBankResp struct {
	RespBase
	Bank UserBank `json:"bank"`
}

type AvailableRechargeChannel struct {
	ChannelId              int64  `json:"channelId"`
	ChannelCode            string `json:"channelCode"`
	ChannelName            string `json:"channelName"`
	DisplayName            string `json:"displayName"`
	Icon                   string `json:"icon"`
	Currency               string `json:"currency"`
	SingleMinAmount        int64  `json:"singleMinAmount"`
	SingleMaxAmount        int64  `json:"singleMaxAmount"`
	FeeType                int64  `json:"feeType"` // 0未知 1费率 2固定
	FeeRate                string `json:"feeRate"`
	FeeFixedAmount         int64  `json:"feeFixedAmount"`
	PlatformId             int64  `json:"platformId"`
	ProductId              int64  `json:"productId"`
	AccountId              int64  `json:"accountId"`
	UserSuccessTotalAmount int64  `json:"userSuccessTotalAmount"`
}

type CancelMyPayOrderReq struct {
	TenantId int64  `json:"tenantId,optional"`
	OrderNo  string `path:"orderNo"`
}

type ChangeLoginPasswordReq struct {
	OldPassword     string `json:"oldPassword"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type ChangePayPasswordReq struct {
	OldPassword     string `json:"oldPassword"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type CreateRechargeOrderReq struct {
	TenantId       int64  `json:"json:"tenantId,optional"`
	ChannelId      int64  `json:"channelId"`
	RechargeAmount int64  `json:"rechargeAmount"` // 单位：分
	Currency       string `json:"currency"`
	Subject        string `json:"subject,optional"`
	Body           string `json:"body,optional"`
	ClientType     int64  `json:"clientType"` // 0未知 1APP 2H5 3WEB
	ClientIp       string `json:"clientIp,optional"`
	BizOrderNo     string `json:"bizOrderNo,optional"`
}

type CreateRechargeOrderResp struct {
	RespBase
	Data PayOrder `json:"data"`
}

type DeleteBankReq struct {
	Id int64 `path:"id"`
}

type GetIdentityResp struct {
	RespBase
	Data UserIdentity `json:"data"`
}

type GetMyPayOrderReq struct {
	TenantId int64  `form:"tenantId,optional"`
	OrderNo  string `path:"orderNo"`
}

type GetMyPayOrderResp struct {
	RespBase
	Data PayOrder `json:"data"`
}

type GetMyRechargeStatReq struct {
	TenantId int64 `form:"tenantId,optional"`
}

type GetMyRechargeStatResp struct {
	RespBase
	Data UserRechargeStat `json:"data"`
}

type GetProfileResp struct {
	RespBase
	Data UserProfile `json:"data"`
}

type GetSecurityResp struct {
	RespBase
	Data UserSecurity `json:"data"`
}

type GetSystemCoreResp struct {
	Data SystemCore `json:"data"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type InitGoogle2FAResp struct {
	RespBase
	Secret    string `json:"secret"`
	QrCodeUrl string `json:"qrCodeUrl"`
}

type ListAvailableRechargeChannelsReq struct {
	TenantId       int64  `json:"tenantId,optional"`
	RechargeAmount int64  `json:"rechargeAmount"` // 单位：分
	Currency       string `json:"currency"`
	ClientType     int64  `json:"clientType"` // 0未知 1APP 2H5 3WEB
}

type ListAvailableRechargeChannelsResp struct {
	RespBase
	Data []AvailableRechargeChannel `json:"data"`
}

type ListBanksReq struct {
	PageReq
}

type ListBanksResp struct {
	RespBase
	Data []UserBank `json:"data"`
}

type ListMyPayOrdersReq struct {
	TenantId        int64  `form:"tenantId,optional"`
	Cursor          int64  `form:"cursor,optional"`
	Limit           int64  `form:"limit,optional"`
	Status          int64  `form:"status,optional"` // 0未知 1待支付 2支付中 3成功 4失败 5已关闭 6已退款
	OrderNo         string `form:"orderNo,optional"`
	CreateTimeStart int64  `form:"createTimeStart,optional"`
	CreateTimeEnd   int64  `form:"createTimeEnd,optional"`
}

type ListMyPayOrdersResp struct {
	RespBase
	Data []PayOrder `json:"data"`
}

type LoginReq struct {
	TenantCode string `json:"tenantCode"`
	LoginType  int64  `json:"loginType"`
	Account    string `json:"account"`
	Password   string `json:"password"`
	GoogleCode string `json:"googleCode,optional"`
	LoginIp    string `json:"loginIp,optional"`
}

type LoginResp struct {
	RespBase
	UserId  int64       `json:"userId"`
	Token   TokenInfo   `json:"token"`
	Profile UserProfile `json:"profile"`
}

type PageReq struct {
	Cursor int64 `form:"cursor,optional"`
	Limit  int64 `form:"limit,optional"`
}

type PayOrder struct {
	Id           int64  `json:"id"`
	TenantId     int64  `json:"tenantId"`
	UserId       int64  `json:"userId"`
	OrderNo      string `json:"orderNo"`
	BizOrderNo   string `json:"bizOrderNo"`
	PlatformId   int64  `json:"platformId"`
	ProductId    int64  `json:"productId"`
	AccountId    int64  `json:"accountId"`
	ChannelId    int64  `json:"channelId"`
	Currency     string `json:"currency"`
	OrderAmount  int64  `json:"orderAmount"`
	PayAmount    int64  `json:"payAmount"`
	FeeAmount    int64  `json:"feeAmount"`
	Subject      string `json:"subject"`
	Body         string `json:"body"`
	ClientType   int64  `json:"clientType"` // 0未知 1APP 2H5 3WEB
	ClientIp     string `json:"clientIp"`
	Status       int64  `json:"status"` // 0未知 1待支付 2支付中 3成功 4失败 5已关闭 6已退款
	ThirdTradeNo string `json:"thirdTradeNo"`
	ThirdOrderNo string `json:"thirdOrderNo"`
	PayUrl       string `json:"payUrl"`
	QrContent    string `json:"qrContent"`
	RequestData  string `json:"requestData"`
	ResponseData string `json:"responseData"`
	NotifyData   string `json:"notifyData"`
	ExpireTime   int64  `json:"expireTime"`
	PaidTime     int64  `json:"paidTime"`
	NotifyTime   int64  `json:"notifyTime"`
	CloseTime    int64  `json:"closeTime"`
	Remark       string `json:"remark"`
	CreateTime   int64  `json:"createTime"`
	UpdateTime   int64  `json:"updateTime"`
}

type QueryMyPayOrderStatusReq struct {
	TenantId int64  `form:"tenantId,optional"`
	OrderNo  string `path:"orderNo"`
}

type QueryMyPayOrderStatusResp struct {
	RespBase
	Data PayOrder `json:"data"`
}

type RefreshTokenReq struct {
	TenantCode   string `json:"tenantCode,optional"`
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	RespBase
	Token TokenInfo `json:"token"`
}

type RegisterReq struct {
	TenantCode      string `json:"tenantCode"`
	RegisterType    int64  `json:"registerType"`
	Username        string `json:"username,optional"`
	Phone           string `json:"phone,optional"`
	Email           string `json:"email,optional"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
	InviteCode      string `json:"inviteCode,optional"`
	Source          string `json:"source,optional"`
	RegisterIp      string `json:"registerIp,optional"`
}

type RegisterResp struct {
	RespBase
	UserId  int64       `json:"userId"`
	Token   TokenInfo   `json:"token"`
	Profile UserProfile `json:"profile"`
}

type RespBase struct {
	Code       int32  `json:"code"`
	Msg        string `json:"msg"`
	Total      int64  `json:"total,optional"`
	HasNext    bool   `json:"hasNext,optional"`
	HasPrev    bool   `json:"hasPrev,optional"`
	NextCursor int64  `json:"nextCursor,optional"`
	PrevCursor int64  `json:"prevCursor,optional"`
}

type SetDefaultBankReq struct {
	Id int64 `path:"id"`
}

type SetPayPasswordReq struct {
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type SubmitIdentityReq struct {
	Phone         string `json:"phone,optional"`
	Email         string `json:"email,optional"`
	RealName      string `json:"realName"`
	Gender        int64  `json:"gender,optional"`
	Birthday      string `json:"birthday,optional"`
	CountryCode   string `json:"countryCode,optional"`
	Province      string `json:"province,optional"`
	City          string `json:"city,optional"`
	Address       string `json:"address,optional"`
	IdType        int64  `json:"idType"`
	IdNo          string `json:"idNo"`
	FrontImage    string `json:"frontImage,optional"`
	BackImage     string `json:"backImage,optional"`
	HandheldImage string `json:"handheldImage,optional"`
	KycLevel      int64  `json:"kycLevel,optional"`
}

type SubmitIdentityResp struct {
	RespBase
	Data UserIdentity `json:"data"`
}

type SystemCore struct {
	IsCaptchaEnabled  bool `json:"isCaptchaEnabled"`
	IsRegisterEnabled bool `json:"isRegisterEnabled"`
}

type TenantInfo struct {
	TenantId     int64  `json:"tenantId"`
	TenantCode   string `json:"tenantCode"`
	TenantName   string `json:"tenantName"`
	TenantStatus int32  `json:"tenantStatus"`
	ExpireTime   int64  `json:"expireTime"`
}

type TenantJsonScope struct {
	TenantId   int64  `json:"tenantId,optional"`
	TenantCode string `json:"tenantCode,optional"`
}

type TenantScope struct {
	TenantId   int64  `form:"tenantId,optional"`
	TenantCode string `form:"tenantCode,optional"`
}

type TokenInfo struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpireTime   int64  `json:"expireTime"`
}

type UpdateBankReq struct {
	Id          int64  `path:"id"`
	BankName    string `json:"bankName"`
	BankCode    string `json:"bankCode,optional"`
	AccountName string `json:"accountName"`
	AccountNo   string `json:"accountNo"`
	BranchName  string `json:"branchName,optional"`
	CountryCode string `json:"countryCode,optional"`
	IsDefault   bool   `json:"isDefault,optional"`
}

type UpdateBankResp struct {
	RespBase
	Bank UserBank `json:"bank"`
}

type UpdateProfileReq struct {
	Nickname    string `json:"nickname,optional"`
	Avatar      string `json:"avatar,optional"`
	Language    string `json:"language,optional"`
	Timezone    string `json:"timezone,optional"`
	Signature   string `json:"signature,optional"`
	Gender      int64  `json:"gender,optional"`
	Birthday    string `json:"birthday,optional"`
	CountryCode string `json:"countryCode,optional"`
	Province    string `json:"province,optional"`
	City        string `json:"city,optional"`
	Address     string `json:"address,optional"`
}

type UpdateProfileResp struct {
	RespBase
	Profile UserProfile `json:"profile"`
}

type UserBank struct {
	Id              int64  `json:"id"`
	TenantId        int64  `json:"tenantId"`
	UserId          int64  `json:"userId"`
	BankName        string `json:"bankName"`
	BankCode        string `json:"bankCode,optional"`
	AccountName     string `json:"accountName"`
	AccountNo       string `json:"accountNo"`
	MaskedAccountNo string `json:"maskedAccountNo,optional"`
	BranchName      string `json:"branchName,optional"`
	CountryCode     string `json:"countryCode,optional"`
	IsDefault       bool   `json:"isDefault"`
	Status          int64  `json:"status"`
	CreateTime      int64  `json:"createTime,optional"`
	UpdateTime      int64  `json:"updateTime,optional"`
}

type UserBankListItem struct {
	Id              int64  `json:"id"`
	TenantId        int64  `json:"tenantId"`
	UserId          int64  `json:"userId"`
	UserNo          string `json:"userNo"`
	Username        string `json:"username"`
	BankName        string `json:"bankName"`
	BankCode        string `json:"bankCode,optional"`
	AccountName     string `json:"accountName"`
	AccountNo       string `json:"accountNo"`
	MaskedAccountNo string `json:"maskedAccountNo,optional"`
	BranchName      string `json:"branchName,optional"`
	CountryCode     string `json:"countryCode,optional"`
	IsDefault       bool   `json:"isDefault"`
	Status          int64  `json:"status"`
	CreateTime      int64  `json:"createTime,optional"`
}

type UserBase struct {
	Id             int64  `json:"id"`
	TenantId       int64  `json:"tenantId"`
	UserNo         string `json:"userNo"`
	Username       string `json:"username"`
	Nickname       string `json:"nickname,optional"`
	Avatar         string `json:"avatar,optional"`
	Language       string `json:"language,optional"`
	Timezone       string `json:"timezone,optional"`
	InviteCode     string `json:"inviteCode,optional"`
	Signature      string `json:"signature,optional"`
	RegisterType   int64  `json:"registerType"`
	Status         int64  `json:"status"`
	MemberLevel    int32  `json:"memberLevel"`
	Source         string `json:"source,optional"`
	ReferrerUserId int64  `json:"referrerUserId,optional"`
	LastLoginIp    string `json:"lastLoginIp,optional"`
	LastLoginTime  int64  `json:"lastLoginTime,optional"`
	RegisterIp     string `json:"registerIp,optional"`
	RegisterTime   int64  `json:"registerTime,optional"`
	Remark         string `json:"remark,optional"`
	Deleted        bool   `json:"deleted"`
	CreateTime     int64  `json:"createTime,optional"`
	UpdateTime     int64  `json:"updateTime,optional"`
}

type UserDetail struct {
	Base     UserBase     `json:"base"`
	Identity UserIdentity `json:"identity,optional"`
	Security UserSecurity `json:"security,optional"`
	Banks    []UserBank   `json:"banks,optional"`
}

type UserIdReq struct {
	UserId int64 `path:"userId"`
}

type UserIdentity struct {
	Id            int64  `json:"id"`
	TenantId      int64  `json:"tenantId"`
	UserId        int64  `json:"userId"`
	Phone         string `json:"phone,optional"`
	Email         string `json:"email,optional"`
	RealName      string `json:"realName,optional"`
	Gender        int64  `json:"gender,optional"`
	Birthday      string `json:"birthday,optional"`
	CountryCode   string `json:"countryCode,optional"`
	Province      string `json:"province,optional"`
	City          string `json:"city,optional"`
	Address       string `json:"address,optional"`
	IdType        int64  `json:"idType,optional"`
	IdNo          string `json:"idNo,optional"`
	FrontImage    string `json:"frontImage,optional"`
	BackImage     string `json:"backImage,optional"`
	HandheldImage string `json:"handheldImage,optional"`
	KycLevel      int64  `json:"kycLevel,optional"`
	VerifyStatus  int64  `json:"verifyStatus,optional"`
	RejectReason  string `json:"rejectReason,optional"`
	SubmitTime    int64  `json:"submitTime,optional"`
	VerifyTime    int64  `json:"verifyTime,optional"`
	VerifyBy      int64  `json:"verifyBy,optional"`
	CreateTime    int64  `json:"createTime,optional"`
	UpdateTime    int64  `json:"updateTime,optional"`
}

type UserIdentityListItem struct {
	UserId       int64  `json:"userId"`
	UserNo       string `json:"userNo"`
	Username     string `json:"username"`
	Phone        string `json:"phone,optional"`
	Email        string `json:"email,optional"`
	RealName     string `json:"realName,optional"`
	IdType       int64  `json:"idType,optional"`
	IdNo         string `json:"idNo,optional"`
	KycLevel     int64  `json:"kycLevel,optional"`
	VerifyStatus int64  `json:"verifyStatus,optional"`
	RejectReason string `json:"rejectReason,optional"`
	SubmitTime   int64  `json:"submitTime,optional"`
	VerifyTime   int64  `json:"verifyTime,optional"`
	VerifyBy     int64  `json:"verifyBy,optional"`
}

type UserListItem struct {
	UserId        int64  `json:"userId"`
	UserNo        string `json:"userNo"`
	Username      string `json:"username"`
	Nickname      string `json:"nickname,optional"`
	Avatar        string `json:"avatar,optional"`
	Phone         string `json:"phone,optional"`
	Email         string `json:"email,optional"`
	RealName      string `json:"realName,optional"`
	Status        int64  `json:"status"`
	MemberLevel   int32  `json:"memberLevel"`
	KycLevel      int64  `json:"kycLevel,optional"`
	VerifyStatus  int64  `json:"verifyStatus,optional"`
	InviteCode    string `json:"inviteCode,optional"`
	LastLoginIp   string `json:"lastLoginIp,optional"`
	LastLoginTime int64  `json:"lastLoginTime,optional"`
	RegisterTime  int64  `json:"registerTime,optional"`
}

type UserProfile struct {
	Base     UserBase     `json:"base"`
	Identity UserIdentity `json:"identity,optional"`
	Security UserSecurity `json:"security,optional"`
}

type UserRechargeStat struct {
	Id                 int64 `json:"id"`
	TenantId           int64 `json:"tenantId"`
	UserId             int64 `json:"userId"`
	SuccessOrderCount  int64 `json:"successOrderCount"`
	SuccessTotalAmount int64 `json:"successTotalAmount"`
	TodaySuccessAmount int64 `json:"todaySuccessAmount"`
	TodaySuccessCount  int64 `json:"todaySuccessCount"`
	FirstSuccessTime   int64 `json:"firstSuccessTime"`
	LastSuccessTime    int64 `json:"lastSuccessTime"`
	CreateTime         int64 `json:"createTime"`
	UpdateTime         int64 `json:"updateTime"`
}

type UserSecurity struct {
	Id              int64 `json:"id"`
	TenantId        int64 `json:"tenantId"`
	UserId          int64 `json:"userId"`
	HasPayPassword  bool  `json:"hasPayPassword"`
	GoogleEnabled   bool  `json:"googleEnabled"`
	LoginErrorCount int32 `json:"loginErrorCount"`
	PayErrorCount   int32 `json:"payErrorCount"`
	LockUntil       int64 `json:"lockUntil,optional"`
	RiskLevel       int64 `json:"riskLevel"`
	CreateTime      int64 `json:"createTime,optional"`
	UpdateTime      int64 `json:"updateTime,optional"`
}

type VerifyGoogle2FAReq struct {
	GoogleCode string `json:"googleCode"`
}
