CREATE TABLE `t_user` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `user_no` varchar(32) NOT NULL COMMENT '用户编号',
  `username` varchar(64) NOT NULL COMMENT '用户名',
  `nickname` varchar(64) DEFAULT NULL COMMENT '昵称',
  `avatar` varchar(255) DEFAULT NULL COMMENT '头像',
  `password_hash` varchar(255) NOT NULL COMMENT '登录密码哈希',
  `register_type` tinyint NOT NULL DEFAULT 1 COMMENT '注册方式：1用户名 2手机号 3邮箱 4游客',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：1正常 2禁用 3冻结 4注销',
  `member_level` int NOT NULL DEFAULT 0 COMMENT '会员等级',
  `language` varchar(16) DEFAULT NULL COMMENT '语言',
  `timezone` varchar(64) DEFAULT NULL COMMENT '时区',
  `invite_code` varchar(32) DEFAULT NULL COMMENT '邀请码',
  `signature` varchar(255) DEFAULT NULL COMMENT '个性签名',
  `source` varchar(64) DEFAULT NULL COMMENT '注册来源',
  `referrer_user_id` bigint DEFAULT NULL COMMENT '邀请人ID',
  `last_login_ip` varchar(64) DEFAULT NULL COMMENT '最后登录IP',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `register_ip` varchar(64) DEFAULT NULL COMMENT '注册IP',
  `register_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_no` (`tenant_id`, `user_no`),
  UNIQUE KEY `uk_tenant_username` (`tenant_id`, `username`),
  UNIQUE KEY `uk_tenant_invite_code` (`tenant_id`, `invite_code`),
  KEY `idx_tenant_status` (`tenant_id`, `status`),
  KEY `idx_tenant_deleted` (`tenant_id`, `deleted`),
  KEY `idx_tenant_register_time` (`tenant_id`, `register_time`),
  KEY `idx_referrer_user_id` (`referrer_user_id`),
  KEY `idx_last_login_time` (`last_login_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户基础表';


CREATE TABLE `t_user_identity` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `real_name` varchar(64) DEFAULT NULL COMMENT '真实姓名',
  `gender` tinyint NOT NULL DEFAULT 0 COMMENT '性别：0未知 1男 2女',
  `birthday` date DEFAULT NULL COMMENT '生日',
  `country_code` varchar(16) DEFAULT NULL COMMENT '国家/地区代码',
  `province` varchar(64) DEFAULT NULL COMMENT '省/州',
  `city` varchar(64) DEFAULT NULL COMMENT '城市',
  `address` varchar(255) DEFAULT NULL COMMENT '地址',
  `id_type` tinyint NOT NULL DEFAULT 0 COMMENT '证件类型：0未提交 1身份证 2护照 3驾驶证',
  `id_no` varchar(128) DEFAULT NULL COMMENT '证件号码',
  `front_image` varchar(255) DEFAULT NULL COMMENT '证件正面',
  `back_image` varchar(255) DEFAULT NULL COMMENT '证件反面',
  `handheld_image` varchar(255) DEFAULT NULL COMMENT '手持证件照',
  `kyc_level` tinyint NOT NULL DEFAULT 0 COMMENT 'KYC等级：0未认证 1初级 2高级',
  `verify_status` tinyint NOT NULL DEFAULT 0 COMMENT '实名状态：0未提交 1审核中 2通过 3拒绝',
  `reject_reason` varchar(255) DEFAULT NULL COMMENT '驳回原因',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `verify_time` datetime DEFAULT NULL COMMENT '审核时间',
  `verify_by` bigint DEFAULT NULL COMMENT '审核人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_id` (`tenant_id`, `user_id`),
  UNIQUE KEY `uk_tenant_phone` (`tenant_id`, `phone`),
  UNIQUE KEY `uk_tenant_email` (`tenant_id`, `email`),
  KEY `idx_tenant_verify_status` (`tenant_id`, `verify_status`),
  KEY `idx_tenant_kyc_level` (`tenant_id`, `kyc_level`),
  KEY `idx_tenant_real_name` (`tenant_id`, `real_name`),
  KEY `idx_tenant_id_no` (`tenant_id`, `id_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户实名表';


CREATE TABLE `t_user_security` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `pay_password_hash` varchar(255) DEFAULT NULL COMMENT '支付密码哈希',
  `google_secret` varchar(255) DEFAULT NULL COMMENT 'Google密钥',
  `google_enabled` tinyint NOT NULL DEFAULT 0 COMMENT 'Google2FA是否启用：0否 1是',
  `login_error_count` int NOT NULL DEFAULT 0 COMMENT '登录错误次数',
  `pay_error_count` int NOT NULL DEFAULT 0 COMMENT '支付密码错误次数',
  `lock_until` datetime DEFAULT NULL COMMENT '锁定到期时间',
  `risk_level` tinyint NOT NULL DEFAULT 0 COMMENT '风控等级：0正常 1关注 2高风险',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_user_id` (`tenant_id`, `user_id`),
  KEY `idx_tenant_google_enabled` (`tenant_id`, `google_enabled`),
  KEY `idx_tenant_risk_level` (`tenant_id`, `risk_level`),
  KEY `idx_lock_until` (`lock_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户安全表';

CREATE TABLE `t_user_bank` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `bank_name` varchar(128) NOT NULL COMMENT '银行名称',
  `bank_code` varchar(32) DEFAULT NULL COMMENT '银行编码',
  `account_name` varchar(128) NOT NULL COMMENT '开户名',
  `account_no` varchar(128) NOT NULL COMMENT '银行卡号',
  `branch_name` varchar(255) DEFAULT NULL COMMENT '支行名称',
  `country_code` varchar(16) DEFAULT NULL COMMENT '国家地区',
  `is_default` tinyint NOT NULL DEFAULT 0 COMMENT '是否默认：0否 1是',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：1正常 2禁用',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_user_id` (`tenant_id`, `user_id`),
  KEY `idx_tenant_status` (`tenant_id`, `status`),
  KEY `idx_tenant_is_default` (`tenant_id`, `is_default`),
  KEY `idx_tenant_account_no` (`tenant_id`, `account_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户银行卡表';