// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package server

import (
	"context"

	"wklive/proto/market"
	"wklive/services/market/internal/logic/market"
	"wklive/services/market/internal/svc"
)

type MarketServer struct {
	svcCtx *svc.ServiceContext
	market.UnimplementedMarketServer
}

func NewMarketServer(svcCtx *svc.ServiceContext) *MarketServer {
	return &MarketServer{
		svcCtx: svcCtx,
	}
}

// Reads an authoritative snapshot from the permanent archive at or before
func (s *MarketServer) GetAuthoritativeSnapshot(ctx context.Context, in *market.GetAuthoritativeSnapshotReq) (*market.GetAuthoritativeSnapshotResp, error) {
	l := marketlogic.NewGetAuthoritativeSnapshotLogic(ctx, s.svcCtx)
	return l.GetAuthoritativeSnapshot(in)
}

// Resolves the product-specific or market-default calendar and reports
func (s *MarketServer) GetTradingStatus(ctx context.Context, in *market.GetTradingStatusReq) (*market.GetTradingStatusResp, error) {
	l := marketlogic.NewGetTradingStatusLogic(ctx, s.svcCtx)
	return l.GetTradingStatus(in)
}

// Resolves an enabled, app-visible tenant product for downstream services.
func (s *MarketServer) ResolveTenantProduct(ctx context.Context, in *market.ResolveTenantProductReq) (*market.ResolveTenantProductResp, error) {
	l := marketlogic.NewResolveTenantProductLogic(ctx, s.svcCtx)
	return l.ResolveTenantProduct(in)
}
