// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tCryptoRechargeTxFieldNames          = builder.RawFieldNames(&TCryptoRechargeTx{})
	tCryptoRechargeTxRows                = strings.Join(tCryptoRechargeTxFieldNames, ",")
	tCryptoRechargeTxRowsExpectAutoSet   = strings.Join(stringx.Remove(tCryptoRechargeTxFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tCryptoRechargeTxRowsWithPlaceHolder = strings.Join(stringx.Remove(tCryptoRechargeTxFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTCryptoRechargeTxIdPrefix              = "cache:tCryptoRechargeTx:id:"
	cacheTCryptoRechargeTxChainCodeTxHashPrefix = "cache:tCryptoRechargeTx:chainCode:txHash:"
)

type (
	tCryptoRechargeTxModel interface {
		Insert(ctx context.Context, data *TCryptoRechargeTx) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TCryptoRechargeTx, error)
		FindOneByChainCodeTxHash(ctx context.Context, chainCode int64, txHash string) (*TCryptoRechargeTx, error)
		Update(ctx context.Context, data *TCryptoRechargeTx) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTCryptoRechargeTxModel struct {
		sqlc.CachedConn
		table string
	}

	TCryptoRechargeTx struct {
		Id                   int64          `db:"id"`                     // 主键ID
		TenantId             int64          `db:"tenant_id"`              // 租户ID
		UserId               int64          `db:"user_id"`                // 用户ID
		OrderId              int64          `db:"order_id"`               // 充值订单ID
		OrderNo              string         `db:"order_no"`               // 充值订单号
		Coin                 string         `db:"coin"`                   // 币种
		ChainCode            int64          `db:"chain_code"`             // 链类型
		TxHash               string         `db:"tx_hash"`                // 交易哈希
		FromAddress          string         `db:"from_address"`           // 付款地址
		ToAddress            string         `db:"to_address"`             // 收款地址
		Memo                 string         `db:"memo"`                   // memo/tag
		Amount               float64        `db:"amount"`                 // 链上到账数量
		BlockHeight          int64          `db:"block_height"`           // 区块高度
		ConfirmCount         int64          `db:"confirm_count"`          // 当前确认数
		RequiredConfirmCount int64          `db:"required_confirm_count"` // 要求确认数
		Status               int64          `db:"status"`                 // 状态:1待确认 2确认中 3已确认 4失败 5已入账
		RawData              sql.NullString `db:"raw_data"`               // 链上原始数据
		CreateTimes          int64          `db:"create_times"`
		UpdateTimes          int64          `db:"update_times"`
	}
)

func newTCryptoRechargeTxModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTCryptoRechargeTxModel {
	return &defaultTCryptoRechargeTxModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_crypto_recharge_tx`",
	}
}

func (m *defaultTCryptoRechargeTxModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tCryptoRechargeTxChainCodeTxHashKey := fmt.Sprintf("%s%v:%v", cacheTCryptoRechargeTxChainCodeTxHashPrefix, data.ChainCode, data.TxHash)
	tCryptoRechargeTxIdKey := fmt.Sprintf("%s%v", cacheTCryptoRechargeTxIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tCryptoRechargeTxChainCodeTxHashKey, tCryptoRechargeTxIdKey)
	return err
}

func (m *defaultTCryptoRechargeTxModel) FindOne(ctx context.Context, id int64) (*TCryptoRechargeTx, error) {
	tCryptoRechargeTxIdKey := fmt.Sprintf("%s%v", cacheTCryptoRechargeTxIdPrefix, id)
	var resp TCryptoRechargeTx
	err := m.QueryRowCtx(ctx, &resp, tCryptoRechargeTxIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tCryptoRechargeTxRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTCryptoRechargeTxModel) FindOneByChainCodeTxHash(ctx context.Context, chainCode int64, txHash string) (*TCryptoRechargeTx, error) {
	tCryptoRechargeTxChainCodeTxHashKey := fmt.Sprintf("%s%v:%v", cacheTCryptoRechargeTxChainCodeTxHashPrefix, chainCode, txHash)
	var resp TCryptoRechargeTx
	err := m.QueryRowIndexCtx(ctx, &resp, tCryptoRechargeTxChainCodeTxHashKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `chain_code` = ? and `tx_hash` = ? limit 1", tCryptoRechargeTxRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, chainCode, txHash); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTCryptoRechargeTxModel) Insert(ctx context.Context, data *TCryptoRechargeTx) (sql.Result, error) {
	tCryptoRechargeTxChainCodeTxHashKey := fmt.Sprintf("%s%v:%v", cacheTCryptoRechargeTxChainCodeTxHashPrefix, data.ChainCode, data.TxHash)
	tCryptoRechargeTxIdKey := fmt.Sprintf("%s%v", cacheTCryptoRechargeTxIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tCryptoRechargeTxRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.UserId, data.OrderId, data.OrderNo, data.Coin, data.ChainCode, data.TxHash, data.FromAddress, data.ToAddress, data.Memo, data.Amount, data.BlockHeight, data.ConfirmCount, data.RequiredConfirmCount, data.Status, data.RawData, data.CreateTimes, data.UpdateTimes)
	}, tCryptoRechargeTxChainCodeTxHashKey, tCryptoRechargeTxIdKey)
	return ret, err
}

func (m *defaultTCryptoRechargeTxModel) Update(ctx context.Context, newData *TCryptoRechargeTx) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tCryptoRechargeTxChainCodeTxHashKey := fmt.Sprintf("%s%v:%v", cacheTCryptoRechargeTxChainCodeTxHashPrefix, data.ChainCode, data.TxHash)
	tCryptoRechargeTxIdKey := fmt.Sprintf("%s%v", cacheTCryptoRechargeTxIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tCryptoRechargeTxRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.UserId, newData.OrderId, newData.OrderNo, newData.Coin, newData.ChainCode, newData.TxHash, newData.FromAddress, newData.ToAddress, newData.Memo, newData.Amount, newData.BlockHeight, newData.ConfirmCount, newData.RequiredConfirmCount, newData.Status, newData.RawData, newData.CreateTimes, newData.UpdateTimes, newData.Id)
	}, tCryptoRechargeTxChainCodeTxHashKey, tCryptoRechargeTxIdKey)
	return err
}

func (m *defaultTCryptoRechargeTxModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTCryptoRechargeTxIdPrefix, primary)
}

func (m *defaultTCryptoRechargeTxModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tCryptoRechargeTxRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTCryptoRechargeTxModel) tableName() string {
	return m.table
}
