// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tPayOutboxFieldNames          = builder.RawFieldNames(&TPayOutbox{})
	tPayOutboxRows                = strings.Join(tPayOutboxFieldNames, ",")
	tPayOutboxRowsExpectAutoSet   = strings.Join(stringx.Remove(tPayOutboxFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tPayOutboxRowsWithPlaceHolder = strings.Join(stringx.Remove(tPayOutboxFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTPayOutboxIdPrefix      = "cache:tPayOutbox:id:"
	cacheTPayOutboxEventNoPrefix = "cache:tPayOutbox:eventNo:"
)

type (
	tPayOutboxModel interface {
		Insert(ctx context.Context, data *TPayOutbox) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TPayOutbox, error)
		FindOneByEventNo(ctx context.Context, eventNo string) (*TPayOutbox, error)
		Update(ctx context.Context, data *TPayOutbox) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTPayOutboxModel struct {
		sqlc.CachedConn
		table string
	}

	TPayOutbox struct {
		Id            int64  `db:"id"`             // 主键ID
		EventNo       string `db:"event_no"`       // 事件唯一编号
		EventType     string `db:"event_type"`     // 事件类型
		AggregateType string `db:"aggregate_type"` // 聚合类型
		AggregateId   int64  `db:"aggregate_id"`   // 聚合ID
		AggregateNo   string `db:"aggregate_no"`   // 聚合业务号
		Payload       string `db:"payload"`        // 事件内容
		Status        int64  `db:"status"`         // 状态：1待处理 2处理中 3成功 4失败
		RetryCount    int64  `db:"retry_count"`    // 重试次数
		NextRetryAt   int64  `db:"next_retry_at"`  // 下次重试时间
		LastErrorMsg  string `db:"last_error_msg"` // 最近错误
		CreateTimes   int64  `db:"create_times"`   // 创建时间
		UpdateTimes   int64  `db:"update_times"`   // 更新时间
	}
)

func newTPayOutboxModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTPayOutboxModel {
	return &defaultTPayOutboxModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_pay_outbox`",
	}
}

func (m *defaultTPayOutboxModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tPayOutboxEventNoKey := fmt.Sprintf("%s%v", cacheTPayOutboxEventNoPrefix, data.EventNo)
	tPayOutboxIdKey := fmt.Sprintf("%s%v", cacheTPayOutboxIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tPayOutboxEventNoKey, tPayOutboxIdKey)
	return err
}

func (m *defaultTPayOutboxModel) FindOne(ctx context.Context, id int64) (*TPayOutbox, error) {
	tPayOutboxIdKey := fmt.Sprintf("%s%v", cacheTPayOutboxIdPrefix, id)
	var resp TPayOutbox
	err := m.QueryRowCtx(ctx, &resp, tPayOutboxIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tPayOutboxRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPayOutboxModel) FindOneByEventNo(ctx context.Context, eventNo string) (*TPayOutbox, error) {
	tPayOutboxEventNoKey := fmt.Sprintf("%s%v", cacheTPayOutboxEventNoPrefix, eventNo)
	var resp TPayOutbox
	err := m.QueryRowIndexCtx(ctx, &resp, tPayOutboxEventNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `event_no` = ? limit 1", tPayOutboxRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, eventNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPayOutboxModel) Insert(ctx context.Context, data *TPayOutbox) (sql.Result, error) {
	tPayOutboxEventNoKey := fmt.Sprintf("%s%v", cacheTPayOutboxEventNoPrefix, data.EventNo)
	tPayOutboxIdKey := fmt.Sprintf("%s%v", cacheTPayOutboxIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tPayOutboxRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.EventNo, data.EventType, data.AggregateType, data.AggregateId, data.AggregateNo, data.Payload, data.Status, data.RetryCount, data.NextRetryAt, data.LastErrorMsg, data.CreateTimes, data.UpdateTimes)
	}, tPayOutboxEventNoKey, tPayOutboxIdKey)
	return ret, err
}

func (m *defaultTPayOutboxModel) Update(ctx context.Context, newData *TPayOutbox) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tPayOutboxEventNoKey := fmt.Sprintf("%s%v", cacheTPayOutboxEventNoPrefix, data.EventNo)
	tPayOutboxIdKey := fmt.Sprintf("%s%v", cacheTPayOutboxIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tPayOutboxRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.EventNo, newData.EventType, newData.AggregateType, newData.AggregateId, newData.AggregateNo, newData.Payload, newData.Status, newData.RetryCount, newData.NextRetryAt, newData.LastErrorMsg, newData.CreateTimes, newData.UpdateTimes, newData.Id)
	}, tPayOutboxEventNoKey, tPayOutboxIdKey)
	return err
}

func (m *defaultTPayOutboxModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTPayOutboxIdPrefix, primary)
}

func (m *defaultTPayOutboxModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tPayOutboxRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTPayOutboxModel) tableName() string {
	return m.table
}
