// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tPayNotifyLogFieldNames          = builder.RawFieldNames(&TPayNotifyLog{})
	tPayNotifyLogRows                = strings.Join(tPayNotifyLogFieldNames, ",")
	tPayNotifyLogRowsExpectAutoSet   = strings.Join(stringx.Remove(tPayNotifyLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tPayNotifyLogRowsWithPlaceHolder = strings.Join(stringx.Remove(tPayNotifyLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTPayNotifyLogIdPrefix = "cache:tPayNotifyLog:id:"
)

type (
	tPayNotifyLogModel interface {
		Insert(ctx context.Context, data *TPayNotifyLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TPayNotifyLog, error)
		Update(ctx context.Context, data *TPayNotifyLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTPayNotifyLogModel struct {
		sqlc.CachedConn
		table string
	}

	TPayNotifyLog struct {
		Id            int64          `db:"id"`             // 回调日志ID
		TenantId      int64          `db:"tenant_id"`      // 租户ID
		OrderId       sql.NullInt64  `db:"order_id"`       // 支付订单ID
		OrderNo       sql.NullString `db:"order_no"`       // 平台订单号
		PlatformId    int64          `db:"platform_id"`    // 平台ID
		ChannelId     sql.NullInt64  `db:"channel_id"`     // 通道ID
		NotifyStatus  int64          `db:"notify_status"`  // 处理状态：1待处理 2成功 3失败
		NotifyBody    sql.NullString `db:"notify_body"`    // 回调原文
		SignResult    int64          `db:"sign_result"`    // 验签结果：0未验 1通过 2失败
		ProcessResult sql.NullString `db:"process_result"` // 处理结果
		ErrorMessage  sql.NullString `db:"error_message"`  // 错误信息
		NotifyTime    sql.NullTime   `db:"notify_time"`    // 回调时间
		CreateTime    time.Time      `db:"create_time"`    // 创建时间
	}
)

func newTPayNotifyLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTPayNotifyLogModel {
	return &defaultTPayNotifyLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_pay_notify_log`",
	}
}

func (m *defaultTPayNotifyLogModel) Delete(ctx context.Context, id int64) error {
	tPayNotifyLogIdKey := fmt.Sprintf("%s%v", cacheTPayNotifyLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tPayNotifyLogIdKey)
	return err
}

func (m *defaultTPayNotifyLogModel) FindOne(ctx context.Context, id int64) (*TPayNotifyLog, error) {
	tPayNotifyLogIdKey := fmt.Sprintf("%s%v", cacheTPayNotifyLogIdPrefix, id)
	var resp TPayNotifyLog
	err := m.QueryRowCtx(ctx, &resp, tPayNotifyLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tPayNotifyLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPayNotifyLogModel) Insert(ctx context.Context, data *TPayNotifyLog) (sql.Result, error) {
	tPayNotifyLogIdKey := fmt.Sprintf("%s%v", cacheTPayNotifyLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tPayNotifyLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.OrderId, data.OrderNo, data.PlatformId, data.ChannelId, data.NotifyStatus, data.NotifyBody, data.SignResult, data.ProcessResult, data.ErrorMessage, data.NotifyTime)
	}, tPayNotifyLogIdKey)
	return ret, err
}

func (m *defaultTPayNotifyLogModel) Update(ctx context.Context, data *TPayNotifyLog) error {
	tPayNotifyLogIdKey := fmt.Sprintf("%s%v", cacheTPayNotifyLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tPayNotifyLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TenantId, data.OrderId, data.OrderNo, data.PlatformId, data.ChannelId, data.NotifyStatus, data.NotifyBody, data.SignResult, data.ProcessResult, data.ErrorMessage, data.NotifyTime, data.Id)
	}, tPayNotifyLogIdKey)
	return err
}

func (m *defaultTPayNotifyLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTPayNotifyLogIdPrefix, primary)
}

func (m *defaultTPayNotifyLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tPayNotifyLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTPayNotifyLogModel) tableName() string {
	return m.table
}
