// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tPayOrderFieldNames          = builder.RawFieldNames(&TPayOrder{})
	tPayOrderRows                = strings.Join(tPayOrderFieldNames, ",")
	tPayOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(tPayOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tPayOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(tPayOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTPayOrderIdPrefix                 = "cache:tPayOrder:id:"
	cacheTPayOrderOrderNoPrefix            = "cache:tPayOrder:orderNo:"
	cacheTPayOrderTenantIdBizOrderNoPrefix = "cache:tPayOrder:tenantId:bizOrderNo:"
)

type (
	tPayOrderModel interface {
		Insert(ctx context.Context, data *TPayOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TPayOrder, error)
		FindOneByOrderNo(ctx context.Context, orderNo string) (*TPayOrder, error)
		FindOneByTenantIdBizOrderNo(ctx context.Context, tenantId int64, bizOrderNo sql.NullString) (*TPayOrder, error)
		Update(ctx context.Context, data *TPayOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTPayOrderModel struct {
		sqlc.CachedConn
		table string
	}

	TPayOrder struct {
		Id           int64          `db:"id"`             // 支付订单ID
		TenantId     int64          `db:"tenant_id"`      // 租户ID
		UserId       int64          `db:"user_id"`        // 用户ID
		OrderNo      string         `db:"order_no"`       // 平台订单号
		BizOrderNo   sql.NullString `db:"biz_order_no"`   // 业务订单号
		PlatformId   int64          `db:"platform_id"`    // 平台ID
		ProductId    int64          `db:"product_id"`     // 产品ID
		AccountId    int64          `db:"account_id"`     // 账号ID
		ChannelId    int64          `db:"channel_id"`     // 通道ID
		Currency     string         `db:"currency"`       // 币种
		OrderAmount  int64          `db:"order_amount"`   // 订单金额，单位分
		PayAmount    int64          `db:"pay_amount"`     // 实际支付金额，单位分
		FeeAmount    int64          `db:"fee_amount"`     // 手续费金额，单位分
		Subject      sql.NullString `db:"subject"`        // 标题
		Body         sql.NullString `db:"body"`           // 描述
		ClientType   int64          `db:"client_type"`    // 客户端类型：1APP 2H5 3WEB
		ClientIp     sql.NullString `db:"client_ip"`      // 客户端IP
		Status       int64          `db:"status"`         // 状态：1待支付 2支付中 3成功 4失败 5已关闭 6已退款
		ThirdTradeNo sql.NullString `db:"third_trade_no"` // 三方交易号
		ThirdOrderNo sql.NullString `db:"third_order_no"` // 三方订单号
		PayUrl       sql.NullString `db:"pay_url"`        // 支付链接
		QrContent    sql.NullString `db:"qr_content"`     // 二维码内容
		RequestData  sql.NullString `db:"request_data"`   // 请求快照
		ResponseData sql.NullString `db:"response_data"`  // 响应快照
		NotifyData   sql.NullString `db:"notify_data"`    // 回调数据
		ExpireTime   sql.NullTime   `db:"expire_time"`    // 过期时间
		PaidTime     sql.NullTime   `db:"paid_time"`      // 支付时间
		NotifyTime   sql.NullTime   `db:"notify_time"`    // 回调时间
		CloseTime    sql.NullTime   `db:"close_time"`     // 关闭时间
		Remark       sql.NullString `db:"remark"`         // 备注
		CreateTime   time.Time      `db:"create_time"`    // 创建时间
		UpdateTime   time.Time      `db:"update_time"`    // 更新时间
	}
)

func newTPayOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTPayOrderModel {
	return &defaultTPayOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_pay_order`",
	}
}

func (m *defaultTPayOrderModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tPayOrderIdKey := fmt.Sprintf("%s%v", cacheTPayOrderIdPrefix, id)
	tPayOrderOrderNoKey := fmt.Sprintf("%s%v", cacheTPayOrderOrderNoPrefix, data.OrderNo)
	tPayOrderTenantIdBizOrderNoKey := fmt.Sprintf("%s%v:%v", cacheTPayOrderTenantIdBizOrderNoPrefix, data.TenantId, data.BizOrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tPayOrderIdKey, tPayOrderOrderNoKey, tPayOrderTenantIdBizOrderNoKey)
	return err
}

func (m *defaultTPayOrderModel) FindOne(ctx context.Context, id int64) (*TPayOrder, error) {
	tPayOrderIdKey := fmt.Sprintf("%s%v", cacheTPayOrderIdPrefix, id)
	var resp TPayOrder
	err := m.QueryRowCtx(ctx, &resp, tPayOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tPayOrderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPayOrderModel) FindOneByOrderNo(ctx context.Context, orderNo string) (*TPayOrder, error) {
	tPayOrderOrderNoKey := fmt.Sprintf("%s%v", cacheTPayOrderOrderNoPrefix, orderNo)
	var resp TPayOrder
	err := m.QueryRowIndexCtx(ctx, &resp, tPayOrderOrderNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", tPayOrderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, orderNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPayOrderModel) FindOneByTenantIdBizOrderNo(ctx context.Context, tenantId int64, bizOrderNo sql.NullString) (*TPayOrder, error) {
	tPayOrderTenantIdBizOrderNoKey := fmt.Sprintf("%s%v:%v", cacheTPayOrderTenantIdBizOrderNoPrefix, tenantId, bizOrderNo)
	var resp TPayOrder
	err := m.QueryRowIndexCtx(ctx, &resp, tPayOrderTenantIdBizOrderNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `biz_order_no` = ? limit 1", tPayOrderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, bizOrderNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPayOrderModel) Insert(ctx context.Context, data *TPayOrder) (sql.Result, error) {
	tPayOrderIdKey := fmt.Sprintf("%s%v", cacheTPayOrderIdPrefix, data.Id)
	tPayOrderOrderNoKey := fmt.Sprintf("%s%v", cacheTPayOrderOrderNoPrefix, data.OrderNo)
	tPayOrderTenantIdBizOrderNoKey := fmt.Sprintf("%s%v:%v", cacheTPayOrderTenantIdBizOrderNoPrefix, data.TenantId, data.BizOrderNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tPayOrderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.UserId, data.OrderNo, data.BizOrderNo, data.PlatformId, data.ProductId, data.AccountId, data.ChannelId, data.Currency, data.OrderAmount, data.PayAmount, data.FeeAmount, data.Subject, data.Body, data.ClientType, data.ClientIp, data.Status, data.ThirdTradeNo, data.ThirdOrderNo, data.PayUrl, data.QrContent, data.RequestData, data.ResponseData, data.NotifyData, data.ExpireTime, data.PaidTime, data.NotifyTime, data.CloseTime, data.Remark)
	}, tPayOrderIdKey, tPayOrderOrderNoKey, tPayOrderTenantIdBizOrderNoKey)
	return ret, err
}

func (m *defaultTPayOrderModel) Update(ctx context.Context, newData *TPayOrder) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tPayOrderIdKey := fmt.Sprintf("%s%v", cacheTPayOrderIdPrefix, data.Id)
	tPayOrderOrderNoKey := fmt.Sprintf("%s%v", cacheTPayOrderOrderNoPrefix, data.OrderNo)
	tPayOrderTenantIdBizOrderNoKey := fmt.Sprintf("%s%v:%v", cacheTPayOrderTenantIdBizOrderNoPrefix, data.TenantId, data.BizOrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tPayOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.UserId, newData.OrderNo, newData.BizOrderNo, newData.PlatformId, newData.ProductId, newData.AccountId, newData.ChannelId, newData.Currency, newData.OrderAmount, newData.PayAmount, newData.FeeAmount, newData.Subject, newData.Body, newData.ClientType, newData.ClientIp, newData.Status, newData.ThirdTradeNo, newData.ThirdOrderNo, newData.PayUrl, newData.QrContent, newData.RequestData, newData.ResponseData, newData.NotifyData, newData.ExpireTime, newData.PaidTime, newData.NotifyTime, newData.CloseTime, newData.Remark, newData.Id)
	}, tPayOrderIdKey, tPayOrderOrderNoKey, tPayOrderTenantIdBizOrderNoKey)
	return err
}

func (m *defaultTPayOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTPayOrderIdPrefix, primary)
}

func (m *defaultTPayOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tPayOrderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTPayOrderModel) tableName() string {
	return m.table
}
