-- 开发阶段破坏性迁移：不保留旧结构和数据。
-- 删除完成后，执行 services/trade/trade.sql 创建最终结构。
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `t_contract_delivery_settlement`;
DROP TABLE IF EXISTS `t_contract_funding_settlement`;
DROP TABLE IF EXISTS `t_trade_settlement_instruction`;
DROP TABLE IF EXISTS `t_trade_asset_reservation`;
DROP TABLE IF EXISTS `t_trade_event_inbox`;
DROP TABLE IF EXISTS `t_biz_trade_event`;
DROP TABLE IF EXISTS `t_risk_order_check_log`;
DROP TABLE IF EXISTS `t_risk_user_symbol_limit`;
DROP TABLE IF EXISTS `t_risk_user_trade_limit`;
DROP TABLE IF EXISTS `t_trade_symbol_leverage_default`;
DROP TABLE IF EXISTS `t_trade_symbol_leverage_config`;
DROP TABLE IF EXISTS `t_contract_leverage_config`;
DROP TABLE IF EXISTS `t_contract_position_history`;
DROP TABLE IF EXISTS `t_contract_margin_snapshot`;
DROP TABLE IF EXISTS `t_contract_position`;
DROP TABLE IF EXISTS `t_trade_cancel_log`;
DROP TABLE IF EXISTS `t_trade_fill`;
DROP TABLE IF EXISTS `t_trade_order_seconds`;
DROP TABLE IF EXISTS `t_trade_order_contract`;
DROP TABLE IF EXISTS `t_trade_order_spot`;
DROP TABLE IF EXISTS `t_trade_order`;
DROP TABLE IF EXISTS `t_contract_user_config`;
DROP TABLE IF EXISTS `t_trade_user_config`;
DROP TABLE IF EXISTS `t_trade_symbol_session`;
DROP TABLE IF EXISTS `t_trade_symbol_seconds`;
DROP TABLE IF EXISTS `t_trade_symbol_contract`;
DROP TABLE IF EXISTS `t_trade_symbol_spot`;
DROP TABLE IF EXISTS `t_trade_symbol`;
SET FOREIGN_KEY_CHECKS = 1;
