<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { liquidityApi } from "@/api/liquidity";
import type { SymbolConfig } from "@/types/liquidity";
const loading=ref(false), dialog=ref(false), rows=ref<SymbolConfig[]>([]);
const query=reactive({tenantId:1,keyword:"",status:"",limit:20});
const form=reactive({tenantId:1,symbolId:0,liquidityMode:1,internalProviderId:0,externalProviderId:0,externalSymbol:"",referencePriceSource:"price-engine",referencePriceKind:"MARK",quoteValidityMs:3000,refreshIntervalMs:1000,quoteTtlMs:5000,repriceThresholdBps:"2",baseSpreadBps:"5",maxSpreadBps:"20",maxPriceDeviationBps:"50",minQuoteQty:"0.001",maxQuoteQty:"1",maxQuoteNotional:"100000",targetBaseInventory:"0",minBaseInventory:"-10",maxBaseInventory:"10",maxNetExposure:"10",maxDailyNotional:"1000000",inventorySkewBps:"2",hedgeThreshold:"1",hedgeRatio:"1",selfTradePrevention:1});
async function load(){loading.value=true;try{const r=await liquidityApi.symbolConfigs(query);rows.value=(r.data||[]) as unknown as SymbolConfig[]}finally{loading.value=false}}
async function create(){await liquidityApi.createSymbolConfig(form);ElMessage.success("策略配置已创建");dialog.value=false;await load()}
async function action(row:SymbolConfig,type:"start"|"pause"|"stop"){await liquidityApi.symbolAction(row.id,type);ElMessage.success("操作已提交");await load()}
const mode=(v:number)=>["未知","内部做市","外部路由","内部做市 + 外部对冲"][v]||"未知";
const status=(v:number)=>["未知","运行中","已停用","已暂停","已熔断"][v]||"未知";
onMounted(load);
</script>
<template>
  <div class="page-head"><div><h1>交易对策略</h1><p>配置现货、交割与永续合约的报价和对冲参数</p></div><el-button type="primary" @click="dialog=true">＋ 新建策略</el-button></div>
  <section class="panel"><div class="toolbar"><el-input v-model="query.keyword" placeholder="交易对 / 外部交易对" clearable style="width:260px"/><el-select v-model="query.status" clearable placeholder="全部状态" style="width:150px"><el-option label="运行中" :value="1"/><el-option label="已停用" :value="2"/><el-option label="已暂停" :value="3"/><el-option label="已熔断" :value="4"/></el-select><el-button @click="load">查询</el-button></div>
  <div class="table-wrap"><el-table :data="rows" v-loading="loading"><el-table-column label="交易对" min-width="140"><template #default="{row}"><b>{{ row.symbol||`#${row.symbolId}` }}</b></template></el-table-column><el-table-column label="产品" width="110"><template #default="{row}">{{ ["未知","现货","合约","秒合约"][row.productType] }}</template></el-table-column><el-table-column label="流动性模式" min-width="190"><template #default="{row}">{{ mode(row.liquidityMode) }}</template></el-table-column><el-table-column prop="referencePriceSource" label="参考价格源" width="150"/><el-table-column label="点差(BPS)" width="120"><template #default="{row}">{{ row.baseSpreadBps }} / {{ row.maxSpreadBps }}</template></el-table-column><el-table-column prop="refreshIntervalMs" label="刷新间隔(ms)" width="125"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="row.status===1?'success':row.status===4?'danger':'warning'">{{ status(row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" fixed="right" width="210"><template #default="{row}"><el-button link type="success" @click="action(row,'start')">启动</el-button><el-button link type="warning" @click="action(row,'pause')">暂停</el-button><el-button link type="danger" @click="action(row,'stop')">停止</el-button></template></el-table-column></el-table></div></section>
  <el-dialog v-model="dialog" title="新建交易对流动性策略" width="760px"><el-form :model="form" label-width="130px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="交易对 ID"><el-input-number v-model="form.symbolId" :min="1"/></el-form-item></el-col><el-col :span="12"><el-form-item label="流动性模式"><el-select v-model="form.liquidityMode"><el-option label="内部做市" :value="1"/><el-option label="外部路由" :value="2"/><el-option label="内部做市 + 外部对冲" :value="3"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="内部提供方 ID"><el-input-number v-model="form.internalProviderId" :min="0"/></el-form-item></el-col><el-col :span="12"><el-form-item label="外部提供方 ID"><el-input-number v-model="form.externalProviderId" :min="0"/></el-form-item></el-col><el-col :span="12"><el-form-item label="外部交易对"><el-input v-model="form.externalSymbol" placeholder="BTCUSDT"/></el-form-item></el-col><el-col :span="12"><el-form-item label="参考价格类型"><el-input v-model="form.referencePriceKind"/></el-form-item></el-col><el-col :span="8"><el-form-item label="基础点差(BPS)"><el-input v-model="form.baseSpreadBps"/></el-form-item></el-col><el-col :span="8"><el-form-item label="最大点差(BPS)"><el-input v-model="form.maxSpreadBps"/></el-form-item></el-col><el-col :span="8"><el-form-item label="刷新间隔(ms)"><el-input-number v-model="form.refreshIntervalMs" :min="100"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="create">创建策略</el-button></template></el-dialog>
</template>
