// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tRiskOrderCheckLogFieldNames          = builder.RawFieldNames(&TRiskOrderCheckLog{})
	tRiskOrderCheckLogRows                = strings.Join(tRiskOrderCheckLogFieldNames, ",")
	tRiskOrderCheckLogRowsExpectAutoSet   = strings.Join(stringx.Remove(tRiskOrderCheckLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tRiskOrderCheckLogRowsWithPlaceHolder = strings.Join(stringx.Remove(tRiskOrderCheckLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTRiskOrderCheckLogIdPrefix = "cache:tRiskOrderCheckLog:id:"
)

type (
	tRiskOrderCheckLogModel interface {
		Insert(ctx context.Context, data *TRiskOrderCheckLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TRiskOrderCheckLog, error)
		Update(ctx context.Context, data *TRiskOrderCheckLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTRiskOrderCheckLogModel struct {
		sqlc.CachedConn
		table string
	}

	TRiskOrderCheckLog struct {
		Id            uint64         `db:"id"`              // 主键ID
		TenantId      uint64         `db:"tenant_id"`       // 租户ID
		OrderNo       string         `db:"order_no"`        // 平台订单号
		ClientOrderId string         `db:"client_order_id"` // 客户端订单号
		UserId        uint64         `db:"user_id"`         // 用户ID
		SymbolId      uint64         `db:"symbol_id"`       // 交易标的ID
		MarketType    int64          `db:"market_type"`     // 市场类型：1现货 2秒合约 3U本位 4币本位
		CheckType     int64          `db:"check_type"`      // 检查类型：1余额检查 2保证金检查 3仓位检查 4交易权限检查 5价格保护检查 6数量限制检查 7名义价值限制检查 8频率限制检查
		CheckResult   int64          `db:"check_result"`    // 检查结果：1通过 2拒绝 3告警放行
		RejectCode    string         `db:"reject_code"`     // 拒绝码
		RejectMsg     string         `db:"reject_msg"`      // 拒绝原因描述
		RequestPrice  float64        `db:"request_price"`   // 请求价格
		RequestQty    float64        `db:"request_qty"`     // 请求数量
		RequestAmount float64        `db:"request_amount"`  // 请求名义价值或金额
		OperatorId    uint64         `db:"operator_id"`     // 操作人ID，系统操作时可为0
		Source        int64          `db:"source"`          // 来源：1系统 2用户 3后台管理 4任务
		CheckSnapshot sql.NullString `db:"check_snapshot"`  // 检查时的上下文快照，JSON格式
		CreateTimes   int64          `db:"create_times"`    // 创建时间，毫秒时间戳
	}
)

func newTRiskOrderCheckLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTRiskOrderCheckLogModel {
	return &defaultTRiskOrderCheckLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_risk_order_check_log`",
	}
}

func (m *defaultTRiskOrderCheckLogModel) Delete(ctx context.Context, id uint64) error {
	tRiskOrderCheckLogIdKey := fmt.Sprintf("%s%v", cacheTRiskOrderCheckLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tRiskOrderCheckLogIdKey)
	return err
}

func (m *defaultTRiskOrderCheckLogModel) FindOne(ctx context.Context, id uint64) (*TRiskOrderCheckLog, error) {
	tRiskOrderCheckLogIdKey := fmt.Sprintf("%s%v", cacheTRiskOrderCheckLogIdPrefix, id)
	var resp TRiskOrderCheckLog
	err := m.QueryRowCtx(ctx, &resp, tRiskOrderCheckLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tRiskOrderCheckLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTRiskOrderCheckLogModel) Insert(ctx context.Context, data *TRiskOrderCheckLog) (sql.Result, error) {
	tRiskOrderCheckLogIdKey := fmt.Sprintf("%s%v", cacheTRiskOrderCheckLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tRiskOrderCheckLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.OrderNo, data.ClientOrderId, data.UserId, data.SymbolId, data.MarketType, data.CheckType, data.CheckResult, data.RejectCode, data.RejectMsg, data.RequestPrice, data.RequestQty, data.RequestAmount, data.OperatorId, data.Source, data.CheckSnapshot, data.CreateTimes)
	}, tRiskOrderCheckLogIdKey)
	return ret, err
}

func (m *defaultTRiskOrderCheckLogModel) Update(ctx context.Context, data *TRiskOrderCheckLog) error {
	tRiskOrderCheckLogIdKey := fmt.Sprintf("%s%v", cacheTRiskOrderCheckLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tRiskOrderCheckLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TenantId, data.OrderNo, data.ClientOrderId, data.UserId, data.SymbolId, data.MarketType, data.CheckType, data.CheckResult, data.RejectCode, data.RejectMsg, data.RequestPrice, data.RequestQty, data.RequestAmount, data.OperatorId, data.Source, data.CheckSnapshot, data.CreateTimes, data.Id)
	}, tRiskOrderCheckLogIdKey)
	return err
}

func (m *defaultTRiskOrderCheckLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTRiskOrderCheckLogIdPrefix, primary)
}

func (m *defaultTRiskOrderCheckLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tRiskOrderCheckLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTRiskOrderCheckLogModel) tableName() string {
	return m.table
}
