// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/shopspring/decimal"
)

var (
	tTradeSymbolFieldNames          = builder.RawFieldNames(&TTradeSymbol{})
	tTradeSymbolRows                = strings.Join(tTradeSymbolFieldNames, ",")
	tTradeSymbolRowsExpectAutoSet   = strings.Join(stringx.Remove(tTradeSymbolFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTradeSymbolRowsWithPlaceHolder = strings.Join(stringx.Remove(tTradeSymbolFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTTradeSymbolIdPrefix                                                     = "cache:tTradeSymbol:id:"
	cacheTTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypePrefix = "cache:tTradeSymbol:tenantId:symbol:productType:contractType:contractValueType:"
)

type (
	tTradeSymbolModel interface {
		Insert(ctx context.Context, data *TTradeSymbol) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTradeSymbol, error)
		FindOneByTenantIdSymbolProductTypeContractTypeContractValueType(ctx context.Context, tenantId int64, symbol string, productType int64, contractType int64, contractValueType int64) (*TTradeSymbol, error)
		Update(ctx context.Context, data *TTradeSymbol) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTradeSymbolModel struct {
		sqlc.CachedConn
		table string
	}

	TTradeSymbol struct {
		Id                int64           `db:"id"`                  // 主键ID
		TenantId          int64           `db:"tenant_id"`           // 租户ID
		Symbol            string          `db:"symbol"`              // 统一交易标的代码，如BTCUSDT、ETHUSD-PERP
		DisplaySymbol     string          `db:"display_symbol"`      // 前端展示名称
		ProductType       int64           `db:"product_type"`        // 产品大类：1现货 2衍生品 3秒合约
		BaseAsset         string          `db:"base_asset"`          // 基础资产，例如BTC
		QuoteAsset        string          `db:"quote_asset"`         // 计价资产，例如USDT
		SettleAsset       string          `db:"settle_asset"`        // 结算资产，现货一般等于quote_asset
		MarginAsset       string          `db:"margin_asset"`        // 保证金资产；现货为空，U本位为稳定币，币本位为基础币
		ContractType      int64           `db:"contract_type"`       // 合约期限类型：0不适用 1永续 2交割
		ContractValueType int64           `db:"contract_value_type"` // 合约价值类型：0不适用 1线性 2反向
		Status            int64           `db:"status"`              // 交易状态：1启用 2禁用 3仅平仓
		PriceScale        int64           `db:"price_scale"`         // 价格精度，小数位数
		QtyScale          int64           `db:"qty_scale"`           // 数量精度，小数位数
		MinPrice          decimal.Decimal `db:"min_price"`           // 最小下单价格
		MaxPrice          decimal.Decimal `db:"max_price"`           // 最大下单价格
		PriceTick         decimal.Decimal `db:"price_tick"`          // 价格步长
		MinQty            decimal.Decimal `db:"min_qty"`             // 最小下单数量
		MaxQty            decimal.Decimal `db:"max_qty"`             // 最大下单数量
		QtyStep           decimal.Decimal `db:"qty_step"`            // 数量步长
		MinNotional       decimal.Decimal `db:"min_notional"`        // 最小名义价值
		MaxNotional       decimal.Decimal `db:"max_notional"`        // 最大名义价值，0表示不限
		ListingTime       int64           `db:"listing_time"`        // 产品上线时间，毫秒时间戳，0表示不限
		TradingStartTime  int64           `db:"trading_start_time"`  // 开始交易时间，毫秒时间戳，0表示不限
		TradingEndTime    int64           `db:"trading_end_time"`    // 停止交易时间，毫秒时间戳，0表示不限
		Sort              int64           `db:"sort"`                // 排序值，越小越靠前
		Remark            string          `db:"remark"`              // 备注
		CreateTimes       int64           `db:"create_times"`        // 创建时间，毫秒时间戳
		UpdateTimes       int64           `db:"update_times"`        // 更新时间，毫秒时间戳
	}
)

func newTTradeSymbolModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTTradeSymbolModel {
	return &defaultTTradeSymbolModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_trade_symbol`",
	}
}

func (m *defaultTTradeSymbolModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tTradeSymbolIdKey := fmt.Sprintf("%s%v", cacheTTradeSymbolIdPrefix, id)
	tTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypeKey := fmt.Sprintf("%s%v:%v:%v:%v:%v", cacheTTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypePrefix, data.TenantId, data.Symbol, data.ProductType, data.ContractType, data.ContractValueType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tTradeSymbolIdKey, tTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypeKey)
	return err
}

func (m *defaultTTradeSymbolModel) FindOne(ctx context.Context, id int64) (*TTradeSymbol, error) {
	tTradeSymbolIdKey := fmt.Sprintf("%s%v", cacheTTradeSymbolIdPrefix, id)
	var resp TTradeSymbol
	err := m.QueryRowCtx(ctx, &resp, tTradeSymbolIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTradeSymbolRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTradeSymbolModel) FindOneByTenantIdSymbolProductTypeContractTypeContractValueType(ctx context.Context, tenantId int64, symbol string, productType int64, contractType int64, contractValueType int64) (*TTradeSymbol, error) {
	tTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypeKey := fmt.Sprintf("%s%v:%v:%v:%v:%v", cacheTTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypePrefix, tenantId, symbol, productType, contractType, contractValueType)
	var resp TTradeSymbol
	err := m.QueryRowIndexCtx(ctx, &resp, tTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `symbol` = ? and `product_type` = ? and `contract_type` = ? and `contract_value_type` = ? limit 1", tTradeSymbolRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, symbol, productType, contractType, contractValueType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTradeSymbolModel) Insert(ctx context.Context, data *TTradeSymbol) (sql.Result, error) {
	tTradeSymbolIdKey := fmt.Sprintf("%s%v", cacheTTradeSymbolIdPrefix, data.Id)
	tTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypeKey := fmt.Sprintf("%s%v:%v:%v:%v:%v", cacheTTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypePrefix, data.TenantId, data.Symbol, data.ProductType, data.ContractType, data.ContractValueType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tTradeSymbolRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.Symbol, data.DisplaySymbol, data.ProductType, data.BaseAsset, data.QuoteAsset, data.SettleAsset, data.MarginAsset, data.ContractType, data.ContractValueType, data.Status, data.PriceScale, data.QtyScale, data.MinPrice, data.MaxPrice, data.PriceTick, data.MinQty, data.MaxQty, data.QtyStep, data.MinNotional, data.MaxNotional, data.ListingTime, data.TradingStartTime, data.TradingEndTime, data.Sort, data.Remark, data.CreateTimes, data.UpdateTimes)
	}, tTradeSymbolIdKey, tTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypeKey)
	return ret, err
}

func (m *defaultTTradeSymbolModel) Update(ctx context.Context, newData *TTradeSymbol) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tTradeSymbolIdKey := fmt.Sprintf("%s%v", cacheTTradeSymbolIdPrefix, data.Id)
	tTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypeKey := fmt.Sprintf("%s%v:%v:%v:%v:%v", cacheTTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypePrefix, data.TenantId, data.Symbol, data.ProductType, data.ContractType, data.ContractValueType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTradeSymbolRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.Symbol, newData.DisplaySymbol, newData.ProductType, newData.BaseAsset, newData.QuoteAsset, newData.SettleAsset, newData.MarginAsset, newData.ContractType, newData.ContractValueType, newData.Status, newData.PriceScale, newData.QtyScale, newData.MinPrice, newData.MaxPrice, newData.PriceTick, newData.MinQty, newData.MaxQty, newData.QtyStep, newData.MinNotional, newData.MaxNotional, newData.ListingTime, newData.TradingStartTime, newData.TradingEndTime, newData.Sort, newData.Remark, newData.CreateTimes, newData.UpdateTimes, newData.Id)
	}, tTradeSymbolIdKey, tTradeSymbolTenantIdSymbolProductTypeContractTypeContractValueTypeKey)
	return err
}

func (m *defaultTTradeSymbolModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTTradeSymbolIdPrefix, primary)
}

func (m *defaultTTradeSymbolModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTradeSymbolRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTTradeSymbolModel) tableName() string {
	return m.table
}
