// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/shopspring/decimal"
)

var (
	tTradeOrderSecondsFieldNames          = builder.RawFieldNames(&TTradeOrderSeconds{})
	tTradeOrderSecondsRows                = strings.Join(tTradeOrderSecondsFieldNames, ",")
	tTradeOrderSecondsRowsExpectAutoSet   = strings.Join(stringx.Remove(tTradeOrderSecondsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTradeOrderSecondsRowsWithPlaceHolder = strings.Join(stringx.Remove(tTradeOrderSecondsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTTradeOrderSecondsIdPrefix              = "cache:tTradeOrderSeconds:id:"
	cacheTTradeOrderSecondsTenantIdOrderIdPrefix = "cache:tTradeOrderSeconds:tenantId:orderId:"
)

type (
	tTradeOrderSecondsModel interface {
		Insert(ctx context.Context, data *TTradeOrderSeconds) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTradeOrderSeconds, error)
		FindOneByTenantIdOrderId(ctx context.Context, tenantId int64, orderId int64) (*TTradeOrderSeconds, error)
		Update(ctx context.Context, data *TTradeOrderSeconds) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTradeOrderSecondsModel struct {
		sqlc.CachedConn
		table string
	}

	TTradeOrderSeconds struct {
		Id                    int64           `db:"id"`                      // 主键ID
		TenantId              int64           `db:"tenant_id"`               // 租户ID
		OrderId               int64           `db:"order_id"`                // 订单ID
		Direction             int64           `db:"direction"`               // 方向：1看涨 2看跌
		DurationSeconds       int64           `db:"duration_seconds"`        // 到期周期秒数
		StakeAsset            string          `db:"stake_asset"`             // 本金资产
		StakeAmount           decimal.Decimal `db:"stake_amount"`            // 本金金额
		PayoutRate            decimal.Decimal `db:"payout_rate"`             // 下单时锁定的收益率
		FeeRate               decimal.Decimal `db:"fee_rate"`                // 下单时锁定的手续费率
		FrozenAt              int64           `db:"frozen_at"`               // 本金冻结成功时间
		ActivatedAt           int64           `db:"activated_at"`            // 起始价锁定并激活时间
		StartPrice            decimal.Decimal `db:"start_price"`             // 起始价格
		StartPriceTime        int64           `db:"start_price_time"`        // 起始价格时间
		StartPriceSource      string          `db:"start_price_source"`      // 起始价格来源快照
		ExpireTime            int64           `db:"expire_time"`             // 到期时间
		SettlementPrice       decimal.Decimal `db:"settlement_price"`        // 结算价格
		SettlementPriceTime   int64           `db:"settlement_price_time"`   // 结算价格时间
		SettlementPriceSource string          `db:"settlement_price_source"` // 结算价格来源快照
		PriceAlgorithm        string          `db:"price_algorithm"`         // 结算采样算法及版本快照
		Result                int64           `db:"result"`                  // 结果：0待定 1胜 2负 3平 4作废
		ProfitAmount          decimal.Decimal `db:"profit_amount"`           // 盈利金额，不含返还本金
		FeeAmount             decimal.Decimal `db:"fee_amount"`              // 手续费金额
		ReturnAmount          decimal.Decimal `db:"return_amount"`           // 最终返还本金及收益总额
		SettlementStatus      int64           `db:"settlement_status"`       // 流程状态：0待冻结 1激活中 2进行中 3结算中 4已结算 5退款中 6已退款 7人工处理
		ReservationNo         string          `db:"reservation_no"`          // Asset资金预占号
		SettlementReason      string          `db:"settlement_reason"`       // 结算、作废、退款或人工处理原因
		SettledAt             int64           `db:"settled_at"`              // 结算或退款完成时间
		Version               int64           `db:"version"`                 // 并发状态转移版本号
		CreateTimes           int64           `db:"create_times"`            // 创建时间
		UpdateTimes           int64           `db:"update_times"`            // 更新时间
	}
)

func newTTradeOrderSecondsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTTradeOrderSecondsModel {
	return &defaultTTradeOrderSecondsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_trade_order_seconds`",
	}
}

func (m *defaultTTradeOrderSecondsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tTradeOrderSecondsIdKey := fmt.Sprintf("%s%v", cacheTTradeOrderSecondsIdPrefix, id)
	tTradeOrderSecondsTenantIdOrderIdKey := fmt.Sprintf("%s%v:%v", cacheTTradeOrderSecondsTenantIdOrderIdPrefix, data.TenantId, data.OrderId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tTradeOrderSecondsIdKey, tTradeOrderSecondsTenantIdOrderIdKey)
	return err
}

func (m *defaultTTradeOrderSecondsModel) FindOne(ctx context.Context, id int64) (*TTradeOrderSeconds, error) {
	tTradeOrderSecondsIdKey := fmt.Sprintf("%s%v", cacheTTradeOrderSecondsIdPrefix, id)
	var resp TTradeOrderSeconds
	err := m.QueryRowCtx(ctx, &resp, tTradeOrderSecondsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTradeOrderSecondsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTradeOrderSecondsModel) FindOneByTenantIdOrderId(ctx context.Context, tenantId int64, orderId int64) (*TTradeOrderSeconds, error) {
	tTradeOrderSecondsTenantIdOrderIdKey := fmt.Sprintf("%s%v:%v", cacheTTradeOrderSecondsTenantIdOrderIdPrefix, tenantId, orderId)
	var resp TTradeOrderSeconds
	err := m.QueryRowIndexCtx(ctx, &resp, tTradeOrderSecondsTenantIdOrderIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `order_id` = ? limit 1", tTradeOrderSecondsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, orderId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTradeOrderSecondsModel) Insert(ctx context.Context, data *TTradeOrderSeconds) (sql.Result, error) {
	tTradeOrderSecondsIdKey := fmt.Sprintf("%s%v", cacheTTradeOrderSecondsIdPrefix, data.Id)
	tTradeOrderSecondsTenantIdOrderIdKey := fmt.Sprintf("%s%v:%v", cacheTTradeOrderSecondsTenantIdOrderIdPrefix, data.TenantId, data.OrderId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tTradeOrderSecondsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.OrderId, data.Direction, data.DurationSeconds, data.StakeAsset, data.StakeAmount, data.PayoutRate, data.FeeRate, data.FrozenAt, data.ActivatedAt, data.StartPrice, data.StartPriceTime, data.StartPriceSource, data.ExpireTime, data.SettlementPrice, data.SettlementPriceTime, data.SettlementPriceSource, data.PriceAlgorithm, data.Result, data.ProfitAmount, data.FeeAmount, data.ReturnAmount, data.SettlementStatus, data.ReservationNo, data.SettlementReason, data.SettledAt, data.Version, data.CreateTimes, data.UpdateTimes)
	}, tTradeOrderSecondsIdKey, tTradeOrderSecondsTenantIdOrderIdKey)
	return ret, err
}

func (m *defaultTTradeOrderSecondsModel) Update(ctx context.Context, newData *TTradeOrderSeconds) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tTradeOrderSecondsIdKey := fmt.Sprintf("%s%v", cacheTTradeOrderSecondsIdPrefix, data.Id)
	tTradeOrderSecondsTenantIdOrderIdKey := fmt.Sprintf("%s%v:%v", cacheTTradeOrderSecondsTenantIdOrderIdPrefix, data.TenantId, data.OrderId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTradeOrderSecondsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.OrderId, newData.Direction, newData.DurationSeconds, newData.StakeAsset, newData.StakeAmount, newData.PayoutRate, newData.FeeRate, newData.FrozenAt, newData.ActivatedAt, newData.StartPrice, newData.StartPriceTime, newData.StartPriceSource, newData.ExpireTime, newData.SettlementPrice, newData.SettlementPriceTime, newData.SettlementPriceSource, newData.PriceAlgorithm, newData.Result, newData.ProfitAmount, newData.FeeAmount, newData.ReturnAmount, newData.SettlementStatus, newData.ReservationNo, newData.SettlementReason, newData.SettledAt, newData.Version, newData.CreateTimes, newData.UpdateTimes, newData.Id)
	}, tTradeOrderSecondsIdKey, tTradeOrderSecondsTenantIdOrderIdKey)
	return err
}

func (m *defaultTTradeOrderSecondsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTTradeOrderSecondsIdPrefix, primary)
}

func (m *defaultTTradeOrderSecondsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTradeOrderSecondsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTTradeOrderSecondsModel) tableName() string {
	return m.table
}
