// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: asset.proto

package server

import (
	"context"

	"wklive/proto/asset"
	"wklive/services/asset/internal/logic/admin"
	"wklive/services/asset/internal/svc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	asset.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// 创建APP资产操作币种显示配置
func (s *AdminServer) CreateAssetCoinConfig(ctx context.Context, in *asset.CreateAssetCoinConfigReq) (*asset.AssetCoinConfigResp, error) {
	l := adminlogic.NewCreateAssetCoinConfigLogic(ctx, s.svcCtx)
	return l.CreateAssetCoinConfig(in)
}

// 更新APP资产操作币种显示配置
func (s *AdminServer) UpdateAssetCoinConfig(ctx context.Context, in *asset.UpdateAssetCoinConfigReq) (*asset.AssetCoinConfigResp, error) {
	l := adminlogic.NewUpdateAssetCoinConfigLogic(ctx, s.svcCtx)
	return l.UpdateAssetCoinConfig(in)
}

// 删除APP资产操作币种显示配置
func (s *AdminServer) DeleteAssetCoinConfig(ctx context.Context, in *asset.DeleteAssetCoinConfigReq) (*asset.DeleteAssetCoinConfigResp, error) {
	l := adminlogic.NewDeleteAssetCoinConfigLogic(ctx, s.svcCtx)
	return l.DeleteAssetCoinConfig(in)
}

// 查询APP资产操作币种显示配置详情
func (s *AdminServer) GetAssetCoinConfig(ctx context.Context, in *asset.GetAssetCoinConfigReq) (*asset.AssetCoinConfigResp, error) {
	l := adminlogic.NewGetAssetCoinConfigLogic(ctx, s.svcCtx)
	return l.GetAssetCoinConfig(in)
}

// 分页查询APP资产操作币种显示配置
func (s *AdminServer) PageAssetCoinConfigs(ctx context.Context, in *asset.PageAssetCoinConfigsReq) (*asset.PageAssetCoinConfigsResp, error) {
	l := adminlogic.NewPageAssetCoinConfigsLogic(ctx, s.svcCtx)
	return l.PageAssetCoinConfigs(in)
}

// 分页查询资产
func (s *AdminServer) PageUserAssets(ctx context.Context, in *asset.PageUserAssetsReq) (*asset.PageUserAssetsResp, error) {
	l := adminlogic.NewPageUserAssetsLogic(ctx, s.svcCtx)
	return l.PageUserAssets(in)
}

// 查询用户资产详情
func (s *AdminServer) GetUserAssetDetail(ctx context.Context, in *asset.GetUserAssetDetailReq) (*asset.GetUserAssetDetailResp, error) {
	l := adminlogic.NewGetUserAssetDetailLogic(ctx, s.svcCtx)
	return l.GetUserAssetDetail(in)
}

// 分页查询资产流水
func (s *AdminServer) PageAssetFlows(ctx context.Context, in *asset.PageAssetFlowsReq) (*asset.PageAssetFlowsResp, error) {
	l := adminlogic.NewPageAssetFlowsLogic(ctx, s.svcCtx)
	return l.PageAssetFlows(in)
}

// 按强平号查询保险基金赔付事实
func (s *AdminServer) GetInsuranceCover(ctx context.Context, in *asset.GetInsuranceCoverReq) (*asset.GetInsuranceCoverResp, error) {
	l := adminlogic.NewGetInsuranceCoverLogic(ctx, s.svcCtx)
	return l.GetInsuranceCover(in)
}

// 分页查询冻结明细
func (s *AdminServer) PageAssetFreezes(ctx context.Context, in *asset.PageAssetFreezesReq) (*asset.PageAssetFreezesResp, error) {
	l := adminlogic.NewPageAssetFreezesLogic(ctx, s.svcCtx)
	return l.PageAssetFreezes(in)
}

// 分页查询锁仓明细
func (s *AdminServer) PageAssetLocks(ctx context.Context, in *asset.PageAssetLocksReq) (*asset.PageAssetLocksResp, error) {
	l := adminlogic.NewPageAssetLocksLogic(ctx, s.svcCtx)
	return l.PageAssetLocks(in)
}

// 后台人工加币
func (s *AdminServer) AddAsset(ctx context.Context, in *asset.AddAssetReq) (*asset.ManualChangeAssetResp, error) {
	l := adminlogic.NewAddAssetLogic(ctx, s.svcCtx)
	return l.AddAsset(in)
}

// 后台人工减币
func (s *AdminServer) SubAsset(ctx context.Context, in *asset.SubAssetReq) (*asset.ManualChangeAssetResp, error) {
	l := adminlogic.NewSubAssetLogic(ctx, s.svcCtx)
	return l.SubAsset(in)
}

// 后台冻结资产
func (s *AdminServer) FreezeAsset(ctx context.Context, in *asset.ManualFreezeAssetReq) (*asset.ManualChangeAssetResp, error) {
	l := adminlogic.NewFreezeAssetLogic(ctx, s.svcCtx)
	return l.FreezeAsset(in)
}

// 后台解冻资产
func (s *AdminServer) UnfreezeAsset(ctx context.Context, in *asset.ManualUnfreezeAssetReq) (*asset.ManualChangeAssetResp, error) {
	l := adminlogic.NewUnfreezeAssetLogic(ctx, s.svcCtx)
	return l.UnfreezeAsset(in)
}

// 后台锁仓资产
func (s *AdminServer) LockAsset(ctx context.Context, in *asset.ManualLockAssetReq) (*asset.ManualChangeAssetResp, error) {
	l := adminlogic.NewLockAssetLogic(ctx, s.svcCtx)
	return l.LockAsset(in)
}

// 后台解锁资产
func (s *AdminServer) UnlockAsset(ctx context.Context, in *asset.ManualUnlockAssetReq) (*asset.ManualChangeAssetResp, error) {
	l := adminlogic.NewUnlockAssetLogic(ctx, s.svcCtx)
	return l.UnlockAsset(in)
}

// 设置平台账户（保险基金等，不属于任何用户）
func (s *AdminServer) SetPlatformAccount(ctx context.Context, in *asset.SetPlatformAccountReq) (*asset.PlatformAccountResp, error) {
	l := adminlogic.NewSetPlatformAccountLogic(ctx, s.svcCtx)
	return l.SetPlatformAccount(in)
}

// 查询平台账户
func (s *AdminServer) GetPlatformAccount(ctx context.Context, in *asset.GetPlatformAccountReq) (*asset.PlatformAccountResp, error) {
	l := adminlogic.NewGetPlatformAccountLogic(ctx, s.svcCtx)
	return l.GetPlatformAccount(in)
}

// 幂等调整平台账户余额
func (s *AdminServer) AdjustPlatformAccount(ctx context.Context, in *asset.AdjustPlatformAccountReq) (*asset.PlatformAccountResp, error) {
	l := adminlogic.NewAdjustPlatformAccountLogic(ctx, s.svcCtx)
	return l.AdjustPlatformAccount(in)
}

// 创建平台兜底资金政策草稿
func (s *AdminServer) CreatePlatformBackstopPolicy(ctx context.Context, in *asset.CreatePlatformBackstopPolicyReq) (*asset.PlatformBackstopPolicyResp, error) {
	l := adminlogic.NewCreatePlatformBackstopPolicyLogic(ctx, s.svcCtx)
	return l.CreatePlatformBackstopPolicy(in)
}

// 独立管理员复核平台兜底资金政策
func (s *AdminServer) ReviewPlatformBackstopPolicy(ctx context.Context, in *asset.ReviewPlatformBackstopPolicyReq) (*asset.PlatformBackstopPolicyResp, error) {
	l := adminlogic.NewReviewPlatformBackstopPolicyLogic(ctx, s.svcCtx)
	return l.ReviewPlatformBackstopPolicy(in)
}

// 查询平台兜底资金政策
func (s *AdminServer) GetPlatformBackstopPolicy(ctx context.Context, in *asset.GetPlatformBackstopPolicyReq) (*asset.PlatformBackstopPolicyResp, error) {
	l := adminlogic.NewGetPlatformBackstopPolicyLogic(ctx, s.svcCtx)
	return l.GetPlatformBackstopPolicy(in)
}

// 分页查询平台兜底资金政策
func (s *AdminServer) ListPlatformBackstopPolicies(ctx context.Context, in *asset.ListPlatformBackstopPoliciesReq) (*asset.ListPlatformBackstopPoliciesResp, error) {
	l := adminlogic.NewListPlatformBackstopPoliciesLogic(ctx, s.svcCtx)
	return l.ListPlatformBackstopPolicies(in)
}
