CREATE TABLE `t_chat_user` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `user_type` tinyint NOT NULL DEFAULT '1' COMMENT '用户类型:1客服商户 2客服坐席',
  `is_owner` tinyint NOT NULL DEFAULT '2' COMMENT '是否商户主账号:1是 2否',
  `username` varchar(64) NOT NULL DEFAULT '' COMMENT '登录账号',
  `password` varchar(255) NOT NULL DEFAULT '' COMMENT 'bcrypt密码',
  `nickname` varchar(64) NOT NULL DEFAULT '' COMMENT '昵称',
  `avatar_url` varchar(512) NOT NULL DEFAULT '' COMMENT '头像URL',
  `mobile` varchar(32) NOT NULL DEFAULT '' COMMENT '手机号',
  `email` varchar(128) NOT NULL DEFAULT '' COMMENT '邮箱',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '启用状态:1启用 2禁用',
  `last_login_ip` varchar(64) NOT NULL DEFAULT '' COMMENT '最后登录IP',
  `last_login_time` bigint NOT NULL DEFAULT '0' COMMENT '最后登录时间戳(毫秒)',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_username` (`merchant_id`,`username`),
  KEY `idx_merchant_user_type` (`merchant_id`,`user_type`),
  KEY `idx_merchant_enabled` (`merchant_id`,`enabled`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服用户/商户账号';

CREATE TABLE `t_chat_merchant_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `api_key` varchar(64) NOT NULL DEFAULT '' COMMENT '对接客服API Key',
  `api_secret` varchar(128) NOT NULL DEFAULT '' COMMENT '对接客服API Secret',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '启用状态:1启用 2禁用',
  `expire_time` bigint NOT NULL DEFAULT '0' COMMENT '到期时间戳(毫秒)',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_id` (`merchant_id`),
  UNIQUE KEY `uk_api_key` (`api_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服商户资料/对接配置';

CREATE TABLE `t_chat_agent` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `chat_user_id` bigint NOT NULL DEFAULT '0' COMMENT '客服用户ID',
  `group_id` bigint NOT NULL DEFAULT '0' COMMENT '客服分组ID',
  `agent_no` varchar(64) NOT NULL DEFAULT '' COMMENT '坐席编号',
  `welcome_message` varchar(500) NOT NULL DEFAULT '' COMMENT '欢迎语',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '在线状态:1离线 2在线 3忙碌 4休息',
  `auto_online` tinyint NOT NULL DEFAULT '2' COMMENT '登录是否自动上线:1是 2否',
  `max_session_count` int NOT NULL DEFAULT '10' COMMENT '最大同时接待数',
  `current_session_count` int NOT NULL DEFAULT '0' COMMENT '当前接待数',
  `last_active_time` bigint NOT NULL DEFAULT '0' COMMENT '最后活跃时间戳(毫秒)',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_chat_user` (`merchant_id`,`chat_user_id`),
  UNIQUE KEY `uk_merchant_agent_no` (`merchant_id`,`agent_no`),
  KEY `idx_merchant_group` (`merchant_id`,`group_id`),
  KEY `idx_merchant_status` (`merchant_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服坐席';

CREATE TABLE `t_chat_session` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `session_no` varchar(64) NOT NULL DEFAULT '' COMMENT '会话编号',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `user_id` bigint NOT NULL DEFAULT '0' COMMENT '用户ID',
  `source` tinyint NOT NULL DEFAULT '1' COMMENT '来源:1APP 2WEB 3后台 4系统',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态:1等待接入 2服务中 3等待用户 4等待客服 5已结束',
  `priority` tinyint NOT NULL DEFAULT '2' COMMENT '优先级:1低 2普通 3高 4紧急',
  `agent_id` bigint NOT NULL DEFAULT '0' COMMENT '当前坐席ID',
  `group_id` bigint NOT NULL DEFAULT '0' COMMENT '目标客服分组ID',
  `title` varchar(128) NOT NULL DEFAULT '' COMMENT '会话标题',
  `category` varchar(64) NOT NULL DEFAULT '' COMMENT '问题分类',
  `last_message_no` varchar(64) NOT NULL DEFAULT '' COMMENT '最后一条消息编号',
  `last_message` varchar(512) NOT NULL DEFAULT '' COMMENT '最后一条消息摘要',
  `last_sender_type` tinyint NOT NULL DEFAULT '0' COMMENT '最后一条消息发送方:1用户 2客服 3系统',
  `last_message_time` bigint NOT NULL DEFAULT '0' COMMENT '最后一条消息时间戳(毫秒)',
  `user_unread_count` int NOT NULL DEFAULT '0' COMMENT '用户未读数',
  `agent_unread_count` int NOT NULL DEFAULT '0' COMMENT '坐席未读数',
  `close_time` bigint NOT NULL DEFAULT '0' COMMENT '结束时间戳(毫秒)',
  `close_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '结束原因',
  `ext_json` json DEFAULT NULL COMMENT '扩展信息',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session_no` (`session_no`),
  KEY `idx_merchant_user_status` (`merchant_id`,`user_id`,`status`),
  KEY `idx_merchant_agent_status` (`merchant_id`,`agent_id`,`status`),
  KEY `idx_merchant_group_status` (`merchant_id`,`group_id`,`status`),
  KEY `idx_merchant_status_priority` (`merchant_id`,`status`,`priority`),
  KEY `idx_last_message_no` (`last_message_no`),
  KEY `idx_last_message_time` (`last_message_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服会话';

CREATE TABLE `t_chat_assignment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `session_no` varchar(64) NOT NULL DEFAULT '' COMMENT '会话编号',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `from_agent_id` bigint NOT NULL DEFAULT '0' COMMENT '原坐席ID',
  `to_agent_id` bigint NOT NULL DEFAULT '0' COMMENT '目标坐席ID',
  `assign_type` tinyint NOT NULL DEFAULT '1' COMMENT '分配方式:1自动 2手动 3转接',
  `operator_id` bigint NOT NULL DEFAULT '0' COMMENT '操作人ID',
  `reason` varchar(255) NOT NULL DEFAULT '' COMMENT '分配/转接原因',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  KEY `idx_session_no` (`session_no`),
  KEY `idx_merchant_to_agent` (`merchant_id`,`to_agent_id`),
  KEY `idx_create_times` (`create_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服会话分配记录';

CREATE TABLE `t_chat_quick_reply` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `agent_id` bigint NOT NULL DEFAULT '0' COMMENT '坐席ID,0表示公共快捷回复',
  `category_id` bigint NOT NULL DEFAULT '0' COMMENT '分类ID',
  `title` varchar(128) NOT NULL DEFAULT '' COMMENT '快捷回复标题',
  `content` text COMMENT '快捷回复内容',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '启用状态:1启用 2禁用',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序,越小越靠前',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  KEY `idx_merchant_agent` (`merchant_id`,`agent_id`),
  KEY `idx_merchant_category` (`merchant_id`,`category_id`),
  KEY `idx_merchant_enabled_sort` (`merchant_id`,`enabled`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服快捷回复';

CREATE TABLE `t_chat_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `parent_id` bigint NOT NULL DEFAULT '0' COMMENT '父级分类ID',
  `category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '分类编码',
  `category_name` varchar(128) NOT NULL DEFAULT '' COMMENT '分类名称',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '启用状态:1启用 2禁用',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序,越小越靠前',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_category_code` (`merchant_id`,`category_code`),
  KEY `idx_merchant_parent` (`merchant_id`,`parent_id`),
  KEY `idx_merchant_enabled_sort` (`merchant_id`,`enabled`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服问题分类';

CREATE TABLE `t_chat_satisfaction` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `session_no` varchar(64) NOT NULL DEFAULT '' COMMENT '会话编号',
  `user_id` bigint NOT NULL DEFAULT '0' COMMENT '用户ID',
  `agent_id` bigint NOT NULL DEFAULT '0' COMMENT '坐席ID',
  `score` tinyint NOT NULL DEFAULT '0' COMMENT '满意度评分:1-5',
  `content` varchar(500) NOT NULL DEFAULT '' COMMENT '评价内容',
  `tags` varchar(255) NOT NULL DEFAULT '' COMMENT '评价标签,逗号分隔',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session_no` (`session_no`),
  KEY `idx_merchant_agent` (`merchant_id`,`agent_id`),
  KEY `idx_merchant_user` (`merchant_id`,`user_id`),
  KEY `idx_create_times` (`create_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服会话满意度评价';

CREATE TABLE `t_chat_read_cursor` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `session_no` varchar(64) NOT NULL DEFAULT '' COMMENT '会话编号',
  `reader_type` tinyint NOT NULL DEFAULT '0' COMMENT '读取方类型:1用户 2客服',
  `reader_id` bigint NOT NULL DEFAULT '0' COMMENT '读取方ID',
  `device_id` varchar(128) NOT NULL DEFAULT '' COMMENT '设备ID,为空表示默认设备',
  `last_read_message_no` varchar(64) NOT NULL DEFAULT '' COMMENT '最后已读消息编号',
  `last_read_time` bigint NOT NULL DEFAULT '0' COMMENT '最后已读时间戳(毫秒)',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reader_device` (`merchant_id`,`session_no`,`reader_type`,`reader_id`,`device_id`),
  KEY `idx_session_reader` (`session_no`,`reader_type`,`reader_id`),
  KEY `idx_last_read_time` (`last_read_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服消息已读游标';

CREATE TABLE `t_chat_group` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `group_code` varchar(64) NOT NULL DEFAULT '' COMMENT '分组编码',
  `group_name` varchar(128) NOT NULL DEFAULT '' COMMENT '分组名称',
  `description` varchar(255) NOT NULL DEFAULT '' COMMENT '分组描述',
  `enabled` tinyint NOT NULL DEFAULT '1' COMMENT '启用状态:1启用 2禁用',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序,越小越靠前',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_group_code` (`merchant_id`,`group_code`),
  KEY `idx_merchant_enabled_sort` (`merchant_id`,`enabled`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服分组';

CREATE TABLE `t_chat_work_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint NOT NULL DEFAULT '0' COMMENT '客服商户ID',
  `work_order_no` varchar(64) NOT NULL DEFAULT '' COMMENT '工单编号',
  `session_no` varchar(64) NOT NULL DEFAULT '' COMMENT '关联会话编号',
  `user_id` bigint NOT NULL DEFAULT '0' COMMENT '用户ID',
  `agent_id` bigint NOT NULL DEFAULT '0' COMMENT '坐席ID',
  `group_id` bigint NOT NULL DEFAULT '0' COMMENT '客服分组ID',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT '工单标题',
  `content` text COMMENT '工单内容/离线留言',
  `contact_name` varchar(64) NOT NULL DEFAULT '' COMMENT '联系人',
  `contact_mobile` varchar(32) NOT NULL DEFAULT '' COMMENT '联系电话',
  `contact_email` varchar(128) NOT NULL DEFAULT '' COMMENT '联系邮箱',
  `priority` tinyint NOT NULL DEFAULT '2' COMMENT '优先级:1低 2普通 3高 4紧急',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态:1待处理 2处理中 3已完成 4已关闭',
  `handler_id` bigint NOT NULL DEFAULT '0' COMMENT '处理人ID',
  `handle_result` varchar(500) NOT NULL DEFAULT '' COMMENT '处理结果',
  `finish_time` bigint NOT NULL DEFAULT '0' COMMENT '完成时间戳(毫秒)',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_times` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳(毫秒)',
  `update_times` bigint NOT NULL DEFAULT '0' COMMENT '更新时间戳(毫秒)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_work_order_no` (`work_order_no`),
  KEY `idx_merchant_status` (`merchant_id`,`status`),
  KEY `idx_merchant_user` (`merchant_id`,`user_id`),
  KEY `idx_merchant_agent` (`merchant_id`,`agent_id`),
  KEY `idx_merchant_group_status` (`merchant_id`,`group_id`,`status`),
  KEY `idx_session_no` (`session_no`),
  KEY `idx_create_times` (`create_times`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服工单/离线留言';
