// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/staking/model.proto

package staking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 质押产品
type StakeProduct struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProductNo        string                 `protobuf:"bytes,3,opt,name=product_no,json=productNo,proto3" json:"product_no,omitempty"`
	ProductName      string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductType      ProductType            `protobuf:"varint,5,opt,name=product_type,json=productType,proto3,enum=staking.ProductType" json:"product_type,omitempty"`
	CoinName         string                 `protobuf:"bytes,6,opt,name=coin_name,json=coinName,proto3" json:"coin_name,omitempty"`
	CoinSymbol       string                 `protobuf:"bytes,7,opt,name=coin_symbol,json=coinSymbol,proto3" json:"coin_symbol,omitempty"`
	RewardCoinName   string                 `protobuf:"bytes,8,opt,name=reward_coin_name,json=rewardCoinName,proto3" json:"reward_coin_name,omitempty"`
	RewardCoinSymbol string                 `protobuf:"bytes,9,opt,name=reward_coin_symbol,json=rewardCoinSymbol,proto3" json:"reward_coin_symbol,omitempty"`
	Apr              string                 `protobuf:"bytes,10,opt,name=apr,proto3" json:"apr,omitempty"`
	LockDays         int32                  `protobuf:"varint,11,opt,name=lock_days,json=lockDays,proto3" json:"lock_days,omitempty"`
	MinAmount        string                 `protobuf:"bytes,12,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount        string                 `protobuf:"bytes,13,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	StepAmount       string                 `protobuf:"bytes,14,opt,name=step_amount,json=stepAmount,proto3" json:"step_amount,omitempty"`
	TotalAmount      string                 `protobuf:"bytes,15,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	StakedAmount     string                 `protobuf:"bytes,16,opt,name=staked_amount,json=stakedAmount,proto3" json:"staked_amount,omitempty"`
	UserLimitAmount  string                 `protobuf:"bytes,17,opt,name=user_limit_amount,json=userLimitAmount,proto3" json:"user_limit_amount,omitempty"`
	InterestMode     InterestMode           `protobuf:"varint,18,opt,name=interest_mode,json=interestMode,proto3,enum=staking.InterestMode" json:"interest_mode,omitempty"`
	RewardMode       RewardMode             `protobuf:"varint,19,opt,name=reward_mode,json=rewardMode,proto3,enum=staking.RewardMode" json:"reward_mode,omitempty"`
	AllowEarlyRedeem YesNo                  `protobuf:"varint,20,opt,name=allow_early_redeem,json=allowEarlyRedeem,proto3,enum=staking.YesNo" json:"allow_early_redeem,omitempty"`
	EarlyRedeemRate  string                 `protobuf:"bytes,21,opt,name=early_redeem_rate,json=earlyRedeemRate,proto3" json:"early_redeem_rate,omitempty"`
	Status           ProductStatus          `protobuf:"varint,22,opt,name=status,proto3,enum=staking.ProductStatus" json:"status,omitempty"`
	Sort             int32                  `protobuf:"varint,23,opt,name=sort,proto3" json:"sort,omitempty"`
	Remark           string                 `protobuf:"bytes,24,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateUserId     uint64                 `protobuf:"varint,25,opt,name=create_user_id,json=createUserId,proto3" json:"create_user_id,omitempty"`
	UpdateUserId     uint64                 `protobuf:"varint,26,opt,name=update_user_id,json=updateUserId,proto3" json:"update_user_id,omitempty"`
	CreateTimes      int64                  `protobuf:"varint,27,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`
	UpdateTimes      int64                  `protobuf:"varint,28,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StakeProduct) Reset() {
	*x = StakeProduct{}
	mi := &file_proto_staking_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakeProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeProduct) ProtoMessage() {}

func (x *StakeProduct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staking_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeProduct.ProtoReflect.Descriptor instead.
func (*StakeProduct) Descriptor() ([]byte, []int) {
	return file_proto_staking_model_proto_rawDescGZIP(), []int{0}
}

func (x *StakeProduct) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StakeProduct) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *StakeProduct) GetProductNo() string {
	if x != nil {
		return x.ProductNo
	}
	return ""
}

func (x *StakeProduct) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StakeProduct) GetProductType() ProductType {
	if x != nil {
		return x.ProductType
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (x *StakeProduct) GetCoinName() string {
	if x != nil {
		return x.CoinName
	}
	return ""
}

func (x *StakeProduct) GetCoinSymbol() string {
	if x != nil {
		return x.CoinSymbol
	}
	return ""
}

func (x *StakeProduct) GetRewardCoinName() string {
	if x != nil {
		return x.RewardCoinName
	}
	return ""
}

func (x *StakeProduct) GetRewardCoinSymbol() string {
	if x != nil {
		return x.RewardCoinSymbol
	}
	return ""
}

func (x *StakeProduct) GetApr() string {
	if x != nil {
		return x.Apr
	}
	return ""
}

func (x *StakeProduct) GetLockDays() int32 {
	if x != nil {
		return x.LockDays
	}
	return 0
}

func (x *StakeProduct) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *StakeProduct) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *StakeProduct) GetStepAmount() string {
	if x != nil {
		return x.StepAmount
	}
	return ""
}

func (x *StakeProduct) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *StakeProduct) GetStakedAmount() string {
	if x != nil {
		return x.StakedAmount
	}
	return ""
}

func (x *StakeProduct) GetUserLimitAmount() string {
	if x != nil {
		return x.UserLimitAmount
	}
	return ""
}

func (x *StakeProduct) GetInterestMode() InterestMode {
	if x != nil {
		return x.InterestMode
	}
	return InterestMode_INTEREST_MODE_UNSPECIFIED
}

func (x *StakeProduct) GetRewardMode() RewardMode {
	if x != nil {
		return x.RewardMode
	}
	return RewardMode_REWARD_MODE_UNSPECIFIED
}

func (x *StakeProduct) GetAllowEarlyRedeem() YesNo {
	if x != nil {
		return x.AllowEarlyRedeem
	}
	return YesNo_YES_NO_UNSPECIFIED
}

func (x *StakeProduct) GetEarlyRedeemRate() string {
	if x != nil {
		return x.EarlyRedeemRate
	}
	return ""
}

func (x *StakeProduct) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

func (x *StakeProduct) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *StakeProduct) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *StakeProduct) GetCreateUserId() uint64 {
	if x != nil {
		return x.CreateUserId
	}
	return 0
}

func (x *StakeProduct) GetUpdateUserId() uint64 {
	if x != nil {
		return x.UpdateUserId
	}
	return 0
}

func (x *StakeProduct) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *StakeProduct) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

// 质押订单
type StakeOrder struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrderNo          string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Uid              uint64                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	ProductId        uint64                 `protobuf:"varint,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductNo        string                 `protobuf:"bytes,6,opt,name=product_no,json=productNo,proto3" json:"product_no,omitempty"`
	ProductName      string                 `protobuf:"bytes,7,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductType      ProductType            `protobuf:"varint,8,opt,name=product_type,json=productType,proto3,enum=staking.ProductType" json:"product_type,omitempty"`
	CoinName         string                 `protobuf:"bytes,9,opt,name=coin_name,json=coinName,proto3" json:"coin_name,omitempty"`
	CoinSymbol       string                 `protobuf:"bytes,10,opt,name=coin_symbol,json=coinSymbol,proto3" json:"coin_symbol,omitempty"`
	RewardCoinName   string                 `protobuf:"bytes,11,opt,name=reward_coin_name,json=rewardCoinName,proto3" json:"reward_coin_name,omitempty"`
	RewardCoinSymbol string                 `protobuf:"bytes,12,opt,name=reward_coin_symbol,json=rewardCoinSymbol,proto3" json:"reward_coin_symbol,omitempty"`
	StakeAmount      string                 `protobuf:"bytes,13,opt,name=stake_amount,json=stakeAmount,proto3" json:"stake_amount,omitempty"`
	Apr              string                 `protobuf:"bytes,14,opt,name=apr,proto3" json:"apr,omitempty"`
	LockDays         int32                  `protobuf:"varint,15,opt,name=lock_days,json=lockDays,proto3" json:"lock_days,omitempty"`
	InterestMode     InterestMode           `protobuf:"varint,16,opt,name=interest_mode,json=interestMode,proto3,enum=staking.InterestMode" json:"interest_mode,omitempty"`
	RewardMode       RewardMode             `protobuf:"varint,17,opt,name=reward_mode,json=rewardMode,proto3,enum=staking.RewardMode" json:"reward_mode,omitempty"`
	AllowEarlyRedeem YesNo                  `protobuf:"varint,18,opt,name=allow_early_redeem,json=allowEarlyRedeem,proto3,enum=staking.YesNo" json:"allow_early_redeem,omitempty"`
	EarlyRedeemRate  string                 `protobuf:"bytes,19,opt,name=early_redeem_rate,json=earlyRedeemRate,proto3" json:"early_redeem_rate,omitempty"`
	InterestDays     int32                  `protobuf:"varint,20,opt,name=interest_days,json=interestDays,proto3" json:"interest_days,omitempty"`
	StartTimes       int64                  `protobuf:"varint,21,opt,name=start_times,json=startTimes,proto3" json:"start_times,omitempty"`
	EndTimes         int64                  `protobuf:"varint,22,opt,name=end_times,json=endTimes,proto3" json:"end_times,omitempty"`
	LastRewardTimes  int64                  `protobuf:"varint,23,opt,name=last_reward_times,json=lastRewardTimes,proto3" json:"last_reward_times,omitempty"`
	NextRewardTimes  int64                  `protobuf:"varint,24,opt,name=next_reward_times,json=nextRewardTimes,proto3" json:"next_reward_times,omitempty"`
	TotalReward      string                 `protobuf:"bytes,25,opt,name=total_reward,json=totalReward,proto3" json:"total_reward,omitempty"`
	PendingReward    string                 `protobuf:"bytes,26,opt,name=pending_reward,json=pendingReward,proto3" json:"pending_reward,omitempty"`
	RedeemAmount     string                 `protobuf:"bytes,27,opt,name=redeem_amount,json=redeemAmount,proto3" json:"redeem_amount,omitempty"`
	RedeemFee        string                 `protobuf:"bytes,28,opt,name=redeem_fee,json=redeemFee,proto3" json:"redeem_fee,omitempty"`
	Status           OrderStatus            `protobuf:"varint,29,opt,name=status,proto3,enum=staking.OrderStatus" json:"status,omitempty"`
	RedeemType       RedeemType             `protobuf:"varint,30,opt,name=redeem_type,json=redeemType,proto3,enum=staking.RedeemType" json:"redeem_type,omitempty"`
	RedeemApplyTimes int64                  `protobuf:"varint,31,opt,name=redeem_apply_times,json=redeemApplyTimes,proto3" json:"redeem_apply_times,omitempty"`
	RedeemTimes      int64                  `protobuf:"varint,32,opt,name=redeem_times,json=redeemTimes,proto3" json:"redeem_times,omitempty"`
	Source           SourceType             `protobuf:"varint,33,opt,name=source,proto3,enum=staking.SourceType" json:"source,omitempty"`
	Remark           string                 `protobuf:"bytes,34,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateUserId     uint64                 `protobuf:"varint,35,opt,name=create_user_id,json=createUserId,proto3" json:"create_user_id,omitempty"`
	UpdateUserId     uint64                 `protobuf:"varint,36,opt,name=update_user_id,json=updateUserId,proto3" json:"update_user_id,omitempty"`
	CreateTimes      int64                  `protobuf:"varint,37,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`
	UpdateTimes      int64                  `protobuf:"varint,38,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StakeOrder) Reset() {
	*x = StakeOrder{}
	mi := &file_proto_staking_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakeOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeOrder) ProtoMessage() {}

func (x *StakeOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staking_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeOrder.ProtoReflect.Descriptor instead.
func (*StakeOrder) Descriptor() ([]byte, []int) {
	return file_proto_staking_model_proto_rawDescGZIP(), []int{1}
}

func (x *StakeOrder) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StakeOrder) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *StakeOrder) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *StakeOrder) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *StakeOrder) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StakeOrder) GetProductNo() string {
	if x != nil {
		return x.ProductNo
	}
	return ""
}

func (x *StakeOrder) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StakeOrder) GetProductType() ProductType {
	if x != nil {
		return x.ProductType
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (x *StakeOrder) GetCoinName() string {
	if x != nil {
		return x.CoinName
	}
	return ""
}

func (x *StakeOrder) GetCoinSymbol() string {
	if x != nil {
		return x.CoinSymbol
	}
	return ""
}

func (x *StakeOrder) GetRewardCoinName() string {
	if x != nil {
		return x.RewardCoinName
	}
	return ""
}

func (x *StakeOrder) GetRewardCoinSymbol() string {
	if x != nil {
		return x.RewardCoinSymbol
	}
	return ""
}

func (x *StakeOrder) GetStakeAmount() string {
	if x != nil {
		return x.StakeAmount
	}
	return ""
}

func (x *StakeOrder) GetApr() string {
	if x != nil {
		return x.Apr
	}
	return ""
}

func (x *StakeOrder) GetLockDays() int32 {
	if x != nil {
		return x.LockDays
	}
	return 0
}

func (x *StakeOrder) GetInterestMode() InterestMode {
	if x != nil {
		return x.InterestMode
	}
	return InterestMode_INTEREST_MODE_UNSPECIFIED
}

func (x *StakeOrder) GetRewardMode() RewardMode {
	if x != nil {
		return x.RewardMode
	}
	return RewardMode_REWARD_MODE_UNSPECIFIED
}

func (x *StakeOrder) GetAllowEarlyRedeem() YesNo {
	if x != nil {
		return x.AllowEarlyRedeem
	}
	return YesNo_YES_NO_UNSPECIFIED
}

func (x *StakeOrder) GetEarlyRedeemRate() string {
	if x != nil {
		return x.EarlyRedeemRate
	}
	return ""
}

func (x *StakeOrder) GetInterestDays() int32 {
	if x != nil {
		return x.InterestDays
	}
	return 0
}

func (x *StakeOrder) GetStartTimes() int64 {
	if x != nil {
		return x.StartTimes
	}
	return 0
}

func (x *StakeOrder) GetEndTimes() int64 {
	if x != nil {
		return x.EndTimes
	}
	return 0
}

func (x *StakeOrder) GetLastRewardTimes() int64 {
	if x != nil {
		return x.LastRewardTimes
	}
	return 0
}

func (x *StakeOrder) GetNextRewardTimes() int64 {
	if x != nil {
		return x.NextRewardTimes
	}
	return 0
}

func (x *StakeOrder) GetTotalReward() string {
	if x != nil {
		return x.TotalReward
	}
	return ""
}

func (x *StakeOrder) GetPendingReward() string {
	if x != nil {
		return x.PendingReward
	}
	return ""
}

func (x *StakeOrder) GetRedeemAmount() string {
	if x != nil {
		return x.RedeemAmount
	}
	return ""
}

func (x *StakeOrder) GetRedeemFee() string {
	if x != nil {
		return x.RedeemFee
	}
	return ""
}

func (x *StakeOrder) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *StakeOrder) GetRedeemType() RedeemType {
	if x != nil {
		return x.RedeemType
	}
	return RedeemType_REDEEM_TYPE_UNSPECIFIED
}

func (x *StakeOrder) GetRedeemApplyTimes() int64 {
	if x != nil {
		return x.RedeemApplyTimes
	}
	return 0
}

func (x *StakeOrder) GetRedeemTimes() int64 {
	if x != nil {
		return x.RedeemTimes
	}
	return 0
}

func (x *StakeOrder) GetSource() SourceType {
	if x != nil {
		return x.Source
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *StakeOrder) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *StakeOrder) GetCreateUserId() uint64 {
	if x != nil {
		return x.CreateUserId
	}
	return 0
}

func (x *StakeOrder) GetUpdateUserId() uint64 {
	if x != nil {
		return x.UpdateUserId
	}
	return 0
}

func (x *StakeOrder) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *StakeOrder) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

// 收益记录
type StakeRewardLog struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrderId          uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo          string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Uid              uint64                 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	ProductId        uint64                 `protobuf:"varint,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName      string                 `protobuf:"bytes,7,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	CoinSymbol       string                 `protobuf:"bytes,8,opt,name=coin_symbol,json=coinSymbol,proto3" json:"coin_symbol,omitempty"`
	RewardCoinSymbol string                 `protobuf:"bytes,9,opt,name=reward_coin_symbol,json=rewardCoinSymbol,proto3" json:"reward_coin_symbol,omitempty"`
	RewardAmount     string                 `protobuf:"bytes,10,opt,name=reward_amount,json=rewardAmount,proto3" json:"reward_amount,omitempty"`
	BeforeReward     string                 `protobuf:"bytes,11,opt,name=before_reward,json=beforeReward,proto3" json:"before_reward,omitempty"`
	AfterReward      string                 `protobuf:"bytes,12,opt,name=after_reward,json=afterReward,proto3" json:"after_reward,omitempty"`
	RewardType       RewardType             `protobuf:"varint,13,opt,name=reward_type,json=rewardType,proto3,enum=staking.RewardType" json:"reward_type,omitempty"`
	RewardStatus     RewardStatus           `protobuf:"varint,14,opt,name=reward_status,json=rewardStatus,proto3,enum=staking.RewardStatus" json:"reward_status,omitempty"`
	RewardTimes      int64                  `protobuf:"varint,15,opt,name=reward_times,json=rewardTimes,proto3" json:"reward_times,omitempty"`
	Remark           string                 `protobuf:"bytes,16,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateUserId     uint64                 `protobuf:"varint,17,opt,name=create_user_id,json=createUserId,proto3" json:"create_user_id,omitempty"`
	UpdateUserId     uint64                 `protobuf:"varint,18,opt,name=update_user_id,json=updateUserId,proto3" json:"update_user_id,omitempty"`
	CreateTimes      int64                  `protobuf:"varint,19,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`
	UpdateTimes      int64                  `protobuf:"varint,20,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StakeRewardLog) Reset() {
	*x = StakeRewardLog{}
	mi := &file_proto_staking_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakeRewardLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeRewardLog) ProtoMessage() {}

func (x *StakeRewardLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staking_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeRewardLog.ProtoReflect.Descriptor instead.
func (*StakeRewardLog) Descriptor() ([]byte, []int) {
	return file_proto_staking_model_proto_rawDescGZIP(), []int{2}
}

func (x *StakeRewardLog) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StakeRewardLog) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *StakeRewardLog) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *StakeRewardLog) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *StakeRewardLog) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *StakeRewardLog) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StakeRewardLog) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StakeRewardLog) GetCoinSymbol() string {
	if x != nil {
		return x.CoinSymbol
	}
	return ""
}

func (x *StakeRewardLog) GetRewardCoinSymbol() string {
	if x != nil {
		return x.RewardCoinSymbol
	}
	return ""
}

func (x *StakeRewardLog) GetRewardAmount() string {
	if x != nil {
		return x.RewardAmount
	}
	return ""
}

func (x *StakeRewardLog) GetBeforeReward() string {
	if x != nil {
		return x.BeforeReward
	}
	return ""
}

func (x *StakeRewardLog) GetAfterReward() string {
	if x != nil {
		return x.AfterReward
	}
	return ""
}

func (x *StakeRewardLog) GetRewardType() RewardType {
	if x != nil {
		return x.RewardType
	}
	return RewardType_REWARD_TYPE_UNSPECIFIED
}

func (x *StakeRewardLog) GetRewardStatus() RewardStatus {
	if x != nil {
		return x.RewardStatus
	}
	return RewardStatus_REWARD_STATUS_UNSPECIFIED
}

func (x *StakeRewardLog) GetRewardTimes() int64 {
	if x != nil {
		return x.RewardTimes
	}
	return 0
}

func (x *StakeRewardLog) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *StakeRewardLog) GetCreateUserId() uint64 {
	if x != nil {
		return x.CreateUserId
	}
	return 0
}

func (x *StakeRewardLog) GetUpdateUserId() uint64 {
	if x != nil {
		return x.UpdateUserId
	}
	return 0
}

func (x *StakeRewardLog) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *StakeRewardLog) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

// 赎回记录
type StakeRedeemLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Uid           uint64                 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	ProductId     uint64                 `protobuf:"varint,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RedeemNo      string                 `protobuf:"bytes,7,opt,name=redeem_no,json=redeemNo,proto3" json:"redeem_no,omitempty"`
	RedeemType    RedeemType             `protobuf:"varint,8,opt,name=redeem_type,json=redeemType,proto3,enum=staking.RedeemType" json:"redeem_type,omitempty"`
	StakeAmount   string                 `protobuf:"bytes,9,opt,name=stake_amount,json=stakeAmount,proto3" json:"stake_amount,omitempty"`
	RedeemAmount  string                 `protobuf:"bytes,10,opt,name=redeem_amount,json=redeemAmount,proto3" json:"redeem_amount,omitempty"`
	RewardAmount  string                 `protobuf:"bytes,11,opt,name=reward_amount,json=rewardAmount,proto3" json:"reward_amount,omitempty"`
	FeeRate       string                 `protobuf:"bytes,12,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	FeeAmount     string                 `protobuf:"bytes,13,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	RedeemStatus  RedeemStatus           `protobuf:"varint,14,opt,name=redeem_status,json=redeemStatus,proto3,enum=staking.RedeemStatus" json:"redeem_status,omitempty"`
	RedeemTimes   int64                  `protobuf:"varint,15,opt,name=redeem_times,json=redeemTimes,proto3" json:"redeem_times,omitempty"`
	Remark        string                 `protobuf:"bytes,16,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateUserId  uint64                 `protobuf:"varint,17,opt,name=create_user_id,json=createUserId,proto3" json:"create_user_id,omitempty"`
	UpdateUserId  uint64                 `protobuf:"varint,18,opt,name=update_user_id,json=updateUserId,proto3" json:"update_user_id,omitempty"`
	CreateTimes   int64                  `protobuf:"varint,19,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`
	UpdateTimes   int64                  `protobuf:"varint,20,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StakeRedeemLog) Reset() {
	*x = StakeRedeemLog{}
	mi := &file_proto_staking_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakeRedeemLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeRedeemLog) ProtoMessage() {}

func (x *StakeRedeemLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staking_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeRedeemLog.ProtoReflect.Descriptor instead.
func (*StakeRedeemLog) Descriptor() ([]byte, []int) {
	return file_proto_staking_model_proto_rawDescGZIP(), []int{3}
}

func (x *StakeRedeemLog) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StakeRedeemLog) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *StakeRedeemLog) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *StakeRedeemLog) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *StakeRedeemLog) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *StakeRedeemLog) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StakeRedeemLog) GetRedeemNo() string {
	if x != nil {
		return x.RedeemNo
	}
	return ""
}

func (x *StakeRedeemLog) GetRedeemType() RedeemType {
	if x != nil {
		return x.RedeemType
	}
	return RedeemType_REDEEM_TYPE_UNSPECIFIED
}

func (x *StakeRedeemLog) GetStakeAmount() string {
	if x != nil {
		return x.StakeAmount
	}
	return ""
}

func (x *StakeRedeemLog) GetRedeemAmount() string {
	if x != nil {
		return x.RedeemAmount
	}
	return ""
}

func (x *StakeRedeemLog) GetRewardAmount() string {
	if x != nil {
		return x.RewardAmount
	}
	return ""
}

func (x *StakeRedeemLog) GetFeeRate() string {
	if x != nil {
		return x.FeeRate
	}
	return ""
}

func (x *StakeRedeemLog) GetFeeAmount() string {
	if x != nil {
		return x.FeeAmount
	}
	return ""
}

func (x *StakeRedeemLog) GetRedeemStatus() RedeemStatus {
	if x != nil {
		return x.RedeemStatus
	}
	return RedeemStatus_REDEEM_STATUS_UNSPECIFIED
}

func (x *StakeRedeemLog) GetRedeemTimes() int64 {
	if x != nil {
		return x.RedeemTimes
	}
	return 0
}

func (x *StakeRedeemLog) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *StakeRedeemLog) GetCreateUserId() uint64 {
	if x != nil {
		return x.CreateUserId
	}
	return 0
}

func (x *StakeRedeemLog) GetUpdateUserId() uint64 {
	if x != nil {
		return x.UpdateUserId
	}
	return 0
}

func (x *StakeRedeemLog) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *StakeRedeemLog) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

var File_proto_staking_model_proto protoreflect.FileDescriptor

const file_proto_staking_model_proto_rawDesc = "" +
	"\n" +
	"\x19proto/staking/model.proto\x12\astaking\x1a\x18proto/staking/enum.proto\"\x98\b\n" +
	"\fStakeProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x1d\n" +
	"\n" +
	"product_no\x18\x03 \x01(\tR\tproductNo\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x127\n" +
	"\fproduct_type\x18\x05 \x01(\x0e2\x14.staking.ProductTypeR\vproductType\x12\x1b\n" +
	"\tcoin_name\x18\x06 \x01(\tR\bcoinName\x12\x1f\n" +
	"\vcoin_symbol\x18\a \x01(\tR\n" +
	"coinSymbol\x12(\n" +
	"\x10reward_coin_name\x18\b \x01(\tR\x0erewardCoinName\x12,\n" +
	"\x12reward_coin_symbol\x18\t \x01(\tR\x10rewardCoinSymbol\x12\x10\n" +
	"\x03apr\x18\n" +
	" \x01(\tR\x03apr\x12\x1b\n" +
	"\tlock_days\x18\v \x01(\x05R\blockDays\x12\x1d\n" +
	"\n" +
	"min_amount\x18\f \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\r \x01(\tR\tmaxAmount\x12\x1f\n" +
	"\vstep_amount\x18\x0e \x01(\tR\n" +
	"stepAmount\x12!\n" +
	"\ftotal_amount\x18\x0f \x01(\tR\vtotalAmount\x12#\n" +
	"\rstaked_amount\x18\x10 \x01(\tR\fstakedAmount\x12*\n" +
	"\x11user_limit_amount\x18\x11 \x01(\tR\x0fuserLimitAmount\x12:\n" +
	"\rinterest_mode\x18\x12 \x01(\x0e2\x15.staking.InterestModeR\finterestMode\x124\n" +
	"\vreward_mode\x18\x13 \x01(\x0e2\x13.staking.RewardModeR\n" +
	"rewardMode\x12<\n" +
	"\x12allow_early_redeem\x18\x14 \x01(\x0e2\x0e.staking.YesNoR\x10allowEarlyRedeem\x12*\n" +
	"\x11early_redeem_rate\x18\x15 \x01(\tR\x0fearlyRedeemRate\x12.\n" +
	"\x06status\x18\x16 \x01(\x0e2\x16.staking.ProductStatusR\x06status\x12\x12\n" +
	"\x04sort\x18\x17 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06remark\x18\x18 \x01(\tR\x06remark\x12$\n" +
	"\x0ecreate_user_id\x18\x19 \x01(\x04R\fcreateUserId\x12$\n" +
	"\x0eupdate_user_id\x18\x1a \x01(\x04R\fupdateUserId\x12!\n" +
	"\fcreate_times\x18\x1b \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\x1c \x01(\x03R\vupdateTimes\"\x99\v\n" +
	"\n" +
	"StakeOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x04R\x03uid\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\x04R\tproductId\x12\x1d\n" +
	"\n" +
	"product_no\x18\x06 \x01(\tR\tproductNo\x12!\n" +
	"\fproduct_name\x18\a \x01(\tR\vproductName\x127\n" +
	"\fproduct_type\x18\b \x01(\x0e2\x14.staking.ProductTypeR\vproductType\x12\x1b\n" +
	"\tcoin_name\x18\t \x01(\tR\bcoinName\x12\x1f\n" +
	"\vcoin_symbol\x18\n" +
	" \x01(\tR\n" +
	"coinSymbol\x12(\n" +
	"\x10reward_coin_name\x18\v \x01(\tR\x0erewardCoinName\x12,\n" +
	"\x12reward_coin_symbol\x18\f \x01(\tR\x10rewardCoinSymbol\x12!\n" +
	"\fstake_amount\x18\r \x01(\tR\vstakeAmount\x12\x10\n" +
	"\x03apr\x18\x0e \x01(\tR\x03apr\x12\x1b\n" +
	"\tlock_days\x18\x0f \x01(\x05R\blockDays\x12:\n" +
	"\rinterest_mode\x18\x10 \x01(\x0e2\x15.staking.InterestModeR\finterestMode\x124\n" +
	"\vreward_mode\x18\x11 \x01(\x0e2\x13.staking.RewardModeR\n" +
	"rewardMode\x12<\n" +
	"\x12allow_early_redeem\x18\x12 \x01(\x0e2\x0e.staking.YesNoR\x10allowEarlyRedeem\x12*\n" +
	"\x11early_redeem_rate\x18\x13 \x01(\tR\x0fearlyRedeemRate\x12#\n" +
	"\rinterest_days\x18\x14 \x01(\x05R\finterestDays\x12\x1f\n" +
	"\vstart_times\x18\x15 \x01(\x03R\n" +
	"startTimes\x12\x1b\n" +
	"\tend_times\x18\x16 \x01(\x03R\bendTimes\x12*\n" +
	"\x11last_reward_times\x18\x17 \x01(\x03R\x0flastRewardTimes\x12*\n" +
	"\x11next_reward_times\x18\x18 \x01(\x03R\x0fnextRewardTimes\x12!\n" +
	"\ftotal_reward\x18\x19 \x01(\tR\vtotalReward\x12%\n" +
	"\x0epending_reward\x18\x1a \x01(\tR\rpendingReward\x12#\n" +
	"\rredeem_amount\x18\x1b \x01(\tR\fredeemAmount\x12\x1d\n" +
	"\n" +
	"redeem_fee\x18\x1c \x01(\tR\tredeemFee\x12,\n" +
	"\x06status\x18\x1d \x01(\x0e2\x14.staking.OrderStatusR\x06status\x124\n" +
	"\vredeem_type\x18\x1e \x01(\x0e2\x13.staking.RedeemTypeR\n" +
	"redeemType\x12,\n" +
	"\x12redeem_apply_times\x18\x1f \x01(\x03R\x10redeemApplyTimes\x12!\n" +
	"\fredeem_times\x18  \x01(\x03R\vredeemTimes\x12+\n" +
	"\x06source\x18! \x01(\x0e2\x13.staking.SourceTypeR\x06source\x12\x16\n" +
	"\x06remark\x18\" \x01(\tR\x06remark\x12$\n" +
	"\x0ecreate_user_id\x18# \x01(\x04R\fcreateUserId\x12$\n" +
	"\x0eupdate_user_id\x18$ \x01(\x04R\fupdateUserId\x12!\n" +
	"\fcreate_times\x18% \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18& \x01(\x03R\vupdateTimes\"\xc2\x05\n" +
	"\x0eStakeRewardLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\x04R\x03uid\x12\x1d\n" +
	"\n" +
	"product_id\x18\x06 \x01(\x04R\tproductId\x12!\n" +
	"\fproduct_name\x18\a \x01(\tR\vproductName\x12\x1f\n" +
	"\vcoin_symbol\x18\b \x01(\tR\n" +
	"coinSymbol\x12,\n" +
	"\x12reward_coin_symbol\x18\t \x01(\tR\x10rewardCoinSymbol\x12#\n" +
	"\rreward_amount\x18\n" +
	" \x01(\tR\frewardAmount\x12#\n" +
	"\rbefore_reward\x18\v \x01(\tR\fbeforeReward\x12!\n" +
	"\fafter_reward\x18\f \x01(\tR\vafterReward\x124\n" +
	"\vreward_type\x18\r \x01(\x0e2\x13.staking.RewardTypeR\n" +
	"rewardType\x12:\n" +
	"\rreward_status\x18\x0e \x01(\x0e2\x15.staking.RewardStatusR\frewardStatus\x12!\n" +
	"\freward_times\x18\x0f \x01(\x03R\vrewardTimes\x12\x16\n" +
	"\x06remark\x18\x10 \x01(\tR\x06remark\x12$\n" +
	"\x0ecreate_user_id\x18\x11 \x01(\x04R\fcreateUserId\x12$\n" +
	"\x0eupdate_user_id\x18\x12 \x01(\x04R\fupdateUserId\x12!\n" +
	"\fcreate_times\x18\x13 \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\x14 \x01(\x03R\vupdateTimes\"\xa7\x05\n" +
	"\x0eStakeRedeemLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\x04R\x03uid\x12\x1d\n" +
	"\n" +
	"product_id\x18\x06 \x01(\x04R\tproductId\x12\x1b\n" +
	"\tredeem_no\x18\a \x01(\tR\bredeemNo\x124\n" +
	"\vredeem_type\x18\b \x01(\x0e2\x13.staking.RedeemTypeR\n" +
	"redeemType\x12!\n" +
	"\fstake_amount\x18\t \x01(\tR\vstakeAmount\x12#\n" +
	"\rredeem_amount\x18\n" +
	" \x01(\tR\fredeemAmount\x12#\n" +
	"\rreward_amount\x18\v \x01(\tR\frewardAmount\x12\x19\n" +
	"\bfee_rate\x18\f \x01(\tR\afeeRate\x12\x1d\n" +
	"\n" +
	"fee_amount\x18\r \x01(\tR\tfeeAmount\x12:\n" +
	"\rredeem_status\x18\x0e \x01(\x0e2\x15.staking.RedeemStatusR\fredeemStatus\x12!\n" +
	"\fredeem_times\x18\x0f \x01(\x03R\vredeemTimes\x12\x16\n" +
	"\x06remark\x18\x10 \x01(\tR\x06remark\x12$\n" +
	"\x0ecreate_user_id\x18\x11 \x01(\x04R\fcreateUserId\x12$\n" +
	"\x0eupdate_user_id\x18\x12 \x01(\x04R\fupdateUserId\x12!\n" +
	"\fcreate_times\x18\x13 \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\x14 \x01(\x03R\vupdateTimesB\x1eZ\x1cwklive/proto/staking;stakingb\x06proto3"

var (
	file_proto_staking_model_proto_rawDescOnce sync.Once
	file_proto_staking_model_proto_rawDescData []byte
)

func file_proto_staking_model_proto_rawDescGZIP() []byte {
	file_proto_staking_model_proto_rawDescOnce.Do(func() {
		file_proto_staking_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_staking_model_proto_rawDesc), len(file_proto_staking_model_proto_rawDesc)))
	})
	return file_proto_staking_model_proto_rawDescData
}

var file_proto_staking_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_staking_model_proto_goTypes = []any{
	(*StakeProduct)(nil),   // 0: staking.StakeProduct
	(*StakeOrder)(nil),     // 1: staking.StakeOrder
	(*StakeRewardLog)(nil), // 2: staking.StakeRewardLog
	(*StakeRedeemLog)(nil), // 3: staking.StakeRedeemLog
	(ProductType)(0),       // 4: staking.ProductType
	(InterestMode)(0),      // 5: staking.InterestMode
	(RewardMode)(0),        // 6: staking.RewardMode
	(YesNo)(0),             // 7: staking.YesNo
	(ProductStatus)(0),     // 8: staking.ProductStatus
	(OrderStatus)(0),       // 9: staking.OrderStatus
	(RedeemType)(0),        // 10: staking.RedeemType
	(SourceType)(0),        // 11: staking.SourceType
	(RewardType)(0),        // 12: staking.RewardType
	(RewardStatus)(0),      // 13: staking.RewardStatus
	(RedeemStatus)(0),      // 14: staking.RedeemStatus
}
var file_proto_staking_model_proto_depIdxs = []int32{
	4,  // 0: staking.StakeProduct.product_type:type_name -> staking.ProductType
	5,  // 1: staking.StakeProduct.interest_mode:type_name -> staking.InterestMode
	6,  // 2: staking.StakeProduct.reward_mode:type_name -> staking.RewardMode
	7,  // 3: staking.StakeProduct.allow_early_redeem:type_name -> staking.YesNo
	8,  // 4: staking.StakeProduct.status:type_name -> staking.ProductStatus
	4,  // 5: staking.StakeOrder.product_type:type_name -> staking.ProductType
	5,  // 6: staking.StakeOrder.interest_mode:type_name -> staking.InterestMode
	6,  // 7: staking.StakeOrder.reward_mode:type_name -> staking.RewardMode
	7,  // 8: staking.StakeOrder.allow_early_redeem:type_name -> staking.YesNo
	9,  // 9: staking.StakeOrder.status:type_name -> staking.OrderStatus
	10, // 10: staking.StakeOrder.redeem_type:type_name -> staking.RedeemType
	11, // 11: staking.StakeOrder.source:type_name -> staking.SourceType
	12, // 12: staking.StakeRewardLog.reward_type:type_name -> staking.RewardType
	13, // 13: staking.StakeRewardLog.reward_status:type_name -> staking.RewardStatus
	10, // 14: staking.StakeRedeemLog.redeem_type:type_name -> staking.RedeemType
	14, // 15: staking.StakeRedeemLog.redeem_status:type_name -> staking.RedeemStatus
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_staking_model_proto_init() }
func file_proto_staking_model_proto_init() {
	if File_proto_staking_model_proto != nil {
		return
	}
	file_proto_staking_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_staking_model_proto_rawDesc), len(file_proto_staking_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_staking_model_proto_goTypes,
		DependencyIndexes: file_proto_staking_model_proto_depIdxs,
		MessageInfos:      file_proto_staking_model_proto_msgTypes,
	}.Build()
	File_proto_staking_model_proto = out.File
	file_proto_staking_model_proto_goTypes = nil
	file_proto_staking_model_proto_depIdxs = nil
}
