// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	chat_agent "chat-admin-api/internal/handler/chat_agent"
	chat_auth "chat-admin-api/internal/handler/chat_auth"
	chat_category "chat-admin-api/internal/handler/chat_category"
	chat_group "chat-admin-api/internal/handler/chat_group"
	chat_quick_reply "chat-admin-api/internal/handler/chat_quick_reply"
	chat_session "chat-admin-api/internal/handler/chat_session"
	chat_work_order "chat-admin-api/internal/handler/chat_work_order"
	"chat-admin-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/agents",
					Handler: chat_agent.CreateChatAgentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/agents",
					Handler: chat_agent.PageChatAgentsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/agents/:id",
					Handler: chat_agent.GetChatAgentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/agents/:id",
					Handler: chat_agent.UpdateChatAgentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/agents/:id/status",
					Handler: chat_agent.UpdateChatAgentStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/chat/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: chat_auth.LoginHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/chat/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: chat_auth.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/options",
					Handler: chat_auth.OptionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: chat_auth.ProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/profile",
					Handler: chat_auth.UpdateProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/profile/avatar",
					Handler: chat_auth.UploadProfileAvatarHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/chat/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/categories",
					Handler: chat_category.CreateChatCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/categories",
					Handler: chat_category.PageChatCategoriesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/categories/:id",
					Handler: chat_category.GetChatCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/categories/:id",
					Handler: chat_category.UpdateChatCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/categories/:id",
					Handler: chat_category.DeleteChatCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/categories/enabled",
					Handler: chat_category.ListEnabledChatCategoriesHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/chat/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/groups",
					Handler: chat_group.CreateChatGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groups",
					Handler: chat_group.PageChatGroupsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groups/:id",
					Handler: chat_group.GetChatGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/groups/:id",
					Handler: chat_group.UpdateChatGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/groups/:id",
					Handler: chat_group.DeleteChatGroupHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/chat/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/quick-replies",
					Handler: chat_quick_reply.CreateChatQuickReplyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/quick-replies",
					Handler: chat_quick_reply.PageChatQuickRepliesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/quick-replies/:id",
					Handler: chat_quick_reply.GetChatQuickReplyHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/quick-replies/:id",
					Handler: chat_quick_reply.UpdateChatQuickReplyHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/quick-replies/:id",
					Handler: chat_quick_reply.DeleteChatQuickReplyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/quick-replies/enabled",
					Handler: chat_quick_reply.ListEnabledChatQuickRepliesHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/chat/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/sessions",
					Handler: chat_session.PageChatSessionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/sessions/:sessionNo",
					Handler: chat_session.GetChatSessionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/sessions/:sessionNo/close",
					Handler: chat_session.CloseChatSessionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/sessions/:sessionNo/messages",
					Handler: chat_session.PageChatMessagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/sessions/:sessionNo/read",
					Handler: chat_session.MarkAgentMessagesReadHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/chat/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/work-orders",
					Handler: chat_work_order.CreateChatWorkOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/work-orders",
					Handler: chat_work_order.PageChatWorkOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/work-orders/:id",
					Handler: chat_work_order.GetChatWorkOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/work-orders/:id",
					Handler: chat_work_order.UpdateChatWorkOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/work-orders/:id",
					Handler: chat_work_order.DeleteChatWorkOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/work-orders/:id/handle",
					Handler: chat_work_order.HandleChatWorkOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/chat/admin"),
	)
}
