// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: chat.proto

package chatinternal

import (
	"context"

	"wklive/proto/chat"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcceptChatSessionReq           = chat.AcceptChatSessionReq
	AcceptChatSessionResp          = chat.AcceptChatSessionResp
	AcceptChatSessionUser          = chat.AcceptChatSessionUser
	AdminChatAgentResp             = chat.AdminChatAgentResp
	AdminChatCategoryResp          = chat.AdminChatCategoryResp
	AdminChatConfigResp            = chat.AdminChatConfigResp
	AdminChatGroupResp             = chat.AdminChatGroupResp
	AdminChatMessageResp           = chat.AdminChatMessageResp
	AdminChatQuickReplyResp        = chat.AdminChatQuickReplyResp
	AdminChatSessionResp           = chat.AdminChatSessionResp
	AdminChatSubscribeRequest      = chat.AdminChatSubscribeRequest
	AdminChatWorkOrderResp         = chat.AdminChatWorkOrderResp
	AdminCommonResp                = chat.AdminCommonResp
	AdminMarkMessagesReadResp      = chat.AdminMarkMessagesReadResp
	AppChatConfigResp              = chat.AppChatConfigResp
	AppChatMessageResp             = chat.AppChatMessageResp
	AppChatSatisfactionResp        = chat.AppChatSatisfactionResp
	AppChatSessionResp             = chat.AppChatSessionResp
	AppChatSubscribeRequest        = chat.AppChatSubscribeRequest
	AppCommonResp                  = chat.AppCommonResp
	AppListChatMessagesResp        = chat.AppListChatMessagesResp
	AuthChatMerchantData           = chat.AuthChatMerchantData
	AuthChatMerchantReq            = chat.AuthChatMerchantReq
	AuthChatMerchantResp           = chat.AuthChatMerchantResp
	ChatAdminLoginData             = chat.ChatAdminLoginData
	ChatAdminLoginReq              = chat.ChatAdminLoginReq
	ChatAdminLoginResp             = chat.ChatAdminLoginResp
	ChatAdminLogoutReq             = chat.ChatAdminLogoutReq
	ChatAdminProfileReq            = chat.ChatAdminProfileReq
	ChatAdminProfileResp           = chat.ChatAdminProfileResp
	ChatAppConfig                  = chat.ChatAppConfig
	CloseChatSessionReq            = chat.CloseChatSessionReq
	CloseMyChatSessionReq          = chat.CloseMyChatSessionReq
	CreateChatAgentReq             = chat.CreateChatAgentReq
	CreateChatCategoryReq          = chat.CreateChatCategoryReq
	CreateChatGroupReq             = chat.CreateChatGroupReq
	CreateChatQuickReplyReq        = chat.CreateChatQuickReplyReq
	CreateChatWorkOrderReq         = chat.CreateChatWorkOrderReq
	DeleteChatCategoryReq          = chat.DeleteChatCategoryReq
	DeleteChatGroupReq             = chat.DeleteChatGroupReq
	DeleteChatQuickReplyReq        = chat.DeleteChatQuickReplyReq
	DeleteChatWorkOrderReq         = chat.DeleteChatWorkOrderReq
	GenerateChatSessionNoReq       = chat.GenerateChatSessionNoReq
	GenerateChatSessionNoResp      = chat.GenerateChatSessionNoResp
	GetAppChatConfigReq            = chat.GetAppChatConfigReq
	GetChatAgentReq                = chat.GetChatAgentReq
	GetChatCategoryReq             = chat.GetChatCategoryReq
	GetChatConfigReq               = chat.GetChatConfigReq
	GetChatGroupReq                = chat.GetChatGroupReq
	GetChatQuickReplyReq           = chat.GetChatQuickReplyReq
	GetChatSessionByUserReq        = chat.GetChatSessionByUserReq
	GetChatSessionReq              = chat.GetChatSessionReq
	GetChatUserByIdReq             = chat.GetChatUserByIdReq
	GetChatUserByIdResp            = chat.GetChatUserByIdResp
	GetChatWorkOrderReq            = chat.GetChatWorkOrderReq
	HandleChatWorkOrderReq         = chat.HandleChatWorkOrderReq
	ListChatCategoriesResp         = chat.ListChatCategoriesResp
	ListChatQuickRepliesResp       = chat.ListChatQuickRepliesResp
	ListEnabledChatCategoriesReq   = chat.ListEnabledChatCategoriesReq
	ListEnabledChatQuickRepliesReq = chat.ListEnabledChatQuickRepliesReq
	ListMyChatMessagesReq          = chat.ListMyChatMessagesReq
	MarkAgentMessagesReadReq       = chat.MarkAgentMessagesReadReq
	OpenChatSessionReq             = chat.OpenChatSessionReq
	OpenChatSessionResp            = chat.OpenChatSessionResp
	OperateAgentMessageReq         = chat.OperateAgentMessageReq
	OperateUserMessageReq          = chat.OperateUserMessageReq
	PageChatAgentsReq              = chat.PageChatAgentsReq
	PageChatAgentsResp             = chat.PageChatAgentsResp
	PageChatCategoriesReq          = chat.PageChatCategoriesReq
	PageChatCategoriesResp         = chat.PageChatCategoriesResp
	PageChatGroupsReq              = chat.PageChatGroupsReq
	PageChatGroupsResp             = chat.PageChatGroupsResp
	PageChatMessagesReq            = chat.PageChatMessagesReq
	PageChatMessagesResp           = chat.PageChatMessagesResp
	PageChatQuickRepliesReq        = chat.PageChatQuickRepliesReq
	PageChatQuickRepliesResp       = chat.PageChatQuickRepliesResp
	PageChatSessionsReq            = chat.PageChatSessionsReq
	PageChatSessionsResp           = chat.PageChatSessionsResp
	PageChatWorkOrdersReq          = chat.PageChatWorkOrdersReq
	PageChatWorkOrdersResp         = chat.PageChatWorkOrdersResp
	SendAgentMessageReq            = chat.SendAgentMessageReq
	SendAgentTypingReq             = chat.SendAgentTypingReq
	SendUserMessageReq             = chat.SendUserMessageReq
	SendUserTypingReq              = chat.SendUserTypingReq
	SubmitChatSatisfactionReq      = chat.SubmitChatSatisfactionReq
	SyncChatMerchantUserReq        = chat.SyncChatMerchantUserReq
	SyncChatMerchantUserResp       = chat.SyncChatMerchantUserResp
	UpdateChatAdminProfileReq      = chat.UpdateChatAdminProfileReq
	UpdateChatAgentReq             = chat.UpdateChatAgentReq
	UpdateChatAgentStatusReq       = chat.UpdateChatAgentStatusReq
	UpdateChatCategoryReq          = chat.UpdateChatCategoryReq
	UpdateChatConfigReq            = chat.UpdateChatConfigReq
	UpdateChatGroupReq             = chat.UpdateChatGroupReq
	UpdateChatQuickReplyReq        = chat.UpdateChatQuickReplyReq
	UpdateChatWorkOrderReq         = chat.UpdateChatWorkOrderReq

	ChatInternal interface {
		// 同步客服商户主账号
		SyncChatMerchantUser(ctx context.Context, in *SyncChatMerchantUserReq, opts ...grpc.CallOption) (*SyncChatMerchantUserResp, error)
	}

	defaultChatInternal struct {
		cli zrpc.Client
	}
)

func NewChatInternal(cli zrpc.Client) ChatInternal {
	return &defaultChatInternal{
		cli: cli,
	}
}

// 同步客服商户主账号
func (m *defaultChatInternal) SyncChatMerchantUser(ctx context.Context, in *SyncChatMerchantUserReq, opts ...grpc.CallOption) (*SyncChatMerchantUserResp, error) {
	client := chat.NewChatInternalClient(m.cli.Conn())
	return client.SyncChatMerchantUser(ctx, in, opts...)
}
