**

!admin-ui
!admin-ui/**
!app-packages
!app-packages/**
!app-web
!app-web/**
!chat-admin-ui
!chat-admin-ui/**
!liquidity-admin-ui
!liquidity-admin-ui/**
!deploy
!deploy/common
!deploy/common/docker
!deploy/common/docker/Dockerfile.web
!deploy/common/config
!deploy/common/config/nginx-spa.conf.template

**/node_modules
**/dist
**/coverage
**/*.log
**/.DS_Store
