// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tUserIdentityFieldNames          = builder.RawFieldNames(&TUserIdentity{})
	tUserIdentityRows                = strings.Join(tUserIdentityFieldNames, ",")
	tUserIdentityRowsExpectAutoSet   = strings.Join(stringx.Remove(tUserIdentityFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tUserIdentityRowsWithPlaceHolder = strings.Join(stringx.Remove(tUserIdentityFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTUserIdentityIdPrefix             = "cache:tUserIdentity:id:"
	cacheTUserIdentityTenantIdEmailPrefix  = "cache:tUserIdentity:tenantId:email:"
	cacheTUserIdentityTenantIdPhonePrefix  = "cache:tUserIdentity:tenantId:phone:"
	cacheTUserIdentityTenantIdUserIdPrefix = "cache:tUserIdentity:tenantId:userId:"
)

type (
	tUserIdentityModel interface {
		Insert(ctx context.Context, data *TUserIdentity) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TUserIdentity, error)
		FindOneByTenantIdEmail(ctx context.Context, tenantId int64, email sql.NullString) (*TUserIdentity, error)
		FindOneByTenantIdPhone(ctx context.Context, tenantId int64, phone sql.NullString) (*TUserIdentity, error)
		FindOneByTenantIdUserId(ctx context.Context, tenantId int64, userId int64) (*TUserIdentity, error)
		Update(ctx context.Context, data *TUserIdentity) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTUserIdentityModel struct {
		sqlc.CachedConn
		table string
	}

	TUserIdentity struct {
		Id            int64          `db:"id"`             // 主键ID
		TenantId      int64          `db:"tenant_id"`      // 租户ID
		UserId        int64          `db:"user_id"`        // 用户ID
		Phone         sql.NullString `db:"phone"`          // 手机号
		Email         sql.NullString `db:"email"`          // 邮箱
		RealName      sql.NullString `db:"real_name"`      // 真实姓名
		Gender        int64          `db:"gender"`         // 性别：0未知 1男 2女
		Birthday      sql.NullTime   `db:"birthday"`       // 生日
		CountryCode   sql.NullString `db:"country_code"`   // 国家/地区代码
		Province      sql.NullString `db:"province"`       // 省/州
		City          sql.NullString `db:"city"`           // 城市
		Address       sql.NullString `db:"address"`        // 地址
		IdType        int64          `db:"id_type"`        // 证件类型：0未提交 1身份证 2护照 3驾驶证
		IdNo          sql.NullString `db:"id_no"`          // 证件号码
		FrontImage    sql.NullString `db:"front_image"`    // 证件正面
		BackImage     sql.NullString `db:"back_image"`     // 证件反面
		HandheldImage sql.NullString `db:"handheld_image"` // 手持证件照
		KycLevel      int64          `db:"kyc_level"`      // KYC等级：0未认证 1初级 2高级
		VerifyStatus  int64          `db:"verify_status"`  // 实名状态：0未提交 1审核中 2通过 3拒绝
		RejectReason  sql.NullString `db:"reject_reason"`  // 驳回原因
		SubmitTime    int64          `db:"submit_time"`    // 提交时间
		VerifyTime    int64          `db:"verify_time"`    // 审核时间
		VerifyBy      sql.NullInt64  `db:"verify_by"`      // 审核人
		CreateTimes   int64          `db:"create_times"`   // 创建时间
		UpdateTimes   int64          `db:"update_times"`   // 更新时间
	}
)

func newTUserIdentityModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTUserIdentityModel {
	return &defaultTUserIdentityModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_user_identity`",
	}
}

func (m *defaultTUserIdentityModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tUserIdentityIdKey := fmt.Sprintf("%s%v", cacheTUserIdentityIdPrefix, id)
	tUserIdentityTenantIdEmailKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdEmailPrefix, data.TenantId, data.Email)
	tUserIdentityTenantIdPhoneKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdPhonePrefix, data.TenantId, data.Phone)
	tUserIdentityTenantIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdUserIdPrefix, data.TenantId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tUserIdentityIdKey, tUserIdentityTenantIdEmailKey, tUserIdentityTenantIdPhoneKey, tUserIdentityTenantIdUserIdKey)
	return err
}

func (m *defaultTUserIdentityModel) FindOne(ctx context.Context, id int64) (*TUserIdentity, error) {
	tUserIdentityIdKey := fmt.Sprintf("%s%v", cacheTUserIdentityIdPrefix, id)
	var resp TUserIdentity
	err := m.QueryRowCtx(ctx, &resp, tUserIdentityIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUserIdentityRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserIdentityModel) FindOneByTenantIdEmail(ctx context.Context, tenantId int64, email sql.NullString) (*TUserIdentity, error) {
	tUserIdentityTenantIdEmailKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdEmailPrefix, tenantId, email)
	var resp TUserIdentity
	err := m.QueryRowIndexCtx(ctx, &resp, tUserIdentityTenantIdEmailKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `email` = ? limit 1", tUserIdentityRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, email); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserIdentityModel) FindOneByTenantIdPhone(ctx context.Context, tenantId int64, phone sql.NullString) (*TUserIdentity, error) {
	tUserIdentityTenantIdPhoneKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdPhonePrefix, tenantId, phone)
	var resp TUserIdentity
	err := m.QueryRowIndexCtx(ctx, &resp, tUserIdentityTenantIdPhoneKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `phone` = ? limit 1", tUserIdentityRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, phone); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserIdentityModel) FindOneByTenantIdUserId(ctx context.Context, tenantId int64, userId int64) (*TUserIdentity, error) {
	tUserIdentityTenantIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdUserIdPrefix, tenantId, userId)
	var resp TUserIdentity
	err := m.QueryRowIndexCtx(ctx, &resp, tUserIdentityTenantIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `user_id` = ? limit 1", tUserIdentityRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserIdentityModel) Insert(ctx context.Context, data *TUserIdentity) (sql.Result, error) {
	tUserIdentityIdKey := fmt.Sprintf("%s%v", cacheTUserIdentityIdPrefix, data.Id)
	tUserIdentityTenantIdEmailKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdEmailPrefix, data.TenantId, data.Email)
	tUserIdentityTenantIdPhoneKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdPhonePrefix, data.TenantId, data.Phone)
	tUserIdentityTenantIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdUserIdPrefix, data.TenantId, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tUserIdentityRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.UserId, data.Phone, data.Email, data.RealName, data.Gender, data.Birthday, data.CountryCode, data.Province, data.City, data.Address, data.IdType, data.IdNo, data.FrontImage, data.BackImage, data.HandheldImage, data.KycLevel, data.VerifyStatus, data.RejectReason, data.SubmitTime, data.VerifyTime, data.VerifyBy, data.CreateTimes, data.UpdateTimes)
	}, tUserIdentityIdKey, tUserIdentityTenantIdEmailKey, tUserIdentityTenantIdPhoneKey, tUserIdentityTenantIdUserIdKey)
	return ret, err
}

func (m *defaultTUserIdentityModel) Update(ctx context.Context, newData *TUserIdentity) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tUserIdentityIdKey := fmt.Sprintf("%s%v", cacheTUserIdentityIdPrefix, data.Id)
	tUserIdentityTenantIdEmailKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdEmailPrefix, data.TenantId, data.Email)
	tUserIdentityTenantIdPhoneKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdPhonePrefix, data.TenantId, data.Phone)
	tUserIdentityTenantIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheTUserIdentityTenantIdUserIdPrefix, data.TenantId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tUserIdentityRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.UserId, newData.Phone, newData.Email, newData.RealName, newData.Gender, newData.Birthday, newData.CountryCode, newData.Province, newData.City, newData.Address, newData.IdType, newData.IdNo, newData.FrontImage, newData.BackImage, newData.HandheldImage, newData.KycLevel, newData.VerifyStatus, newData.RejectReason, newData.SubmitTime, newData.VerifyTime, newData.VerifyBy, newData.CreateTimes, newData.UpdateTimes, newData.Id)
	}, tUserIdentityIdKey, tUserIdentityTenantIdEmailKey, tUserIdentityTenantIdPhoneKey, tUserIdentityTenantIdUserIdKey)
	return err
}

func (m *defaultTUserIdentityModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTUserIdentityIdPrefix, primary)
}

func (m *defaultTUserIdentityModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUserIdentityRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTUserIdentityModel) tableName() string {
	return m.table
}
