// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/payment/model.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayPlatform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                   // 平台ID
	PlatformCode  string                 `protobuf:"bytes,2,opt,name=platform_code,json=platformCode,proto3" json:"platform_code,omitempty"`                            // 平台编码，如 alipay/wechat/stripe/usdt/bank
	PlatformName  string                 `protobuf:"bytes,3,opt,name=platform_name,json=platformName,proto3" json:"platform_name,omitempty"`                            // 平台名称
	PlatformType  PlatformType           `protobuf:"varint,4,opt,name=platform_type,json=platformType,proto3,enum=payment.PlatformType" json:"platform_type,omitempty"` // 类型：1三方支付 2银行转账 3链上支付 4人工代收
	NotifyUrl     string                 `protobuf:"bytes,5,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`                                     // 统一异步通知地址
	ReturnUrl     string                 `protobuf:"bytes,6,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`                                     // 默认同步跳转地址
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`                                                                // 图标
	Status        CommonStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=payment.CommonStatus" json:"status,omitempty"`                                 // 状态：1启用 2停用
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`                                                            // 备注
	CreateTimes   int64                  `protobuf:"varint,10,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`                             // 创建时间
	UpdateTimes   int64                  `protobuf:"varint,11,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`                             // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayPlatform) Reset() {
	*x = PayPlatform{}
	mi := &file_proto_payment_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPlatform) ProtoMessage() {}

func (x *PayPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPlatform.ProtoReflect.Descriptor instead.
func (*PayPlatform) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{0}
}

func (x *PayPlatform) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PayPlatform) GetPlatformCode() string {
	if x != nil {
		return x.PlatformCode
	}
	return ""
}

func (x *PayPlatform) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

func (x *PayPlatform) GetPlatformType() PlatformType {
	if x != nil {
		return x.PlatformType
	}
	return PlatformType_PLATFORM_TYPE_UNKNOWN
}

func (x *PayPlatform) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *PayPlatform) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *PayPlatform) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PayPlatform) GetStatus() CommonStatus {
	if x != nil {
		return x.Status
	}
	return CommonStatus_COMMON_STATUS_UNKNOWN
}

func (x *PayPlatform) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PayPlatform) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *PayPlatform) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

type PayProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                       // 产品ID
	PlatformId    int64                  `protobuf:"varint,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`                     // 平台ID
	ProductCode   string                 `protobuf:"bytes,3,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`                   // 产品编码
	ProductName   string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`                   // 产品名称
	SceneType     SceneType              `protobuf:"varint,5,opt,name=scene_type,json=sceneType,proto3,enum=payment.SceneType" json:"scene_type,omitempty"` // 场景：1APP 2H5 3WEB 4收银台 5链上
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`                                            // 币种
	Status        CommonStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=payment.CommonStatus" json:"status,omitempty"`                     // 状态：1启用 2停用
	Remark        string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`                                                // 备注
	CreateTimes   int64                  `protobuf:"varint,9,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`                  // 创建时间
	UpdateTimes   int64                  `protobuf:"varint,10,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`                 // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayProduct) Reset() {
	*x = PayProduct{}
	mi := &file_proto_payment_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayProduct) ProtoMessage() {}

func (x *PayProduct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayProduct.ProtoReflect.Descriptor instead.
func (*PayProduct) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{1}
}

func (x *PayProduct) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PayProduct) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *PayProduct) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *PayProduct) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *PayProduct) GetSceneType() SceneType {
	if x != nil {
		return x.SceneType
	}
	return SceneType_SCENE_TYPE_UNKNOWN
}

func (x *PayProduct) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PayProduct) GetStatus() CommonStatus {
	if x != nil {
		return x.Status
	}
	return CommonStatus_COMMON_STATUS_UNKNOWN
}

func (x *PayProduct) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PayProduct) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *PayProduct) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

type TenantPayPlatform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                           // 主键ID
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                               // 租户ID
	PlatformId    int64                  `protobuf:"varint,3,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`                         // 平台ID
	Status        CommonStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=payment.CommonStatus" json:"status,omitempty"`                         // 状态：1启用 2停用
	OpenStatus    OpenStatus             `protobuf:"varint,5,opt,name=open_status,json=openStatus,proto3,enum=payment.OpenStatus" json:"open_status,omitempty"` // 开通状态：1待配置 2已开通 3审核中 4驳回
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`                                                    // 备注
	CreateTimes   int64                  `protobuf:"varint,7,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`                      // 创建时间
	UpdateTimes   int64                  `protobuf:"varint,8,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`                      // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPayPlatform) Reset() {
	*x = TenantPayPlatform{}
	mi := &file_proto_payment_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPayPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPayPlatform) ProtoMessage() {}

func (x *TenantPayPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPayPlatform.ProtoReflect.Descriptor instead.
func (*TenantPayPlatform) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{2}
}

func (x *TenantPayPlatform) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantPayPlatform) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TenantPayPlatform) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *TenantPayPlatform) GetStatus() CommonStatus {
	if x != nil {
		return x.Status
	}
	return CommonStatus_COMMON_STATUS_UNKNOWN
}

func (x *TenantPayPlatform) GetOpenStatus() OpenStatus {
	if x != nil {
		return x.OpenStatus
	}
	return OpenStatus_OPEN_STATUS_UNKNOWN
}

func (x *TenantPayPlatform) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TenantPayPlatform) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *TenantPayPlatform) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

type TenantPayAccount struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                  // 账号ID
	TenantId            int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                      // 租户ID
	TenantPayPlatformId int64                  `protobuf:"varint,3,opt,name=tenant_pay_platform_id,json=tenantPayPlatformId,proto3" json:"tenant_pay_platform_id,omitempty"` // 租户开通平台ID
	PlatformId          int64                  `protobuf:"varint,4,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`                                // 平台ID
	AccountCode         string                 `protobuf:"bytes,5,opt,name=account_code,json=accountCode,proto3" json:"account_code,omitempty"`                              // 账号编码
	AccountName         string                 `protobuf:"bytes,6,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`                              // 账号名称
	AppId               string                 `protobuf:"bytes,7,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                                                // 应用ID
	MerchantId          string                 `protobuf:"bytes,8,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`                                 // 商户号
	MerchantName        string                 `protobuf:"bytes,9,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`                           // 商户名称
	PublicKey           string                 `protobuf:"bytes,10,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                                   // 公钥
	ExtConfig           string                 `protobuf:"bytes,11,opt,name=ext_config,json=extConfig,proto3" json:"ext_config,omitempty"`                                   // 扩展配置(JSON)
	Status              CommonStatus           `protobuf:"varint,12,opt,name=status,proto3,enum=payment.CommonStatus" json:"status,omitempty"`                               // 状态：1启用 2停用
	IsDefault           int64                  `protobuf:"varint,13,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`                                  // 是否默认账号：0否 1是
	Remark              string                 `protobuf:"bytes,14,opt,name=remark,proto3" json:"remark,omitempty"`                                                          // 备注
	CreateTimes         int64                  `protobuf:"varint,15,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`                            // 创建时间
	UpdateTimes         int64                  `protobuf:"varint,16,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`                            // 更新时间
	ApiKeyCipher        string                 `protobuf:"bytes,17,opt,name=api_key_cipher,json=apiKeyCipher,proto3" json:"api_key_cipher,omitempty"`                        // API Key密文
	ApiSecretCipher     string                 `protobuf:"bytes,18,opt,name=api_secret_cipher,json=apiSecretCipher,proto3" json:"api_secret_cipher,omitempty"`               // API Secret密文
	PrivateKeyCipher    string                 `protobuf:"bytes,19,opt,name=private_key_cipher,json=privateKeyCipher,proto3" json:"private_key_cipher,omitempty"`            // 私钥密文
	CertCipher          string                 `protobuf:"bytes,20,opt,name=cert_cipher,json=certCipher,proto3" json:"cert_cipher,omitempty"`                                // 证书密文
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TenantPayAccount) Reset() {
	*x = TenantPayAccount{}
	mi := &file_proto_payment_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPayAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPayAccount) ProtoMessage() {}

func (x *TenantPayAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPayAccount.ProtoReflect.Descriptor instead.
func (*TenantPayAccount) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{3}
}

func (x *TenantPayAccount) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantPayAccount) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TenantPayAccount) GetTenantPayPlatformId() int64 {
	if x != nil {
		return x.TenantPayPlatformId
	}
	return 0
}

func (x *TenantPayAccount) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *TenantPayAccount) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

func (x *TenantPayAccount) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *TenantPayAccount) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *TenantPayAccount) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *TenantPayAccount) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *TenantPayAccount) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *TenantPayAccount) GetExtConfig() string {
	if x != nil {
		return x.ExtConfig
	}
	return ""
}

func (x *TenantPayAccount) GetStatus() CommonStatus {
	if x != nil {
		return x.Status
	}
	return CommonStatus_COMMON_STATUS_UNKNOWN
}

func (x *TenantPayAccount) GetIsDefault() int64 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *TenantPayAccount) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TenantPayAccount) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *TenantPayAccount) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

func (x *TenantPayAccount) GetApiKeyCipher() string {
	if x != nil {
		return x.ApiKeyCipher
	}
	return ""
}

func (x *TenantPayAccount) GetApiSecretCipher() string {
	if x != nil {
		return x.ApiSecretCipher
	}
	return ""
}

func (x *TenantPayAccount) GetPrivateKeyCipher() string {
	if x != nil {
		return x.PrivateKeyCipher
	}
	return ""
}

func (x *TenantPayAccount) GetCertCipher() string {
	if x != nil {
		return x.CertCipher
	}
	return ""
}

type TenantPayChannel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                     // 通道ID
	TenantId        int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                         // 租户ID
	PlatformId      int64                  `protobuf:"varint,3,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`                   // 平台ID
	ProductId       int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`                      // 产品ID
	AccountId       int64                  `protobuf:"varint,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                      // 租户支付账号ID
	ChannelCode     string                 `protobuf:"bytes,6,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`                 // 通道编码
	ChannelName     string                 `protobuf:"bytes,7,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`                 // 通道名称
	DisplayName     string                 `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`                 // 前端展示名称
	Icon            string                 `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty"`                                                  // 图标
	Currency        string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`                                         // 币种
	Sort            int64                  `protobuf:"varint,11,opt,name=sort,proto3" json:"sort,omitempty"`                                                // 排序
	Visible         int64                  `protobuf:"varint,12,opt,name=visible,proto3" json:"visible,omitempty"`                                          // 是否显示：0否 1是
	Status          CommonStatus           `protobuf:"varint,13,opt,name=status,proto3,enum=payment.CommonStatus" json:"status,omitempty"`                  // 状态：1启用 2停用
	SingleMinAmount int64                  `protobuf:"varint,14,opt,name=single_min_amount,json=singleMinAmount,proto3" json:"single_min_amount,omitempty"` // 单笔最小金额，单位分
	SingleMaxAmount int64                  `protobuf:"varint,15,opt,name=single_max_amount,json=singleMaxAmount,proto3" json:"single_max_amount,omitempty"` // 单笔最大金额，0表示不限制，单位分
	DailyMaxAmount  int64                  `protobuf:"varint,16,opt,name=daily_max_amount,json=dailyMaxAmount,proto3" json:"daily_max_amount,omitempty"`    // 单日最大金额，0表示不限制，单位分
	DailyMaxCount   int64                  `protobuf:"varint,17,opt,name=daily_max_count,json=dailyMaxCount,proto3" json:"daily_max_count,omitempty"`       // 单日最大次数，0表示不限制
	FeeType         FeeType                `protobuf:"varint,18,opt,name=fee_type,json=feeType,proto3,enum=payment.FeeType" json:"fee_type,omitempty"`      // 手续费类型：1比例 2固定
	FeeRate         string                 `protobuf:"bytes,19,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`                            // 手续费比例
	FeeFixedAmount  int64                  `protobuf:"varint,20,opt,name=fee_fixed_amount,json=feeFixedAmount,proto3" json:"fee_fixed_amount,omitempty"`    // 固定手续费，单位分
	ExtConfig       string                 `protobuf:"bytes,21,opt,name=ext_config,json=extConfig,proto3" json:"ext_config,omitempty"`                      // 扩展配置(JSON)
	Remark          string                 `protobuf:"bytes,22,opt,name=remark,proto3" json:"remark,omitempty"`                                             // 备注
	CreateTimes     int64                  `protobuf:"varint,23,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`               // 创建时间
	UpdateTimes     int64                  `protobuf:"varint,24,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`               // 更新时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TenantPayChannel) Reset() {
	*x = TenantPayChannel{}
	mi := &file_proto_payment_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPayChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPayChannel) ProtoMessage() {}

func (x *TenantPayChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPayChannel.ProtoReflect.Descriptor instead.
func (*TenantPayChannel) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{4}
}

func (x *TenantPayChannel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantPayChannel) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TenantPayChannel) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *TenantPayChannel) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *TenantPayChannel) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TenantPayChannel) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *TenantPayChannel) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *TenantPayChannel) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TenantPayChannel) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *TenantPayChannel) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TenantPayChannel) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *TenantPayChannel) GetVisible() int64 {
	if x != nil {
		return x.Visible
	}
	return 0
}

func (x *TenantPayChannel) GetStatus() CommonStatus {
	if x != nil {
		return x.Status
	}
	return CommonStatus_COMMON_STATUS_UNKNOWN
}

func (x *TenantPayChannel) GetSingleMinAmount() int64 {
	if x != nil {
		return x.SingleMinAmount
	}
	return 0
}

func (x *TenantPayChannel) GetSingleMaxAmount() int64 {
	if x != nil {
		return x.SingleMaxAmount
	}
	return 0
}

func (x *TenantPayChannel) GetDailyMaxAmount() int64 {
	if x != nil {
		return x.DailyMaxAmount
	}
	return 0
}

func (x *TenantPayChannel) GetDailyMaxCount() int64 {
	if x != nil {
		return x.DailyMaxCount
	}
	return 0
}

func (x *TenantPayChannel) GetFeeType() FeeType {
	if x != nil {
		return x.FeeType
	}
	return FeeType_FEE_TYPE_UNKNOWN
}

func (x *TenantPayChannel) GetFeeRate() string {
	if x != nil {
		return x.FeeRate
	}
	return ""
}

func (x *TenantPayChannel) GetFeeFixedAmount() int64 {
	if x != nil {
		return x.FeeFixedAmount
	}
	return 0
}

func (x *TenantPayChannel) GetExtConfig() string {
	if x != nil {
		return x.ExtConfig
	}
	return ""
}

func (x *TenantPayChannel) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TenantPayChannel) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *TenantPayChannel) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

type TenantPayChannelRule struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                      // 规则ID
	TenantId             int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                          // 租户ID
	ChannelId            int64                  `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                                       // 通道ID
	RuleName             string                 `protobuf:"bytes,4,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`                                           // 规则名称
	Priority             int64                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                                          // 优先级，越小越优先
	Status               CommonStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=payment.CommonStatus" json:"status,omitempty"`                                    // 状态：1启用 2停用
	SingleAmountMin      int64                  `protobuf:"varint,7,opt,name=single_amount_min,json=singleAmountMin,proto3" json:"single_amount_min,omitempty"`                   // 单笔充值最小金额，单位分
	SingleAmountMax      int64                  `protobuf:"varint,8,opt,name=single_amount_max,json=singleAmountMax,proto3" json:"single_amount_max,omitempty"`                   // 单笔充值最大金额，0表示不限制，单位分
	UserTotalRechargeMin int64                  `protobuf:"varint,9,opt,name=user_total_recharge_min,json=userTotalRechargeMin,proto3" json:"user_total_recharge_min,omitempty"`  // 用户累计充值最小金额，单位分
	UserTotalRechargeMax int64                  `protobuf:"varint,10,opt,name=user_total_recharge_max,json=userTotalRechargeMax,proto3" json:"user_total_recharge_max,omitempty"` // 用户累计充值最大金额，0表示不限制，单位分
	MemberLevelMin       int64                  `protobuf:"varint,11,opt,name=member_level_min,json=memberLevelMin,proto3" json:"member_level_min,omitempty"`                     // 会员等级最小值
	MemberLevelMax       int64                  `protobuf:"varint,12,opt,name=member_level_max,json=memberLevelMax,proto3" json:"member_level_max,omitempty"`                     // 会员等级最大值，0表示不限制
	KycLevelMin          int64                  `protobuf:"varint,13,opt,name=kyc_level_min,json=kycLevelMin,proto3" json:"kyc_level_min,omitempty"`                              // KYC等级最小值
	KycLevelMax          int64                  `protobuf:"varint,14,opt,name=kyc_level_max,json=kycLevelMax,proto3" json:"kyc_level_max,omitempty"`                              // KYC等级最大值，0表示不限制
	AllowNewUser         int64                  `protobuf:"varint,15,opt,name=allow_new_user,json=allowNewUser,proto3" json:"allow_new_user,omitempty"`                           // 是否允许新用户：0否 1是
	AllowOldUser         int64                  `protobuf:"varint,16,opt,name=allow_old_user,json=allowOldUser,proto3" json:"allow_old_user,omitempty"`                           // 是否允许老用户：0否 1是
	AllowTags            string                 `protobuf:"bytes,17,opt,name=allow_tags,json=allowTags,proto3" json:"allow_tags,omitempty"`                                       // 允许的用户标签(JSON数组)
	DenyTags             string                 `protobuf:"bytes,18,opt,name=deny_tags,json=denyTags,proto3" json:"deny_tags,omitempty"`                                          // 禁止的用户标签(JSON数组)
	Remark               string                 `protobuf:"bytes,19,opt,name=remark,proto3" json:"remark,omitempty"`                                                              // 备注
	CreateTimes          int64                  `protobuf:"varint,20,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`                                // 创建时间
	UpdateTimes          int64                  `protobuf:"varint,21,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`                                // 更新时间
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TenantPayChannelRule) Reset() {
	*x = TenantPayChannelRule{}
	mi := &file_proto_payment_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPayChannelRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPayChannelRule) ProtoMessage() {}

func (x *TenantPayChannelRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPayChannelRule.ProtoReflect.Descriptor instead.
func (*TenantPayChannelRule) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{5}
}

func (x *TenantPayChannelRule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantPayChannelRule) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TenantPayChannelRule) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *TenantPayChannelRule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *TenantPayChannelRule) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TenantPayChannelRule) GetStatus() CommonStatus {
	if x != nil {
		return x.Status
	}
	return CommonStatus_COMMON_STATUS_UNKNOWN
}

func (x *TenantPayChannelRule) GetSingleAmountMin() int64 {
	if x != nil {
		return x.SingleAmountMin
	}
	return 0
}

func (x *TenantPayChannelRule) GetSingleAmountMax() int64 {
	if x != nil {
		return x.SingleAmountMax
	}
	return 0
}

func (x *TenantPayChannelRule) GetUserTotalRechargeMin() int64 {
	if x != nil {
		return x.UserTotalRechargeMin
	}
	return 0
}

func (x *TenantPayChannelRule) GetUserTotalRechargeMax() int64 {
	if x != nil {
		return x.UserTotalRechargeMax
	}
	return 0
}

func (x *TenantPayChannelRule) GetMemberLevelMin() int64 {
	if x != nil {
		return x.MemberLevelMin
	}
	return 0
}

func (x *TenantPayChannelRule) GetMemberLevelMax() int64 {
	if x != nil {
		return x.MemberLevelMax
	}
	return 0
}

func (x *TenantPayChannelRule) GetKycLevelMin() int64 {
	if x != nil {
		return x.KycLevelMin
	}
	return 0
}

func (x *TenantPayChannelRule) GetKycLevelMax() int64 {
	if x != nil {
		return x.KycLevelMax
	}
	return 0
}

func (x *TenantPayChannelRule) GetAllowNewUser() int64 {
	if x != nil {
		return x.AllowNewUser
	}
	return 0
}

func (x *TenantPayChannelRule) GetAllowOldUser() int64 {
	if x != nil {
		return x.AllowOldUser
	}
	return 0
}

func (x *TenantPayChannelRule) GetAllowTags() string {
	if x != nil {
		return x.AllowTags
	}
	return ""
}

func (x *TenantPayChannelRule) GetDenyTags() string {
	if x != nil {
		return x.DenyTags
	}
	return ""
}

func (x *TenantPayChannelRule) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TenantPayChannelRule) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *TenantPayChannelRule) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

type UserRechargeStat struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                             // 主键ID
	TenantId           int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                 // 租户ID
	UserId             int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                       // 用户ID
	SuccessOrderCount  int64                  `protobuf:"varint,4,opt,name=success_order_count,json=successOrderCount,proto3" json:"success_order_count,omitempty"`    // 成功充值笔数
	SuccessTotalAmount int64                  `protobuf:"varint,5,opt,name=success_total_amount,json=successTotalAmount,proto3" json:"success_total_amount,omitempty"` // 成功累计充值金额，单位分
	TodaySuccessAmount int64                  `protobuf:"varint,6,opt,name=today_success_amount,json=todaySuccessAmount,proto3" json:"today_success_amount,omitempty"` // 今日成功充值金额，单位分
	TodaySuccessCount  int64                  `protobuf:"varint,7,opt,name=today_success_count,json=todaySuccessCount,proto3" json:"today_success_count,omitempty"`    // 今日成功充值次数
	FirstSuccessTime   int64                  `protobuf:"varint,8,opt,name=first_success_time,json=firstSuccessTime,proto3" json:"first_success_time,omitempty"`       // 首次成功充值时间
	LastSuccessTime    int64                  `protobuf:"varint,9,opt,name=last_success_time,json=lastSuccessTime,proto3" json:"last_success_time,omitempty"`          // 最近成功充值时间
	CreateTimes        int64                  `protobuf:"varint,10,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`                       // 创建时间
	UpdateTimes        int64                  `protobuf:"varint,11,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`                       // 更新时间
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserRechargeStat) Reset() {
	*x = UserRechargeStat{}
	mi := &file_proto_payment_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRechargeStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRechargeStat) ProtoMessage() {}

func (x *UserRechargeStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRechargeStat.ProtoReflect.Descriptor instead.
func (*UserRechargeStat) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{6}
}

func (x *UserRechargeStat) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRechargeStat) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UserRechargeStat) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRechargeStat) GetSuccessOrderCount() int64 {
	if x != nil {
		return x.SuccessOrderCount
	}
	return 0
}

func (x *UserRechargeStat) GetSuccessTotalAmount() int64 {
	if x != nil {
		return x.SuccessTotalAmount
	}
	return 0
}

func (x *UserRechargeStat) GetTodaySuccessAmount() int64 {
	if x != nil {
		return x.TodaySuccessAmount
	}
	return 0
}

func (x *UserRechargeStat) GetTodaySuccessCount() int64 {
	if x != nil {
		return x.TodaySuccessCount
	}
	return 0
}

func (x *UserRechargeStat) GetFirstSuccessTime() int64 {
	if x != nil {
		return x.FirstSuccessTime
	}
	return 0
}

func (x *UserRechargeStat) GetLastSuccessTime() int64 {
	if x != nil {
		return x.LastSuccessTime
	}
	return 0
}

func (x *UserRechargeStat) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *UserRechargeStat) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

type RechargeOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                            // 充值订单ID
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                // 租户ID
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                      // 用户ID
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                                    // 平台订单号
	BizOrderNo    string                 `protobuf:"bytes,5,opt,name=biz_order_no,json=bizOrderNo,proto3" json:"biz_order_no,omitempty"`                         // 业务订单号
	PlatformId    int64                  `protobuf:"varint,6,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`                          // 平台ID
	ProductId     int64                  `protobuf:"varint,7,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`                             // 产品ID
	AccountId     int64                  `protobuf:"varint,8,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                             // 账号ID
	ChannelId     int64                  `protobuf:"varint,9,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                             // 通道ID
	Currency      string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`                                                // 币种
	OrderAmount   int64                  `protobuf:"varint,11,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`                      // 订单金额，单位分
	PayAmount     int64                  `protobuf:"varint,12,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`                            // 实际支付金额，单位分
	FeeAmount     int64                  `protobuf:"varint,13,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`                            // 手续费金额，单位分
	Subject       string                 `protobuf:"bytes,14,opt,name=subject,proto3" json:"subject,omitempty"`                                                  // 标题
	Body          string                 `protobuf:"bytes,15,opt,name=body,proto3" json:"body,omitempty"`                                                        // 描述
	ClientType    ClientType             `protobuf:"varint,16,opt,name=client_type,json=clientType,proto3,enum=payment.ClientType" json:"client_type,omitempty"` // 客户端类型：1APP 2H5 3WEB
	ClientIp      string                 `protobuf:"bytes,17,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                                // 客户端IP
	Status        PayOrderStatus         `protobuf:"varint,18,opt,name=status,proto3,enum=payment.PayOrderStatus" json:"status,omitempty"`                       // 状态：1待支付 2支付中 3成功 4失败 5已关闭 6已退款
	ThirdTradeNo  string                 `protobuf:"bytes,19,opt,name=third_trade_no,json=thirdTradeNo,proto3" json:"third_trade_no,omitempty"`                  // 三方交易号
	ThirdOrderNo  string                 `protobuf:"bytes,20,opt,name=third_order_no,json=thirdOrderNo,proto3" json:"third_order_no,omitempty"`                  // 三方订单号
	PayUrl        string                 `protobuf:"bytes,21,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`                                      // 支付链接
	QrContent     string                 `protobuf:"bytes,22,opt,name=qr_content,json=qrContent,proto3" json:"qr_content,omitempty"`                             // 二维码内容
	RequestData   string                 `protobuf:"bytes,23,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`                       // 请求快照(JSON)
	ResponseData  string                 `protobuf:"bytes,24,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`                    // 响应快照(JSON)
	NotifyData    string                 `protobuf:"bytes,25,opt,name=notify_data,json=notifyData,proto3" json:"notify_data,omitempty"`                          // 回调数据(JSON)
	ExpireTime    int64                  `protobuf:"varint,26,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`                         // 过期时间
	PaidTime      int64                  `protobuf:"varint,27,opt,name=paid_time,json=paidTime,proto3" json:"paid_time,omitempty"`                               // 支付时间
	NotifyTime    int64                  `protobuf:"varint,28,opt,name=notify_time,json=notifyTime,proto3" json:"notify_time,omitempty"`                         // 回调时间
	CloseTime     int64                  `protobuf:"varint,29,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`                            // 关闭时间
	Remark        string                 `protobuf:"bytes,30,opt,name=remark,proto3" json:"remark,omitempty"`                                                    // 备注
	CreateTimes   int64                  `protobuf:"varint,31,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`                      // 创建时间
	UpdateTimes   int64                  `protobuf:"varint,32,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`                      // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeOrder) Reset() {
	*x = RechargeOrder{}
	mi := &file_proto_payment_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeOrder) ProtoMessage() {}

func (x *RechargeOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeOrder.ProtoReflect.Descriptor instead.
func (*RechargeOrder) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{7}
}

func (x *RechargeOrder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RechargeOrder) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *RechargeOrder) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RechargeOrder) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RechargeOrder) GetBizOrderNo() string {
	if x != nil {
		return x.BizOrderNo
	}
	return ""
}

func (x *RechargeOrder) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *RechargeOrder) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *RechargeOrder) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RechargeOrder) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *RechargeOrder) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RechargeOrder) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *RechargeOrder) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *RechargeOrder) GetFeeAmount() int64 {
	if x != nil {
		return x.FeeAmount
	}
	return 0
}

func (x *RechargeOrder) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RechargeOrder) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RechargeOrder) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLIENT_TYPE_UNKNOWN
}

func (x *RechargeOrder) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *RechargeOrder) GetStatus() PayOrderStatus {
	if x != nil {
		return x.Status
	}
	return PayOrderStatus_PAY_ORDER_STATUS_UNKNOWN
}

func (x *RechargeOrder) GetThirdTradeNo() string {
	if x != nil {
		return x.ThirdTradeNo
	}
	return ""
}

func (x *RechargeOrder) GetThirdOrderNo() string {
	if x != nil {
		return x.ThirdOrderNo
	}
	return ""
}

func (x *RechargeOrder) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *RechargeOrder) GetQrContent() string {
	if x != nil {
		return x.QrContent
	}
	return ""
}

func (x *RechargeOrder) GetRequestData() string {
	if x != nil {
		return x.RequestData
	}
	return ""
}

func (x *RechargeOrder) GetResponseData() string {
	if x != nil {
		return x.ResponseData
	}
	return ""
}

func (x *RechargeOrder) GetNotifyData() string {
	if x != nil {
		return x.NotifyData
	}
	return ""
}

func (x *RechargeOrder) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *RechargeOrder) GetPaidTime() int64 {
	if x != nil {
		return x.PaidTime
	}
	return 0
}

func (x *RechargeOrder) GetNotifyTime() int64 {
	if x != nil {
		return x.NotifyTime
	}
	return 0
}

func (x *RechargeOrder) GetCloseTime() int64 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

func (x *RechargeOrder) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RechargeOrder) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *RechargeOrder) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

type PayNotifyLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                          // 回调日志ID
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                              // 租户ID
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                                                 // 订单ID
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                                                  // 平台订单号
	PlatformId    int64                  `protobuf:"varint,5,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`                                        // 平台ID
	ChannelId     int64                  `protobuf:"varint,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                                           // 通道ID
	NotifyStatus  NotifyProcessStatus    `protobuf:"varint,7,opt,name=notify_status,json=notifyStatus,proto3,enum=payment.NotifyProcessStatus" json:"notify_status,omitempty"` // 处理状态：1待处理 2成功 3失败
	NotifyBody    string                 `protobuf:"bytes,8,opt,name=notify_body,json=notifyBody,proto3" json:"notify_body,omitempty"`                                         // 回调原文
	SignResult    SignResult             `protobuf:"varint,9,opt,name=sign_result,json=signResult,proto3,enum=payment.SignResult" json:"sign_result,omitempty"`                // 验签结果：0未验 1通过 2失败
	ProcessResult string                 `protobuf:"bytes,10,opt,name=process_result,json=processResult,proto3" json:"process_result,omitempty"`                               // 处理结果
	ErrorMessage  string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                  // 错误信息
	NotifyTime    int64                  `protobuf:"varint,12,opt,name=notify_time,json=notifyTime,proto3" json:"notify_time,omitempty"`                                       // 回调时间
	CreateTimes   int64                  `protobuf:"varint,13,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`                                    // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayNotifyLog) Reset() {
	*x = PayNotifyLog{}
	mi := &file_proto_payment_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayNotifyLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayNotifyLog) ProtoMessage() {}

func (x *PayNotifyLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayNotifyLog.ProtoReflect.Descriptor instead.
func (*PayNotifyLog) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{8}
}

func (x *PayNotifyLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PayNotifyLog) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *PayNotifyLog) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PayNotifyLog) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PayNotifyLog) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *PayNotifyLog) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *PayNotifyLog) GetNotifyStatus() NotifyProcessStatus {
	if x != nil {
		return x.NotifyStatus
	}
	return NotifyProcessStatus_NOTIFY_PROCESS_STATUS_UNKNOWN
}

func (x *PayNotifyLog) GetNotifyBody() string {
	if x != nil {
		return x.NotifyBody
	}
	return ""
}

func (x *PayNotifyLog) GetSignResult() SignResult {
	if x != nil {
		return x.SignResult
	}
	return SignResult_SIGN_RESULT_UNKNOWN
}

func (x *PayNotifyLog) GetProcessResult() string {
	if x != nil {
		return x.ProcessResult
	}
	return ""
}

func (x *PayNotifyLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PayNotifyLog) GetNotifyTime() int64 {
	if x != nil {
		return x.NotifyTime
	}
	return 0
}

func (x *PayNotifyLog) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

type VisiblePayChannel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChannelId       int64                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                     // 通道ID
	ChannelCode     string                 `protobuf:"bytes,2,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`                // 通道编码
	ChannelName     string                 `protobuf:"bytes,3,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`                // 通道名称
	DisplayName     string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`                // 前端展示名称
	Icon            string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`                                                 // 图标
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`                                         // 币种
	SingleMinAmount int64                  `protobuf:"varint,7,opt,name=single_min_amount,json=singleMinAmount,proto3" json:"single_min_amount,omitempty"` // 单笔最小金额，单位分
	SingleMaxAmount int64                  `protobuf:"varint,8,opt,name=single_max_amount,json=singleMaxAmount,proto3" json:"single_max_amount,omitempty"` // 单笔最大金额，单位分
	FeeType         FeeType                `protobuf:"varint,9,opt,name=fee_type,json=feeType,proto3,enum=payment.FeeType" json:"fee_type,omitempty"`      // 手续费类型：1比例 2固定
	FeeRate         string                 `protobuf:"bytes,10,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`                           // 手续费比例
	FeeFixedAmount  int64                  `protobuf:"varint,11,opt,name=fee_fixed_amount,json=feeFixedAmount,proto3" json:"fee_fixed_amount,omitempty"`   // 固定手续费，单位分
	PlatformId      int64                  `protobuf:"varint,12,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`                 // 平台ID
	ProductId       int64                  `protobuf:"varint,13,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`                    // 产品ID
	AccountId       int64                  `protobuf:"varint,14,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                    // 账号ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VisiblePayChannel) Reset() {
	*x = VisiblePayChannel{}
	mi := &file_proto_payment_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisiblePayChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisiblePayChannel) ProtoMessage() {}

func (x *VisiblePayChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisiblePayChannel.ProtoReflect.Descriptor instead.
func (*VisiblePayChannel) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{9}
}

func (x *VisiblePayChannel) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *VisiblePayChannel) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *VisiblePayChannel) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *VisiblePayChannel) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *VisiblePayChannel) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *VisiblePayChannel) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *VisiblePayChannel) GetSingleMinAmount() int64 {
	if x != nil {
		return x.SingleMinAmount
	}
	return 0
}

func (x *VisiblePayChannel) GetSingleMaxAmount() int64 {
	if x != nil {
		return x.SingleMaxAmount
	}
	return 0
}

func (x *VisiblePayChannel) GetFeeType() FeeType {
	if x != nil {
		return x.FeeType
	}
	return FeeType_FEE_TYPE_UNKNOWN
}

func (x *VisiblePayChannel) GetFeeRate() string {
	if x != nil {
		return x.FeeRate
	}
	return ""
}

func (x *VisiblePayChannel) GetFeeFixedAmount() int64 {
	if x != nil {
		return x.FeeFixedAmount
	}
	return 0
}

func (x *VisiblePayChannel) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *VisiblePayChannel) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *VisiblePayChannel) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type WithdrawOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                            // 提现订单ID
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                // 租户ID
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                      // 用户ID
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                                    // 平台订单号
	BizOrderNo    string                 `protobuf:"bytes,5,opt,name=biz_order_no,json=bizOrderNo,proto3" json:"biz_order_no,omitempty"`                         // 业务订单号
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`                                                 // 币种
	Amount        int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`                                                    // 订单金额，单位分
	FeeAmount     int64                  `protobuf:"varint,8,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`                             // 手续费金额，单位分
	ActualAmount  int64                  `protobuf:"varint,9,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`                    // 实际到账金额，单位分
	ClientType    ClientType             `protobuf:"varint,10,opt,name=client_type,json=clientType,proto3,enum=payment.ClientType" json:"client_type,omitempty"` // 客户端类型：1APP 2H5 3WEB
	ClientIp      string                 `protobuf:"bytes,11,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                                // 客户端IP
	Status        PayOrderStatus         `protobuf:"varint,12,opt,name=status,proto3,enum=payment.PayOrderStatus" json:"status,omitempty"`                       // 状态：1待处理 2处理中 3成功 4失败 5已关闭
	ThirdTradeNo  string                 `protobuf:"bytes,13,opt,name=third_trade_no,json=thirdTradeNo,proto3" json:"third_trade_no,omitempty"`                  // 三方交易号
	ThirdOrderNo  string                 `protobuf:"bytes,14,opt,name=third_order_no,json=thirdOrderNo,proto3" json:"third_order_no,omitempty"`                  // 三方订单号
	RequestData   string                 `protobuf:"bytes,15,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`                       // 请求快照(JSON)
	ResponseData  string                 `protobuf:"bytes,16,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`                    // 响应快照(JSON)
	NotifyData    string                 `protobuf:"bytes,17,opt,name=notify_data,json=notifyData,proto3" json:"notify_data,omitempty"`                          // 回调数据(JSON)
	ProcessTime   int64                  `protobuf:"varint,18,opt,name=process_time,json=processTime,proto3" json:"process_time,omitempty"`                      // 处理时间
	NotifyTime    int64                  `protobuf:"varint,19,opt,name=notify_time,json=notifyTime,proto3" json:"notify_time,omitempty"`                         // 回调时间
	CloseTime     int64                  `protobuf:"varint,20,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`                            // 关闭时间
	Remark        string                 `protobuf:"bytes,21,opt,name=remark,proto3" json:"remark,omitempty"`                                                    // 备注
	CreateTimes   int64                  `protobuf:"varint,22,opt,name=create_times,json=createTimes,proto3" json:"create_times,omitempty"`                      // 创建时间
	UpdateTimes   int64                  `protobuf:"varint,23,opt,name=update_times,json=updateTimes,proto3" json:"update_times,omitempty"`                      // 更新时间
	PlatformId    int64                  `protobuf:"varint,24,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`                         // 平台ID
	ProductId     int64                  `protobuf:"varint,25,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`                            // 产品ID
	AccountId     int64                  `protobuf:"varint,26,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                            // 账号ID
	ChannelId     int64                  `protobuf:"varint,27,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                            // 通道ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawOrder) Reset() {
	*x = WithdrawOrder{}
	mi := &file_proto_payment_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawOrder) ProtoMessage() {}

func (x *WithdrawOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawOrder.ProtoReflect.Descriptor instead.
func (*WithdrawOrder) Descriptor() ([]byte, []int) {
	return file_proto_payment_model_proto_rawDescGZIP(), []int{10}
}

func (x *WithdrawOrder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WithdrawOrder) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *WithdrawOrder) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawOrder) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *WithdrawOrder) GetBizOrderNo() string {
	if x != nil {
		return x.BizOrderNo
	}
	return ""
}

func (x *WithdrawOrder) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WithdrawOrder) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawOrder) GetFeeAmount() int64 {
	if x != nil {
		return x.FeeAmount
	}
	return 0
}

func (x *WithdrawOrder) GetActualAmount() int64 {
	if x != nil {
		return x.ActualAmount
	}
	return 0
}

func (x *WithdrawOrder) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLIENT_TYPE_UNKNOWN
}

func (x *WithdrawOrder) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *WithdrawOrder) GetStatus() PayOrderStatus {
	if x != nil {
		return x.Status
	}
	return PayOrderStatus_PAY_ORDER_STATUS_UNKNOWN
}

func (x *WithdrawOrder) GetThirdTradeNo() string {
	if x != nil {
		return x.ThirdTradeNo
	}
	return ""
}

func (x *WithdrawOrder) GetThirdOrderNo() string {
	if x != nil {
		return x.ThirdOrderNo
	}
	return ""
}

func (x *WithdrawOrder) GetRequestData() string {
	if x != nil {
		return x.RequestData
	}
	return ""
}

func (x *WithdrawOrder) GetResponseData() string {
	if x != nil {
		return x.ResponseData
	}
	return ""
}

func (x *WithdrawOrder) GetNotifyData() string {
	if x != nil {
		return x.NotifyData
	}
	return ""
}

func (x *WithdrawOrder) GetProcessTime() int64 {
	if x != nil {
		return x.ProcessTime
	}
	return 0
}

func (x *WithdrawOrder) GetNotifyTime() int64 {
	if x != nil {
		return x.NotifyTime
	}
	return 0
}

func (x *WithdrawOrder) GetCloseTime() int64 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

func (x *WithdrawOrder) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *WithdrawOrder) GetCreateTimes() int64 {
	if x != nil {
		return x.CreateTimes
	}
	return 0
}

func (x *WithdrawOrder) GetUpdateTimes() int64 {
	if x != nil {
		return x.UpdateTimes
	}
	return 0
}

func (x *WithdrawOrder) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *WithdrawOrder) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *WithdrawOrder) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WithdrawOrder) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

var File_proto_payment_model_proto protoreflect.FileDescriptor

const file_proto_payment_model_proto_rawDesc = "" +
	"\n" +
	"\x19proto/payment/model.proto\x12\apayment\x1a\x18proto/payment/enum.proto\"\x82\x03\n" +
	"\vPayPlatform\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rplatform_code\x18\x02 \x01(\tR\fplatformCode\x12#\n" +
	"\rplatform_name\x18\x03 \x01(\tR\fplatformName\x12:\n" +
	"\rplatform_type\x18\x04 \x01(\x0e2\x15.payment.PlatformTypeR\fplatformType\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x05 \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\x06 \x01(\tR\treturnUrl\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12-\n" +
	"\x06status\x18\b \x01(\x0e2\x15.payment.CommonStatusR\x06status\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12!\n" +
	"\fcreate_times\x18\n" +
	" \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\v \x01(\x03R\vupdateTimes\"\xdf\x02\n" +
	"\n" +
	"PayProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\x03R\n" +
	"platformId\x12!\n" +
	"\fproduct_code\x18\x03 \x01(\tR\vproductCode\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x121\n" +
	"\n" +
	"scene_type\x18\x05 \x01(\x0e2\x12.payment.SceneTypeR\tsceneType\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.payment.CommonStatusR\x06status\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\x12!\n" +
	"\fcreate_times\x18\t \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\n" +
	" \x01(\x03R\vupdateTimes\"\xa4\x02\n" +
	"\x11TenantPayPlatform\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1f\n" +
	"\vplatform_id\x18\x03 \x01(\x03R\n" +
	"platformId\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.payment.CommonStatusR\x06status\x124\n" +
	"\vopen_status\x18\x05 \x01(\x0e2\x13.payment.OpenStatusR\n" +
	"openStatus\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x12!\n" +
	"\fcreate_times\x18\a \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\b \x01(\x03R\vupdateTimes\"\xc3\x05\n" +
	"\x10TenantPayAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x123\n" +
	"\x16tenant_pay_platform_id\x18\x03 \x01(\x03R\x13tenantPayPlatformId\x12\x1f\n" +
	"\vplatform_id\x18\x04 \x01(\x03R\n" +
	"platformId\x12!\n" +
	"\faccount_code\x18\x05 \x01(\tR\vaccountCode\x12!\n" +
	"\faccount_name\x18\x06 \x01(\tR\vaccountName\x12\x15\n" +
	"\x06app_id\x18\a \x01(\tR\x05appId\x12\x1f\n" +
	"\vmerchant_id\x18\b \x01(\tR\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\t \x01(\tR\fmerchantName\x12\x1d\n" +
	"\n" +
	"public_key\x18\n" +
	" \x01(\tR\tpublicKey\x12\x1d\n" +
	"\n" +
	"ext_config\x18\v \x01(\tR\textConfig\x12-\n" +
	"\x06status\x18\f \x01(\x0e2\x15.payment.CommonStatusR\x06status\x12\x1d\n" +
	"\n" +
	"is_default\x18\r \x01(\x03R\tisDefault\x12\x16\n" +
	"\x06remark\x18\x0e \x01(\tR\x06remark\x12!\n" +
	"\fcreate_times\x18\x0f \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\x10 \x01(\x03R\vupdateTimes\x12$\n" +
	"\x0eapi_key_cipher\x18\x11 \x01(\tR\fapiKeyCipher\x12*\n" +
	"\x11api_secret_cipher\x18\x12 \x01(\tR\x0fapiSecretCipher\x12,\n" +
	"\x12private_key_cipher\x18\x13 \x01(\tR\x10privateKeyCipher\x12\x1f\n" +
	"\vcert_cipher\x18\x14 \x01(\tR\n" +
	"certCipher\"\xad\x06\n" +
	"\x10TenantPayChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1f\n" +
	"\vplatform_id\x18\x03 \x01(\x03R\n" +
	"platformId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\x03R\taccountId\x12!\n" +
	"\fchannel_code\x18\x06 \x01(\tR\vchannelCode\x12!\n" +
	"\fchannel_name\x18\a \x01(\tR\vchannelName\x12!\n" +
	"\fdisplay_name\x18\b \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04icon\x18\t \x01(\tR\x04icon\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\x12\x12\n" +
	"\x04sort\x18\v \x01(\x03R\x04sort\x12\x18\n" +
	"\avisible\x18\f \x01(\x03R\avisible\x12-\n" +
	"\x06status\x18\r \x01(\x0e2\x15.payment.CommonStatusR\x06status\x12*\n" +
	"\x11single_min_amount\x18\x0e \x01(\x03R\x0fsingleMinAmount\x12*\n" +
	"\x11single_max_amount\x18\x0f \x01(\x03R\x0fsingleMaxAmount\x12(\n" +
	"\x10daily_max_amount\x18\x10 \x01(\x03R\x0edailyMaxAmount\x12&\n" +
	"\x0fdaily_max_count\x18\x11 \x01(\x03R\rdailyMaxCount\x12+\n" +
	"\bfee_type\x18\x12 \x01(\x0e2\x10.payment.FeeTypeR\afeeType\x12\x19\n" +
	"\bfee_rate\x18\x13 \x01(\tR\afeeRate\x12(\n" +
	"\x10fee_fixed_amount\x18\x14 \x01(\x03R\x0efeeFixedAmount\x12\x1d\n" +
	"\n" +
	"ext_config\x18\x15 \x01(\tR\textConfig\x12\x16\n" +
	"\x06remark\x18\x16 \x01(\tR\x06remark\x12!\n" +
	"\fcreate_times\x18\x17 \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\x18 \x01(\x03R\vupdateTimes\"\x92\x06\n" +
	"\x14TenantPayChannelRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\x03R\tchannelId\x12\x1b\n" +
	"\trule_name\x18\x04 \x01(\tR\bruleName\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x03R\bpriority\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.payment.CommonStatusR\x06status\x12*\n" +
	"\x11single_amount_min\x18\a \x01(\x03R\x0fsingleAmountMin\x12*\n" +
	"\x11single_amount_max\x18\b \x01(\x03R\x0fsingleAmountMax\x125\n" +
	"\x17user_total_recharge_min\x18\t \x01(\x03R\x14userTotalRechargeMin\x125\n" +
	"\x17user_total_recharge_max\x18\n" +
	" \x01(\x03R\x14userTotalRechargeMax\x12(\n" +
	"\x10member_level_min\x18\v \x01(\x03R\x0ememberLevelMin\x12(\n" +
	"\x10member_level_max\x18\f \x01(\x03R\x0ememberLevelMax\x12\"\n" +
	"\rkyc_level_min\x18\r \x01(\x03R\vkycLevelMin\x12\"\n" +
	"\rkyc_level_max\x18\x0e \x01(\x03R\vkycLevelMax\x12$\n" +
	"\x0eallow_new_user\x18\x0f \x01(\x03R\fallowNewUser\x12$\n" +
	"\x0eallow_old_user\x18\x10 \x01(\x03R\fallowOldUser\x12\x1d\n" +
	"\n" +
	"allow_tags\x18\x11 \x01(\tR\tallowTags\x12\x1b\n" +
	"\tdeny_tags\x18\x12 \x01(\tR\bdenyTags\x12\x16\n" +
	"\x06remark\x18\x13 \x01(\tR\x06remark\x12!\n" +
	"\fcreate_times\x18\x14 \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\x15 \x01(\x03R\vupdateTimes\"\xbc\x03\n" +
	"\x10UserRechargeStat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12.\n" +
	"\x13success_order_count\x18\x04 \x01(\x03R\x11successOrderCount\x120\n" +
	"\x14success_total_amount\x18\x05 \x01(\x03R\x12successTotalAmount\x120\n" +
	"\x14today_success_amount\x18\x06 \x01(\x03R\x12todaySuccessAmount\x12.\n" +
	"\x13today_success_count\x18\a \x01(\x03R\x11todaySuccessCount\x12,\n" +
	"\x12first_success_time\x18\b \x01(\x03R\x10firstSuccessTime\x12*\n" +
	"\x11last_success_time\x18\t \x01(\x03R\x0flastSuccessTime\x12!\n" +
	"\fcreate_times\x18\n" +
	" \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\v \x01(\x03R\vupdateTimes\"\x88\b\n" +
	"\rRechargeOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12 \n" +
	"\fbiz_order_no\x18\x05 \x01(\tR\n" +
	"bizOrderNo\x12\x1f\n" +
	"\vplatform_id\x18\x06 \x01(\x03R\n" +
	"platformId\x12\x1d\n" +
	"\n" +
	"product_id\x18\a \x01(\x03R\tproductId\x12\x1d\n" +
	"\n" +
	"account_id\x18\b \x01(\x03R\taccountId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\t \x01(\x03R\tchannelId\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\x12!\n" +
	"\forder_amount\x18\v \x01(\x03R\vorderAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\f \x01(\x03R\tpayAmount\x12\x1d\n" +
	"\n" +
	"fee_amount\x18\r \x01(\x03R\tfeeAmount\x12\x18\n" +
	"\asubject\x18\x0e \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x0f \x01(\tR\x04body\x124\n" +
	"\vclient_type\x18\x10 \x01(\x0e2\x13.payment.ClientTypeR\n" +
	"clientType\x12\x1b\n" +
	"\tclient_ip\x18\x11 \x01(\tR\bclientIp\x12/\n" +
	"\x06status\x18\x12 \x01(\x0e2\x17.payment.PayOrderStatusR\x06status\x12$\n" +
	"\x0ethird_trade_no\x18\x13 \x01(\tR\fthirdTradeNo\x12$\n" +
	"\x0ethird_order_no\x18\x14 \x01(\tR\fthirdOrderNo\x12\x17\n" +
	"\apay_url\x18\x15 \x01(\tR\x06payUrl\x12\x1d\n" +
	"\n" +
	"qr_content\x18\x16 \x01(\tR\tqrContent\x12!\n" +
	"\frequest_data\x18\x17 \x01(\tR\vrequestData\x12#\n" +
	"\rresponse_data\x18\x18 \x01(\tR\fresponseData\x12\x1f\n" +
	"\vnotify_data\x18\x19 \x01(\tR\n" +
	"notifyData\x12\x1f\n" +
	"\vexpire_time\x18\x1a \x01(\x03R\n" +
	"expireTime\x12\x1b\n" +
	"\tpaid_time\x18\x1b \x01(\x03R\bpaidTime\x12\x1f\n" +
	"\vnotify_time\x18\x1c \x01(\x03R\n" +
	"notifyTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x1d \x01(\x03R\tcloseTime\x12\x16\n" +
	"\x06remark\x18\x1e \x01(\tR\x06remark\x12!\n" +
	"\fcreate_times\x18\x1f \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18  \x01(\x03R\vupdateTimes\"\xdb\x03\n" +
	"\fPayNotifyLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vplatform_id\x18\x05 \x01(\x03R\n" +
	"platformId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x06 \x01(\x03R\tchannelId\x12A\n" +
	"\rnotify_status\x18\a \x01(\x0e2\x1c.payment.NotifyProcessStatusR\fnotifyStatus\x12\x1f\n" +
	"\vnotify_body\x18\b \x01(\tR\n" +
	"notifyBody\x124\n" +
	"\vsign_result\x18\t \x01(\x0e2\x13.payment.SignResultR\n" +
	"signResult\x12%\n" +
	"\x0eprocess_result\x18\n" +
	" \x01(\tR\rprocessResult\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vnotify_time\x18\f \x01(\x03R\n" +
	"notifyTime\x12!\n" +
	"\fcreate_times\x18\r \x01(\x03R\vcreateTimes\"\xf4\x03\n" +
	"\x11VisiblePayChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x03R\tchannelId\x12!\n" +
	"\fchannel_code\x18\x02 \x01(\tR\vchannelCode\x12!\n" +
	"\fchannel_name\x18\x03 \x01(\tR\vchannelName\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12*\n" +
	"\x11single_min_amount\x18\a \x01(\x03R\x0fsingleMinAmount\x12*\n" +
	"\x11single_max_amount\x18\b \x01(\x03R\x0fsingleMaxAmount\x12+\n" +
	"\bfee_type\x18\t \x01(\x0e2\x10.payment.FeeTypeR\afeeType\x12\x19\n" +
	"\bfee_rate\x18\n" +
	" \x01(\tR\afeeRate\x12(\n" +
	"\x10fee_fixed_amount\x18\v \x01(\x03R\x0efeeFixedAmount\x12\x1f\n" +
	"\vplatform_id\x18\f \x01(\x03R\n" +
	"platformId\x12\x1d\n" +
	"\n" +
	"product_id\x18\r \x01(\x03R\tproductId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x0e \x01(\x03R\taccountId\"\x82\a\n" +
	"\rWithdrawOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12 \n" +
	"\fbiz_order_no\x18\x05 \x01(\tR\n" +
	"bizOrderNo\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"fee_amount\x18\b \x01(\x03R\tfeeAmount\x12#\n" +
	"\ractual_amount\x18\t \x01(\x03R\factualAmount\x124\n" +
	"\vclient_type\x18\n" +
	" \x01(\x0e2\x13.payment.ClientTypeR\n" +
	"clientType\x12\x1b\n" +
	"\tclient_ip\x18\v \x01(\tR\bclientIp\x12/\n" +
	"\x06status\x18\f \x01(\x0e2\x17.payment.PayOrderStatusR\x06status\x12$\n" +
	"\x0ethird_trade_no\x18\r \x01(\tR\fthirdTradeNo\x12$\n" +
	"\x0ethird_order_no\x18\x0e \x01(\tR\fthirdOrderNo\x12!\n" +
	"\frequest_data\x18\x0f \x01(\tR\vrequestData\x12#\n" +
	"\rresponse_data\x18\x10 \x01(\tR\fresponseData\x12\x1f\n" +
	"\vnotify_data\x18\x11 \x01(\tR\n" +
	"notifyData\x12!\n" +
	"\fprocess_time\x18\x12 \x01(\x03R\vprocessTime\x12\x1f\n" +
	"\vnotify_time\x18\x13 \x01(\x03R\n" +
	"notifyTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x14 \x01(\x03R\tcloseTime\x12\x16\n" +
	"\x06remark\x18\x15 \x01(\tR\x06remark\x12!\n" +
	"\fcreate_times\x18\x16 \x01(\x03R\vcreateTimes\x12!\n" +
	"\fupdate_times\x18\x17 \x01(\x03R\vupdateTimes\x12\x1f\n" +
	"\vplatform_id\x18\x18 \x01(\x03R\n" +
	"platformId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x19 \x01(\x03R\tproductId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x1a \x01(\x03R\taccountId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x1b \x01(\x03R\tchannelIdB\x1eZ\x1cwklive/proto/payment;paymentb\x06proto3"

var (
	file_proto_payment_model_proto_rawDescOnce sync.Once
	file_proto_payment_model_proto_rawDescData []byte
)

func file_proto_payment_model_proto_rawDescGZIP() []byte {
	file_proto_payment_model_proto_rawDescOnce.Do(func() {
		file_proto_payment_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_model_proto_rawDesc), len(file_proto_payment_model_proto_rawDesc)))
	})
	return file_proto_payment_model_proto_rawDescData
}

var file_proto_payment_model_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_payment_model_proto_goTypes = []any{
	(*PayPlatform)(nil),          // 0: payment.PayPlatform
	(*PayProduct)(nil),           // 1: payment.PayProduct
	(*TenantPayPlatform)(nil),    // 2: payment.TenantPayPlatform
	(*TenantPayAccount)(nil),     // 3: payment.TenantPayAccount
	(*TenantPayChannel)(nil),     // 4: payment.TenantPayChannel
	(*TenantPayChannelRule)(nil), // 5: payment.TenantPayChannelRule
	(*UserRechargeStat)(nil),     // 6: payment.UserRechargeStat
	(*RechargeOrder)(nil),        // 7: payment.RechargeOrder
	(*PayNotifyLog)(nil),         // 8: payment.PayNotifyLog
	(*VisiblePayChannel)(nil),    // 9: payment.VisiblePayChannel
	(*WithdrawOrder)(nil),        // 10: payment.WithdrawOrder
	(PlatformType)(0),            // 11: payment.PlatformType
	(CommonStatus)(0),            // 12: payment.CommonStatus
	(SceneType)(0),               // 13: payment.SceneType
	(OpenStatus)(0),              // 14: payment.OpenStatus
	(FeeType)(0),                 // 15: payment.FeeType
	(ClientType)(0),              // 16: payment.ClientType
	(PayOrderStatus)(0),          // 17: payment.PayOrderStatus
	(NotifyProcessStatus)(0),     // 18: payment.NotifyProcessStatus
	(SignResult)(0),              // 19: payment.SignResult
}
var file_proto_payment_model_proto_depIdxs = []int32{
	11, // 0: payment.PayPlatform.platform_type:type_name -> payment.PlatformType
	12, // 1: payment.PayPlatform.status:type_name -> payment.CommonStatus
	13, // 2: payment.PayProduct.scene_type:type_name -> payment.SceneType
	12, // 3: payment.PayProduct.status:type_name -> payment.CommonStatus
	12, // 4: payment.TenantPayPlatform.status:type_name -> payment.CommonStatus
	14, // 5: payment.TenantPayPlatform.open_status:type_name -> payment.OpenStatus
	12, // 6: payment.TenantPayAccount.status:type_name -> payment.CommonStatus
	12, // 7: payment.TenantPayChannel.status:type_name -> payment.CommonStatus
	15, // 8: payment.TenantPayChannel.fee_type:type_name -> payment.FeeType
	12, // 9: payment.TenantPayChannelRule.status:type_name -> payment.CommonStatus
	16, // 10: payment.RechargeOrder.client_type:type_name -> payment.ClientType
	17, // 11: payment.RechargeOrder.status:type_name -> payment.PayOrderStatus
	18, // 12: payment.PayNotifyLog.notify_status:type_name -> payment.NotifyProcessStatus
	19, // 13: payment.PayNotifyLog.sign_result:type_name -> payment.SignResult
	15, // 14: payment.VisiblePayChannel.fee_type:type_name -> payment.FeeType
	16, // 15: payment.WithdrawOrder.client_type:type_name -> payment.ClientType
	17, // 16: payment.WithdrawOrder.status:type_name -> payment.PayOrderStatus
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_payment_model_proto_init() }
func file_proto_payment_model_proto_init() {
	if File_proto_payment_model_proto != nil {
		return
	}
	file_proto_payment_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_model_proto_rawDesc), len(file_proto_payment_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_payment_model_proto_goTypes,
		DependencyIndexes: file_proto_payment_model_proto_depIdxs,
		MessageInfos:      file_proto_payment_model_proto_msgTypes,
	}.Build()
	File_proto_payment_model_proto = out.File
	file_proto_payment_model_proto_goTypes = nil
	file_proto_payment_model_proto_depIdxs = nil
}
