Name: app
Host: 0.0.0.0
Port: 5555

SystemRpc:
  Etcd:
    Hosts:
    - "127.0.0.1:2379"
    Key: system.rpc

UserRpc:
  Etcd:
    Hosts:
    - "127.0.0.1:2379"
    Key: user.rpc

PaymentRpc:
  Etcd:
    Hosts:
    - "127.0.0.1:2379"
    Key: payment.rpc

ItickRpc:
  Etcd:
    Hosts:
    - "127.0.0.1:2379"
    Key: itick.rpc

AssetRpc:
  Etcd:
    Hosts:
    - "127.0.0.1:2379"
    Key: asset.rpc

OptionRpc:
  Etcd:
    Hosts:
    - "127.0.0.1:2379"
    Key: option.rpc

StakingRpc:
  Etcd:
    Hosts:
    - "127.0.0.1:2379"
    Key: staking.rpc

TradeRpc:
  Etcd:
    Hosts:
    - "127.0.0.1:2379"
    Key: trade.rpc
