// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	App_Register_FullMethodName              = "/user.App/Register"
	App_Login_FullMethodName                 = "/user.App/Login"
	App_GuestLogin_FullMethodName            = "/user.App/GuestLogin"
	App_CreateGuestTransfer_FullMethodName   = "/user.App/CreateGuestTransfer"
	App_ExchangeGuestTransfer_FullMethodName = "/user.App/ExchangeGuestTransfer"
	App_Logout_FullMethodName                = "/user.App/Logout"
	App_RefreshToken_FullMethodName          = "/user.App/RefreshToken"
	App_GetProfile_FullMethodName            = "/user.App/GetProfile"
	App_UpdateProfile_FullMethodName         = "/user.App/UpdateProfile"
	App_ChangeLoginPassword_FullMethodName   = "/user.App/ChangeLoginPassword"
	App_GetIdentity_FullMethodName           = "/user.App/GetIdentity"
	App_SubmitIdentity_FullMethodName        = "/user.App/SubmitIdentity"
	App_UpdateIdentity_FullMethodName        = "/user.App/UpdateIdentity"
	App_GetSecurity_FullMethodName           = "/user.App/GetSecurity"
	App_SetPayPassword_FullMethodName        = "/user.App/SetPayPassword"
	App_ChangePayPassword_FullMethodName     = "/user.App/ChangePayPassword"
	App_InitGoogle2FA_FullMethodName         = "/user.App/InitGoogle2FA"
	App_EnableGoogle2FA_FullMethodName       = "/user.App/EnableGoogle2FA"
	App_DisableGoogle2FA_FullMethodName      = "/user.App/DisableGoogle2FA"
	App_ListBanks_FullMethodName             = "/user.App/ListBanks"
	App_AddBank_FullMethodName               = "/user.App/AddBank"
	App_UpdateBank_FullMethodName            = "/user.App/UpdateBank"
	App_DeleteBank_FullMethodName            = "/user.App/DeleteBank"
	App_SetDefaultBank_FullMethodName        = "/user.App/SetDefaultBank"
)

// AppClient is the client API for App service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// APP端接口
type AppClient interface {
	// 用户注册
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	// 用户登录
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	// 游客登了
	GuestLogin(ctx context.Context, in *GuestLoginReq, opts ...grpc.CallOption) (*GuestLoginResp, error)
	// 创建游客跨域迁移码
	CreateGuestTransfer(ctx context.Context, in *CreateGuestTransferReq, opts ...grpc.CallOption) (*CreateGuestTransferResp, error)
	// 兑换游客跨域迁移码
	ExchangeGuestTransfer(ctx context.Context, in *ExchangeGuestTransferReq, opts ...grpc.CallOption) (*ExchangeGuestTransferResp, error)
	// 用户登出
	Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*UserCommonResp, error)
	// 刷新Token
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
	// 用户资料相关接口
	GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileResp, error)
	// 更新用户资料
	UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UpdateProfileResp, error)
	// 修改登录密码
	ChangeLoginPassword(ctx context.Context, in *ChangeLoginPasswordReq, opts ...grpc.CallOption) (*UserCommonResp, error)
	// 实名认证相关接口
	GetIdentity(ctx context.Context, in *GetIdentityReq, opts ...grpc.CallOption) (*GetIdentityResp, error)
	// 提交实名认证信息
	SubmitIdentity(ctx context.Context, in *SubmitIdentityReq, opts ...grpc.CallOption) (*SubmitIdentityResp, error)
	// 修改实名认证信息
	UpdateIdentity(ctx context.Context, in *UpdateIdentityReq, opts ...grpc.CallOption) (*UpdateIdentityResp, error)
	// 安全设置相关接口
	GetSecurity(ctx context.Context, in *GetSecurityReq, opts ...grpc.CallOption) (*GetSecurityResp, error)
	// 设置支付密码
	SetPayPassword(ctx context.Context, in *SetPayPasswordReq, opts ...grpc.CallOption) (*UserCommonResp, error)
	// 修改支付密码
	ChangePayPassword(ctx context.Context, in *ChangePayPasswordReq, opts ...grpc.CallOption) (*UserCommonResp, error)
	// 初始化谷歌2FA
	InitGoogle2FA(ctx context.Context, in *InitGoogle2FAReq, opts ...grpc.CallOption) (*InitGoogle2FAResp, error)
	// 启用谷歌2FA
	EnableGoogle2FA(ctx context.Context, in *EnableGoogle2FAReq, opts ...grpc.CallOption) (*UserCommonResp, error)
	// 禁用谷歌2FA
	DisableGoogle2FA(ctx context.Context, in *DisableGoogle2FAReq, opts ...grpc.CallOption) (*UserCommonResp, error)
	// 银行卡相关接口
	ListBanks(ctx context.Context, in *ListBanksReq, opts ...grpc.CallOption) (*ListBanksResp, error)
	// 添加银行卡
	AddBank(ctx context.Context, in *AddBankReq, opts ...grpc.CallOption) (*AddBankResp, error)
	// 更新银行卡
	UpdateBank(ctx context.Context, in *UpdateBankReq, opts ...grpc.CallOption) (*UpdateBankResp, error)
	// 删除银行卡
	DeleteBank(ctx context.Context, in *DeleteBankReq, opts ...grpc.CallOption) (*UserCommonResp, error)
	// 设置默认银行卡
	SetDefaultBank(ctx context.Context, in *SetDefaultBankReq, opts ...grpc.CallOption) (*UserCommonResp, error)
}

type appClient struct {
	cc grpc.ClientConnInterface
}

func NewAppClient(cc grpc.ClientConnInterface) AppClient {
	return &appClient{cc}
}

func (c *appClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, App_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, App_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GuestLogin(ctx context.Context, in *GuestLoginReq, opts ...grpc.CallOption) (*GuestLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuestLoginResp)
	err := c.cc.Invoke(ctx, App_GuestLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) CreateGuestTransfer(ctx context.Context, in *CreateGuestTransferReq, opts ...grpc.CallOption) (*CreateGuestTransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGuestTransferResp)
	err := c.cc.Invoke(ctx, App_CreateGuestTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ExchangeGuestTransfer(ctx context.Context, in *ExchangeGuestTransferReq, opts ...grpc.CallOption) (*ExchangeGuestTransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeGuestTransferResp)
	err := c.cc.Invoke(ctx, App_ExchangeGuestTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*UserCommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCommonResp)
	err := c.cc.Invoke(ctx, App_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResp)
	err := c.cc.Invoke(ctx, App_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResp)
	err := c.cc.Invoke(ctx, App_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UpdateProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResp)
	err := c.cc.Invoke(ctx, App_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ChangeLoginPassword(ctx context.Context, in *ChangeLoginPasswordReq, opts ...grpc.CallOption) (*UserCommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCommonResp)
	err := c.cc.Invoke(ctx, App_ChangeLoginPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetIdentity(ctx context.Context, in *GetIdentityReq, opts ...grpc.CallOption) (*GetIdentityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdentityResp)
	err := c.cc.Invoke(ctx, App_GetIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SubmitIdentity(ctx context.Context, in *SubmitIdentityReq, opts ...grpc.CallOption) (*SubmitIdentityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitIdentityResp)
	err := c.cc.Invoke(ctx, App_SubmitIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UpdateIdentity(ctx context.Context, in *UpdateIdentityReq, opts ...grpc.CallOption) (*UpdateIdentityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateIdentityResp)
	err := c.cc.Invoke(ctx, App_UpdateIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetSecurity(ctx context.Context, in *GetSecurityReq, opts ...grpc.CallOption) (*GetSecurityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecurityResp)
	err := c.cc.Invoke(ctx, App_GetSecurity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetPayPassword(ctx context.Context, in *SetPayPasswordReq, opts ...grpc.CallOption) (*UserCommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCommonResp)
	err := c.cc.Invoke(ctx, App_SetPayPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ChangePayPassword(ctx context.Context, in *ChangePayPasswordReq, opts ...grpc.CallOption) (*UserCommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCommonResp)
	err := c.cc.Invoke(ctx, App_ChangePayPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) InitGoogle2FA(ctx context.Context, in *InitGoogle2FAReq, opts ...grpc.CallOption) (*InitGoogle2FAResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitGoogle2FAResp)
	err := c.cc.Invoke(ctx, App_InitGoogle2FA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) EnableGoogle2FA(ctx context.Context, in *EnableGoogle2FAReq, opts ...grpc.CallOption) (*UserCommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCommonResp)
	err := c.cc.Invoke(ctx, App_EnableGoogle2FA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) DisableGoogle2FA(ctx context.Context, in *DisableGoogle2FAReq, opts ...grpc.CallOption) (*UserCommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCommonResp)
	err := c.cc.Invoke(ctx, App_DisableGoogle2FA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ListBanks(ctx context.Context, in *ListBanksReq, opts ...grpc.CallOption) (*ListBanksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBanksResp)
	err := c.cc.Invoke(ctx, App_ListBanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) AddBank(ctx context.Context, in *AddBankReq, opts ...grpc.CallOption) (*AddBankResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBankResp)
	err := c.cc.Invoke(ctx, App_AddBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UpdateBank(ctx context.Context, in *UpdateBankReq, opts ...grpc.CallOption) (*UpdateBankResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBankResp)
	err := c.cc.Invoke(ctx, App_UpdateBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) DeleteBank(ctx context.Context, in *DeleteBankReq, opts ...grpc.CallOption) (*UserCommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCommonResp)
	err := c.cc.Invoke(ctx, App_DeleteBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetDefaultBank(ctx context.Context, in *SetDefaultBankReq, opts ...grpc.CallOption) (*UserCommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCommonResp)
	err := c.cc.Invoke(ctx, App_SetDefaultBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServer is the server API for App service.
// All implementations must embed UnimplementedAppServer
// for forward compatibility.
//
// APP端接口
type AppServer interface {
	// 用户注册
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	// 用户登录
	Login(context.Context, *LoginReq) (*LoginResp, error)
	// 游客登了
	GuestLogin(context.Context, *GuestLoginReq) (*GuestLoginResp, error)
	// 创建游客跨域迁移码
	CreateGuestTransfer(context.Context, *CreateGuestTransferReq) (*CreateGuestTransferResp, error)
	// 兑换游客跨域迁移码
	ExchangeGuestTransfer(context.Context, *ExchangeGuestTransferReq) (*ExchangeGuestTransferResp, error)
	// 用户登出
	Logout(context.Context, *LogoutReq) (*UserCommonResp, error)
	// 刷新Token
	RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenResp, error)
	// 用户资料相关接口
	GetProfile(context.Context, *GetProfileReq) (*GetProfileResp, error)
	// 更新用户资料
	UpdateProfile(context.Context, *UpdateProfileReq) (*UpdateProfileResp, error)
	// 修改登录密码
	ChangeLoginPassword(context.Context, *ChangeLoginPasswordReq) (*UserCommonResp, error)
	// 实名认证相关接口
	GetIdentity(context.Context, *GetIdentityReq) (*GetIdentityResp, error)
	// 提交实名认证信息
	SubmitIdentity(context.Context, *SubmitIdentityReq) (*SubmitIdentityResp, error)
	// 修改实名认证信息
	UpdateIdentity(context.Context, *UpdateIdentityReq) (*UpdateIdentityResp, error)
	// 安全设置相关接口
	GetSecurity(context.Context, *GetSecurityReq) (*GetSecurityResp, error)
	// 设置支付密码
	SetPayPassword(context.Context, *SetPayPasswordReq) (*UserCommonResp, error)
	// 修改支付密码
	ChangePayPassword(context.Context, *ChangePayPasswordReq) (*UserCommonResp, error)
	// 初始化谷歌2FA
	InitGoogle2FA(context.Context, *InitGoogle2FAReq) (*InitGoogle2FAResp, error)
	// 启用谷歌2FA
	EnableGoogle2FA(context.Context, *EnableGoogle2FAReq) (*UserCommonResp, error)
	// 禁用谷歌2FA
	DisableGoogle2FA(context.Context, *DisableGoogle2FAReq) (*UserCommonResp, error)
	// 银行卡相关接口
	ListBanks(context.Context, *ListBanksReq) (*ListBanksResp, error)
	// 添加银行卡
	AddBank(context.Context, *AddBankReq) (*AddBankResp, error)
	// 更新银行卡
	UpdateBank(context.Context, *UpdateBankReq) (*UpdateBankResp, error)
	// 删除银行卡
	DeleteBank(context.Context, *DeleteBankReq) (*UserCommonResp, error)
	// 设置默认银行卡
	SetDefaultBank(context.Context, *SetDefaultBankReq) (*UserCommonResp, error)
	mustEmbedUnimplementedAppServer()
}

// UnimplementedAppServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppServer struct{}

func (UnimplementedAppServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAppServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAppServer) GuestLogin(context.Context, *GuestLoginReq) (*GuestLoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GuestLogin not implemented")
}
func (UnimplementedAppServer) CreateGuestTransfer(context.Context, *CreateGuestTransferReq) (*CreateGuestTransferResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGuestTransfer not implemented")
}
func (UnimplementedAppServer) ExchangeGuestTransfer(context.Context, *ExchangeGuestTransferReq) (*ExchangeGuestTransferResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeGuestTransfer not implemented")
}
func (UnimplementedAppServer) Logout(context.Context, *LogoutReq) (*UserCommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAppServer) RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAppServer) GetProfile(context.Context, *GetProfileReq) (*GetProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedAppServer) UpdateProfile(context.Context, *UpdateProfileReq) (*UpdateProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedAppServer) ChangeLoginPassword(context.Context, *ChangeLoginPasswordReq) (*UserCommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeLoginPassword not implemented")
}
func (UnimplementedAppServer) GetIdentity(context.Context, *GetIdentityReq) (*GetIdentityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentity not implemented")
}
func (UnimplementedAppServer) SubmitIdentity(context.Context, *SubmitIdentityReq) (*SubmitIdentityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitIdentity not implemented")
}
func (UnimplementedAppServer) UpdateIdentity(context.Context, *UpdateIdentityReq) (*UpdateIdentityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateIdentity not implemented")
}
func (UnimplementedAppServer) GetSecurity(context.Context, *GetSecurityReq) (*GetSecurityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecurity not implemented")
}
func (UnimplementedAppServer) SetPayPassword(context.Context, *SetPayPasswordReq) (*UserCommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPayPassword not implemented")
}
func (UnimplementedAppServer) ChangePayPassword(context.Context, *ChangePayPasswordReq) (*UserCommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePayPassword not implemented")
}
func (UnimplementedAppServer) InitGoogle2FA(context.Context, *InitGoogle2FAReq) (*InitGoogle2FAResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InitGoogle2FA not implemented")
}
func (UnimplementedAppServer) EnableGoogle2FA(context.Context, *EnableGoogle2FAReq) (*UserCommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableGoogle2FA not implemented")
}
func (UnimplementedAppServer) DisableGoogle2FA(context.Context, *DisableGoogle2FAReq) (*UserCommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableGoogle2FA not implemented")
}
func (UnimplementedAppServer) ListBanks(context.Context, *ListBanksReq) (*ListBanksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBanks not implemented")
}
func (UnimplementedAppServer) AddBank(context.Context, *AddBankReq) (*AddBankResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBank not implemented")
}
func (UnimplementedAppServer) UpdateBank(context.Context, *UpdateBankReq) (*UpdateBankResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBank not implemented")
}
func (UnimplementedAppServer) DeleteBank(context.Context, *DeleteBankReq) (*UserCommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBank not implemented")
}
func (UnimplementedAppServer) SetDefaultBank(context.Context, *SetDefaultBankReq) (*UserCommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultBank not implemented")
}
func (UnimplementedAppServer) mustEmbedUnimplementedAppServer() {}
func (UnimplementedAppServer) testEmbeddedByValue()             {}

// UnsafeAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServer will
// result in compilation errors.
type UnsafeAppServer interface {
	mustEmbedUnimplementedAppServer()
}

func RegisterAppServer(s grpc.ServiceRegistrar, srv AppServer) {
	// If the following call panics, it indicates UnimplementedAppServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&App_ServiceDesc, srv)
}

func _App_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GuestLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GuestLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GuestLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GuestLogin(ctx, req.(*GuestLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_CreateGuestTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGuestTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).CreateGuestTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_CreateGuestTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).CreateGuestTransfer(ctx, req.(*CreateGuestTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ExchangeGuestTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeGuestTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ExchangeGuestTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_ExchangeGuestTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ExchangeGuestTransfer(ctx, req.(*ExchangeGuestTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Logout(ctx, req.(*LogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).RefreshToken(ctx, req.(*RefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetProfile(ctx, req.(*GetProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UpdateProfile(ctx, req.(*UpdateProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ChangeLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeLoginPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ChangeLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_ChangeLoginPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ChangeLoginPassword(ctx, req.(*ChangeLoginPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GetIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetIdentity(ctx, req.(*GetIdentityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SubmitIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitIdentityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SubmitIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_SubmitIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SubmitIdentity(ctx, req.(*SubmitIdentityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UpdateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIdentityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UpdateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UpdateIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UpdateIdentity(ctx, req.(*UpdateIdentityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetSecurity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecurityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetSecurity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GetSecurity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetSecurity(ctx, req.(*GetSecurityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetPayPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPayPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetPayPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_SetPayPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetPayPassword(ctx, req.(*SetPayPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ChangePayPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePayPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ChangePayPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_ChangePayPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ChangePayPassword(ctx, req.(*ChangePayPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_InitGoogle2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitGoogle2FAReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).InitGoogle2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_InitGoogle2FA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).InitGoogle2FA(ctx, req.(*InitGoogle2FAReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_EnableGoogle2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableGoogle2FAReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).EnableGoogle2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_EnableGoogle2FA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).EnableGoogle2FA(ctx, req.(*EnableGoogle2FAReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_DisableGoogle2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableGoogle2FAReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).DisableGoogle2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_DisableGoogle2FA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).DisableGoogle2FA(ctx, req.(*DisableGoogle2FAReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ListBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBanksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ListBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_ListBanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ListBanks(ctx, req.(*ListBanksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_AddBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).AddBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_AddBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).AddBank(ctx, req.(*AddBankReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UpdateBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UpdateBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_UpdateBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UpdateBank(ctx, req.(*UpdateBankReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_DeleteBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).DeleteBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_DeleteBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).DeleteBank(ctx, req.(*DeleteBankReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetDefaultBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultBankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetDefaultBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_SetDefaultBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetDefaultBank(ctx, req.(*SetDefaultBankReq))
	}
	return interceptor(ctx, in, info, handler)
}

// App_ServiceDesc is the grpc.ServiceDesc for App service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var App_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _App_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _App_Login_Handler,
		},
		{
			MethodName: "GuestLogin",
			Handler:    _App_GuestLogin_Handler,
		},
		{
			MethodName: "CreateGuestTransfer",
			Handler:    _App_CreateGuestTransfer_Handler,
		},
		{
			MethodName: "ExchangeGuestTransfer",
			Handler:    _App_ExchangeGuestTransfer_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _App_Logout_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _App_RefreshToken_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _App_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _App_UpdateProfile_Handler,
		},
		{
			MethodName: "ChangeLoginPassword",
			Handler:    _App_ChangeLoginPassword_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _App_GetIdentity_Handler,
		},
		{
			MethodName: "SubmitIdentity",
			Handler:    _App_SubmitIdentity_Handler,
		},
		{
			MethodName: "UpdateIdentity",
			Handler:    _App_UpdateIdentity_Handler,
		},
		{
			MethodName: "GetSecurity",
			Handler:    _App_GetSecurity_Handler,
		},
		{
			MethodName: "SetPayPassword",
			Handler:    _App_SetPayPassword_Handler,
		},
		{
			MethodName: "ChangePayPassword",
			Handler:    _App_ChangePayPassword_Handler,
		},
		{
			MethodName: "InitGoogle2FA",
			Handler:    _App_InitGoogle2FA_Handler,
		},
		{
			MethodName: "EnableGoogle2FA",
			Handler:    _App_EnableGoogle2FA_Handler,
		},
		{
			MethodName: "DisableGoogle2FA",
			Handler:    _App_DisableGoogle2FA_Handler,
		},
		{
			MethodName: "ListBanks",
			Handler:    _App_ListBanks_Handler,
		},
		{
			MethodName: "AddBank",
			Handler:    _App_AddBank_Handler,
		},
		{
			MethodName: "UpdateBank",
			Handler:    _App_UpdateBank_Handler,
		},
		{
			MethodName: "DeleteBank",
			Handler:    _App_DeleteBank_Handler,
		},
		{
			MethodName: "SetDefaultBank",
			Handler:    _App_SetDefaultBank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}

const (
	Admin_GuestDomainMigrationStats_FullMethodName = "/user.Admin/GuestDomainMigrationStats"
	Admin_CreateUser_FullMethodName                = "/user.Admin/CreateUser"
	Admin_GetUserDetail_FullMethodName             = "/user.Admin/GetUserDetail"
	Admin_ListUsers_FullMethodName                 = "/user.Admin/ListUsers"
	Admin_UpdateUserBase_FullMethodName            = "/user.Admin/UpdateUserBase"
	Admin_UpdateUserStatus_FullMethodName          = "/user.Admin/UpdateUserStatus"
	Admin_UpdateUserLevel_FullMethodName           = "/user.Admin/UpdateUserLevel"
	Admin_ResetLoginPassword_FullMethodName        = "/user.Admin/ResetLoginPassword"
	Admin_ResetPayPassword_FullMethodName          = "/user.Admin/ResetPayPassword"
	Admin_UnlockUser_FullMethodName                = "/user.Admin/UnlockUser"
	Admin_UpdateRiskLevel_FullMethodName           = "/user.Admin/UpdateRiskLevel"
	Admin_DeleteUser_FullMethodName                = "/user.Admin/DeleteUser"
	Admin_GetUserSecurity_FullMethodName           = "/user.Admin/GetUserSecurity"
	Admin_ResetUserGoogle2FA_FullMethodName        = "/user.Admin/ResetUserGoogle2FA"
	Admin_ListUserIdentities_FullMethodName        = "/user.Admin/ListUserIdentities"
	Admin_ReviewUserIdentity_FullMethodName        = "/user.Admin/ReviewUserIdentity"
	Admin_ListUserBanks_FullMethodName             = "/user.Admin/ListUserBanks"
	Admin_GetUserBank_FullMethodName               = "/user.Admin/GetUserBank"
	Admin_AddUserBank_FullMethodName               = "/user.Admin/AddUserBank"
	Admin_UpdateUserBank_FullMethodName            = "/user.Admin/UpdateUserBank"
	Admin_DeleteUserBank_FullMethodName            = "/user.Admin/DeleteUserBank"
	Admin_UpdateUserBankStatus_FullMethodName      = "/user.Admin/UpdateUserBankStatus"
	Admin_SetDefaultUserBank_FullMethodName        = "/user.Admin/SetDefaultUserBank"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 管理后台接口
type AdminClient interface {
	// 退役域名未迁移游客及活跃分布统计
	GuestDomainMigrationStats(ctx context.Context, in *GuestDomainMigrationStatsReq, opts ...grpc.CallOption) (*GuestDomainMigrationStatsResp, error)
	// 创建用户
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
	// 获取用户详情
	GetUserDetail(ctx context.Context, in *GetUserDetailReq, opts ...grpc.CallOption) (*GetUserDetailResp, error)
	// 用户列表
	ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error)
	// 更新用户基本信息
	UpdateUserBase(ctx context.Context, in *UpdateUserBaseReq, opts ...grpc.CallOption) (*UpdateUserBaseResp, error)
	// 更新用户状态
	UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 更新用户会员等级
	UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 重置登录密码
	ResetLoginPassword(ctx context.Context, in *ResetLoginPasswordReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 重置支付密码
	ResetPayPassword(ctx context.Context, in *ResetPayPasswordReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 解锁用户（解除登录锁定）
	UnlockUser(ctx context.Context, in *UnlockUserReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 更新用户风险等级
	UpdateRiskLevel(ctx context.Context, in *UpdateRiskLevelReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 删除用户
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 获取用户安全设置
	GetUserSecurity(ctx context.Context, in *GetUserSecurityReq, opts ...grpc.CallOption) (*GetUserSecurityResp, error)
	// 重置用户谷歌2FA
	ResetUserGoogle2FA(ctx context.Context, in *ResetUserGoogle2FAReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 实名认证信息列表
	ListUserIdentities(ctx context.Context, in *ListUserIdentitiesReq, opts ...grpc.CallOption) (*ListUserIdentitiesResp, error)
	// 审核实名认证信息
	ReviewUserIdentity(ctx context.Context, in *ReviewUserIdentityReq, opts ...grpc.CallOption) (*ReviewUserIdentityResp, error)
	// 用户银行卡列表
	ListUserBanks(ctx context.Context, in *ListUserBanksReq, opts ...grpc.CallOption) (*ListUserBanksResp, error)
	// 获取用户银行卡详情
	GetUserBank(ctx context.Context, in *GetUserBankReq, opts ...grpc.CallOption) (*GetUserBankResp, error)
	// 添加用户银行卡
	AddUserBank(ctx context.Context, in *AddUserBankReq, opts ...grpc.CallOption) (*AddUserBankResp, error)
	// 更新用户银行卡
	UpdateUserBank(ctx context.Context, in *UpdateUserBankReq, opts ...grpc.CallOption) (*UpdateUserBankResp, error)
	// 删除用户银行卡
	DeleteUserBank(ctx context.Context, in *DeleteUserBankReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 更新用户银行卡状态
	UpdateUserBankStatus(ctx context.Context, in *UpdateUserBankStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 设置默认用户银行卡
	SetDefaultUserBank(ctx context.Context, in *SetDefaultUserBankReq, opts ...grpc.CallOption) (*CommonResp, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GuestDomainMigrationStats(ctx context.Context, in *GuestDomainMigrationStatsReq, opts ...grpc.CallOption) (*GuestDomainMigrationStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuestDomainMigrationStatsResp)
	err := c.cc.Invoke(ctx, Admin_GuestDomainMigrationStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResp)
	err := c.cc.Invoke(ctx, Admin_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetUserDetail(ctx context.Context, in *GetUserDetailReq, opts ...grpc.CallOption) (*GetUserDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDetailResp)
	err := c.cc.Invoke(ctx, Admin_GetUserDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResp)
	err := c.cc.Invoke(ctx, Admin_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateUserBase(ctx context.Context, in *UpdateUserBaseReq, opts ...grpc.CallOption) (*UpdateUserBaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserBaseResp)
	err := c.cc.Invoke(ctx, Admin_UpdateUserBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UpdateUserStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UpdateUserLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ResetLoginPassword(ctx context.Context, in *ResetLoginPasswordReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_ResetLoginPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ResetPayPassword(ctx context.Context, in *ResetPayPasswordReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_ResetPayPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UnlockUser(ctx context.Context, in *UnlockUserReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UnlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateRiskLevel(ctx context.Context, in *UpdateRiskLevelReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UpdateRiskLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetUserSecurity(ctx context.Context, in *GetUserSecurityReq, opts ...grpc.CallOption) (*GetUserSecurityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSecurityResp)
	err := c.cc.Invoke(ctx, Admin_GetUserSecurity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ResetUserGoogle2FA(ctx context.Context, in *ResetUserGoogle2FAReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_ResetUserGoogle2FA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListUserIdentities(ctx context.Context, in *ListUserIdentitiesReq, opts ...grpc.CallOption) (*ListUserIdentitiesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserIdentitiesResp)
	err := c.cc.Invoke(ctx, Admin_ListUserIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ReviewUserIdentity(ctx context.Context, in *ReviewUserIdentityReq, opts ...grpc.CallOption) (*ReviewUserIdentityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewUserIdentityResp)
	err := c.cc.Invoke(ctx, Admin_ReviewUserIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListUserBanks(ctx context.Context, in *ListUserBanksReq, opts ...grpc.CallOption) (*ListUserBanksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserBanksResp)
	err := c.cc.Invoke(ctx, Admin_ListUserBanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetUserBank(ctx context.Context, in *GetUserBankReq, opts ...grpc.CallOption) (*GetUserBankResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserBankResp)
	err := c.cc.Invoke(ctx, Admin_GetUserBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AddUserBank(ctx context.Context, in *AddUserBankReq, opts ...grpc.CallOption) (*AddUserBankResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserBankResp)
	err := c.cc.Invoke(ctx, Admin_AddUserBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateUserBank(ctx context.Context, in *UpdateUserBankReq, opts ...grpc.CallOption) (*UpdateUserBankResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserBankResp)
	err := c.cc.Invoke(ctx, Admin_UpdateUserBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteUserBank(ctx context.Context, in *DeleteUserBankReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_DeleteUserBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateUserBankStatus(ctx context.Context, in *UpdateUserBankStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_UpdateUserBankStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SetDefaultUserBank(ctx context.Context, in *SetDefaultUserBankReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Admin_SetDefaultUserBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
//
// 管理后台接口
type AdminServer interface {
	// 退役域名未迁移游客及活跃分布统计
	GuestDomainMigrationStats(context.Context, *GuestDomainMigrationStatsReq) (*GuestDomainMigrationStatsResp, error)
	// 创建用户
	CreateUser(context.Context, *CreateUserReq) (*CreateUserResp, error)
	// 获取用户详情
	GetUserDetail(context.Context, *GetUserDetailReq) (*GetUserDetailResp, error)
	// 用户列表
	ListUsers(context.Context, *ListUsersReq) (*ListUsersResp, error)
	// 更新用户基本信息
	UpdateUserBase(context.Context, *UpdateUserBaseReq) (*UpdateUserBaseResp, error)
	// 更新用户状态
	UpdateUserStatus(context.Context, *UpdateUserStatusReq) (*CommonResp, error)
	// 更新用户会员等级
	UpdateUserLevel(context.Context, *UpdateUserLevelReq) (*CommonResp, error)
	// 重置登录密码
	ResetLoginPassword(context.Context, *ResetLoginPasswordReq) (*CommonResp, error)
	// 重置支付密码
	ResetPayPassword(context.Context, *ResetPayPasswordReq) (*CommonResp, error)
	// 解锁用户（解除登录锁定）
	UnlockUser(context.Context, *UnlockUserReq) (*CommonResp, error)
	// 更新用户风险等级
	UpdateRiskLevel(context.Context, *UpdateRiskLevelReq) (*CommonResp, error)
	// 删除用户
	DeleteUser(context.Context, *DeleteUserReq) (*CommonResp, error)
	// 获取用户安全设置
	GetUserSecurity(context.Context, *GetUserSecurityReq) (*GetUserSecurityResp, error)
	// 重置用户谷歌2FA
	ResetUserGoogle2FA(context.Context, *ResetUserGoogle2FAReq) (*CommonResp, error)
	// 实名认证信息列表
	ListUserIdentities(context.Context, *ListUserIdentitiesReq) (*ListUserIdentitiesResp, error)
	// 审核实名认证信息
	ReviewUserIdentity(context.Context, *ReviewUserIdentityReq) (*ReviewUserIdentityResp, error)
	// 用户银行卡列表
	ListUserBanks(context.Context, *ListUserBanksReq) (*ListUserBanksResp, error)
	// 获取用户银行卡详情
	GetUserBank(context.Context, *GetUserBankReq) (*GetUserBankResp, error)
	// 添加用户银行卡
	AddUserBank(context.Context, *AddUserBankReq) (*AddUserBankResp, error)
	// 更新用户银行卡
	UpdateUserBank(context.Context, *UpdateUserBankReq) (*UpdateUserBankResp, error)
	// 删除用户银行卡
	DeleteUserBank(context.Context, *DeleteUserBankReq) (*CommonResp, error)
	// 更新用户银行卡状态
	UpdateUserBankStatus(context.Context, *UpdateUserBankStatusReq) (*CommonResp, error)
	// 设置默认用户银行卡
	SetDefaultUserBank(context.Context, *SetDefaultUserBankReq) (*CommonResp, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) GuestDomainMigrationStats(context.Context, *GuestDomainMigrationStatsReq) (*GuestDomainMigrationStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GuestDomainMigrationStats not implemented")
}
func (UnimplementedAdminServer) CreateUser(context.Context, *CreateUserReq) (*CreateUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedAdminServer) GetUserDetail(context.Context, *GetUserDetailReq) (*GetUserDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDetail not implemented")
}
func (UnimplementedAdminServer) ListUsers(context.Context, *ListUsersReq) (*ListUsersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedAdminServer) UpdateUserBase(context.Context, *UpdateUserBaseReq) (*UpdateUserBaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserBase not implemented")
}
func (UnimplementedAdminServer) UpdateUserStatus(context.Context, *UpdateUserStatusReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserStatus not implemented")
}
func (UnimplementedAdminServer) UpdateUserLevel(context.Context, *UpdateUserLevelReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserLevel not implemented")
}
func (UnimplementedAdminServer) ResetLoginPassword(context.Context, *ResetLoginPasswordReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetLoginPassword not implemented")
}
func (UnimplementedAdminServer) ResetPayPassword(context.Context, *ResetPayPasswordReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPayPassword not implemented")
}
func (UnimplementedAdminServer) UnlockUser(context.Context, *UnlockUserReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockUser not implemented")
}
func (UnimplementedAdminServer) UpdateRiskLevel(context.Context, *UpdateRiskLevelReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRiskLevel not implemented")
}
func (UnimplementedAdminServer) DeleteUser(context.Context, *DeleteUserReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedAdminServer) GetUserSecurity(context.Context, *GetUserSecurityReq) (*GetUserSecurityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSecurity not implemented")
}
func (UnimplementedAdminServer) ResetUserGoogle2FA(context.Context, *ResetUserGoogle2FAReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetUserGoogle2FA not implemented")
}
func (UnimplementedAdminServer) ListUserIdentities(context.Context, *ListUserIdentitiesReq) (*ListUserIdentitiesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserIdentities not implemented")
}
func (UnimplementedAdminServer) ReviewUserIdentity(context.Context, *ReviewUserIdentityReq) (*ReviewUserIdentityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewUserIdentity not implemented")
}
func (UnimplementedAdminServer) ListUserBanks(context.Context, *ListUserBanksReq) (*ListUserBanksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserBanks not implemented")
}
func (UnimplementedAdminServer) GetUserBank(context.Context, *GetUserBankReq) (*GetUserBankResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBank not implemented")
}
func (UnimplementedAdminServer) AddUserBank(context.Context, *AddUserBankReq) (*AddUserBankResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserBank not implemented")
}
func (UnimplementedAdminServer) UpdateUserBank(context.Context, *UpdateUserBankReq) (*UpdateUserBankResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserBank not implemented")
}
func (UnimplementedAdminServer) DeleteUserBank(context.Context, *DeleteUserBankReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserBank not implemented")
}
func (UnimplementedAdminServer) UpdateUserBankStatus(context.Context, *UpdateUserBankStatusReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserBankStatus not implemented")
}
func (UnimplementedAdminServer) SetDefaultUserBank(context.Context, *SetDefaultUserBankReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultUserBank not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_GuestDomainMigrationStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestDomainMigrationStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GuestDomainMigrationStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GuestDomainMigrationStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GuestDomainMigrationStats(ctx, req.(*GuestDomainMigrationStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateUser(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetUserDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetUserDetail(ctx, req.(*GetUserDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListUsers(ctx, req.(*ListUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateUserBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserBaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateUserBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateUserBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateUserBase(ctx, req.(*UpdateUserBaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateUserStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateUserStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateUserStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateUserStatus(ctx, req.(*UpdateUserStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateUserLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateUserLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateUserLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateUserLevel(ctx, req.(*UpdateUserLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ResetLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetLoginPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ResetLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ResetLoginPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ResetLoginPassword(ctx, req.(*ResetLoginPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ResetPayPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPayPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ResetPayPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ResetPayPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ResetPayPassword(ctx, req.(*ResetPayPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UnlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UnlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UnlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UnlockUser(ctx, req.(*UnlockUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateRiskLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRiskLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateRiskLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateRiskLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateRiskLevel(ctx, req.(*UpdateRiskLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteUser(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetUserSecurity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSecurityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetUserSecurity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetUserSecurity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetUserSecurity(ctx, req.(*GetUserSecurityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ResetUserGoogle2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUserGoogle2FAReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ResetUserGoogle2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ResetUserGoogle2FA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ResetUserGoogle2FA(ctx, req.(*ResetUserGoogle2FAReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListUserIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserIdentitiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListUserIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListUserIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListUserIdentities(ctx, req.(*ListUserIdentitiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ReviewUserIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewUserIdentityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ReviewUserIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ReviewUserIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ReviewUserIdentity(ctx, req.(*ReviewUserIdentityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListUserBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserBanksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListUserBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListUserBanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListUserBanks(ctx, req.(*ListUserBanksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetUserBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetUserBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetUserBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetUserBank(ctx, req.(*GetUserBankReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AddUserBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserBankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AddUserBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AddUserBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AddUserBank(ctx, req.(*AddUserBankReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateUserBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserBankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateUserBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateUserBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateUserBank(ctx, req.(*UpdateUserBankReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteUserBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserBankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteUserBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteUserBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteUserBank(ctx, req.(*DeleteUserBankReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateUserBankStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserBankStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateUserBankStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateUserBankStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateUserBankStatus(ctx, req.(*UpdateUserBankStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SetDefaultUserBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultUserBankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SetDefaultUserBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_SetDefaultUserBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SetDefaultUserBank(ctx, req.(*SetDefaultUserBankReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GuestDomainMigrationStats",
			Handler:    _Admin_GuestDomainMigrationStats_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Admin_CreateUser_Handler,
		},
		{
			MethodName: "GetUserDetail",
			Handler:    _Admin_GetUserDetail_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Admin_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUserBase",
			Handler:    _Admin_UpdateUserBase_Handler,
		},
		{
			MethodName: "UpdateUserStatus",
			Handler:    _Admin_UpdateUserStatus_Handler,
		},
		{
			MethodName: "UpdateUserLevel",
			Handler:    _Admin_UpdateUserLevel_Handler,
		},
		{
			MethodName: "ResetLoginPassword",
			Handler:    _Admin_ResetLoginPassword_Handler,
		},
		{
			MethodName: "ResetPayPassword",
			Handler:    _Admin_ResetPayPassword_Handler,
		},
		{
			MethodName: "UnlockUser",
			Handler:    _Admin_UnlockUser_Handler,
		},
		{
			MethodName: "UpdateRiskLevel",
			Handler:    _Admin_UpdateRiskLevel_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Admin_DeleteUser_Handler,
		},
		{
			MethodName: "GetUserSecurity",
			Handler:    _Admin_GetUserSecurity_Handler,
		},
		{
			MethodName: "ResetUserGoogle2FA",
			Handler:    _Admin_ResetUserGoogle2FA_Handler,
		},
		{
			MethodName: "ListUserIdentities",
			Handler:    _Admin_ListUserIdentities_Handler,
		},
		{
			MethodName: "ReviewUserIdentity",
			Handler:    _Admin_ReviewUserIdentity_Handler,
		},
		{
			MethodName: "ListUserBanks",
			Handler:    _Admin_ListUserBanks_Handler,
		},
		{
			MethodName: "GetUserBank",
			Handler:    _Admin_GetUserBank_Handler,
		},
		{
			MethodName: "AddUserBank",
			Handler:    _Admin_AddUserBank_Handler,
		},
		{
			MethodName: "UpdateUserBank",
			Handler:    _Admin_UpdateUserBank_Handler,
		},
		{
			MethodName: "DeleteUserBank",
			Handler:    _Admin_DeleteUserBank_Handler,
		},
		{
			MethodName: "UpdateUserBankStatus",
			Handler:    _Admin_UpdateUserBankStatus_Handler,
		},
		{
			MethodName: "SetDefaultUserBank",
			Handler:    _Admin_SetDefaultUserBank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}

const (
	User_CreateInternalTradingUser_FullMethodName = "/user.User/CreateInternalTradingUser"
	User_GetInternalTradingUser_FullMethodName    = "/user.User/GetInternalTradingUser"
	User_ListInternalTradingUsers_FullMethodName  = "/user.User/ListInternalTradingUsers"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 仅供平台内部服务调用，不暴露给用户端。
type UserClient interface {
	CreateInternalTradingUser(ctx context.Context, in *CreateInternalTradingUserReq, opts ...grpc.CallOption) (*InternalTradingUserResp, error)
	GetInternalTradingUser(ctx context.Context, in *GetInternalTradingUserReq, opts ...grpc.CallOption) (*InternalTradingUserResp, error)
	ListInternalTradingUsers(ctx context.Context, in *ListInternalTradingUsersReq, opts ...grpc.CallOption) (*ListInternalTradingUsersResp, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) CreateInternalTradingUser(ctx context.Context, in *CreateInternalTradingUserReq, opts ...grpc.CallOption) (*InternalTradingUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalTradingUserResp)
	err := c.cc.Invoke(ctx, User_CreateInternalTradingUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetInternalTradingUser(ctx context.Context, in *GetInternalTradingUserReq, opts ...grpc.CallOption) (*InternalTradingUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalTradingUserResp)
	err := c.cc.Invoke(ctx, User_GetInternalTradingUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ListInternalTradingUsers(ctx context.Context, in *ListInternalTradingUsersReq, opts ...grpc.CallOption) (*ListInternalTradingUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInternalTradingUsersResp)
	err := c.cc.Invoke(ctx, User_ListInternalTradingUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
//
// 仅供平台内部服务调用，不暴露给用户端。
type UserServer interface {
	CreateInternalTradingUser(context.Context, *CreateInternalTradingUserReq) (*InternalTradingUserResp, error)
	GetInternalTradingUser(context.Context, *GetInternalTradingUserReq) (*InternalTradingUserResp, error)
	ListInternalTradingUsers(context.Context, *ListInternalTradingUsersReq) (*ListInternalTradingUsersResp, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) CreateInternalTradingUser(context.Context, *CreateInternalTradingUserReq) (*InternalTradingUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInternalTradingUser not implemented")
}
func (UnimplementedUserServer) GetInternalTradingUser(context.Context, *GetInternalTradingUserReq) (*InternalTradingUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInternalTradingUser not implemented")
}
func (UnimplementedUserServer) ListInternalTradingUsers(context.Context, *ListInternalTradingUsersReq) (*ListInternalTradingUsersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInternalTradingUsers not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call panics, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_CreateInternalTradingUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInternalTradingUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateInternalTradingUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CreateInternalTradingUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateInternalTradingUser(ctx, req.(*CreateInternalTradingUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetInternalTradingUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInternalTradingUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetInternalTradingUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetInternalTradingUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetInternalTradingUser(ctx, req.(*GetInternalTradingUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ListInternalTradingUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInternalTradingUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ListInternalTradingUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_ListInternalTradingUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ListInternalTradingUsers(ctx, req.(*ListInternalTradingUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInternalTradingUser",
			Handler:    _User_CreateInternalTradingUser_Handler,
		},
		{
			MethodName: "GetInternalTradingUser",
			Handler:    _User_GetInternalTradingUser_Handler,
		},
		{
			MethodName: "ListInternalTradingUsers",
			Handler:    _User_ListInternalTradingUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}
