export const chatEventType = {
  MESSAGE: "CHAT_EVENT_TYPE_MESSAGE",
  QUEUE_JOIN: "CHAT_EVENT_TYPE_QUEUE_JOIN",
  QUEUE_UPDATE: "CHAT_EVENT_TYPE_QUEUE_UPDATE",
  QUEUE_LEAVE: "CHAT_EVENT_TYPE_QUEUE_LEAVE",
  USER_JOIN: "CHAT_EVENT_TYPE_USER_JOIN",
  USER_LEAVE: "CHAT_EVENT_TYPE_USER_LEAVE",
  AGENT_JOIN: "CHAT_EVENT_TYPE_AGENT_JOIN",
  AGENT_LEAVE: "CHAT_EVENT_TYPE_AGENT_LEAVE",
  AGENT_ASSIGNED: "CHAT_EVENT_TYPE_AGENT_ASSIGNED",
  SESSION_CLOSE: "CHAT_EVENT_TYPE_SESSION_CLOSE",
  TYPING: "CHAT_EVENT_TYPE_TYPING",
  STOP_TYPING: "CHAT_EVENT_TYPE_STOP_TYPING",
  EVALUATION_INVITE: "CHAT_EVENT_TYPE_EVALUATION_INVITE",
  EVALUATION_SUBMIT: "CHAT_EVENT_TYPE_EVALUATION_SUBMIT",
  SYSTEM: "CHAT_EVENT_TYPE_SYSTEM",
  HEARTBEAT: "CHAT_EVENT_TYPE_HEARTBEAT",
  ERROR: "CHAT_EVENT_TYPE_ERROR",
  DELIVERED: "CHAT_EVENT_TYPE_DELIVERED",
} as const;

export type ChatEventType = (typeof chatEventType)[keyof typeof chatEventType];

export const chatAdminWsEventTypes: ReadonlySet<ChatEventType | string> =
  new Set(Object.values(chatEventType));
