export const chatEventType = {
  MESSAGE: "CHAT_EVENT_TYPE_MESSAGE",
  SYSTEM_NOTICE: "CHAT_EVENT_TYPE_SYSTEM_NOTICE",
  QUEUE_UPDATE: "CHAT_EVENT_TYPE_QUEUE_UPDATE",
  AGENT_ACCEPTED: "CHAT_EVENT_TYPE_AGENT_ACCEPTED",
  AGENT_LEAVE: "CHAT_EVENT_TYPE_AGENT_LEAVE",
  SESSION_CLOSE: "CHAT_EVENT_TYPE_SESSION_CLOSE",
  EVALUATION_INVITE: "CHAT_EVENT_TYPE_EVALUATION_INVITE",
  EVALUATION_SUBMIT: "CHAT_EVENT_TYPE_EVALUATION_SUBMIT",
  TYPING: "CHAT_EVENT_TYPE_TYPING",
  MESSAGE_DELIVERED: "CHAT_EVENT_TYPE_MESSAGE_DELIVERED",
  MESSAGE_READ: "CHAT_EVENT_TYPE_MESSAGE_READ",
  MESSAGE_RECALL: "CHAT_EVENT_TYPE_MESSAGE_RECALL",
  MESSAGE_DELETE: "CHAT_EVENT_TYPE_MESSAGE_DELETE",
  HEARTBEAT: "CHAT_EVENT_TYPE_HEARTBEAT",
  ERROR: "CHAT_EVENT_TYPE_ERROR",
} as const;

export type ChatEventType = (typeof chatEventType)[keyof typeof chatEventType];

export const chatUiWsEventTypes: ReadonlySet<ChatEventType | string> =
  new Set(Object.values(chatEventType));
