export const chatEventType = {
  WS_CONNECTED: "CHAT_EVENT_TYPE_WS_CONNECTED",
  MESSAGE: "CHAT_EVENT_TYPE_MESSAGE",
  SYSTEM_NOTICE: "CHAT_EVENT_TYPE_SYSTEM_NOTICE",
  QUEUE_UPDATE: "CHAT_EVENT_TYPE_QUEUE_UPDATE",
  AGENT_ACCEPTED: "CHAT_EVENT_TYPE_AGENT_ACCEPTED",
  SESSION_CLOSE: "CHAT_EVENT_TYPE_SESSION_CLOSE",
  EVALUATION_INVITE: "CHAT_EVENT_TYPE_EVALUATION_INVITE",
  EVALUATION_SUBMIT: "CHAT_EVENT_TYPE_EVALUATION_SUBMIT",
  TYPING: "CHAT_EVENT_TYPE_TYPING",
  MESSAGE_DELIVERED: "CHAT_EVENT_TYPE_MESSAGE_DELIVERED",
  ERROR: "CHAT_EVENT_TYPE_ERROR",
} as const;

export type ChatEventType = (typeof chatEventType)[keyof typeof chatEventType];

export const chatUiWsEventTypes: ReadonlySet<ChatEventType | string> =
  new Set(Object.values(chatEventType));
